### ISSUE TITLE
WikiExport with links to markdown files

### ISSUE THREAD

**Issue by neildryan** [lervag/wiki.vim#100]
When using :WikiExport, any links to markdown pages (for instance `index.md`) will still be links to markdown pages in an HTML export. I was wondering if it'd be useful to change markdown links to html links? This would be useful when creating a wiki of linked HTML files so that links actually work.

If this functionality doesn't belong in this plugin, I can just make a quick find/replace function that runs before WikiExport. Thanks!

**Comment by lervag** [comment]
Interesting. I don't really use the export feature for much, only to sometimes print a page and share it with people.

Could you provide a small example of this and perhaps the relevant pandoc options and "workflow" to create the relevant output?

**Comment by neildryan** [comment]
Sure! Let's say there's two files `file1.md`, and `file2.md`.
```markdown
# File 1
[Link to file 2](file2.md)
```

```markdown
# File 2
```

If I convert both to HTML, File 1 will look like:
```html
<h1> File 1</h1>
<a href='file2.md'>Link to file 2</a>
```

This isn't ideal; if I'm viewing File 1 in-browser and I click on the link, I'll get `file2.md`, instead of `file2.html`. Having HTML links allows navigation in-browser between exported wiki files.

Again, I recognize that this might not be enough of the common case to justify including, though it seems like a simple find/replace on a temporary file.

**Comment by lervag** [comment]
Yes, feel free to suggest a PR. I can help with the regexes, if you want. I find Vims regexes to be simpler and more convenient to work with than Pythons. And yes, I'd prefer to avoid Python.

However, I'm curious if there might be an option for pandoc that does this automatically? The reason I ask: if we do this on wiki.vim side, before exporting with pandoc, then we need to respect various settings like `g:wiki_link_extension`. I.e., the default settings rely on implicit extensions. Thus, a regex approach is not so straightforward. Still, it is not impossible, we just need to capture the corner cases.

**Comment by neildryan** [comment]
I poked through pandoc documentation, seems like the only "built-in" way would be to use pandoc's [built-in lua filters](https://pandoc.org/lua-filters.html), but the file with the Lua function would need to know about `g:wiki_link_extension`, so I think it's just easier to do entirely in Vim. The only issue that I'm foreseeing is if someone's using the default `g:wiki_link_extension = ''` -- would the "right" approach be to treat any links without an extension as internal wiki links, and convert them to HTML? There's also an issue with anchors `wiki_page.md#Header#lower header` would need to change to `wiki_page.html#Header#lower header`. Any other edge cases that I'm missing? I can poke at this over the weekend.

**Comment by lervag** [comment]
Ok, I see. Then I agree it might be useful to have this as part of wiki.vim. I understood that you are looking for a way to export the entire wiki, and this might be possible to add. However, I think it is good to start small, so I suggest first working with the current `:WikiExport` and add a filter similar to what we've discussed.

I'm not fully sure how anchors work in HTML. But do they need to be translated, perhaps? Remove whitespace and convert to lower cases?

**Comment by lervag** [comment]
Is this issue properly solved by #106?

**Comment by neildryan** [comment]
If someone comes along and has a wiki directory without extensions and wants HTML export (to address links like `[[name]]`, we can change it then. That feels like a pretty small use case; I'll close this for now.

**Comment by lervag** [comment]
Sounds good! :)

**Comment by aldur** [comment]
Sorry to reopen this, but I was trying to use this feature to automatically replace the `md` extension of link of
exported markdown wiki wiki files. 

To enable that, the manual specifies to set
the `g:wiki_link_extension` variable and then set `-link_ext_replace` while
calling `export()`, as follows:

```bash
let g:wiki_link_extension = '.md'
```

The problem is that, this way, the `.md` extension does not get converted to
`.html`.

I believe this is caused by the following regex, that hardcodes a colon twice (once in the regex, the second in `g:wiki_link_extension`. We might think of fixing it as follows:

```dif
M autoload/wiki/page.vim
@@ -520,7 +520,7 @@ endfunction
 function! s:convert_links_to_html(lines) abort " {{{1
   if g:wiki_link_target_type ==# 'md'
     let l:rx = '\[\([^\\\[\]]\{-}\)\]'
-          \ . '(\([^\(\)\\]\{-}\)\.' . g:wiki_link_extension
+          \ . '(\([^\(\)\\]\{-}\)' . g:wiki_link_extension
           \ . '\(#[^#\(\)\\]\{-}\)\{-})'
     let l:sub = '[\1](\2.html\3)'
   elseif g:wiki_link_target_type ==# 'wiki'
```

**Comment by lervag** [comment]
@neildryan Can you test the proposed fix on your end? Does it work as expected for you?

**Comment by neildryan** [comment]
Sorry, busy week -- yeah, this works fine. Should there be something in the docs that clarifies this? I used `md` as my link extension, not sure if that was just my misunderstanding

**Comment by lervag** [comment]
> Sorry, busy week -- yeah, this works fine. Should there be something in the docs that clarifies this? I used `md` as my link extension, not sure if that was just my misunderstanding

No problem. I'm not sure I understand what `this` is in "clarifies this"? I'll be happy to update the docs, but it would be nice with a suggestion on what should be updated.

So, it leaves the following two questions:

1. Should I add the fix suggested by @aldor?
2. Should we update the docs, and if so, do you/anyone have a suggestion for how to update/what in the docs that is unclear?

**Comment by neildryan** [comment]
Ah, sorry.
1. Yes; this is a good fix.
2. I wasn't clear if `g:wiki_link_extension` should be `md` or `.md`, I made mine the former, but this regex solidifies that folks should use the latter and we should probably clarify that. I'd probably just add "...such as `.wiki`, or `.md`" as examples to the documentation for `g:wiki_link_extension`.

**Comment by aldur** [comment]
To add to this: with the fix I suggested, even if `g:wiki_link_extension` is empty, then the `export()` function will correctly append `.html` when exporting to Markdown.

**Comment by lervag** [comment]
Thanks to both of you. I've applied the patch and updated the docs.
