### ISSUE TITLE
Feat: WikiFzfContent

### ISSUE THREAD

**Issue by AdrienLemaire** [lervag/wiki.vim#102]
Since we already have `:WikiFzfPages`, `:WikiFzfTags` and `:WikiFzfToc`, it could be good to offer a default `:WikiFzfContent` command to search for text anywhere in the wiki.

I came up with this snippet for my case:
```vim
function! WikiRgFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case -- %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {
  \ 'dir': wiki#get_root(), 
  \ 'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]
  \}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang WikiFzfContent call WikiRgFzf(<q-args>, <bang>0)
nnoremap <leader>ws :WikiFzfContent<CR>
```

Note: As mentionned in [the README](https://github.com/lervag/wiki.vim#features), I thought that wiki.vim had a dependency to [fzf.vim](https://github.com/junegunn/fzf.vim). But after reading [this comment](https://github.com/lervag/wiki.vim/issues/101#issuecomment-709571804) and the code, I now believe that the dependency is [fzf](https://github.com/junegunn/fzf) (@lervag is then using ctrlsf while I use fzf.vim for functions like `fzf#vim#grep`). Might be worth fixing the README link to clarify this.

If we want to keep the dependency to fzf only, then my snippet needs to be modified:
* Remove the Rg dependency and use fzf only
* use `fzf#run` and `fzf#wrap` instead of `fzf#vim`.
* make the preview feature optional with a settings var, for those who dislike the preview

**Comment by lervag** [comment]
> Since we already have `:WikiFzfPages`, `:WikiFzfTags` and `:WikiFzfToc`, it could be good to offer a default `:WikiFzfContent` command to search for text anywhere in the wiki.

Ah, I'm not so sure I agree on this one. The reason is simply this: as I understand it, `:WikiFzfContent` would essentially be very similar to most kinds of existing search features and plugins. For instance, how would `:WikiFzfContent` differ from the functionality of [ctrlsf](https://github.com/dyng/ctrlsf.vim), or for that matter, [these plugins](https://vimawesome.com/?q=search).

My point is: I think what you want is already provided in a more general and much more polished manner in a bunch of other plugins that would work well with wiki.vim. Thus I don't see why we should add this feature to wiki.vim.

Then you might ask why we have the other three commands? IMHO, there is a slight qualitative difference, because these commands do not really exist from other plugins directly, they _need_ to be defined explicitly to work well.

> Note: As mentionned in [the README](https://github.com/lervag/wiki.vim#features), I thought that wiki.vim had a dependency to [fzf.vim](https://github.com/junegunn/fzf.vim). But after reading [this comment](https://github.com/lervag/wiki.vim/issues/101#issuecomment-709571804) and the code, I now believe that the dependency is [fzf](https://github.com/junegunn/fzf). Might be worth fixing the README link to clarify this.

Yes, I think you are right. I'll fix this!

**Comment by AdrienLemaire** [comment]
Fair enough, thanks for sharing the reason! I also found yesterday about the [coc.nvim fzf-preview.vim](https://github.com/yuki-ycino/fzf-preview.vim) extension, which looks awesome. I'll try to adapt it for wiki.vim :)

**Comment by lervag** [comment]
No problem. Thanks for sharing your ideas/suggestions! :)

**Comment by daturkel** [comment]
Just adding some context on how I handled this feature:

```vim
command! -bang -nargs=* WikiLines
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \  fzf#vim#with_preview({'dir':'~/Documents/wiki/', 'options': ['--prompt','WikiLines> ']},'up:60%','ctrl-/'),
  \   <bang>0)
nnoremap <silent> <localleader>W :WikiLines<CR>
nnoremap <silent> <localleader><localleader>W :WikiLines!<CR>
```

so `,W` searches the lines of all files in my wiki directory using ripgrep in an fzf popup, while `,,W` does the same but fullscreen.

i also do the same for only searching the filenames, but with lowercase `,w`/`,,w`:
```vim
command! -bang WikiPages 
  \ call fzf#vim#files('~/Documents/wiki', 
  \ fzf#vim#with_preview({'options': ['--prompt','Wiki> ']},'up:60%','ctrl-/'), 
  \ <bang>0)
nnoremap <silent> <localleader>w :WikiPages<CR>
nnoremap <silent> <localleader><localleader>w :WikiPages!<CR>
```
