### ISSUE TITLE
wiki.vim calls system() at startup

### ISSUE THREAD

**Issue by nanotee** [lervag/wiki.vim#103]
# Description

This is not a bug per se, but it's an issue I'd encountered a while back because of a misconfigured shell (note to self: do *not* put slow stuff in `.zshenv`...).

Basically, the plugin calls `system('uname')` at startup in `wiki#init#get_os()` ([link](https://github.com/lervag/wiki.vim/blob/0c5394de49db227dd09d8bde3feb724cf5e1f8fa/autoload/wiki/init.vim#L42)). Generally, this isn't an expensive operation, but shelling out can slow down your startup time if you have a slow or misconfigured shell.

Potential fix:
- Use `has()` to detect Mac OS X? Vim can check for the `mac`, `macunix`, `osx` and `osxdarwin` features. Neovim can only officially check for the `mac` feature according to the documentation, but internally it has [the same variables](https://github.com/neovim/neovim/blob/f7aeac7263c792e1503f9169abed20b6f5b9da99/src/nvim/eval/funcs.c#L4133-L4138) as Vim. Unfortunately I don't have an OSX system to test the reliability of this method...

# Minimal working example

If you use zsh, put `sleep 3` in your `.zshenv`, it should slow down your startup time significantly.

---

Thank you for making wiki.vim. I've been using it for a few months now and it is an essential part of my setup.

**Comment by lervag** [comment]
Thanks. I understand where you're coming from. However, I've previously tried to rely on `has()` mechanism for OS detection, and it did not work flowlessly. The `uname` approach seemed/seems easier and less error prone. I don't remember exactly why, though. I'll look into it.

**Comment by lervag** [comment]
In neovim, the `mac`, `macunix`, `osx` and `osxdarwin` are synonyms. Again, I don't remember exactly why, but I'm quite sure that the `has('mac')` did not accuractely recognize all MacOS systems. I did a quick google search, and I found other threads on this topic, see e.g. [this SO answer](https://vi.stackexchange.com/a/2577/21). Similarly, see [this SO thread](https://stackoverflow.com/questions/2842078/how-do-i-detect-os-x-in-my-vimrc-file-so-certain-configurations-will-only-appl).

So, it seems `uname` is unavoidable. :\

> Thank you for making wiki.vim. I've been using it for a few months now and it is an essential part of my setup.

Happy to hear it! :)

**Comment by nanotee** [comment]
Thanks for the quick reply!

> I've previously tried to rely on has() mechanism for OS detection, and it did not work flowlessly.

I was afraid this would be the case. The links you provided are insightful, I'll have to keep this in mind if I ever need to do OS detection.

I have since fixed my zsh config so it's not really that big of an issue for me, it was just a little surprising.

Another potential solution I had considered is that Neovim's implementation of the `system()` function differs slightly from Vim's: `system('uname')` spawns a shell while `system(['uname'])` does not. Using the latter does seem to fix any shell-related problems, at least on Neovim, though it requires handling the command differently in both editors, so it's not ideal...

Thanks again for your work!

**Comment by lervag** [comment]
> Another potential solution I had considered is that Neovim's implementation of the `system()` function differs slightly from Vim's: `system('uname')` spawns a shell while `system(['uname'])` does not. Using the latter does seem to fix any shell-related problems, at least on Neovim, though it requires handling the command differently in both editors, so it's not ideal...

Agreed, it does not sound very robust to rely on this sort of "inconsistency". I think the current state, although not perfect, is a pragmatic solution. I also really think that adding intensive stuff to ones `.zshenv` really seems inappropriate. This file should contain environment variables and similar, things that should load very fast.

> Thanks again for your work!

I'm happy you like it and that it's useful :)
