### ISSUE TITLE
Page renaming fails if the target directory that does not exist

### ISSUE THREAD

**Issue by wasowski** [lervag/wiki.vim#107]
`wiki#page#rename` fails with a generic message `Cannot rename` if the target directory does not exist.  This makes it difficult (or more difficult than need be) to move pages around. At the very least, I think the error message should be more specific, but I am wondering whether the directories should not be created automatically with something like `mkdir -p` before attempting to move.  One possibility is to keep the current behavior of `WikiPageRename` as is (with a clearer error message) and add `WikiePageRename!` that would also create folders.

Opinions?

(I created a PR to show a test case demonstrating the problem, and also added a small patch to produce a more informative error message.)

**Comment by lervag** [comment]
Thanks for opening this issue! I think it makes sense to create the directory if it does not exist (at least if we ask first). I'll look into your PR later, I've been very busy working on something on vimtex lately, and there's only so much time... :)

**Comment by wasowski** [comment]
No rush at all.  I think the page renaming functionality has still several deficiencies that makes it hard to reorganize your wiki (and messy wiki is really a problem over time).  I just started with this tiny issue, because I am also very overloaded, so I am trying to move in the smallest steps possible, and slowly.  No rush at all.

**Comment by lervag** [comment]
Thanks. Just as a general remark: I've found it useful to "ignore" the mess in my wiki. Entropy always increases. I try to decrease the entropy whenever I work on a topic, but I find it more important to add my thoughts with low-to-no barrier than to make everything structured and well thought-out. I consider my wiki to be very a very long-term investment and anytime I add or improve features to wiki.vim it increases the value of my wiki. [/ot]

**Comment by lervag** [comment]
Ok, let's move the discussion to #108 to keep things in one thread. I'll respond more thorougly there.
