### ISSUE TITLE
Support for Asciidoc style of links

### ISSUE THREAD

**Issue by mgoral** [lervag/wiki.vim#109]
Hi!

First of all, thanks for the great plugin! I use it daily for working with my personal notes and it really is a missing glue which ties things together.

I'd like to know if you're interested in merging support for other styles of links. I'm a big fan of Asciidoc and Asciidoctor so no wonder that links which wiki.vim generates (both `md` and `wiki` link styles) don't fit because other tools don't recognize them as correct Asciidoc links.

Asciidoctor supports inter-document cross references which look like this:

```
<<file.adoc#,title>>
```

They're documented in Asciidoctor's user manual, on Github and forums:

- https://asciidoctor.org/docs/user-manual/#inter-document-cross-references
- https://github.com/asciidoctor/asciidoctor/issues/844
- https://discuss.asciidoctor.org/Relative-InterDocument-Cross-References-one-level-up-td3006.html#a3010

As I said, I have already coded the necessary part and keep it in a private git repo, so it's only the question if you're interested in including it in upstream. If so, I'll gladly send a PR.

Thanks in advance,
MG

**Comment by lervag** [comment]
> First of all, thanks for the great plugin! I use it daily for working with my personal notes and it really is a missing glue which ties things together.

Very happy to hear it! :)

> I'd like to know if you're interested in merging support for other styles of links. I'm a big fan of Asciidoc and Asciidoctor so no wonder that links which wiki.vim generates (both `md` and `wiki` link styles) don't fit because other tools don't recognize them as correct Asciidoc links.

Definitely! Or, at least, I'm interested in considering it! I think there are two main things to consider:

  i) will adding the new link type add a "conflict" with people used to the current wiki and markdown link types?

  ii) if yes on previous: we can still add support, but it may need to be protected with an option that might be defaulted to disabled.

I personally think that wiki.vim should in principle work with any (relevant) filetype, i.e. not limited to e.g. regular markdown. I've tried to consider this when implementing and working on it, but I think there might be some rough edges. In any case, the main features are related to parsing and handling of links. So, adding support for new link types is something I'm generally very happy to do!

> As I said, I have already coded the necessary part and keep it in a private git repo, so it's only the question if you're interested in including it in upstream. If so, I'll gladly send a PR.

Then by all means, feel free to propose a PR! I'll be glad to review and assist in making this fit and merged with wiki.vim.

I'm quite busy at the moment both with some work related things and with something on vimtex, so I might be be able to respond immediately. Still, I try to prioritize responses to PRs, as I respect the effort and work when other people actually contribute real code!

**Comment by mgoral** [comment]
> i) will adding the new link type add a "conflict" with people used to the current wiki and markdown link types?

I think not, but I'm not sure what kind of conflicts you have in mind? The only ones which I can think of is that wiki.vim will now recognize new kind of links and will jump to the places where it finds them, but this shouldn't be a big deal. Other "breaking" change is that I also added a support for toggling adoc style links, so `<leader>wf` toggles them like that: wiki -> md -> adoc -> wiki. 

I just discovered that wiki.vim implements omni function and I'm now fighting with it (can't force it to complete anchors), so I think I'll send a PR when it's ready. Worst case, omni completion for Asciidoc won't complete anchors. :)

**Comment by lervag** [comment]
> > i) will adding the new link type add a "conflict" with people used to the current wiki and markdown link types?
> 
> I think not, but I'm not sure what kind of conflicts you have in mind?

No conflict in particular, just general conservative cautiousness.

> The only ones which I can think of is that wiki.vim will now recognize new kind of links and will jump to the places where it finds them, but this shouldn't be a big deal.

Agreed!

> Other "breaking" change is that I also added a support for toggling adoc style links, so `<leader>wf` toggles them like that: wiki -> md -> adoc -> wiki.

Also not a big deal, I think. Except I think perhaps we should allow configuration for this behaviour, if it is not already available (have to admit I don't remember!).

> I just discovered that wiki.vim implements omni function and I'm now fighting with it (can't force it to complete anchors), so I think I'll send a PR when it's ready. Worst case, omni completion for Asciidoc won't complete anchors. :)

Sounds good! Support for omni completion in asciidoc style links would also be good, I agree. It should not be too hard, but I can see that the regex might be somewhat complex. Let me know if you want help/input.

**Comment by lervag** [comment]
This issue was resolved by @mgoral through #110. Thanks, the contribution is very much appreciated!
