### ISSUE TITLE
Disabling folding

### ISSUE THREAD

**Issue by BonaBeavis** [lervag/wiki.vim#11]
I guess this is kind of a feature request. But here is hacky workaround:

```vim
let g:wiki_mappings_global = {
    \ '<plug>(wiki-link-open)' : '<c>tttt',
    \}
nmap <LocalLeader>w <plug>(wiki-index):set nofoldenable<cr>
au FileType wiki nmap<buffer><cr> <plug>(wiki-link-open):set nofoldenable<cr>
```

**Comment by lervag** [comment]
I'm sorry, but I don't quite follow. Could you please explain what you want to achieve?

**Comment by BonaBeavis** [comment]
I tried it with a minimal init.vim

```vim
set nocompatible              " be iMproved, required
filetype off                  " required
call plug#begin('~/.vim/bundle')
Plug 'lervag/wiki.vim'
call plug#end()
syntax on
filetype plugin indent on    " required

let g:wiki_root = '~/Cloud/wiki/'
set nofoldenable
autocmd Filetype wiki set nofoldenable
```
And the wiki is still folded. I thought it was the plugin, because the filetype stuff gets sourced after the init.vim

**Comment by lervag** [comment]
Sorry, this was actually a bug. In the code that opens a wiki link, I do `normal! zMzvzz` to focus the link target, but `zM` enables folds. I was not aware. I've fixed this now.

**Comment by rattletat** [comment]
Hi @lervag, is there a reason you close all folds? This way, I believe, the user setting of foldlevel is neglected and a foldlevel=0 is forced.

**Comment by lervag** [comment]
Good questions.

> However, I'm not sure why you close all folds by default in the first place. Isn't it done automatically?

No, not necessarily. And I agree/undertand that this is opinionated. Perhaps we should just simplify this to do `zv` if `&foldenable` (which I have there to ensure that the target location is not folded when navigating.

I'd like more opinions on this. @jabirali for instance, what do you think?

**Comment by jabirali** [comment]
Sorry about the late reply... I've been a lot sick lately, so haven't kept up with my notifications :).

> I'd like more opinions on this. @jabirali for instance, what do you think?

Personally, I think I like the same behaviour as you: I like that folding allows me to only see the relevant parts of the file, and I believe the `zMzv` solution fits well with that workflow. 

If you do keep this behaviour, perhaps the snippet of @rattletat can be generalized to all fold levels? Quickly checking the docs, it seems like replacing `zMzv` by `zx` is the most correct solution, and seems to be supported on both Vim and Neovim?

If you decide to remove the `zM` part, I think it could be nice to mention briefly how to set it up again in the documentation :).

**Comment by lervag** [comment]
> replacing `zMzv` by `zx` is the most correct solution

The docs for `zx`:

```
							*zx*
zx		Update folds: Undo manually opened and closed folds: re-apply
		'foldlevel', then do "zv": View cursor line.
		Also forces recomputing folds.  This is useful when using
		'foldexpr' and the buffer is changed in a way that results in
		folds not to be updated properly.
```

I'm not so sure if this is right, though. In the `l:same_file || &foldlevel > 0` case, we don't want to disturb the manually changed folds, only to ensure that the current line is visible (i.e. `zv`). In the other case, we know that `&foldlevel = 0`, which means `zx` should behave the same as `zMzv`, right? Thus, this proposed change does not really change anything? Or did I miss something?

Or did you mean to change the entire snippet and do `zx` in all cases? I don't like that, because e.g. navigation inside the same file should not close other open folds.

Perhaps, though, that this is better (and what you meant)?

```vim
    if l:same_file
      normal! zv
    else
      normal! zx
    endif
```

Opinions, @rattletat and @jabirali?

> If you decide to remove the zM part, I think it could be nice to mention briefly how to set it up again in the documentation :).

Agreed, will do that if I make the change.

**Comment by jabirali** [comment]
Indeed, that's what I meant :). 

Having a different behavior for `l:same_file` is not the issue. I was mainly thinking that I like the current `zMzv` behaviour, but think it would be ideal if `wiki.vim` behaved roughly the same way for `foldlevel=0` and `foldlevel>0`. 

My understanding of the documentation is that replacing `zMzv` with `zx` allows you to handle all fold levels with the same code (as in the code snippet you posted), and provide a consistent behavior.

**Comment by lervag** [comment]
Agreed, thanks. I'll update accordingly.
