### ISSUE TITLE
WikiPageToc doesn't respect g:wiki_link_target_type

### ISSUE THREAD

**Issue by maximilianigl** [lervag/wiki.vim#119]
I've set the target type to `md` with `let g:wiki_link_target_type = 'md'`, but `:WikiPageToc` inserts the TOC with Wiki style links, i.e. `[[link]]` instead of `[text](target)`.

The links appear correct with the related command `:WikiJournalIndex`.

**Comment by lervag** [comment]
Could you provide a simple example with indication of observed vs expected? It would be useful for me both to add a test when implementing, as well as to be sure I understand you correctly.

**Comment by lervag** [comment]
I've made a minor change that should imply that the option is respected, but I'm not sure if the result is quite what you want. Please check.

**Comment by maximilianigl** [comment]
I just tried it and it does what I wanted, thank you!

**Comment by lervag** [comment]
Great, happy to hear it :)
