### ISSUE TITLE
The WikiJournalIndex command always uses the daily date format

### ISSUE THREAD

**Issue by elliottt** [lervag/wiki.vim#121]
# Description

## Expected behavior
When using `:WikiJournalIndex`, the index generated should be finding entries by using the date format that corresponds to the `frequency` setting in `g:wiki_journal`; using a frequency of `weekly` should yield a journal index that finds entries by the `weekly` date format in `g:wiki_journal`.

## Observed behavior
The journal index is always generated with entries that are found by searching with the `daily` format.

# (Brief) Analysis

I believe this is because the implementation of `wiki#journal#make_index()` is unconditionally pulling the date format from the `daily` field of the `g:wiki_journal.date_format` dictionary:

https://github.com/lervag/wiki.vim/blob/548f9052c28f3536bbc197d179ceb108cc66f544/autoload/wiki/journal.vim#L61-L64

Looking up the date format by the value of `g:wiki_journal.frequency` would generate the journal index according to weekly/monthly schedules instead.

**Comment by lervag** [comment]
Thanks. I made the minor update you suggested now, can you test if it suffices? If not, then I'll probably have to take more care and make some real tests of this stuff.

**Comment by elliottt** [comment]
That works! Thanks for the fix :)

**Comment by lervag** [comment]
No problem; thanks for taking the time to look into the problem and locating the source of the issue!
