### ISSUE TITLE
Changing the file name does not update links to it if the url was specified in the format './urltofile'

### ISSUE THREAD

**Issue by DubininDmitry** [lervag/wiki.vim#123]
# Description

I actually always use the link format `./url-to-file` so that the vim coc  plugin can autocomplete the file path.
![image](https://user-images.githubusercontent.com/8066458/103142209-5a40e180-46f7-11eb-8708-579bc2076641.png)
But if I use such a link format, then when the file name changes, the links to it are not updated

# Minimal working example
## Current working link style
I have 2 files: temp1.md and temp2.md
temp1.md have link to temp2.md file:
` [link to temp2](temp2.md)`
When I rename temp2.md file, all working good and link update
![image](https://user-images.githubusercontent.com/8066458/103142307-118a2800-46f9-11eb-9ce8-37515e99d986.png)

## Does not working link style
I have 2 files: temp1.md and temp2.md
temp1.md have link to temp2.md file in other format (and when I press Enter I as usual I can follow the link):
` [link to temp2](./temp2.md)`
When I rename temp2.md file  link in temp1.md file does not update:
![image](https://user-images.githubusercontent.com/8066458/103142360-c7557680-46f9-11eb-9cb5-6c341479743b.png)

---

```vim
let g:wiki_root = '/Documents/demo'                                                                                                     
    let g:wiki_filetypes = ['wiki', 'markdown', 'md']
    let g:wiki_link_target_type = 'md'
    let g:wiki_link_extension = '.md'
    let g:wiki_tags_scan_num_lines = 20
     
    "export settings
    let g:wiki_export = {
          \ 'args' : '',
          \ 'from_format' : 'markdown',
          \ 'ext' : 'html',
          \ 'view' : v:false,
          \ 'output': fnamemodify(tempname(), ':h'),
          \}
    
   " format links
   let g:wiki_map_link_create = 'FormatLinks'
    
   function FormatLinks(text) abort
      return substitute(a:text, '\s\+', '_', 'g')
   endfunction

```

**Comment by lervag** [comment]
Thanks. In this case we need to be sure we agree what is meant by `./`. I would propose that it means `relative to the current file`, as opposed to the already available `/` which means relative to wiki root. I.e., from anywhere in your wiki you can link to `/index` (or `/index.md`) to make a link to the root index.

**Comment by lervag** [comment]
I think I've fixed it, please test.

**Comment by DubininDmitry** [comment]
Works great, thanks!
As far as I can see, the "./" prefix is removed from the url, but this works fine with files in the same directory and subdirectories.

**Comment by lervag** [comment]
Great. And yes, the `./` is removed, but it should not matter, since the prefix does not really add any meaning here anyway.
