### ISSUE TITLE
Renaming a page closes the buffer (and then closes a tab if the last one)

### ISSUE THREAD

**Issue by wasowski** [lervag/wiki.vim#124]
The final part of renaming pages (update and bwipeout) has unintended side effects for me. It closes the buffers, and if the buffer is last in a tab then it also inadvertently looses the tab (with its name and context). I am rather uncertain if this was not a problem before already. In general I would prefer not closing the wiki buffers for updating links. Can't we update them somehow without wipeout? reload? why edit! is not good enough?

I notice that the problem seems to disappear if I deactivate `set hidden`.  Here are some steps to reproduce:
- `set hidden`
- `:tabnew` (or `:vspl`)
- somehow create a wiki page, say `test.md` (make sure that it is only opened in the current tab, not in the other tab)
- `WikiPageRename`, give some name, say `test1.md`
- The renaming works, but the tab is closed (or one of the vertical buffers disappears)

I did not have time yet, to understand which combination of options induces this.

**Comment by lervag** [comment]
I don't use tabs (much), but I do sometimes experience unintended side effects myself, so there is clearly some potential to improve this part. It might work to simply do `edit!` as you propose. E.g. something like this:

1. Remove the `bwipeout` call.
2. Add `edit!` at the place where we currently restore the buffers.

**Comment by wasowski** [comment]
> I don't use tabs (much)

When testing the other patch today I realized that the problem can be demonstrated without tabs as well (just with vertical split). I will revise the description.

**Comment by lervag** [comment]
I think this is fixed now, please test.
