### ISSUE TITLE
Removing periods from link names removes the period before `md`

### ISSUE THREAD

**Issue by daturkel** [lervag/wiki.vim#125]
# Description

Setting the map link create / map create page functions to remove periods from the text also removes the period before the extension.

# Minimal working example

In my config:
```
let g:wiki_filetypes = ['md']

let g:wiki_map_link_create = 'Create'
let g:wiki_map_create_page = 'Create'
function Create(text) abort
  return substitute(tolower(a:text), '\.', '', 'g')
endfunction

let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = '.md'
```

In a file, I type: `node.js`, highlight it, and it enter. I would expect it to turn into `[node.js](nodejs.md)`, but instead it turns into `[node.js](nodejsmd)` (missing `.` before `md`).

**Comment by lervag** [comment]
Thanks, I think this is fixed now.
