### ISSUE TITLE
Completion with file extension?

### ISSUE THREAD

**Issue by daturkel** [lervag/wiki.vim#126]
This is a small feature request. I use the markdown-style links and if I type `[a link](` and hit tab, I get a list of wiki page names, as desired. I would love, however, to have the option for the completion choices to be full filenames rather than just the roots, i.e.:
```
foo.md
bar.md
baz.md
```
instead of just
```
foo
bar
baz
```

**Comment by lervag** [comment]
Thanks, I agree. The completion feature should respect the `g:wiki_link_extension` option. I think it is fixed now.

**Comment by daturkel** [comment]
Can confirm it works, thanks for the quick fix!

**Comment by lervag** [comment]
Great, happy to hear it :)
