### ISSUE TITLE
Asciidoc links created with double suffix

### ISSUE THREAD

**Issue by dgengtek** [lervag/wiki.vim#128]
# Description

Creating a link from the initial string `test` in the index creates `<<test.adoc.adoc#,test>>` to a file ~/wiki/test.adoc which works when working from the plugin wiki.vim but obviously the double suffix is an issue when exporting.

Also is there a way to change the index.wiki to index.adoc?

# Minimal working example

Please provide a minimal working example, for instance something like this:

```
wiki/
├── index.wiki
└── test.adoc
```

```vim
let g:wiki_root = '~/wiki'
let g:wiki_link_target_type = 'adoc'
let g:wiki_link_extension = '.adoc'
let g:wiki_filetypes = ['wiki', 'adoc']
```

**Comment by lervag** [comment]
Thanks, I think this is fixed now.
