### ISSUE TITLE
Link autocomplete doesn't work for parent folders

### ISSUE THREAD

**Issue by daturkel** [lervag/wiki.vim#130]
# Description

The root of my wiki is `~/Documents/wiki`, but I have a couple subfolders inside.

If I'm in a top-level file and type `[foo](` then `<tab>`, I get completion for every page in the wiki, including ones in subfolders.

If I'm in a lower-level folder, however (`~/Documents/wiki/foo/index.md`), then `[foo](` will only autocomplete files _below_ the current file, not all files in the wiki. Additionally, if I try `[foo](../` then `<tab>`, I get filesystem completion, but not wiki.vim completion.

I'm not sure if this is a bug or intended behavior, but I'd love the ability to have the autocomplete support links to files "above" the current file.

# Relevant settings

```vim
let g:wiki_root = '~/Documents/wiki'

let g:wiki_filetypes = ['md']

let g:wiki_map_link_create = 'Create'
let g:wiki_map_create_page = 'Create'
function Create(text) abort
  let lowered = tolower(a:text)
  let no_spaces = substitute(lowered, '\s\+', '-', 'g')
  let no_symbols = substitute(no_spaces, "[!?\\\.']", '', 'g')
  let no_quotes = substitute(no_symbols, '"', '', 'g')
  return no_quotes
endfunction

let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = '.md'

let g:wiki_write_on_nav = 1

nmap <silent> <c-b> <plug>(wiki-index)
nnoremap <silent> <c-t> :e ~/Documents/wiki/todo.md<CR>
nmap <silent> <c-n> <plug>(wiki-open)

```

**Comment by lervag** [comment]
Not a full solution, but: Can you try `[foo](/` then `<tab>`? The `/` indicates the root of the wiki. This type of link will not work if you convert the wiki (e.g. with pandoc), though, which is important to note.

Completion currently does not support going back in the directory tree, but I might consider looking into it.

**Comment by daturkel** [comment]
This...sort of works. `[food](/` indeed does give me a list of all pages in the wiki, but the suggestions actually don't start with a `/`, so selecting any of them will delete the `/` I typed and create `[food](some/link.md)` which, when followed, goes to the wrong place (an empty file).

I confirmed that if I manually insert the slash at the front of the link, then following it does work correctly.

I also noticed while testing this that the autocomplete matching only works on the filename itself, and not the path. Is that intended behavior? E.g. typing `blah` doesn't match `blah/index.md` but `index` does.

**Comment by lervag** [comment]
I've fixed the glitch you noticed; using `/` should now work without removing it. Please test.

> I also noticed while testing this that the autocomplete matching only works on the filename itself, and not the path. Is that intended behavior? E.g. typing `blah` doesn't match `blah/index.md` but `index` does.

I can't reproduce that. For me, it seems to work 

----

Btw, please note that the `[...](...)` markdown link type is really a general purpose link syntax. I think the current completion behaviour is OK, but I don't think it makes that much sense to think of this as general file links with the `../` syntax. For file completion, you can also just do `<c-x><c-f>`, i.e. `[...](../<c-x><c-f>` should already do almost exactly what you want.

**Comment by daturkel** [comment]
> I've fixed the glitch you noticed; using / should now work without removing it. Please test.

I can confirm this is working now! (I think that closes this specific issue.)

> [re: the other autocompletion issue] I can't reproduce that. For me, it seems to work

I can't reproduce it anymore either. Maybe I was doing something weird.

> For file completion, you can also just do <c-x><c-f>, i.e. [...](../<c-x><c-f> should already do almost exactly what you want.

Yep, that works too, but is no longer necessary (for me) now that I know about the `/` completion.

Thanks for your help!

**Comment by lervag** [comment]
Great, happy to hear it! :)
