### ISSUE TITLE
Support for enumerated lists

### ISSUE THREAD

**Issue by cristobaltapia** [lervag/wiki.vim#131]
Hi, I wanted to ask weather it would be possible to also support enumerated lists? Currently only bullet lists are supported by the list-specific commands (like move-up or move-down). Is that something that should be implemented here, or should I use another plugin for that functionality?

**Comment by lervag** [comment]
I guess everything is possible. The reason I have not done it are that I typically don't use many ordered lists myself, so I have not really needed it. Also, it does present a slightly more complex challenge than unordered lists.

But I can consider it. If I were to implement support for ordered lists we would need:

1. To specify the supported syntax (does it suffice with a regex like `^\s*\d\+\.`?`).
2. Do we need to update the numbering after altering (e.g. move-up/-down)?
3. How should nested lists work?

I don't have that much time on my hands, so I won't promise any quick implementations. But I do think it makes sense to add support after deciding on a sufficient specification. I propose the following: We discuss these things here, then I open a new issue with a step-by-step todo list that, by the end, will implement what we agree is a sufficient feature set.

**Comment by cristobaltapia** [comment]
@lervag sure, there is no hurry. Thanks for considering it.


> 1. To specify the supported syntax (does it suffice with a regex like `^\s*\d\+\.`?`).

I think that that should be enough. We don't need fancy sub-enumeration patterns. Maybe we can make the implementation flexible enough so that it can also work with chars, i.e. `^\s*\a+\.`? 

> 2. Do we need to update the numbering after altering (e.g. move-up/-down)?

Yes. Ideally one should be able to add a new line in-between a list and the rest of the numbers would be updated. Btw, one think that might be useful in lists in general would be the automatic insertion of a bullet in a new line (certainly that is also not trivial, as you don't always want that behavior... but just a thought).

> 3. How should nested lists work?

Maybe the level is detected based on the `tabstop` configuration? Also, there could be a function to change the hierarchy level of a line, which gets triggered by the indentation of a line. In that case, the numbers would need to be updated. For example:

before
```
1. one
2. two (<- cursor here. Indent)
3. three
4. four
```

after
```
1. one
    1. two
2. three
3. four
```

Maybe this could also work in visual mode, to move a set of lines one level deeper:

before
```
1. one
2. two (*visual selection)
3. three (*visual selection, Indent)
4. four
```

after
```
1. one
    1. two
    2. three
2. four
```

Maybe a simple way to handle the update of the numbers is to define a function that correctly enumerates consecutive lines that match the regex pattern `^\s*\d+\.`, taking into consideration the nested lists. Then, this function could be executed each time a new element is added, moved, deleted or indented  (previous checking that the line is on an enumerated list).

PS: I like that you used an enumerated list just after you said you normally don't use many ordered lists :)

**Comment by nickwynja** [comment]
@cristobaltapia [bullets.vim](https://github.com/dkarter/bullets.vim) supports this feature. In my opinion, it would be sad to see wiki.vim get bloated with features already implemented in other plugins.

**Comment by cristobaltapia** [comment]
@nickwynja Thanks for pointing that out! That is exactly what I wanted  (actually more)! I agree with you. I think that there is no need to add such functionality to wiki.vim if one can have it with that plugin. Bad research on my side. Sorry.

I will close this issue.

**Comment by lervag** [comment]
> [bullets.vim](https://github.com/dkarter/bullets.vim) supports this feature. In my opinion, it would be sad to see wiki.vim get bloated with features already implemented in other plugins.

@nickwynja Thanks for your comment. I basically agree wholeheartedly. The support for lists in wiki.vim is added "pragmatically" because I wanted those features and I did not see them in any other plugins. I think a sensible way forward is to separate the feature into a new plugin and link to it from the readme and docs. The features in wiki.vim are both more and less complex than those of bullets.vim. The important ones in wiki.vim from my point of view are:

* I can "simplify" lists with `<leader>wlu`.
* I can move list items (with child items) up and down with `<leader>wl[jk]`.

I'm thinking that I might want to add support for the numbered lists first, then separate the plugins after. When separated, I can also link to `bullets.vim` to make it easier for users to choose.

**Comment by nickwynja** [comment]
> The support for lists in wiki.vim is added "pragmatically" because I wanted those features and I did not see them in any other plugins. 

Yes, these are nice features!

> I think a sensible way forward is to separate the feature into a new plugin and link to it from the readme and docs. The features in wiki.vim are both more and less complex than those of bullets.vim.

Maybe they could be contributed to the bullets.vim project directly? I know that contributing to other projects isn't always as easy as it ideally sounds, though.

**Comment by lervag** [comment]
> > I think a sensible way forward is to separate the feature into a new plugin and link to it from the readme and docs. The features in wiki.vim are both more and less complex than those of bullets.vim.
>
> Maybe they could be contributed to the bullets.vim project directly? I know that contributing to other projects isn't always as easy as it ideally sounds, though.

I'll consider that, but I would first want to fully separate this from wiki.vim.

**Comment by lervag** [comment]
FYI: I've now added initial support for ordered lists. It's not fully complete, but the basics are in place for e.g. renumbering to be implemented.

**Comment by lervag** [comment]
FYI: The list functionality is now provided in [lists.vim](https://github.com/lervag/lists.vim) and will be removed from wiki.vim in a few minutes.
