### ISSUE TITLE
Restrict plugin operation to only paths listed to wiki root

### ISSUE THREAD

**Issue by dgengtek** [lervag/wiki.vim#132]
# Description

Is there a way to disable the plugin globally like in vimwiki with `g:vimwiki_global_ext = 0`? 

I am currently still using vimwiki plugin until I get a working conversion from vimwiki syntax to asciidoc syntax but if I use both the vimwiki plugin and the wiki.vim plugin then <CR> for creating links is overriden by wiki.vim when working in the vimwiki root directory.

From help page of vimwiki:
```

*g:vimwiki_global_ext*

Control the creation of |vimwiki-temporary-wiki|s.

If a file with a registered extension (see |vimwiki-register-extension|) is
opened in a directory that is: 1) not listed in |g:vimwiki_list|, and 2) not a
subdirectory of any such directory, then:

Value           Description~
1               make temporary wiki and append it to |g:vimwiki_list|.
0               don't make temporary wiki in that dir.

If your preferred wiki extension is .txt then you can >
    let g:vimwiki_global_ext = 0
to restrict Vimwiki's operation to only those paths listed in g:vimwiki_list.
Other text files wouldn't be treated as wiki pages.

Default: 1
```

**Comment by lervag** [comment]
Currently, no: but you can disable the plugin entirely if you add `let g:wiki_loaded = 1` to your vimrc file.

I do not quite understand why you want this feature. But do I understand correctly that an option like `g:wiki_global` which, if set to 0, implies that the wiki buffer initialization should only happen within the specified `g:wiki_root`?

That is, if we had the following config:

```vim
let g:wiki_root = '~/mywiki`
let g:wiki_global = 0
```

Then `wiki.vim` should only be active for the desired filetypes within `~/mywiki`. Do I understand correctly?

**Comment by dgengtek** [comment]
Thank you for the reply, this helps. `g:wiki_loaded` is not listed in the docs.

> I do not quite understand why you want this feature. 

I was primarily looking if there was already a conventional solution while still using both plugins until I was finished migrating from vimwiki over to wiki.vim. 

Since until now I was loading wiki.vim conditionally in my vimrc for the wiki path though your hint with filetypes lead me to restricting and renaming the files in the wiki to .adoc and setting the option `let g:wiki_filetypes = ['adoc']` instead of  `let g:wiki_filetypes = ['wiki', 'adoc']` which does what I wanted originally namely not be in conflict with vimwiki and only enable the plugin when working with asciidoc.

> But do I understand correctly that an option like g:wiki_global which, if set to 0, implies that the wiki buffer initialization should only happen within the specified g:wiki_root?
> 
> That is, if we had the following config:
> 
> let g:wiki_root = '~/mywiki`
> let g:wiki_global = 0
> 
> Then wiki.vim should only be active for the desired filetypes within ~/mywiki. Do I understand correctly?

Yes this is what `g:vimwiki_global_ext` does in vimwiki.

In that sense you can close the issue if you do not want this feature since `g:wiki_filetypes` already does what I originally wanted.

**Comment by lervag** [comment]
I've added `g:wiki_global_load` (I think this names is slightly better). Let me know if it works as you wanted.
