### ISSUE TITLE
Add the possibility to create new note from WikiFzfPages

### ISSUE THREAD

**Issue by fikovnik** [lervag/wiki.vim#133]
I really like the `WikiFzfPages` and I was wondering if it could have one more functionality: if I search for a page that does not exist, it would allow me to create it straight from fzf using the search query for the file name.

For example I search for non-existing page "VIM folds" and press enter upon which it asks me if I want to create a new page in the wiki root dir called "VIM folds.md". If the query contains path separators, it will also create the appropriate directory structure.

This way there is an easy interface for searching and creating new pages. Something like the [National Velocity](https://notational.net/) App did.

What would be even cooler is if there was another command `WikiFzfSearch` which would search the content wiki files and if no entry found also allowed one to create a new note.

**Comment by lervag** [comment]
> I really like the `WikiFzfPages` and I was wondering if it could have one more functionality: if I search for a page that does not exist, it would allow me to create it straight from fzf using the search query for the file name.

Thanks, this is an interesting proposal, and I agree it looks useful!

I'll have to investigate whether Fzf has a feature that allows this, though. I'm not sure it does.

**Comment by lervag** [comment]
> What would be even cooler is if there was another command WikiFzfSearch which would search the content wiki files and if no entry found also allowed one to create a new note.

I personally use other tools to search content, and I think that makes more sense. I use [ctrlsf.vim](https://github.com/dyng/ctrlsf.vim), which I find extremely useful for lots of things. With ripgrep as a backend, it is also very fast even for large contents. I don't quite see how I can "compete" in this sphere, and although I can see how this is useful to some people, I need to keep the features at a maintable level. So I hope you don't mind (much) that I will reject this feature.

**Comment by lervag** [comment]
I think I figured it out. Let me know what you think.

**Comment by fikovnik** [comment]
Amazing! Thanks a lot!

It is very good as it is, I guess I would only opt for confirmation instead of a delay, but regardless - it is perfect.

Regarding the other feature - I thought it would be possible to plug-in the Rg from fzf.vim - but I understand that it would make another dependency and it is likely something I should done myself in my vimrc. Now I know how to create a new page so I think I can hack it together.

**Comment by lervag** [comment]
> Amazing! Thanks a lot!

Your welcome; thanks for suggesting, I think I might use this feature myself as well. :)
>
> It is very good as it is, I guess I would only opt for confirmation instead of a delay, but regardless - it is perfect.

Actually, I also wanted the confirmation. However, I did not find a way to make the FzF callback function interactive. I could not find any references or documentation of it either, and I figured that the current version works well enough. If you didn't want the new page, then simply close that buffer. The file is not written to disk until you manually do so.

> Regarding the other feature - I thought it would be possible to plug-in the Rg from fzf.vim - but I understand that it would make another dependency and it is likely something I should done myself in my vimrc. Now I know how to create a new page so I think I can hack it together.

Great; I think "hacking" personal solutions is one of the great things about Vim (and very probably also Emacs) that helps us become productive.

**Comment by fikovnik** [comment]
Makes sense. In this case, I guess the is probably no need for the delay.

> Great; I think "hacking" personal solutions is one of the great things about Vim (and very probably also Emacs) that helps us become productive.

I'm actually coming from emacs (I used it for ~6 years) and it was actually this and your other plugin (vimtex) that help me to do the final decision to switch :-) Thanks a lot!

**Comment by lervag** [comment]
> Makes sense. In this case, I guess the is probably no need for the delay.

The delay is there because if I remove it, there will be no message. Thus, it might be surprising to a user what is happening. That is, as you might notice, the warning/message from  wiki.vim disappears after the delay. I can't change that, and so I find it is more important to give some kind of feedback about what happens than to avoid the delay. :\

> > Great; I think "hacking" personal solutions is one of the great things about Vim (and very probably also Emacs) that helps us become productive.
> 
> I'm actually coming from emacs (I used it for ~6 years) and it was actually this and your other plugin (vimtex) that help me to do the final decision to switch :-) Thanks a lot!

Nice. I'm happy you like my work!
