### ISSUE TITLE
Question: sidebar index

### ISSUE THREAD

**Issue by klooj** [lervag/wiki.vim#134]
_This is more of an RFC than a feature request_

## I want to use the root index as a sidebar type file navigator. 

In other words, I'd like to: 

- open the root index in a modifiable buffer with a 25-30 column wide window; and, 
- when following a link, defaults to opening pages in the existing "primary" window---rather than opening the link in the same window as the index or creating another split for it. 

To illustrate, from left to right in the image below: window1 is a file tree [plugin](https://github.com/kyazdani42/nvim-tree.lua), window2 would be the "index" window, and window3 would be the "primary" window. When following a link in window2, the page would open in window3 without resizing anything. Essentially, I'd like the wiki index to open pages the same way files are opened by the tree plugin. 

![image](https://user-images.githubusercontent.com/57016271/107081381-98362880-67c0-11eb-979c-76029685770d.png)

## This functionality would be particularly helpful in my organizing process. 

For better or worse,  I frequently jot things down in a journal entry or some other temporary place and then, once a week, go back and collate and properly classify them into the wiki.  The issue is that many things that will fall under the same classification are scatted among different files. Creating a new split every time I follow a link gets unwieldy quickly but opening it in the index page implements resizing considerations ... which equates to a ton of keystrokes and ninja'ing. 

Like I mentioned at the top, this request is for expertise and advice. I do not know the codebase nor how complicated this implementation would be. If it's non-trivial, I don't want to impose on your time; you could just tell me where to look and generally what levers need to be pulled .  I would not mind taking a stab at a pull request with the eventual solution if you'd like. 

Thanks.

**Comment by lervag** [comment]
> Like I mentioned at the top, this request is for expertise and advice. I do not know the codebase nor how complicated this implementation would be. If it's non-trivial, I don't want to impose on your time;

I have to say I think this is nontrivial, and at the very least a _very_ subjective feature. IMHO, it does not feel like a feature I want to be part of wiki.vim.

> you could just tell me where to look and generally what levers need to be pulled . I would not mind taking a stab at a pull request with the eventual solution if you'd like.

However, I do never really mind to discuss actual PRs and submitted feature suggestions. As long as new features are not in the way of keeping this maintainable, I think it can be interesting.

Still: What are you really asking for? Or, what is the editing process that you
are trying to achieve here?

To me, it sounds like you are creating a lot of small "semirandom" files that
you regularly organize more properly. Further, it seems you are doing this by
creating a keyword in the index, which you toggle into a link to a new page,
then you add the content in the new page. While organizing, you go through this
list of new files and "tidy" things/write things out.

Personlly, I don't see any real use of having a file tree viewer open at any time. I use `:edit ...` or wiki features to open files, or `:WikiFzfPages`, or `:Fzf` or similar type of fuzzy finders. My approach to how I understand your workflow would be quite similar to yours, except:

* I would open the index in a single window, then navigate to the list of new entries.
* I would use `<cr>` or `<ctrl-cr>` (latter opens link in a split) to open the entries, then do the required editing. If I want to copy/organize between files, then I would open the alternate file in a new split, e.g. with `:WikiFzfPages` and `<c-w>s` or similar.
* I use the `<ctrl-^>` mapping extensively (although, on my keyboard `^` is difficult to type, so I have remapped it to `<ctrl-e>`) to switch between the current and alternate buffer. It is really _really_ useful!

So, essentially, I'm challenging you to consider your own workflow. Do you really need what you ask for, or can you live with the built-in features in Vim? I propose that you can, but that you might want to learn some more of these basic/intermediate/advanced features, and that this will also be useful to you in other areas.

That said: I accept that people are different and that we in general have different ways of working and thinking, and I don't mind adding features that I personally don't like/want, if they are well thought out and clearly fits some well-thought out work flow.
