### ISSUE TITLE
Documentation titles do not conform with the name of the project

### ISSUE THREAD

**Issue by C-Fergus** [lervag/wiki.vim#136]
Every reference to the title of the project in the documentation is written as `vimwiki` instead of `wikivim` or `wiki.vim`, including the ASCII header. This prevents accessing the documentation with `:help` using any permutation of `wiki`, `.`, and `vim` other than just `wiki`.

Either the title of the project should be changed or the documentation should be updated to move away from the "vimwiki" name.

Personally I like the name of the project and would be happy to open a pull request to change the docs to use either `wikivim` or `wiki.vim` if you approve of the suggestion. If so, I think `wikivim` is a better solution than `wiki.vim` because I prefer not to type non alphanumerics when referencing object names.

**Comment by C-Fergus** [comment]
I was having issues with helptags still referencing vimwiki after removing it and installing wiki.vim. The main issue is closable although I would still prefer at least one reference to `wikivim` in the docs.

**Comment by lervag** [comment]
The following should work: `:help wiki.txt` (this is the "standard" way to define plugin doc reference), `:help wiki.vim` (this is the name of the plugin), `:help wiki-...`. I don't see that much value in adding `:help wikivim`, to be honest. Your original issue seems related to you having both vimwiki and wiki docs simultaneously, in which case there is an understandable overlap between the help tags.
