### ISSUE TITLE
vimwiki vs vimtex viewer difference question.

### ISSUE THREAD

**Issue by Traap** [lervag/wiki.vim#137]
I use both vimtex and wiki.vim almost daily.  Thank you for these tools.

I use both okular and zathura to view pdf documents on an archlinux computer.

I would like to have wiki.vim _reuse_ the same tab (okular) or window (zathura)
when I export a wiki page as vimtex does.

I am assuming I have configured something wrong, or missed something in the
documentation.

Any pointers are welcomed.

**Comment by lervag** [comment]
> I use both vimtex and wiki.vim almost daily. Thank you for these tools.

Glad to hear you like them!

> I would like to have wiki.vim _reuse_ the same tab (okular) or window (zathura)
> when I export a wiki page as vimtex does.
> 
> I am assuming I have configured something wrong, or missed something in the
> documentation.
> 
> Any pointers are welcomed.

The viewer is specified with `g:wiki_viewer`, and `:WikiExport` will use this choice by default. You can also specify the viewer with an argument, `:WikiExport -viewer "..."`.

Personally, I don't really use the `WikiExport` feature much, and I've never found it necessary to reuse a Zathura window or reuse a tab in Okular. But I would guess that you can add options, if those exists, to specify this?

With Zathura: Let's say you are in a terminal and open a file `test.pdf`. How do you open `other.pdf` in the same Zathura window from a terminal?

**Comment by Traap** [comment]
> With Zathura: Let's say you are in a terminal and open a file `test.pdf`. How do you open `other.pdf` in the same Zathura window from a terminal?

This workflow does create a second window.

When I use vimtex and change LaTeX line then save the file; the compilation reuses the open zathura window.   BTW.  The same behavior is same with SumatraPDF, okular, and zathura viewers.  I use different viewers because of operating system differences and computers differences, some I can't change, that make it difficult for me to always use the same viewer [That is another topic. :) ]

I was hoping WikiExport would behave like vimtex so I could have review the pdf document before I email.  My goal is to use wikivim to take meeting notes and send a pdf document afterwards. 

These are my wiki.vim settings.
let g:wiki_viewer = { 'pdf': 'zathura' }

let g:wiki_export = {
    \ 'args' : '',
    \ 'from_format' : 'markdown',
    \ 'ext' : 'pdf',
    \ 'view' : v:true,
    \ 'output': 'printed',
    \}

**Comment by lervag** [comment]
> > With Zathura: Let's say you are in a terminal and open a file `test.pdf`. How do you open `other.pdf` in the same Zathura window from a terminal?
> 
> This workflow does create a second window.

That's my point; my question is, how do we avoid creating the second window? If I were to implement something for wiki.vim, I would first need to understand _how_ to do it. One possibility would be to add arguments to the viewer to avoid opening a new window, but I don't know which arguments that would be (at least not for Zathura or Okular).

Another possibility would be to allow a custom event or function instead of a viewer. That could allow a hack with xdotool and Zathura that might work, but it is hard to see an elegant solution here. Still, it might allow relevant user customization.

> When I use vimtex and change LaTeX line then save the file; the compilation reuses the open zathura window.

This is because of the `--forward-search` option, which relies on SyncTeX. We don't have synctex in this case, and so I don't see how to replicate the behaviour directly.

> I was hoping WikiExport would behave like vimtex so I could have review the pdf document before I email. My goal is to use wikivim to take meeting notes and send a pdf document afterwards.

Thanks; knowing the end goal is useful.

So, first: are you able to figure out how to do this from a terminal? If so, then I might be able to implement something on top of that.

**Comment by Traap** [comment]
> This is because of the `--forward-search` option, which relies on SyncTeX. We don't have synctex in this case, and so I don't see to replicate the behavior directly.

Understood.  I'll do some digging.


> So, first: are you able to figure out how to do this from a terminal? If so, then I might be able to implement something on top of that.

I have two test environments to check:

1.  Windows 10 / Windows Sub System for Linux 2 & Ubuntu LTS 20.04 /  vim & neovim / SumatraPDF  .. [windoz]
2. ArcoLinux / vim & neovim / okular | zathura .. [linux]

[windoz] is tricky because vim + vimtex | wiki.vim run on Ubuntu and display on Windows 10.
[linux] .. well ... ... ... easy setup.

I'll report back findings.

Thanks for helping.

**Comment by Traap** [comment]
Bottom line:  wiki.vim works.

I have summarize test findings.

Window / Tab reused when underlying pdf file changed via WikiExport.

[windoz]
  * SamatraPDF is installed into Windows 10. 
  * SamatraPDF was configured to reuse open windows / tabs.
  * vim / neovim tested from *Git Bash* on Windows 10 worked.
  * vim / neovim tested from bash wsl2/Ubuntu worked.

  * Okular is installed into Windows 10. 
  * Okular was configured to reuse open windows / tabs.
  * vim / neovim tested from *Git Bash* on Windows 10 worked.
  * vim / neovim tested from bash wsl2/Ubuntu *failed*.  Okular could not find
    the network file path.

  * Zathura is not available for Windoz.

[linux]
  * Okular was configured to reuse open windows / tabs.
  * vim / neovim tested from bash worked.
  * SamataPDF isis not available for archlinux.
  * zathura did not work.

[zathura observations]
  * I could not find configuration options similar to those provided by
    SamatraPDF and Okular.
  * WikiExport always created a new instance of zathura.
  * Oddly, all instances are updated with new text.

I use bspwm tiling window manager.  I need to continue checking window manager
configurations.

**Comment by Traap** [comment]
Wiki.vim is working correctly.

I have a configuration issue with ArocLinuxB 5.11.7-arch-1, 
bspwm, and zathura. Okular is an acceptable alternative.

Thanks Karl for keeping this open as I have tested my 
configurations on several systems.

**Comment by lervag** [comment]
> Bottom line: wiki.vim works.

Thanks! Glad to hear it.

> I have summarize test findings. ...

Thank you, this is useful info.

> [zathura observations]
> ...
> * Oddly, all instances are updated with new text.

Not so odd: Zathura will reload the viewed file automatically if it notices that it changes (see `:man zathurarc` and search for "reload" to get some more info on how this works). To manually reload, use the `R` mapping.

Perhaps an option for you with Zathura would be to have two `WikiExport` variants, one where you explicitly tell wiki.vim not to open a viewer? E.g., make two maps: One to export and view, and another to _just_ export.

> Thanks Karl for keeping this open as I have tested my
> configurations on several systems.

Thanks for testing and reporting your findings. It seems I can safely close this now. Feel free to open new issues!
