### ISSUE TITLE
Unmap default binding

### ISSUE THREAD

**Issue by romariorobby** [lervag/wiki.vim#139]
I use [which-key](https://github.com/liuchengxu/vim-which-key) and i tried to unmap all the default binding with `let g:wiki_mapping_use_defaults  = 'none'` but its not work for me . it works though with this :
```vim
let g:wiki_mappings_global = {
 	\ '<plug>(wiki-reload)' : '<leader>nr', 
\ }
```
but i'd like to unmap all the binding and remap again within my whichkey configurations.
This is some binding what i'd like to unmap:
![image](https://user-images.githubusercontent.com/40323094/112726327-6125fd00-8f4f-11eb-9e04-b9ee3ebbf42d.png)

did i miss something? or am i doing incorrectly?

**Comment by lervag** [comment]
No, it _should_ work. So either it is a bug, or your doing something wrong.

Can you show me how you are applying your configuration? Vimrc file, etc?

**Comment by lervag** [comment]
Just to be clear: If I add `let g:wiki_mappings_use_defaults = 'none'`, the mappings will not be defined on my end.

**Comment by romariorobby** [comment]
> No, it _should_ work. So either it is a bug, or your doing something wrong.
> 
> Can you show me how you are applying your configuration? Vimrc file, etc?
I use neovim 0.5 
![image](https://user-images.githubusercontent.com/40323094/112747707-413f1980-8fe1-11eb-9317-9ac171205b9d.png)

**Comment by lervag** [comment]
> > I use neovim 0.5

I'm sorry, but this does not really help very much. Can you make a minimal example? Please notice that you are not really providing many details here, neither on your config, nor on the issue. What I've understood so far is that you claim that wiki.vim is applying mappings even though you have set `g:wiki_mapping_use_defaults` to `none`. Perhaps it is merely a type? Note `mappings` vs `mapping`?

**Comment by romariorobby** [comment]
Oh Sorry... Problem solved . i just missed type it . it doesnt give me an error or anything thats why. i should read the help wiki carefully. Thanks for the help.

**Comment by lervag** [comment]
> Oh Sorry... Problem solved . i just missed type it . it doesnt give me an error or anything thats why. i should read the help wiki carefully. Thanks for the help.

No problem, glad to hear it works!
