### ISSUE TITLE
Unable to create a wiki page with a name that's a prefix of existing page's name

### ISSUE THREAD

**Issue by digital-carver** [lervag/wiki.vim#140]
If I have an existing page called, let's say, "Testing" (`Testing.md` on the filesystem), and I insert `Test` (from insertmode) then press Enter from normal mode, expecting to create a file called `Test.md`, instead it gets turned into `[/Testing](/Testing)`. 

### Steps

1. Type `Testing` in a wiki file, press Enter twice, to create link and then go to the `Testing.md` page
2. Make some edit on the `Testing.md` page and save it 
3. Go back to the original wiki file, and on  a new line, type `Test`.
4. Press enter on it.

**Expected**: A link to a page called `Test.md` is created.
**Actual behaviour**: The text `Test` is changed into `[/Testing](/Testing)`.

This happens even if I visually select the word Test and then press Enter. 

My wiki.vim config is just 
```
let g:wiki_filetypes = ['md', 'wiki']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
```

and then two lines setting `wiki_root` and `wiki_zotero_root`. 

I'm new to wiki.vim, so I'm not sure if this is a config issue or a bug.

**Comment by lervag** [comment]
Thanks, this has annoyed me as well. I pushed one possible fix for it now. What do you think of this solution?

**Comment by digital-carver** [comment]
I don't have much familiarity with this code base, but if I understand correctly, this changes it to use only exact matches? Wouldn't any such exact matches already have been handled by the `" Next try at wiki root` section of code a few lines ago? So this branch should never actually succeed, if my (admittedly shallow) understanding of this code is right.

**Comment by lervag** [comment]
Ah, yes, you are right. The code can be simplified further. Thanks for looking at the patch and letting me know!

By the way: My patch should still work; the only "issue" is that the modified conditional branch is never reached. So, the original issue sholuld still be fixed, and my main point of "what do you think of this solution?" was regarding usage, and I'm still interested to know if you find the current behaviour satisfying.
