### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by nkh** [lervag/wiki.vim#150]
Hi, any user documentation, blog post, youtube video show casing the different features and/or introduction to the plugin?

the reference manual is fine, complete and easy to read but as any reference manual not real good at explaining how to use the plugin, the different scenarios where it can be used and the difference between using one option/link type/export tool.

PS: the readme contains a reference tot TODO which doesn't exist

**Comment by lervag** [comment]
> Hi, any user documentation, blog post, youtube video show casing the different features and/or introduction to the plugin?

No, not that I'm aware of.

> the reference manual is fine, complete and easy to read

Thanks!

> but as any reference manual not real good at explaining how to use the plugin, the different scenarios where it can be used and the difference between using one option/link type/export tool.

I agree. I've not prioritized such things, as I tend to do the things I like the most. But I see your point and I agree that a short write up about how to use wiki.vim might be useful to new users.

I'm not quite sure exactly how to do this in a good way, though. I don't really keep a personal blog. So perhaps adding a section to the vim docs? Or in the README or in a separate readme like file?

This might also be a topic where others could contribute. If someone were to write something, I would be glad to review it and give my opinions/comments to help make it good.

> PS: the readme contains a reference tot TODO which doesn't exist

Thanks! I'll fix that.

**Comment by nkh** [comment]
Well a wiki could be a good start ;)

I actually have a program that I have tried to document for the last, hrrrm
..., 20 years and that's why I want a wiki in Vim. I want to generate man
pages and an info page from it. because applications without a man page are
bad, even if they are good.

I like the idea of separating wiki and language, actually it would be great
if the links could be anything because I'd love to see a Pod (Perl plain
old documentation) wiki plugin.

Cheers, Nadim.

**Comment by lervag** [comment]
> Well a wiki could be a good start ;)

[Feel free](https://github.com/lervag/wiki.vim/wiki), I don't mind if you or anyone adds content to the repo wiki. But note, I don't have the time to personally maintain the repo wiki.

> I actually have a program that I have tried to document for the last, hrrrm ..., 20 years and that's why I want a wiki in Vim. I want to generate man pages and an info page from it.

How would you generate those? Pandoc? Most people use wiki.vim with Markdown format, I believe. I personally use a Markdown variant where I use the Mediawiki style links for internal/wiki links (i.e. `[[...]]`).

> ... actually it would be great if the links could be anything because I'd love to see a Pod (Perl plain old documentation) wiki plugin.

I don't understand what you mean. There's a lot of different types of links that are currently supported. If you want more, then feel free to open feature requests. But if so, please be specific, provide examples, preferably references to specifications, and so on.

----

wiki.vim is **not** a filetype plugin, and the aim is to be a more or less file agnostic pluging that adds the wiki style link handler for the desired file types.

**Comment by simchuck** [comment]
I am just starting to learn `wiki.vim`, but reading the documentation hasn't really helped me understand enough of the details to develop any kind of acceptable workflow.  I tried to search online for tutorials or videos but came up with nothing.  

It would be a great start if someone could post a 5 minute video that demonstrates a workflow that uses at least a few of the main features, and perhaps also an intro to customisation or other advanced features.

**Comment by lervag** [comment]
> I am just starting to learn `wiki.vim`, but reading the documentation hasn't really helped me understand enough of the details to develop any kind of acceptable workflow. I tried to search online for tutorials or videos but came up with nothing.

> It would be a great start if someone could post a 5 minute video that demonstrates a workflow that uses at least a few of the main features, and perhaps also an intro to customisation or other advanced features.

I think some of my replies above explains in part the lack of tutorials/videos, at least why I have not made any myself. I would not mind a contribution in this direction at all. I think the best I can do here is to write a short text on a reasonable workflow. I'll leave this issue open until I've done that.

**Comment by simchuck** [comment]
Understood.  I would love to help, but since I haven't used `wiki.vim`
before I don't even know where to start.  You mention that it is based on
`vimwiki`, which seems to have a lot of information online.  What are the
main differences?  Are they similar enough that even referencing some of
these other resources would provide a decent starting point?

**Comment by lervag** [comment]
> Understood. I would love to help, but since I haven't used `wiki.vim` before I don't even know where to start.

No problem. Help when and if you find yourself capable to!

> You mention that it is based on `vimwiki`, which seems to have a lot of information online. What are the main differences?

There are many differences. One of the main is that `wiki.vim` does not attempt to implement its own filetype. Instead, the idea is to provide wiki like features, especially with regard to links.

> Are they similar enough that even referencing some of these other resources would provide a decent starting point?

I don't really know, as I don't know these resources.

**Comment by lervag** [comment]
I've added a guide now. If any of you read it and have feedback, it might help me improve it. But please note that it is based on my personal workflow. :)

**Comment by lervag** [comment]
(See `:help wiki-intro-guide` after updating.)
