### ISSUE TITLE
WikiJournalNext, in_journal check

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#151]
I'm on Windows, gVim.

I'm in journal for today, but when I do `:WikiJournal` and tab I can see only `:WikiJournal` and `:WikiJournalIndex`. 
Expected: all "in journal" commands should be available

If you could help, how would i test what is the value of 

```vim
  let b:wiki.in_journal = stridx(resolve(expand('%:p')),
        \ b:wiki.root_journal) == 0
```

I suspect it gives me a wrong value.

**Comment by lervag** [comment]
Can you explain your configuration? Which options do you use for Vim? Where is your wiki located?

When you open a journal entry, what is the output of `:echo b:wiki`? What is the output of `:echo g:wiki_journal`?

**Comment by bybor** [comment]
Thank you!

It looks like my `b:wiki.root_journal` has forward slash : `C:\Users\Alex\vimfiles\vimwiki/diary`, but `expand('%:p')` returns path with only back slashes - `C:\Users\Alex\vimfiles\vimwiki\diary\2021-05-07.wiki`. This is the reason why `stridx` cannot match these values. Not sure how to normalize paths.

=== .vimrc
```
" use `date.exe` from UnxUtils
let g:wiki_date_exe = 'wikidate.exe'
" re-use diary created in vimwiki
let g:wiki_root = '~/vimfiles/vimwiki'
" to use `diary` instead of `journal`
let g:wiki_journal = {
    \ 'name': 'diary',
    \ 'frequency': 'daily',
    \ 'date_format': {
    \   'daily' : '%Y-%m-%d',
    \   'weekly' : '%Y_w%V',
    \   'monthly' : '%Y_m%m',
    \ },
    \}

let g:wiki_link_extension = ['wiki']
```

=== Output of `:echo b:wiki`

{'root': 'C:\Users\Alex\vimfiles\vimwiki', 'in_journal': 0, 'link_extension': ['wiki'], 'root_journal': 'C:\Users\Alex\vimfiles\vimwiki/diary', 'index_name': 'index', 'extension': 'wiki'}

=== Output of `:echo g:wiki_journal`

{'name': 'diary', 'date_format': {'weekly': '%Y_w%V', 'daily': '%Y-%m-%d', 'monthly': '%Y_m%m'}, 'frequency': 'daily'}

**Comment by lervag** [comment]
Can you try to add `set shellslash` to your vimrc?

**Comment by bybor** [comment]
Thanks so much, it solved it!

**Comment by lervag** [comment]
Great, I'm happy to hear it. It might be I should take this into account somehow. Either an update in the docs or perhaps even try to avoid the issue altogether.

**Comment by lervag** [comment]
I would think the `globpath()` is not the right way to do this. But perhaps it could work to add `simplify(...)` around the `printf()`. Since you closed this, does it mean you realized this was not a problem?

**Comment by lervag** [comment]
Hmm, I don't think `simplify` will work.

**Comment by bybor** [comment]
I honestly don't know. I moved on to setup CtrlPWiki integration command and ran into slash issues again among other things.

I found that since I'm on Windows I should really use `let g:wiki_root = '~\vimfiles\vimwiki'` with backslashes. I still have `globpath()` changed as above and `noshellslash`.

I closed this issue because I could solve it for myself and I don't want to take your time on some minor issue. I am glad I could finally find time to go through migration to `wiki.vim`. Thank you very much for your plugins!

Below text should be a different issue, and best of all, should come as a pull request, but I never did one. I hope I'll do it one day.

Regarding CtrlP integration, there is code that assumes `g:ctrlp_user_command` is set, which wasn't in my case. I couldn't find how to check if the variable is set/exists, and configured it to use `fd`. There was one more issue with `wiki#get_root()` returning path ending with `\`. I did a workaround change somewhere to `fnamemodify(v:val, '':p'')'),` call, making it `:p:h` (after searching for how to remove trailing slash in vim).

**Comment by lervag** [comment]
I've tried to implement a fix for this now. Can you test it?

**Comment by bybor** [comment]
It now correctly finds that it's in Journal, great! As for CtrlPWiki I don't have any files listed after I issue the command.

As the result of below call (`autoload\ctrlp\wiki.vim`)
```
function! ctrlp#wiki#init()
  let s:root = wiki#get_root()
```
`s:root` has value `c:\users\alex\vimfiles\vimwiki\` - ending with slash.

With below changes in `autoload\wiki.vim`
```
function! wiki#get_root_global() abort " {{{1
  if empty(g:wiki_root) | return '' | endif

  let l:root = s:is_function(g:wiki_root)
    \ ? call(g:wiki_root, [])
    \ : g:wiki_root
```
  let l:root = fnamemodify(simplify(l:root), **':p:h')**

it removes trailing slash and I see files. I don't know if it's right, but function `wiki#get_root_local()` above uses `:p:h` .

**Comment by lervag** [comment]
Ah, no, I think it's the same issue, but I believe I have a better resolution. Adding `:h` is not right in this case. The problem is the following lines just after that, which looks for `/` explicitly.

**Comment by lervag** [comment]
Please test again now.

**Comment by lervag** [comment]
By the way, I think we the latest changes, everything should work as expected regardless of the `shellslash` option. Could you test that for me and report back? If I'm right, then I can remove the comment in the introduction of the docs.

**Comment by bybor** [comment]
It's perfect! I can confirm that all issues are now resolved, and it works fine without `shellslash`. Thank you very much!

**Comment by bybor** [comment]
I think that this "slash" thing also applies to FZF integration, but it's probably even larger can of worms. I'll try it one day. ;)

For me the greatest selling point of your `wiki.vim` is a possibility of using it as asciidoc (asciidoctor) wiki. Thanks so much!

**Comment by lervag** [comment]
> It's perfect! I can confirm that all issues are now resolved, and it works fine without `shellslash`. Thank you very much!

Great, I'm happy to hear it!

> I think that this "slash" thing also applies to FZF integration, but it's probably even larger can of worms. I'll try it one day. ;)

Yes, that seems slightly more involved. I'll look at it and attempt a fix.

> For me the greatest selling point of your `wiki.vim` is a possibility of using it as asciidoc (asciidoctor) wiki. Thanks so much!

The idea is really to be more or less filetype agnostic. It's clearly not perfect, but it does support quite a lot of types of links, including asciidoc type of links/xrefs. I'm glad you find it useful!
