### ISSUE TITLE
WikiFzfPages, Integration Vim/Windows - shellslash?

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#153]
I am adding this issue to reference "shellslash" code changes for FZF.

The issue I have (not sure if it's slash related)
1) type `WikiFzfPages`, get the popup window with list of items, each like `"/<file path> [] /<file path>"`
2) pick the line containing "2010-12-20"
3) press Enter and get the message in status line "~\vimfiles\vimwiki\c:\users\alex\vimfiles\vimwiki\diary\2010-12-20.wiki" [New DIRECTORY]

I tried `:Files c:\users\alex\vimfiles\vimwiki` which resulted in window with single column and preview (which is OK, default FZF config), and pressing Enter brings me to selected file.

**Comment by lervag** [comment]
I'm not sure if this is slash related either; it might be due to the `c:` part. The hard thing with Windows is that I can't test it myself, so I have to "guess" the solutions. :p

I get the impression that you are not completely lost with making some minor changes and tests, so perhaps I could ask you to do some debugging under my guidance?

But first: You say `:wikiFzfPages` shows each item like `PATH ¤ PATH`. This is not the way it is intended. The point is to only show the part after `¤` and hide the other part. I don't understand why this does not work on your end...

Ok, so: I believe perhaps the problem you are seeing is related to this line:

https://github.com/lervag/wiki.vim/blob/caaaea02bb733a8c5e7ccd4c7c1ab4742df5bee8/autoload/wiki/fzf.vim#L19

It may also be related to these:

https://github.com/lervag/wiki.vim/blob/caaaea02bb733a8c5e7ccd4c7c1ab4742df5bee8/autoload/wiki/fzf.vim#L97-L98

Would you be able to do some minor testing, e.g. by use of statements similar to the following:

```vim
unsilent echom 'DEBUG' l:pages[0]
unsilent echom 'DEBUG' string(a:lines)
```

The lines may not be displayed, but then `:messages` should list them afterwards and the `DEBUG` string helps identify the lines.

Can you confirm that your version of Fzf has the `-d` and `--with-nth` options?

**Comment by bybor** [comment]
My `fzf` version is 0.27.0, and it "knows about" `-d` and `--with-nth`.

Here are the debug messages

DEBUG /C:\Users\Alex\vimfiles\vimwiki\diary\2010-12-20.wiki
DEBUG ['Enhance', '', '/C:\Users\Alex\vimfiles\vimwiki\diary\Enhance the Reports.wiki¤/C:\Users\Alex\vimfiles\vimwiki\diary\Enhance the Reports']

I'll be glad to do debugging and tests, just LMK

**Comment by lervag** [comment]
Thanks. It seems the problem is related to the `l:pages` variable. I believe the substitute command does not work as intended. Can you show the value of `l:pages[0]` before and after the substitute, as well as the value of `l:root`? I.e. something like this:

```vim
let l:root = wiki#get_root() . s:slash
unsilent echom 1 l:root
let l:extension = len(g:wiki_filetypes) == 1
      \ ? g:wiki_filetypes[0]
      \ : '{' . join(g:wiki_filetypes, ',') . '}'
let l:pattern = '**' . s:slash . '*.' . l:extension
let l:pages = globpath(l:root, l:pattern, v:false, v:true)
unsilent echom 2 l:pages[0]
call map(l:pages, '"/" . substitute(v:val, l:root, "", "")')
unsilent echom 3 l:pages[0]
call map(l:pages, {_, x -> x . "¤" . fnamemodify(x, ':r')})
unsilent echom 4 l:pages[0]
```

**Comment by bybor** [comment]
Here it is

```
1 C:\Users\Alex\vimfiles\vimwiki\
2 C:\Users\Alex\vimfiles\vimwiki\diary\2010-12-20.wiki
3 /C:\Users\Alex\vimfiles\vimwiki\diary\2010-12-20.wiki
4 /C:\Users\Alex\vimfiles\vimwiki\diary\2010-12-20.wiki¤/C:\Users\Alex\vimfiles\vimwiki\diary\2010-12-20
```

**Comment by lervag** [comment]
Ah, yes, there it is. I'll push a patch asap, let me know if it solves the issue for you.

**Comment by bybor** [comment]
It does, thank you!

**Comment by lervag** [comment]
Great, glad to hear it!

**Comment by bybor** [comment]
Please excuse my posting here again - may be it should be a new issue?

![2021-05-26 10_40_05-Window](https://user-images.githubusercontent.com/90693/119621625-03a71300-be0f-11eb-8f50-2cc4c22d3eb5.png)

Could you please tell what is the "expected" view of listing on this screenshot? 

Should it be `<name>[]<path>` and preview? or something else?

Thank you!

**Comment by lervag** [comment]
> Could you please tell what is the "expected" view of listing on this screenshot?

It should be simply

```
WikiPages>
  1011/1011
> /diary\2010-12-20
> ...
```

That is, the leading part until `¤` should be hidden. This is the point of the `-d"¤" --with-nth=-1` option. Perhaps the `¤` does not work well on Windows? You could test it by just changing that in three places:

https://github.com/lervag/wiki.vim/blob/a16ed5d59f42afa5abde701c2d1b64b80a70bc7e/autoload/wiki/fzf.vim#L20-L23

https://github.com/lervag/wiki.vim/blob/a16ed5d59f42afa5abde701c2d1b64b80a70bc7e/autoload/wiki/fzf.vim#L97

E.g., try to change `¤` with `#` or `|` or some other character that seems safe to assume is not part of the filename.

**Comment by bybor** [comment]
Yes, I tried it with `#` and it works/can split the path. Could you also somehow add `preview` here please? I think I can change `fzf` options right in this file, but then I will not be able to get updates for plugin because of local changes.

`fzf` under Windows is a wild thing - it turned out it calls shell script using the first `bash` it finds under path (which was `git-bash` from `git for windows` for me). But it works remarkably well.

**Comment by lervag** [comment]
> Yes, I tried it with `#` and it works/can split the path.

Ok, so, if I understand correctly, it may be that a simple solution here is to change the separator to a different character. I'm not sure if `#` is "unique" enough, though. But I believe we can make it a full string. So, can you test if it still works if you change the `#` into `####`? If so, then I'll just make a string based on symbols that should work that is extremely unlikely that anyone uses in their filenames.

> `fzf` under Windows is a wild thing - it turned out it calls shell script using the first `bash` it finds under path (which was `git-bash` from `git for windows` for me). But it works remarkably well.

Heh, yes, I am not surprised this is wild! Also not surprised that it works well :)

> Could you also somehow add `preview` here please? I think I can change `fzf` options right in this file, but then I will not be able to get updates for plugin because of local changes.

This is a new feature request and not relevant for this thread - please open a new issue for it. I believe it should be relatively easy to allow custom options here to enable preview. I personally don't like the previewer. :p

**Comment by bybor** [comment]
Thank you. It works with `####`

**Comment by lervag** [comment]
Ok, so, does this mean my recent commit resolves this issue for you?

**Comment by bybor** [comment]
Works just fine, thanks!

**Comment by lervag** [comment]
Great :)
