### ISSUE TITLE
Support POD

### ISSUE THREAD

**Issue by nkh** [lervag/wiki.vim#154]
Hi, I write this issue as you asked me to in #150.

[POD](https://perldoc.perl.org/perlpod#L%3Cname%3E-a-hyperlink) is the documentation format used in Perl documentation. Some javascript use it too. POD comes with tools to extract documentation and even an old project that generates full project documentation ([pod2projdocs](https://github.com/hubnerd/pod2projdocs)). It would be nice to be able to run it as pandoc is run in the current version.

Renaming links can be interesting, since it the POD can be contained in source files. A good approach, if feasible, would be to allow the renaming of files in the wiki directory (or maybe a few directories).

Do ask if you need examples or a clarification of how it's used by developers. https://metacpan.org/ contains all the POD for all the perl modules.

Edit: @lervag improved formatting and made minor adjustments to make the issue description more clear.

**Comment by lervag** [comment]
> Edit: @lervag improved formatting and made minor adjustments to make the issue description more clear.

First, FYI: I made some minor changes to your description. Please note:

1. It is much easier to read a text if you use punctuation correctly. Use full stops (`.`) after sentences and capitalize the first letter after full stops.
2. Aim for short sentences.
3. It is also useful to use some Markdown formatting, e.g. of links. An example: Write `[example](https://example.com)` to get [example](https://example.com).

> Do ask if you need examples or a clarification of how it's used by developers. https://metacpan.org/ contains all the POD for all the perl modules.

I need more clarification of exactly how you would want to use this from
wiki.vim. You mention several things:

1. Tools to extract documentation from code. But how does this relate at all to wiki.vim?
2. How would `pod2projdocs` be related to wiki.vim? Both this point and the previous seem like tools you use on code, not on a wiki/normal text files?

> Renaming links can be interesting, since it the POD can be contained in source files. A good approach, if feasible, would be to allow the renaming of files in the wiki directory (or maybe a few directories).

I do not understand this paragraph. What do you mean? Note that it can be useful to provide a clear example.

Note: Let's say we work to add support for POD. Then I think it is very important to take it one small step at a time. Start with the most important/basic feature, then add more with time. Think one issue thread per feature. I therefore propose that, after settling the current unclarities, we proceed with a single topic first. And to that end, I think it would be very useful if you provide a clear example of what you want.

**Comment by nkh** [comment]
hi, the most important feature would be to follow links, which format is described here https://perldoc.perl.org/perlpod#L%3Cname%3E-a-hyperlink

**Comment by lervag** [comment]
Thanks. Can you give me some examples as well? E.g. a small set of files in this format with a couple of different links?
