### ISSUE TITLE
WikiFzfPages - error if selecting nothing with <Esc>

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#155]
- Issue `:WikiFzfPages`
- Cancel command with `Esc` without selecting anything

```
Error detected while processing function 17[30]..<SNR>55_callback[23]..function 17[30]..<SNR>55_callback:

Vim(if):E684: list index out of range: 1
```

**Comment by lervag** [comment]
Huh, that's strange. There's no function in wiki.vim named `*callback*`. So this does not come from wiki.vim. I'm not sure where this comes from. Do you have the same behaviour with other Fzf commands?

**Comment by lervag** [comment]
Note, you can check which script defines the `<SNR>55_callback` function by inspecting the output of `:scriptnames`. This command gives a numbered list of scripts that are sourced, and the `<SNR>n` indicates the script. E.g. on my side, I get `:scriptnames` output similar to

```
 ...
 55: ~/.vim/bundle/wiki.vim/autoload/wiki/buffer.vim
 ...
```

and so you can identify the `s:apply_template()` function with `<SNR>55_apply_template` in the output of `:function`.

**Comment by bybor** [comment]
Thanks!

It comes from `fzf\plugin\fzf.vim`. It doesn't happen with fzf's command `:Files`. I would think it's about `s:accept_page` function which is `callback` from fzf's perspective, but I cannot confirm. 

Could you tell if you have an error if you `ESC` without selecting anything in `WikiFzfPages` please?

**Comment by lervag** [comment]
I do not have the same error, no. And in my `fzf/plugin/fzf.vim` there is no such function. Perhaps you could try to update your fzf plugin?

**Comment by bybor** [comment]
Ah, sorry.

I assumed that this code from `wiki.vim\autoload\wiki\fzf.vim`

```
  call fzf#run(fzf#wrap({
        \ 'source': l:pages,
        \ 'sink*': funcref('s:accept_page'),
        \ 'options': l:fzf_opts
        \}))
```

calls `function! s:accept_page(lines) abort "{{{1` few lines below (which is a callback method, right?). But `s:accept_page` expects `a:lines`  to have 2 or 3 elements. If it was less, it could explain "index out of list" error. But it works for you. Let's close this one if it's OK?

**Comment by lervag** [comment]
Of course, I don't mind closing the issue. But if it leaves the issue unresolved, then feel free to keep it open.

Let's assume that the error is within `s:accept_page(lines)` - in this case, it may be interesting to add some minor debug code at the top to examing the content of `a:lines` and check if the error is really from there. I believe it is not, though.

But, again: On my side, I cannot find any function with the name `s:callback`. Can you check your `fzf\plugin\fzf.vim` and give me a link to the proper source on github (or gitlab or wherever) to the actual code? That is, to figure out what is happening, we need to figure out which function this is:

    Error detected while processing function 17[30]..<SNR>55_callback[23]..function 17[30]..<SNR>55_callback:

Which plugin, which file, which line, preferably a link to the source repo.

**Comment by bybor** [comment]
It's `fzf`

Here is the reference to `s:callback` implementation inside `fzf.vim`. It calls `s:accept_page` through a reference passed in `sink*` parameter AFAICS.

https://github.com/junegunn/fzf/blob/a4bc08f5a35da6e374a2ce0da4c931d7fd32fdf1/plugin/fzf.vim#L928

`wiki.vim` calls `fzf#run`, which in turn calls `s:callback`, on this line

https://github.com/junegunn/fzf/blob/a4bc08f5a35da6e374a2ce0da4c931d7fd32fdf1/plugin/fzf.vim#L515

Could you tell what debugging code should I add to inspect `a:lines` content?

**Comment by lervag** [comment]
Thanks. I don't know why, but it seems for some reason that the sink is called with an empty argument on your side when you press esc. On my side, this does not happen. But there's no reason not to just handle bad arguments, so I'll push something that I think may fix this.

**Comment by lervag** [comment]
I believe this should work for you now.
