### ISSUE TITLE
WikiFzfPages - making it possible to use FZF preview

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#157]
Hello!

Could `wiki.vim` have an option to enable fzf preview from WikiFzfPages command?

Thanks

**Comment by lervag** [comment]
You can now add additional options for fzf for `WikiFzfPages` with `g:wiki_fzf_pages_opts` (see docs for a minimal example previewer).

For future reference, the previewer option was first suggested [here](https://github.com/lervag/wiki.vim/issues/153#issuecomment-849699343).
