### ISSUE TITLE
WikiFzfPages command always runs against `journal` path

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#158]
This looks like a regression because I didn't see it few weeks ago.

No matter what current path is, I can see only files from under `journal` path when I run `WikiFzfPages` command, and it cannot find the files that are under wiki root.

**Comment by lervag** [comment]
This is not a problem on my end, so please give more details. What are your options; preferably a minimal vimrc file. How is your wiki layed out?

**Comment by lervag** [comment]
Ah, thanks. It seems this is not so well documented, and this is about how the `expr` argument of the `glob()` and `globpath()` functions work, not about paths in general.

I'm reverting this particular "shellslash fix", which should solve the issue.
