### ISSUE TITLE
Using wiki.vim with MDwiki

### ISSUE THREAD

**Issue by hex337** [lervag/wiki.vim#16]
# Description

I'm looking to use the output of wiki.vim with [MDwiki](http://dynalon.github.io/mdwiki/#!index.md), but MDwiki expects the files to have a .md format, not .wiki.

I can get index.wiki to load properly, but setting up links just doesn't work :(

Is there any chance we can make the file format configurable for this?

MDwiki expects intra-content links to look like `[link name](link_page.md)`. If I use the `.wiki` in the link portion, I get a page that doesn't render the markdown.

Maybe something like:

```vim
let g:wiki_file_format = '.md'
```

Thanks!

**Comment by lervag** [comment]
Yes, this is actually one of my top priorities. I think this issue will be resolved as a consequence of #14, and as such, I will close it. Feel free to continue the discussion either here or in #14.
