### ISSUE TITLE
[FR] Prevent wiki-link-follow from creating a new link

### ISSUE THREAD

**Issue by protist** [lervag/wiki.vim#162]
# Description

By default, pressing `Enter` will trigger `wiki-link-follow`, [which will](https://github.com/lervag/wiki.vim/blob/master/doc/wiki.txt#L625-L628)

> Follow link. Will create a new link if the text under the cursor is not already a link.

If a link exists, I am happy with `Enter` following it. However, if there is no link, I do not want a new link created. In contrast, vimwiki has [the option](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt#L2785-L2795) to suppress the creation of the link if it doesn't exist.

Steps to reproduce
1. Put cursor on plain text.
2. Press `Enter`

Expected behaviour:
3. Nothing happens (e.g. go to next line).

Observed behaviour
3. Link is created

**Comment by lervag** [comment]
I believe there is already an option for this, see `:help g:wiki_link_toggle_on_follow`. Or do I misunderstand your request?

**Comment by protist** [comment]
Oops, sorry, I have no idea how I missed that. Yes, that's what I was after. Thank you for the quick reply, and sorry for the noise!

**Comment by lervag** [comment]
No problem :)
