### ISSUE TITLE
Open text links in vim, and other links with external program

### ISSUE THREAD

**Issue by protist** [lervag/wiki.vim#165]
# Description

* Expected behaviour: text links (e.g. `.md` files) should open in vim; other links (e.g. pdf, png) should open in an external program (e.g. `xdg-open` for Linux).
* Observed behaviour: all links open in vim, including pdfs and pngs.
* To reproduce: open a link to a pdf.

# Minimal working example

I attempted using a modified [wiki_file_handler](https://github.com/lervag/wiki.vim/blob/master/doc/wiki.txt#L189-L204), to call `xdg-open` for any files not ending in `.md` (and the fallback to vim for the `.md` files). This works reasonably well; markdown files open in vim, and everything else opens externally.

```
let g:wiki_file_handler = 'WikiFileHandler'
function! WikiFileHandler(...) abort dict
  if self.path !~# '\.md$'
    silent execute '!xdg-open' fnameescape(self.path) ' >/dev/null 2>%1 &'
    redraw!
    return 1
  endif
  return 0
endfunction
```

However, while this works well for `.md` files, it fails for other kinds of text files without a `.md` suffix. Is there a way to automatically detect if the file is a "plain-text" file, and use vim if so? I already have `xdg-open` set to open plain text in vim, but in this case it will open a new instance of (g)vim.

**Comment by lervag** [comment]
Yes, because you need to specify the scheme. If the scheme is not specified, `wiki:` is assumed. I.e., you need to write `[asd](file:...)`. I strongly advice you to read the sections under `:help wiki-link`, as I think this should be explained there.

**Comment by lervag** [comment]
(Unless I misunderstand you, of course. --- feel free to provide a full example.)

**Comment by protist** [comment]
Thanks @lervag. I actually did read the help, but I think I was unclear in my question.

From the help, my understanding is that the `file:` scheme is useful for absolute paths in the filesystem, i.e. those not in the wiki path, or relative to the current document. If my markdown file is at `/a/long/path/to/text.md`, and I want to link to `/different/path/file.pdf`, then I would use the `file:` scheme, which is much simpler than using the `wiki:` scheme and `[asd](../../../../different/path/file.pdf)`. Having said that, even if I use the `wiki:` scheme, I found it would automatically add `.md`, attempting to open `/different/path/file.pdf.md` instead.

So I guess that raises an additional question:

1)  If I want to open a text file, do I *have* to use the `file:` scheme?
2) Assuming I use the `file:` scheme, how can I open plain-text files in vim, and other files externally?

**Comment by lervag** [comment]
> From the help, my understanding is ...

The `wiki:` scheme (which is the default) implicitly assumes the current wiki extension (e.g. `.md` or `.wiki`, or whatever). It is not intended for any other types of files. `file:...` is intended as the correct way of linking to a file in your system, _except_ the wiki files. So ...

> 1. If I want to open a text file, do I _have_ to use the `file:` scheme?

Yes.

> 2. Assuming I use the `file:` scheme, how can I open plain-text files in vim, and other files externally?

You should use the `g:wiki_file_handler` option. E.g., I personally use this:

```vim
let g:wiki_file_handler = 'personal#wiki#file_handler'
```

Where `personal#wiki#file_handler` is defined here:

https://github.com/lervag/dotnvim/blob/daa2aa4d9a85c789f26246c14dcea7d2b708f228/personal/autoload/personal/wiki.vim#L1-L23

**Comment by lervag** [comment]
You can use the same concept to open a plain-text file in Vim with e.g.

```vim
if self.path =~# '\vtxt$'
  edit self.path
  return 1
endif
```

You can also use more complex conditionals to determine how to handle the file; it should be quite flexible and customizable. If the `g:wiki_file_handler` function does not return 1, then the file handler falls back to the `xdg_open` command (by default); so, you don't need to use `xdg_open` explicitly here.

**Comment by protist** [comment]
Thanks @lervag. So if I understand correctly, it looks like users can't exactly open *all* text files universally in vim (and the rest in `xdg-open`). You'd have to rely on the filename instead. No big deal, I'll just explicitly list the important ones in `~/.vimrc`. Thanks again!

**Comment by lervag** [comment]
> ... it looks like users can't exactly open _all_ text files universally in vim

If you want to do that, you need to find a way to _detect_ if a file is a text file. I don't know how to do that, but one possibility could be to make an assumption. I.e.: Use the file handler function to handle all filetypes that you want to handle without Vim, then fallback to the Vim `edit ...` command. Thus, the default would be to open in Vim, and it would be easy to add exceptions that use one or another external tool.

Happy to help :)

**Comment by protist** [comment]
Thanks again, and sorry for the delay in my reply @lervag; I've been out of town. I figured that the "detection" might work similarly to Linux's `file` command. I assume this (or similar) is how `xdg-open` determines what a "text" file is. But maybe this is will be quite complicated.

Currently, I have `xdg-open` set to open "text" files in `vim` by default. I guess I would expect wiki.vim to open non-text files with `xdg-open`, but any file that `xdg-open` would otherwise open with vim could be opened internally with `edit ...` instead. However, this means that it would have to use an external tool, e.g. `file` and I suppose parse the mime defaults. Probably seems like too much work TBH!

**Comment by lervag** [comment]
> sorry for the delay in my reply

no problem :)

> I figured that the "detection" might work similarly to Linux's file command

Yes, that sounds like a good idea. Or, perhaps better, use `xdg-mime`; e.g.:

```
> xdg-mime query filetype file.log
text/plain
```

I.e., this tool will reply with something like `text/plain` or similar based on the file argument after `xdg-mime query filetype <filearg>`.

To make this work within the handler, I would write something like this in my custom `g:wiki_file_handler` function:

```vim
if system('xdg-mime query filetype ' . self.path) ==# 'text/plain'
  edit self.path
  return 1
endif
```

**Comment by lervag** [comment]
By the way; please note that the default `file:` handler does _not_ automatically use `xdg_open`. Instead, it looks at `g:wiki_viewer` for the current extension. I believe the docs may be somewhat off here, because it does not fall back to `xdg_open` as described. But if you defined e.g. `let g:wiki_viewer = {'pdf': 'xdg_open', 'log': 'firefox'}`, then you should see it works as expected. Let me know what you think; perhaps I should update the docs here.

**Comment by protist** [comment]
Thanks again @lervag  for sticking with this. However, your code doesn't quite seem to work properly. To be clear, I'm using it in the following scenario:
```
let g:wiki_file_handler = 'WikiFileHandler'
function! WikiFileHandler(...) abort dict
  if trim(system('xdg-mime query filetype ' . self.path)) ==# 'text/plain'
    edit self.path
    return 1
  endif
endfunction
```
From troubleshooting, the conditional seems to work perfectly well, i.e. if I follow a link to a PDF, it doesn't go through the `if`. However, the PDF still opens within vim (FWIW `g:wiki_viewer` is still `{'_': 'xdg-open'}`).

If I follow a link to a `text/plain` file, it *does* go through the `if`, but vim literally creates and edits a file called `self.path`.

> Let me know what you think; perhaps I should update the docs here.

Erm, to tell you the truth, I was pretty confused by all of the external file linkage documentation. I *did* read it at first, but must have skimmed over some of it that seemed more esoteric. However, since you mention it, I went back and read the `wiki_viewer` section, and that *does* certainly make sense (now).

**Comment by lervag** [comment]
Sorry, the code was not quite right; it should be

```vim
    ...
    execute 'edit' self.path
    ...
```

> if I follow a link to a PDF, it doesn't go through the if. However, the PDF still opens within vim (FWIW `g:wiki_viewer` is still `{'_': 'xdg-open'}`).

Try to add

```vim
let g:wiki_viewer = {'pdf': 'xdg-open'}
```

Does that work as expected now?

**Comment by lervag** [comment]
I believe this discussion has raised an issue, i.e., that the file handler does not use the `g:wiki_viewer` default key `_`. If you agree, then I'll open an issue (unless you beat me to it) to briefly describe this, and I'll fix it when I get the time.

**Comment by protist** [comment]
Thanks @lervag! Yes, that works perfectly now. I'd be totally happy to open an issue, but I'm not 100% sure how to describe it completely, so I might leave that to you if that's okay.

**Comment by lervag** [comment]
I've created the issue now, and with that, I think the current thread is resolved? (#171)

**Comment by protist** [comment]
Thanks @lervag. Yes this thread is resolved.

**Comment by DanielAjoy** [comment]
I added this to my .vimrc

```
function! personal#wiki#file_handler(...) abort dict

  if self.path =~# 'txt$'
    edit self.path
    return 1
  endif

endfunction

let g:wiki_file_handler = 'personal#wiki#file_handler'

```

And got 

```
Error detected while processing /home/daniel/.vimrc
E746: Function name does not match script file name: personal#wiki#file_handler
```

What am I doing wrong?

**Comment by lervag** [comment]
> I added this to my .vimrc …
> 
> And got
> 
> ```
> Error detected while processing /home/daniel/.vimrc
> E746: Function name does not match script file name: personal#wiki#file_handler
> ```
> 
> What am I doing wrong?

It's simple, when you know the answer. The use of `#` in function names, such as `foo#bar`, is a very specific syntax. It is explained in `:help autoload-functions`.

The simples solution is to change the name from `personal#wiki#file_handler` to `MyWikiFileHandler` or something like that.

**Comment by DanielAjoy** [comment]
Thanks. But now I'm getting the following, I'm using Vim 8.2 and vim.wiki v0.9 (the one that doesn't need Vim 9.1)

```
Error detected while processing function wiki#link#follow[25]..function wiki#link#follow[21]..wiki#url#follow[12]..wiki#url#handlers#file:
line    1:
E121: Undefined variable: _
E116: Invalid arguments for function get(g:wiki_viewer, a:resolved.ext, g:wiki_viewer._)

```

**Comment by lervag** [comment]
Well, now you should open a new issue and explain things in more detail. It's not really possible to see exactly why this happens from the context I see here. So, please open a new issue and provide the info I'm asking for in the template.
