### ISSUE TITLE
Cannot open URLs on macOS

### ISSUE THREAD

**Issue by smancill** [lervag/wiki.vim#17]
The `l:link.open` function has `xdg-open` hard-coded:

https://github.com/lervag/wiki.vim/blob/252f965a7b8aa6719bf080860e6f75723093c2e3/autoload/wiki/url/generic.vim#L10-L12

For PDFs the proper program is selected based on the OS:

https://github.com/lervag/wiki.vim/blob/252f965a7b8aa6719bf080860e6f75723093c2e3/plugin/wiki.vim#L13-L16

**Comment by lervag** [comment]
Yes, you are right. Thanks! I'm fixing asap.

**Comment by lervag** [comment]
Sorry, my initial fix was not quite correct. I should not use the PDF viewer option for generic links. I've added the option `g:wiki_generic_viewer`, which is similar to the `g:wiki_pdf_viewer` option, except the latter will only be used for opening PDF files, whereas the first is used for generic links.
