### ISSUE TITLE
WikiPageRename does not update links in non-root directory files

### ISSUE THREAD

**Issue by digital-carver** [lervag/wiki.vim#170]
# Description

Running `:WikiPageRename` on a file changes its name and links to it from files in the wikiroot directory, but doesn't seem to update links in files in any subdirectories of it.

## MWE
With:

```
❯ tree testwiki
testwiki
├── index.md
└── subf
    ├── File.md
    └── things.md
```

where `testwiki/index.md` contains a line ` [subFile](subf/File.md)`, and `testwiki/subf/things.md` contains a line `[File](File.md)`.

1. Run `:WikiPageRename` on `File.md`
2. Choose the new name as `NewFile`

**Expected**:
Both lines are changed to link to `NewFile.md` now.

**Actual result**:
The file is renamed correctly and the line in `testwiki/index.md` changes to `[subFile](subf/NewFile.md)`, but the line in `testwiki/subf/things.md` doesn't change.

**Comment by digital-carver** [comment]
I'm guessing this has to do with the fact that the `path_to_wiki_url` call returns the path as relative to wiki root? And so only the links that are in that pattern (`subf/File.md` in the above case) are recognized and changed.

**Comment by lervag** [comment]
Yes, you are right. This is a nontrivial fix, but I agree it should be addressed. I personally don't use subdirectories, but there's no reason to not properly support it. I believe a better approach than the current one is to rely on the link graph, as this one parses all the links in the wiki. By utilizing a cache it can probably keep things quite fast, even for larger wikis. I'll look into it when I get the time!

In the meantime, I hope you can live with this bug. :\

**Comment by lervag** [comment]
I've pushed an update that should more or less resolve this. It's still hard, and I'm sure there are still edge cases. But I think the idea and fix should work in most cases.
