### ISSUE TITLE
WikiPageRename doesn't refresh tags

### ISSUE THREAD

**Issue by anjiro** [lervag/wiki.vim#175]
After using `WikiPageRename` I would expect `wiki#tags#get_all()` to include the updated page name, but it still has the old name. I think the right fix would be to change the filename everywhere it occurs in `s:tags.collection` in `autoload/wiki/tags.vim`, but that requires extra global functions so I'm hesitant to take a stab at a pull request.

**Comment by lervag** [comment]
A _simple_ fix would be to refresh all tags. I.e. simply add `call wiki#tags#reload()` at the end of `wiki#page#rename`. Do you see any reason why that would not resolve your issue (just wondering if I'm missing something, here)?

**Comment by lervag** [comment]
Perhaps the minor inconvenience would be that parsing tags may take some time. I am considering to put the tags into a cache to avoid parsing all files everytime. It should be quite simple and would speed up the tag feature quite a lot in big projects, I believe.

**Comment by anjiro** [comment]
I think that the `wiki#tags#reload()` approach would probably work fine, but indeed might take a bit of extra time. For my scale of wiki right now I think it would not be particularly problematic.

**Comment by lervag** [comment]
Ok, I've implemented this now, including the caching. Can you test?
