### ISSUE TITLE
Error when writing '@' when not using zotero

### ISSUE THREAD

**Issue by alextes** [lervag/wiki.vim#177]
Is there a way to turn of the '@' zotero functionality?

Perhaps the plugin could even detect that `.local/zotero` is missing and not do the search at all. Now I get an error any time I write: '@'
![Screenshot 2021-07-22 at 11 12 12](https://user-images.githubusercontent.com/2011351/126615835-6d805d5f-e09f-48e6-a478-b52f4cf8902e.png)

A simple workaround I'm using now is to have that directory.

**Comment by lervag** [comment]
Thanks. I believe this is fixed now. Can you delete the Zotero directory and test?

**Comment by alextes** [comment]
@lervag works! 👌 🙏

**Comment by lervag** [comment]
Happy to hear it!
