### ISSUE TITLE
WikiJournalIndex: sorting, encoding

### ISSUE THREAD

**Issue by artkpv** [lervag/wiki.vim#178]
## Description

`:WikiJournalIndex` command

1. Creates entries sorted first by year then by month descending that makes most recent entry not at the top but some way down. Expected: ability to have it at top or at bottom, i.e. entries sorted.
2. has invalid first symbol if Cyrillic chars used. In the example: "Ð?юль". Expected: first char is correct. In the example: "Июль"
3. After saving and reopenning the encoding is undetected and needs `:e ++enc=utf-i` exectuded. Expected: encoding detected correctly.

## Minimal working example

```
├── index.md
├── index.wiki
└── дневник
    ├── 2021-07-20.md
    ├── 2021-07-21.md
    └── 2021-07-22.md
```

index.md (reopened with `:e ++enc=utf-8`):
```markdown
# Index

# 2021

## Ð?юль

[2021-07-20](journal:2021-07-20)
[2021-07-21](journal:2021-07-21)
[2021-07-22](journal:2021-07-22)

```

index.wiki:
```markdown
[index.md](index.md)
```

`дневник/2021-07-*.md` files are empty with one header at top.

vimrc:
```vim
let g:wiki_filetypes = ['wiki', 'md']

let g:wiki_link_target_type = 'md'

let g:wiki_month_names = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']

let g:wiki_toc_title = 'Содержание'

let g:wiki_journal = {
    \ 'name': 'дневник',
    \ 'frequency': 'daily',
    \ 'date_format': {
    \   'daily' : '%Y-%m-%d',
    \   'weekly' : '%Y_w%V',
    \   'monthly' : '%Y_m%m',
    \ },
    \}

function! MyWikiBufferInit()
  try
    colorscheme onehalflight
    " colorscheme onehalfdark
  catch
  endtry
  try
    CocDisable
  catch
  endtry
  set laststatus=0
  set foldcolumn=4
  au! BufWritePost ~/mydir/notes/* !git add "%";git commit -m "Auto commit of %:t." "%"

  nmap <leader>mh :s_\v^((#+) +)?(.*)_#\2 \3_e<CR> :noh<CR>
  nmap <leader>mH :s_\v^#(#* )? *(.*)_\1\2_e<CR> :noh<CR>
endfunction

augroup MyWikiAutocmds
  autocmd!
  autocmd User WikiBufferInitialized call MyWikiBufferInit()
augroup END

function! MyWikiClean()
    " Clean escape '\' chars inserted by Evernote export.
    %s_\\__gce

    " Clean enclosing of links with '<' and '>' chars.
    %s_\v\<([^\>]+)\>_\1_gce

    %s_\v\!\[\]\((local.*\/([^\)]+))\)(\{wid[^}]*\})?_[\2](\1)_

endfunction

let g:wiki_map_link_create = 'WikiRemoveWhitespaceLinkCreate'

function WikiRemoveWhitespaceLinkCreate(text) abort
  if a:text !~# '\v(md|wiki|txt)$'
    return strftime('%Y%m%d%H%M') . '_' . substitute(tolower(a:text), '\s\+', '_', 'g')
  endif
  return a:text
endfunction

let g:wiki_viewer = {
    \ '_' : 'xdg-open',
    \}

let g:wiki_file_open = 'WikiFileOpen'

function! WikiFileOpen(...) abort dict
  if self.path !~# '\v(md|wiki|txt)$'
    silent execute '!xdg-open' fnameescape(self.path) '&'
    return 1
  endif

  return 0
endfunction
```

**Comment by lervag** [comment]
> Creates entries sorted first by year then by month descending that makes most recent entry not at the top but some way down. Expected: ability to have it at top or at bottom, i.e. entries sorted.

How do you expect this to work? Is it enough with an option like `g:wiki_journal_index_order = 'ascending'` or `= 'descending'`?

> has invalid first symbol if Cyrillic chars used. In the example: "Ð?юль". Expected: first char is correct. In the example: "Июль"

Should be fixed now.

> After saving and reopenning the encoding is undetected and needs `:e ++enc=utf-i` exectuded. Expected: encoding detected correctly.

I don't have this problem. Which version of Vim are you using? Which OS? What's your locale (if Linux, what's the output of `locale`)?

**Comment by lervag** [comment]
By the way, for future issues: I strongly prefer to keep issues separated. If they are related, you can of course feel free to link between them for context. I.e., in this case, you could have first opened an issue for one of your points. Then you could open a new issue and link to the first for the main context and then add your second point. And so on. It makes it easier for me to address the various items in a more structured manner.

**Comment by artkpv** [comment]
> How do you expect this to work? Is it enough with an option like g:wiki_journal_index_order = 'ascending' or = 'descending'?

Yes, that might be useful. But the main issue is that I need to scroll some way down to see the most resent entry like this:

```
# 2021

## May

Entry D

## June

Entry C
Entry B

## July

Entry A

# 2020

# January

Entry BB

# Feb 

Entry CC

// and so on

```
So to get to entry A I need to scroll down. 

> Should be fixed now.

:+1:  Thanks!

> I don't have this problem. Which version of Vim are you using? Which OS? What's your locale (if Linux, what's the output of locale)?

Please see:

```
❯ locale
LANG=ru_RU.utf8
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC="ru_RU.utf8"
LC_TIME="ru_RU.utf8"
LC_COLLATE="ru_RU.utf8"
LC_MONETARY="ru_RU.utf8"
LC_MESSAGES="ru_RU.utf8"
LC_PAPER="ru_RU.utf8"
LC_NAME="ru_RU.utf8"
LC_ADDRESS="ru_RU.utf8"
LC_TELEPHONE="ru_RU.utf8"
LC_MEASUREMENT="ru_RU.utf8"
LC_IDENTIFICATION="ru_RU.utf8"
LC_ALL=
❯ uname -u
uname: неверный ключ — «u»
По команде «uname --help» можно получить дополнительную информацию.
❯ uname
Linux
❯ uname -a
Linux ARCHPC 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux
❯ nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Скомпилирован  builduser

Features: +acl +iconv +tui
See ":help feature-compile"

            общесистемный файл vimrc: "$VIM/sysinit.vim"
          значение $VIM по умолчанию: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lervag** [comment]
Sorry about the late follow up here!

> > How do you expect this to work? Is it enough with an option like g:wiki_journal_index_order = 'ascending' or = 'descending'?
> 
> Yes, that might be useful. But the main issue is that I need to scroll some way down to see the most resent entry like this: ...

Ah, I see. And I agree, the issue here is that it is not properly sorted at all. So, instead of adding an option for now, perhaps instead I could just fix it so it is properly sorted? What would be the most natural order? The most recent entry on top or on bottom?

> So to get to entry A I need to scroll down.

This implies "on top". But if I do fix this and keep it at the bottom, it would still be simple to scroll down with the `G` key.

> > I don't have this problem. Which version of Vim are you using? Which OS? What's your locale (if Linux, what's the output of locale)?
> 
> Please see:
> 
> ```
> ❯ locale
> LANG=ru_RU.utf8
> LC_CTYPE="ru_RU.utf8"
> ...
> LC_IDENTIFICATION="ru_RU.utf8"
> LC_ALL=
> ```

Hmm; on my end, the `LC_ALL` is also defined (`en_US.UTF-8`); perhaps that's the problem?

> ```
> ❯ uname -a
> Linux ARCHPC 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux
> ```

I'm also on Arch, btw... :)

To be honest, except for `LC_ALL`, I have noe idea what may be wrong with the encoding problem.

**Comment by lervag** [comment]
I just pushed an update that at least adds the journal index in a consistent order. Perhaps you would prefer to have it reversed; if so, it would also be trivial to select the lines and filter through `tac` with `%!tac`.

**Comment by artkpv** [comment]
Thanks! It works :)

**Comment by lervag** [comment]
Great, good to hear.

If you are able to reliably reproduce the encoding issue, I would prefer if you open a new issue.
