### ISSUE TITLE
Fix mappings for link url text objects in readme

### ISSUE THREAD

**Issue by AdamWagner** [lervag/wiki.vim#18]
Awesome job on wiki.vim! I really appreciate your approach.

Line 69 in `README.md`

```
  - Text objects
    - `il al` Link url
    - `it at` Link text
```

... should be changed to:

```
  - Text objects
    - `iu au` Link url
    - `it at` Link text
```

`il al` -> `iu au`

Just a tiny typo, yet one that I didn't become aware of until reading through the source for the text objects ;-)

**Comment by lervag** [comment]
Thanks! I still want to do much more with the plugin, but I think it already works quite well. I've been very out of time the last year, so development has halted. But I hope to get some more work done later this year.
