### ISSUE TITLE
Feature: Allow easy additions to the context dictionary for templates

### ISSUE THREAD

**Issue by Ginner** [lervag/wiki.vim#184]
# Description
Allow for adding entries to the context dictionary. This could be used for adding small functions that doesn't require arguments and even strings (if that'd make sense). More advanced substitution is then left to the user defined substitution functions.

In code, the process would  look something like this:
```
let l:context += {
    \ 'day_name' = strftime("%A"),
    \}
```

This would allow for using {day_name} as variable substitution, in addition to the already available date, time, etc. However, I think it could be made more easily  available as a setting in `$MYVIMRC`. E.g.:
```
let g:wiki_template_context = {
    \ 'name': 'John Doe',
    \ 'day_name': strftime("%A"),
    \ 'user': system("whoami"),
    \ }
```

This is in no way a 'need to have' in my view, as the functionality is already available in user defined substitution functions. It is merely nice to have, as a separation between small one-off functions and larger substitution functions.

**Comment by lervag** [comment]
Perhaps a better solution is to extend the format to allow vim script expressions? So, instead of extending the context dictionary, you could instead just write e.g.

```
# {name}

Date: <<strftime("%A")>>
User: <<system("whoami")>>
```

This seems to me to be more general. What do you think?

**Comment by Ginner** [comment]
> What do you think?

I think it would be a very powerful feature! However, without being familiar with the implementation, I fear it opens the door to a lot of bugs that are potentially tough to diagnose. And I like 'centralizing' the code execution to the the plugins and `.vimrc`.

After having discussed the template/substitution further with you (e.g. #183), I think the variable/function substitution functionality is sufficient. I think it'd be trivial for the user, if the existing substitution is understood, to implement his/her own 'context dictionary' or similar.
For that reason, I'll close the issue.

**Comment by lervag** [comment]
> ... I think it'd be trivial for the user, if the existing substitution is understood, to implement his/her own 'context dictionary' or similar.
> For that reason, I'll close the issue.

Yes, I agree it should be possible for users to implement most anything on top of the current framework with use of custom functions. So, even though I think it could be possible to implement my proposed more general feature, I also guess it is better to focus on other issues. Thanks!
