### ISSUE TITLE
TOC and Tags problems

### ISSUE THREAD

**Issue by duytientran** [lervag/wiki.vim#188]
# Description

Hi, sorry for noob questions.

I was wondering how I can list all tags with links under cursor? I am just able to do that for one tag but not all of them.
It would be great if there is a feature that allow us to choose/change wiki index file. Thanks

# My wiki.vim setup

```vim
let g:wiki_filetypes = ['md']
let g:wiki_journal = {
        \ 'name': 'journal',
        \ 'frequency': 'daily',
        \ 'date_format': {
        \   'daily' : '%Y%m%d',
        \   'weekly' : '%Y_w%V',
        \   'monthly' : '%Y_m%m',
        \ },
        \}
let g:wiki_export = {
        \ 'args' : '',
        \ 'from_format' : 'markdown',
        \ 'ext' : 'pdf',
        \ 'link_ext_replace': v:false,
        \ 'view' : v:false,
        \ 'output':  ':~/Downloads/pdfoutput/',
        \}
let g:wiki_tags = {
        \ 'output' : 'cursor',
        \}"
let g:wiki_root = '~/Downloads/testing/'
```

**Comment by lervag** [comment]
> Hi, sorry for noob questions.

No problem.

> I was wondering how I can list all tags with links under cursor?
> I am just able to do that for one tag but not all of them.

> It would be great if there is a feature that allow us to choose/change wiki index file.

If I understand correctly, you want something similar to `:WikiTagSearch -output cursor mytag`, except that you want it for _all_ tags.

This is currently not possible, but it should not be too hard to implement.

PS! Note that in a recent commit, I've changed the `g:wiki_tags` option to `g:wiki_tag_search`.

**Comment by lervag** [comment]
Please confirm if I understood you correctly.

**Comment by duytientran** [comment]
Hi, Thank you for your reply. I do want all tags feature. If possible all
links for each subfolder is great as well
Best regards,
Tien

**Comment by lervag** [comment]
I've made `WikiTagList` similar to `WikiTagSearch` now, except it will list all tags with respective positions/locations. Let me know what you think.
