### ISSUE TITLE
Please add support for frontmatter, especially tags

### ISSUE THREAD

**Issue by aquatix** [lervag/wiki.vim#189]
# Description

Please support (markdown/yaml) frontmatter in Markdown files, especially parsing of the `tags` field to be used with `WikiFzfTags` and such.

I already have syntax highlighting for yaml frontmatter in my wiki.vim/markdown files through https://github.com/aquatix/dotfiles/blob/master/.vim/after/syntax/markdown.vim

# Minimal working example

Syntax is like this:

```markdown
/coffee.md
---
created: 2021-08-30
tags: drink, work, good, life
---

# Why coffee is good

It just is
```

Relevant vimrc config:

```vim
let g:wiki_root = '~/phren'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
let g:wiki_tags_format_pattern = '\v%(^|\s)#\zs[^# ]+'
let g:wiki_tags_scan_num_lines = 500

nmap <leader>wf :WikiFzfTags <CR>
nmap <leader>wb :WikiGraphFindBacklinks <CR>
nmap <leader>ft :WikiFzfToc <CR>
```

**Comment by lervag** [comment]
> Please support (markdown/yaml) frontmatter in Markdown files, especially parsing of the `tags` field to be used with `WikiFzfTags` and such.

Hmm... well; I'm not quite sure. wiki.vim is _not_ a filetype plugin. So I don't think it makes sense to parse the yaml frontmatter.

But, I'm curious: Do you only use the yaml frontmatter for specifying tags? If so, then perhaps it would suffice to allow parsing a line at the top of the file similar to `tags: word1, ...` (the commas could be optional)?

> I already have syntax highlighting for yaml frontmatter in my wiki.vim/markdown files through https://github.com/aquatix/dotfiles/blob/master/.vim/after/syntax/markdown.vim

Again, wiki.vim is _not_ a filetype plugin; it is also not a syntax plugin. So this is not really relevant.

**Comment by lervag** [comment]
> I know it's not a filetype plugin, that's party why I mentioned I already have syntax highlighting for the frontmatter part of a markdown file, so you knew I wasn't asking that from wiki.vim :)

Haha, ok. No problem. Notice, though, how "implied communication" sometimes fails. Simply "I know this is not a filetype plugin, but ..." would have been simpler. Again, no problem; and I'm not always clear in my own communication either, so no worries! :)

> So being able to parse a tags-line near the top like you mention, would certainly fullfill my wish for this ticket.

Great. I'll look into it!

**Comment by aquatix** [comment]
I wasn't aware that it would trigger you, I included the highlighting part because it was something that I wasn't concerned about with regard to wiki.vim, not because I was literally thinking in terms of "not a filetype plugin" :)

Yeah, communication is... fun. And I already think of myself as someone who is slightly better with words.

Anyway, great that you're going to look into supporting that tag-line, it would really help with my personal wiki/second brain thingee :)

**Comment by lervag** [comment]
I've added an initial version now; please test. See `:help g:wiki_tags_parsers`, it should describe how to make it work for yaml files.

**Comment by aquatix** [comment]
I guess I'm a tad sleep deprived, but with the following config I get an error:

```vim
" wiki.vim
Plug 'lervag/wiki.vim'
" let g:wiki_root = '~/wiki'
let g:wiki_root = '~/phren'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
" let g:wiki_mappings_use_defaults = 1
"support for #tag style tags instead of :tag:
let g:wiki_tags_format_pattern = '\v%(^|\s)#\zs[^# ]+'
" parse tags in lines that match "tags: keyword1, keyword2" in addition to the default parser:
let g:wiki_tags_parsers = [
            \ g:wiki#tags#default_parser,
            \ { 'match': {x -> x =~# '^tags: '}, 
            \ 'parse': {x -> split(matchstr(x, '^tags:\zs.*'), '[ ,]\+')}} 
            \ ] 
" number of lines from the top to scan for tags
let g:wiki_tags_scan_num_lines = 500
" search through the tags in the wiki
nmap <leader>wf :WikiFzfTags <CR>
" find backlinks to this document
nmap <leader>wb :WikiGraphFindBacklinks <CR>
" find in ToC/structure of the (markdown) file
nmap <leader>ft :WikiFzfToc <CR>
```

The error is about the default parser config not being defined (yet?) `E121: Undefined variable: g:wiki#tags#default_parser`.

I know you're not a helpdesk, but could you please help me spot my error? :)

**Comment by lervag** [comment]
> I know you're not a helpdesk, but could you please help me spot my error? :)

I'm glad to help :)

I've pushed some further updates and changes. The following tag related config should work, I believe. Please test, I might have been to quick here... :p

```viml
" Use hashes instead of colons for default tag parser
let s:tag_parser = deepcopy(g:wiki#tags#default_parser)
let s:tag_parser.re_match = '\v%(^|\s)#\zs[^# ]+'
let s:tag_parser.re_findstart = '\v%(^|\s)#\zs[^# ]+'

let g:wiki_tag_parsers = [
            \ s:tag_parser,
            \ {'match': {x -> x =~# '^tags: '},
            \  'parse': {x -> split(matchstr(x, '^tags:\zs.*'), '[ ,]\+')}}
            \ ]

let g:wiki_tag_scan_num_lines = 500
```

Notice I've changed some of the option names (I'll make a release in not too long where I describe all the breaking changes).

**Comment by aquatix** [comment]
That looks nice, but my config can't still find the `g:wiki#tags#default_parser`, so the deepcopy fails, and subsequently s:tag_parser is not defined:

```vim
E121: Undefined variable: g:wiki#tags#default_parser
E116: Invalid arguments for function deepcopy(g:wiki#tags#default_parser)
line  451:
E121: Undefined variable: s:tag_parser
line  452:
E121: Undefined variable: s:tag_parser
line  456:
E121: Undefined variable: s:tag_parser
Error detected while processing /home/mbscholt/.dot/dotfiles/.vim/plugged/wiki.vim/plugin/wiki.vim:
line   61:
E121: Undefined variable: g:wiki#tags#default_parser
E116: Invalid arguments for function wiki#init#option
```

With the snippet from my .vimrc:

```vim
Plug 'lervag/wiki.vim'
" let g:wiki_root = '~/wiki'
let g:wiki_root = '~/phren'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
" let g:wiki_mappings_use_defaults = 1
"support for #tag style tags instead of :tag: (hashes instead of colons)
let s:tag_parser = deepcopy(g:wiki#tags#default_parser)
let s:tag_parser.re_match = '\v%(^|\s)#\zs[^# ]+'
let s:tag_parser.re_findstart = '\v%(^|\s)#\zs[^# ]+'
" parse tags in lines that match "tags: keyword1, keyword2" in addition to the default parser:
let g:wiki_tags_parsers = [
            \ s:tag_parser,
            \ {'match': {x -> x =~# '^tags: '},
            \  'parse': {x -> split(matchstr(x, '^tags:\zs.*'), '[ ,]\+')}}
            \ ]
```

I just updated to your latest revision (thanks for the work!), with the above result.

**Comment by lervag** [comment]
Ah! The problem is that you are doing these things _before_ you're calling `plug#end()`. I understand the idea of keeping everything together, but I strongly recommend to separate the `Plug ...` section from the configuration section; for instance because of "gotchas" like this. The point is that the runtime path is not really changed until after `plug#end()`, which explains why the variable is not available.

**Comment by lervag** [comment]
And, to add, just to be clear: My simple solution above will not work, because `autoload/wiki/tags.vim` is not available until after `plug#end()` is called.

**Comment by lervag** [comment]
I've been thinking about this, and I think the current implementation is quite good. If you update your own config by separating the vim-plug section from your configuration section, then things should work. I understand this is somewhat inconvenient, but it should be a relatively quick job.

**Comment by aquatix** [comment]
That plug#end() part... makes painful sense and only goes to show that even after all those years, I'm far from guru level ;)

I moved the config to after the plug#end() and changed the vars to g:wiki_tag_* but somehow creating the tags list results in a non-usable format for fzf:

```
Error detected while processing function wiki#fzf#tags:                                                                                 
line   10:                                                                                                                              
E688: More targets than List items
```

It looks like this now:
https://github.com/aquatix/dotfiles/blob/wikitags/.vimrc#L523

Your help and work is much appreciated!

**Comment by aquatix** [comment]
I can't see something clearly wrong with the code parts of generating tag lists and the fzf tags part, but I'm not entirely sure how to debug the vimscript code to look into the list structure that's being generated. How I can I help you debug this issue?

**Comment by lervag** [comment]
> That plug#end() part... makes painful sense and only goes to show that even after all those years, I'm far from guru level ;)

Yeah, there's always more to learn! I guess it's part of what makes it fun :)

> It looks like this now:
> https://github.com/aquatix/dotfiles/blob/wikitags/.vimrc#L523

Good. But I would suggest you go further: You should avoid mixing config and
plugin loading alltogether to simply avoid any such problems in the future.

https://github.com/aquatix/dotfiles/blob/wikitags/.vimrc#L22-L520

I would do this:

```vim
call plug#begin('~/.vim/plugged')

" Think of sensible.vim as one step above 'nocompatible' mode: a universal
" set of defaults that (hopefully) everyone can agree on.
Plug 'tpope/vim-sensible'

" Rooter changes the working directory to the project root when you open a
" file or directory. Useful when using fzf for example.
Plug 'airblade/vim-rooter'

" Display tags of the current file ordered by scope
" You need ctags: `sudo apt-get install exuberant-ctags` or
" `brew install ctags` for example
Plug 'majutsushi/tagbar'

" ...

" All of the plugins must be added before the following line
call plug#end()

" ====== Configuration ======

nmap <F8> :TagbarToggle<CR>

let g:airline_theme = "hybrid"

" Disable showing current function in airline
let g:airline#extensions#tagbar#enabled = 0

" ...
```

On my end, it looks like this:

* https://github.com/lervag/dotnvim/blob/main/init.vim#L7 (load plugins)
* https://github.com/lervag/dotnvim/blob/main/init.vim#L385 (configure plugins)

----

> I moved the config to after the plug#end() and changed the vars to g:wiki_tag_* but somehow creating the tags list results in a non-usable format for fzf:

That's my fault. I'm pushing a fix now.

> Your help and work is much appreciated!

Thanks, glad to hear it :)

**Comment by aquatix** [comment]
Awesome, works now!

Yeah, your remark(s) made me think, and I'll be reorganising my vimrc accordingly; wanted to first have this working and not change too many things at once :)

I liked the idea of having the `Plug` line together with that plugin's configuration, but as vim's loading mechanism works differently from what I expected, I'll be organising my config more like yours (wow, your vimrc is even longer than mine :) ). Will also help me organising it a bit better, as those things tend to grow organically.

Anyways, this conversation and the implementation is much appreciated! Might even have learned a bit more vimscript.

Thanks and keep it up, I'll certainly be looking through your config for some gems.

**Comment by lervag** [comment]
Yes, I also find my vim (neovim) config is quite organic, and so over the years I have restructured it several times. Now it's become quite settled. Perhaps in some years I'll rewrite in lua, but for now, I should focus on work. :p

Good luck, and have fun with organising your config! :)

**Comment by bybor** [comment]
> 
> 
> Awesome, works now!

@aquatix , could you please share the final configuration that worked for you? I've been using wiki.vim for quite some time, but haven't yet integrated `tags` into my workflow. I use `asciidoc` filetype instead of `markdown`, but I hope to use your approach.

Any form that works for you - updated dotfiles, blog post, this thread?

Thanks!

**Comment by aquatix** [comment]
I'll be focussing on work first too, but maybe I'll spend a (sizable? :/ ) chunk of my weekend reorganising config lines ;)

@bybor certainly! I'll probably be posting on my weblog too, but for now, I have this:

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/wiki.vim'

" And lots of other plugins

call plug#end()

" wiki.vim config
let g:wiki_root = '~/phren'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
" let g:wiki_mappings_use_defaults = 1
"support for #tag style tags instead of :tag: (hashes instead of colons)
runtime autoload/wiki/tags.vim
let s:tag_parser = deepcopy(g:wiki#tags#default_parser)
let s:tag_parser.re_match = '\v%(^|\s)#\zs[^# ]+'
let s:tag_parser.re_findstart = '\v%(^|\s)#\zs[^# ]+'

"let g:wiki_tags_format_pattern = '\v%(^|\s)#\zs[^# ]+'
" parse tags in lines that match "tags: keyword1, keyword2" in addition to the default parser:
let g:wiki_tag_parsers = [
            \ s:tag_parser,
            \ {'match': {x -> x =~# '^tags: '},
            \  'parse': {x -> split(matchstr(x, '^tags:\zs.*'), '[ ,]\+')}}
            \ ]
" number of lines from the top to scan for tags
let g:wiki_tag_scan_num_lines = 500
" search through the tags in the wiki
nmap <leader>wf :WikiFzfTags <CR>
" find backlinks to this document
nmap <leader>wb :WikiGraphFindBacklinks <CR>
" find in ToC/structure of the (markdown) file
```

You can find [my current .vimrc here](https://github.com/aquatix/dotfiles/blob/master/.vimrc)
