### ISSUE TITLE
Adding info about g:wiki_filetypes behaviour in docs

### ISSUE THREAD

**Issue by DerpGusta** [lervag/wiki.vim#190]
I was trying to make markdown as the default extension for my wiki. When I searched the docs, I could not find any info on it.
After some searching, I came to understand that the plugin looks for the filetype to be set in `g:wiki_filetypes` . Once I added `'md'` to the beginning , the default wiki index shortcut redirected to index.md. 

I would like to suggest adding some more info about this behaviour in the documentation like so:

```
*g:wiki_filetypes*
 List of filetypes for which |wiki.vim| should be enabled. 
 If you want to make markdown the default format, you can do so like this:
          let g:wiki_filetypes = [ 'md', 'wiki', ... ]

  Default: ['wiki']
```

**Comment by lervag** [comment]
Thanks; I've tried to improve the docs based on your suggestion. Let me know what you think.
