### ISSUE TITLE
Installation error tags.vim line 88+

### ISSUE THREAD

**Issue by donniep** [lervag/wiki.vim#194]
# Description

The description should provide the details necessary to address the issue.
This typically includes the following:

1. A description of the expected behaviour - _installation without error_
2. A description of the observed behaviour - _receive the following when I open neovim_
```
Error detected while processing /home/donnie/.config/nvim/autoload/plugged/wiki.vim/autoload/wiki/tags.vim:
line   88:
E475: Invalid argument: old_tag, new_tag='', rename_to_existing=v:false) abort " {{{1
line   89:
E121: Undefined variable: a:new_tag
E15: Invalid expression: a:new_tag ==# ''
line   94:
E193: :endfunction not inside a function
line   97:
E475: Invalid argument: old_tag='', new_tag='', ...) abort " {{{1
line   99:
E121: Undefined variable: a:old_tag
E15: Invalid expression: a:old_tag ==# '' ? input('Enter tag to rename (wihtout delimiters): ',
line  101:
E20: Mark not set
line  102:
E121: Undefined variable: l:old_tag
E15: Invalid expression: l:old_tag ==# '' | return | endif
line  107:
E133: :return not inside a function
line  389:
E133: :return not inside a function
line  397:
E133: :return not inside a function
line  527:
E133: :return not inside a function
line  531:
E171: Missing :endif
Error detected while processing /home/donnie/.config/nvim/autoload/plugged/wiki.vim/plugin/wiki.vim:
line   62:
E121: Undefined variable: g:wiki#tags#default_parser
E116: Invalid arguments for function wiki#init#option
Press ENTER or type command to continue
```
3. The steps required to reproduce the issue

- Install neovim on gentoo
- Install vim-plug
- Install vim-polyglot with vim-plug
- Install NERDTree with vim-plug
- Install auto-pairs with vim-plug
- Install vim-markdown with vim-plug
- Install wiki.vim with vim-plug

If your issue is instead a feature request or anything else, please consider if
minimal examples and vimrc files might still be relevant.

# Minimal working example - _See above_

Please provide a minimal working example, for instance something like this:

```
/path/to/minimal-working-example-wiki
├── index.wiki
├── journal
│   └── 2017-11-24.wiki
└── test.wiki
```

The file contents should of course also be included if necessary. Please also
provide a minimal vimrc file, e.g.

```vim
source $HOME/.config/nvim/vim-plug/plugins.vim
autocmd BufNewFile,BufRead *.md set filetype=markdown
autocmd FileType markdown set cursorline

" Vim-Markdown
let g:vim_markdown_edit_url_in = 'tab'
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_folding_disabled = 1

" Wiki.vim
let g:wiki_root = '~/Notes'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'

" Have lines wrap instead of continue off-screen
set linebreak

" Gives Vim access to a broader range of colours
set termguicolors
```

**Comment by lervag** [comment]
Which version of Vim or neovim are you using?

**Comment by lervag** [comment]
I believe this may be caused by using relatively new vimscript syntax that is only supported by Vim 8.1 and neovim 0.5.

**Comment by donniep** [comment]
Neovim 0.4.4.  Also, I installed vim with the same plugins and confirmed that there is no error on vim, so this issue is specific to neovim.

—
Donnie Pennington

On Oct 31, 2021, at 3:50 PM, Karl Yngve Lervåg ***@***.***> wrote:

﻿
Which version of Vim or neovim are you using?

**Comment by lervag** [comment]
> Neovim 0.4.4. Also, I installed vim with the same plugins and confirmed that there is no error on vim, so this issue is specific to neovim.

No, it is as I said specific to the version of neovim. If you install neovim v0.5 I believe things should work.

But I'll reconsider the use of modern syntax.

**Comment by lervag** [comment]
I believe things should work now, please update and test.

**Comment by donniep** [comment]
Yes, thank you.  Fix confirmed.

—
Donnie Pennington

On Nov 1, 2021, at 3:59 AM, Karl Yngve Lervåg ***@***.***> wrote:

﻿
I believe things should work now, please update and test.
