### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by BonaBeavis** [lervag/wiki.vim#195]
# Description

I profiled nvim startup time with [nvim-startup](https://github.com/henriquehbr/nvim-startup.lua).
Wiki.vim takes about 0.5 seconds to load, compared to nvim's startup time 0.1 this is a lot.

# Minimal working example

```vim
set nocompatible
filetype off

call plug#begin('~/.neovim/bundle')
Plug 'henriquehbr/nvim-startup.lua'
Plug 'lervag/wiki.vim'
call plug#end()

syntax on
filetype plugin indent on

lua <<EOF
require 'nvim-startup'.setup {
    startup_file = '/var/tmp/nvim-startuptime'
}
EOF
```

**Comment by lervag** [comment]
No, wiki.vim does not take 500ms to load! With your minimal working example, I get a startup time of about 55 ms, and wiki.vim adds about 13 ms:

```
019.647  000.035  000.035: sourcing /home/lervag/.local/plugged/wiki.vim/autoload/wiki/init.vim
019.808  000.087  000.087: sourcing /home/lervag/.local/plugged/wiki.vim/autoload/wiki/u.vim
026.719  000.533  000.533: sourcing /home/lervag/.local/plugged/wiki.vim/autoload/wiki/tags.vim
032.697  013.147  012.491: sourcing /home/lervag/.local/plugged/wiki.vim/plugin/wiki.vim
```

Feel free to provide more concrete evidence that I'm wrong, of course.

**Comment by BonaBeavis** [comment]
I identified the offending line:
https://github.com/lervag/wiki.vim/blob/c54be18c2aa85db6a3b9ba7836cd59bbe1935e5b/autoload/wiki/u.vim#L75
The system function takes about 200ms to call. So this looks like an upstream issue.

**Comment by lervag** [comment]
Yes, I think it must be an upstream issue.

However, I've added caching to these "static" system calls now, which I believe resolves the issue. Please update and test.

**Comment by BonaBeavis** [comment]
It now takes about 2ms! Thanks a lot!

**Comment by lervag** [comment]
Happy to hear it works :)
