### ISSUE TITLE
Markdown links with spaces in URLs not opening correctly

### ISSUE THREAD

**Issue by briandipalma** [lervag/wiki.vim#199]
# Description

Markdown links can include spaces in their URL but they require angle brackets to navigate when rendered, e.g.
`- [How to calculate contra amount](<How to calculate contra amount.md>)`.

Navigating with wiki.vim keeps the angle brackets in the filename which means it opens a new blank markdown file `<How to calculate contra amount.md>.md` instead of navigating to the linked file.

I guess if the link target type is `md` file name needs a small amount of parsing, i.e. `<$FILE_NAME.md>`?

**Comment by briandipalma** [comment]
Actually now that I think about it the links should have <> added to them on creation if the link text has spaces in it too. Maybe there should be an option to replace spaces with `-` or `_` built in instead of using the transform function you mention in the documentation.

**Comment by lervag** [comment]
> Markdown links can include spaces in their URL but they require angle brackets to navigate when rendered, e.g. `- [How to calculate contra amount](<How to calculate contra amount.md>)`.

I don't think this is part of any standard Markdown references? Could you give me some references to where this syntax is used/understood?

> Actually now that I think about it the links should have <> added to them on creation if the link text has spaces in it too.

I guess one idea would be to add an option for these brackets. Currently, I believe it should be possible to get the desired effect from using the transforms/maps.

If you find this to be a necessary feature, it would be useful with some test/example files, e.g.: a handful (at least 2) example `.md` files and a minimal vimrc. I can help with the minimal vimrc file, if necessary.

> Maybe there should be an option to replace spaces with `-` or `_` built in instead of using the transform function you mention in the documentation.

Perhaps; I think that's a separate issue/request, though.

**Comment by briandipalma** [comment]
You're right it's CommonMark: https://spec.commonmark.org/0.30/#links it works on GitHub though (that's where I'm storing my wiki).

Now that I think about it adding `_` to the links isn't that bad an idea, the file would then be `How_to_calculate_contra_amount.md`, which seems reasonable. I'll test this tomorrow and report but maybe that's a better approach? An option that replaces spaces in newly created links+files with a special character?

**Comment by briandipalma** [comment]
Yes, `[Some link](Some_link.md)` works great, I created the link by visually selecting `Some link` and hitting enter and then added the `_` in the space, hit enter and the file `Some_link.md` was created. It would be nice if there was an option to replace spaces with a specified character in links when they are created. It's not pressing though as I can do this manually.

**Comment by briandipalma** [comment]
I don't think I need spaces at all TBH, I can't just use underscores in my link text, make it simple.

**Comment by lervag** [comment]
Sorry for the delay in responding! It seems you concluded that I did not need to change anything here. But I'm not sure.

Note that you can use a transformation to add the underscore automatically, see e.g. `:help g:wiki_map_link_create` and `:help g:wiki_map_create_page`.

**Comment by briandipalma** [comment]
Yeah I was looking at those but I'm happy enough to just use underscores in my linked text. The simplest solution, I think I was overthinking it earlier.

**Comment by lervag** [comment]
Great. I also tend to prefer simple solutions :)

**Comment by artkpv** [comment]
@briandipalma  thanks for posting this. @lervag , thanks for the wiki.vim tool. I'm rendering my markdown files via https://github.com/simov/markdown-viewer which can't render links with spaces which are not turned into entities (the '%20' entity) or enclosed in '<' and '>' (see https://spec.commonmark.org/0.31.2/#link-destination). However, when I do that for my file, wiki.vim tries to open / create a file with those things (with %20 or with < >) as it is shown above. How to handle spaces in my wiki for links now? I mean I need some pesky ways to convert my markdown for wiki.vim, then for the Markdown VIew, and others (I also render it on an Android app). Why wiki.vim doesn't use the standard? I how to enable it. Thanks

**Comment by lervag** [comment]
> @lervag , thanks for the wiki.vim tool.

Glad you find it useful!

> I'm rendering my markdown files via https://github.com/simov/markdown-viewer which can't render links with spaces which are not turned into entities (the '%20' entity) or enclosed in '<' and '>' (see https://spec.commonmark.org/0.31.2/#link-destination). However, when I do that for my file, wiki.vim tries to open / create a file with those things (with %20 or with < >) as it is shown above. How to handle spaces in my wiki for links now? I mean I need some pesky ways to convert my markdown for wiki.vim, then for the Markdown VIew, and others (I also render it on an Android app). Why wiki.vim doesn't use the standard? I how to enable it. Thanks

In this case, you will want to adjust your link resolver. The docs already have you mostly covered - I believe you might want to read `:help wiki-advanced-config-2`.

For convenience, this is probably what you want:

```vim
" Create a custom resolver to apply URL decoding
function! MyWikiResolver(url) abort
  let l:url = deepcopy(a:url)

  let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

  let l:path = split(l:url.stripped, '#', 1)[0]
  let l:path = wiki#url#utils#url_decode(l:path)
  let l:url.path = wiki#url#utils#resolve_path(l:path, l:url.origin)

  return l:url
endfunction

" Change the wiki scheme resolver to the custom one
let g:wiki_link_schemes = {
      \ 'wiki': {
      \   'resolver': function('MyWikiResolver'),
      \ }
      \}

" Change link creation to apply URL encoding
let g:wiki_link_creation = {
      \ 'md': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \ 'wiki': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \}
```

I would also kindly ask, if the proposed solution here was not what you needed/wanted, that you open a new issue and provide some more details.

**Comment by artkpv** [comment]
@lervag Thanks for the answer!

I've tried quickly but it now resolves Cyrillic chars to '<bf>' . I will try later again. Example:

```
- [Инкубатор](инкубатор.md) 
```
Pressing Enter on that link results in this buffer trying to be opened: "~/m/n/<bf><bf><bf><bf><bf><bf><bf><bf><bf>.md"

Here is my config:

```

let g:wiki_root = '~/mydir/notes/'

let g:wiki_filetypes = ['md']

let g:wiki_link_creation = {
      \ 'md': {
      \   'link_type': 'md',
      \   'url_extension': '',
      \ },
      \}

let g:wiki_month_names = [ '01.Январь', '02.Февраль', '03.Март', '04.Апрель', '05.Май', '06.Июнь', '07.Июль', '08.Август', '09.Сентябрь', '10.Октябрь', '11.Ноябрь', '12.Декабрь' ]

let g:wiki_toc_title = 'Содержание'

let g:wiki_journal = {
    \ 'index_use_journal_scheme': v:false,
    \ 'name': '2024',
    \ 'frequency': 'daily',
    \ 'date_format': {
    \   'daily' : '%Y-%m-%d',
    \ },
    \}

    "\   'weekly' : '%Y-%m-%d_%V_неделя',
    "\   'monthly' : '%Y-%m-%d_месяц',

let g:wiki_template_title_week = '# %(year). %(week) неделя'
let g:wiki_template_title_month = '# %(year). %(month-name) месяц'

function! MyWikiBufferInit() 
  try
    let $TYPESET_PATH = expand("%:p")
    if $TYPESET_PATH !~# '\v\.(index.md|index.wiki)$'
        "set guifont=Nimbus\ Mono\ PS:h7.5
        " set guifont=FreeMono\ For\ Powerline:h7.5
        set guifont=Go\ Mono\ For\ Powerline:h7
        colorscheme PaperColor
    endif
  catch
  endtry
  set laststatus=0
  set foldcolumn=4
  au! BufWritePost ~/mydir/notes/* !git add "%";git commit -m "Auto commit of %:t." "%"

  nmap <leader>mh :s_\v^((#+) +)?(.*)_#\2 \3_e<CR> :noh<CR>
  nmap <leader>mH :s_\v^#(#* )? *(.*)_\1\2_e<CR> :noh<CR>
  set foldlevel=1
  " Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
  "CocDisable
    ALEDisable
endfunction

augroup MyWikiAutocmds
  autocmd!
  autocmd User WikiBufferInitialized call MyWikiBufferInit()
augroup END

function! MyWikiClean() 
    " Clean escape '\' chars inserted by Evernote export.
    %s_\\__gce

    " Clean enclosing of links with '<' and '>' chars.
    %s_\v\<([^\>]+)\>_\1_gce

    %s_\v\!\[\]\((local.*\/([^\)]+))\)(\{wid[^}]*\})?_[\2](\1)_

endfunction

let g:wiki_viewer = {
    \ '_' : 'xdg-open',
    \}

let g:wiki_journal_index = {
    \ 'link_text_parser': { b, d, p -> wiki#toc#get_page_title(p) },
    \ 'link_url_parser': { b, d, p -> wiki#paths#relative(p, expand('%:p:h')) }
    \}


nmap <leader>wjn <Plug>(wiki-journal-next)
nmap <leader>wjp <Plug>(wiki-journal-prev)

let g:wiki_select_method = {
      \ 'pages': function('wiki#fzf#pages'),
      \ 'tags': function('wiki#fzf#tags'),
      \ 'toc': function('wiki#fzf#toc'),
      \}
let g:wiki_fzf_pages_opts = '--preview "bat {1}"'
let g:wiki_fzf_tags_opts = '--preview "bat {2..}"'

nmap <leader>wgp :WikiPages<CR>
nmap <leader>wgc :WikiToc<CR>
nmap <leader>wgt :WikiTags<CR>
nmap <leader>wr :WikiGraphRelated<CR>

function! MyWikiPageRename()
    call inputsave()
    let name = input('Enter new name (' .. expand('%:t') .. '): ')
    call inputrestore()
    call termopen(['./ren.sh', expand('%'), name])
endfunction
nmap <leader>wpr :call MyWikiPageRename()<CR>


" Create a custom resolver to apply URL decoding
function! MyWikiResolver(url) abort
  let l:url = deepcopy(a:url)

  let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

  let l:path = split(l:url.stripped, '#', 1)[0]
  let l:path = wiki#url#utils#url_decode(l:path)
  let l:url.path = wiki#url#utils#resolve_path(l:path, l:url.origin)

  return l:url
endfunction

" Change the wiki scheme resolver to the custom one
let g:wiki_link_schemes = {
      \ 'wiki': {
      \   'resolver': function('MyWikiResolver'),
      \ }
      \}

" Change link creation to apply URL encoding
let g:wiki_link_creation = {
      \ 'md': {
      \   'link_type': 'md',
      \   'url_extension': '',
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \ 'wiki': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \}


```

**Comment by lervag** [comment]
> @lervag Thanks for the answer!
> 
> I've tried quickly but it now resolves Cyrillic chars to '' . …

Interesting. Could you please open a new issue for this?

> Here is my config: …

Ok, that's a mess! For your convenience, this is your config, but cleaned up. Some comments:

* Separate settings, functions, mappings and autocommands. This makes it much easier to see what is happening at a glance! Functions come first, since they are used by the config.
* Remove unnecessary stuff, e.g. options you did not change from defaults.
* Notice that using "2024" as the `g:wiki_journal.name` value seems like a bad idea!

```vim
function! MyWikiBufferInit()
    try
        let $TYPESET_PATH = expand("%:p")
        if $TYPESET_PATH !~# '\v\.(index.md|index.wiki)$'
            set guifont=Go\ Mono\ For\ Powerline:h7
            colorscheme PaperColor
        endif
    catch
    endtry
    set laststatus=0
    set foldcolumn=4
    au! BufWritePost ~/mydir/notes/* !git add "%";git commit -m "Auto commit of %:t." "%"

    nmap <leader>mh :s_\v^((#+) +)?(.*)_#\2 \3_e<CR> :noh<CR>
    nmap <leader>mH :s_\v^#(#* )? *(.*)_\1\2_e<CR> :noh<CR>
    set foldlevel=1
    " Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
    "CocDisable
    ALEDisable
endfunction

function! MyWikiPageRename()
    call inputsave()
    let name = input('Enter new name (' .. expand('%:t') .. '): ')
    call inputrestore()
    call termopen(['./ren.sh', expand('%'), name])
endfunction

" Create a custom resolver to apply URL decoding
function! MyWikiResolver(url) abort
    let l:url = deepcopy(a:url)

    let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

    let l:path = split(l:url.stripped, '#', 1)[0]
    let l:path = wiki#url#utils#url_decode(l:path)
    let l:url.path = wiki#url#utils#resolve_path(l:path, l:url.origin)

    return l:url
endfunction

function! MyWikiClean()
    " Clean escape '\' chars inserted by Evernote export.
    %s_\\__gce

    " Clean enclosing of links with '<' and '>' chars.
    %s_\v\<([^\>]+)\>_\1_gce

    %s_\v\!\[\]\((local.*\/([^\)]+))\)(\{wid[^}]*\})?_[\2](\1)_
endfunction

let g:wiki_root = '~/mydir/notes/'

let g:wiki_link_creation = {
      \ 'md': {
      \   'link_type': 'md',
      \   'url_extension': '',
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \ 'wiki': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \}

let g:wiki_link_schemes = {
      \ 'wiki': {
      \   'resolver': function('MyWikiResolver'),
      \ }
      \}

let g:wiki_month_names = [ '01.Январь', '02.Февраль', '03.Март', '04.Апрель', '05.Май', '06.Июнь', '07.Июль', '08.Август', '09.Сентябрь', '10.Октябрь', '11.Ноябрь', '12.Декабрь' ]

let g:wiki_template_title_week = '# %(year). %(week) неделя'
let g:wiki_template_title_month = '# %(year). %(month-name) месяц'

let g:wiki_toc_title = 'Содержание'

" WARNING: 2024 is a BAD name! Consider using the default "journal" instead.
let g:wiki_journal = {
    \ 'name': '2024',
    \}

let g:wiki_journal_index = {
    \ 'link_text_parser': { b, d, p -> wiki#toc#get_page_title(p) },
    \ 'link_url_parser': { b, d, p -> wiki#paths#relative(p, expand('%:p:h')) }
    \}

let g:wiki_select_method = {
      \ 'pages': function('wiki#fzf#pages'),
      \ 'tags': function('wiki#fzf#tags'),
      \ 'toc': function('wiki#fzf#toc'),
      \}
let g:wiki_fzf_pages_opts = '--preview "bat {1}"'
let g:wiki_fzf_tags_opts = '--preview "bat {2..}"'

nnoremap <leader>wpr :call MyWikiPageRename()<CR>
nnoremap <leader>wgp :WikiPages<CR>
nnoremap <leader>wgc :WikiToc<CR>
nnoremap <leader>wgt :WikiTags<CR>
nnoremap <leader>wr :WikiGraphRelated<CR>
nmap <leader>wjn <Plug>(wiki-journal-next)
nmap <leader>wjp <Plug>(wiki-journal-prev)

augroup MyWikiAutocmds
  autocmd!
  autocmd User WikiBufferInitialized call MyWikiBufferInit()
augroup END
```

**Comment by artkpv** [comment]
Hi @lervag, thanks for the tool and for the above answers!

I still find the way wiki.vim handles spaces in links confusing as it is clearly diverge from the standards (https://spec.commonmark.org/0.31.2/#links , https://github.github.com/gfm/#links, other). I mean that these are implemented by other apps I use as described above. Why not implement in wiki.vim? Also, I noticed that https://github.com/preservim/vim-markdown/blob/master/doc/vim-markdown.txt#L236 also started not to conceal links without < and > , so now I see my links. To reiterate, links with spaces, but without < and >, works for me inside wiki.vim, but they are shown incorrectly or simply don't work in other applications, because wiki.vim doesn't use markdown standards.

**Comment by lervag** [comment]
> I still find the way wiki.vim handles spaces in links confusing as it is clearly diverge from the standards (https://spec.commonmark.org/0.31.2/#links , https://github.github.com/gfm/#links, other). I mean that these are implemented by other apps I use as described above. Why not implement in wiki.vim?

I actually totally agree. wiki.vim should behave "as expected" when used with Markdown files, which means it should _not_ diverge from the shared specs.

Side note: As far as I understand, there is not really a single spec for Markdown. But I think this is irrelevant, because in this case there _is_ a shared concept that is similar in the various flavors found.

Would you by any chance be willing to help me here, specifically by

1. Opening a _new_ issue for this, e.g. "Make wiki.vim follow markdown standards".
2. In the issue, provide the relevant links to the specs I should be aware of. More or less a copy of what you already wrote.
3. If you would be extra kind: Add a few concrete examples of how wiki.vim currently does _not_ follow the standard.

I will make this a priority, but of course, I can't make promises on how fast I'll be able to fix it. Still, I hope I will be able to do it by end of November.
