### ISSUE TITLE
Weekly/monthly journal support

### ISSUE THREAD

**Issue by jgilchrist** [lervag/wiki.vim#2]
Similar to https://github.com/vimwiki/vimwiki/issues/265, I'd like to express my interest in a tweak to the journal functionality to allow it to use weekly journal files.

To provide some flexibility here, do you think it is feasible to allow specifying a custom date format string with which to create the journal file? For example, if the default is `%Y-%m-%d` which would be 2017-11-27 today and 2017-11-28 tomorrow, and you wanted to reduce the frequency of journal entries to weekly, you could specify `%Y-%U` which would be `2017-48` this week and `2017-49` next week, or `%Y-%m` for monthly for example.

Please let me know your thoughts!

**Comment by lervag** [comment]
Yes, this should not be too difficult. I personally use a daily journal with weekly and monthly summaries, and so I already have some support for this in the type of summaries.

To make this work, I would need to add an option that specifies the preferred "resolution" of the diary/journal (daily, weekly or monthly). I would use the following entry formats:

```
%Y-%m-%d  2017-11-27
%Y-w%U    2017-w48
%Y-m%m    2017-m11
```

I'll look into it when I get the time. As you have probably noticed, there is some work remaining to make this plugin more mature and less "personal". I will add this issue to the TODO list in the readme file, and add the feature when time permits.

**Comment by lervag** [comment]
Semi related: #20

**Comment by lervag** [comment]
Sorry for taking so long! The feature should now be supported, at least partly. I'll refine and improve when I get time, but I think it should already be near OK.

**Comment by lervag** [comment]
I think this should work as expected now.

**Comment by jgilchrist** [comment]
Thanks @lervag! I'll give it a go

**Comment by lervag** [comment]
Great! I'm happy to note that you might still have interest in this!
