### ISSUE TITLE
Unnecessary zero-width matches in rx.vim?

### ISSUE THREAD

**Issue by anjiro** [lervag/wiki.vim#202]
`autoload/wiki/rx.vim` uses both [`\@<=`](https://github.com/lervag/wiki.vim/blob/bc393f30194201b613bd163afe4315dcc68462fb/autoload/wiki/rx.vim#L8) and [`\zs`](https://github.com/lervag/wiki.vim/blob/bc393f30194201b613bd163afe4315dcc68462fb/autoload/wiki/rx.vim#L9), and [`\ze`](https://github.com/lervag/wiki.vim/blob/bc393f30194201b613bd163afe4315dcc68462fb/autoload/wiki/rx.vim#L13) and [`\@=`](https://github.com/lervag/wiki.vim/blob/bc393f30194201b613bd163afe4315dcc68462fb/autoload/wiki/rx.vim#L14). `:h /\@<=` suggests using `\zs` instead, and using `\ze` works instead of `\@=`.

Filing this as an issue rather than a patch in case there’s a good reason for it.

**Comment by lervag** [comment]
Agreed, this looks like a mistake. Fixed now.
