### ISSUE TITLE
Ability to make journal links as usual markdown links, i.e. without `journal:` prefix

### ISSUE THREAD

**Issue by artkpv** [lervag/wiki.vim#206]
# Description

I use my wiki at Android phone where I use another app which doesn't understand 'journal:' links so I'm not able to browse my journal.

# Minimal working example

Now: 

```
[2021-11-12 ](journal:2021-11-12-2012)
```

Expected:
```
[2021-11-12 ](myjournaldir/2021-11-12-2012.md)
```
Or absolute.

**Comment by lervag** [comment]
> I use my wiki at Android phone where I use another app which doesn't understand 'journal:' links so I'm not able to browse my journal.

Ah, that's an interesting point. Just curious, the problem here is related to the journal index feature, right? Or is there anything else/more?

I use this `journal:` scheme myself, but only manually.

Also, I'm curious: Which app are you using on Android that allows to following links?

**Comment by artkpv** [comment]
> Ah, that's an interesting point. Just curious, the problem here is related to the journal index feature, right? Or is there anything else/more?

Right, this is journal index. It generates links with `journal:` prefix by default. Not sure about other places

> Also, I'm curious: Which app are you using on Android that allows to following links?

This is [Markor](https://play.google.com/store/apps/details?id=net.gsantner.markor&hl=en_US&gl=US). I also use Termux which is a shell for Android but there I can use wiki.vim

**Comment by lervag** [comment]
I've added an option for this now. Please update, then test if things work as expected after adding this:

```vim
let g:wiki_journal = {'index_use_journal_scheme': v:false}
```

(You can use `0` instead of `v:false`, if you prefer.)

**Comment by artkpv** [comment]
It works nice, thanks! :+1:

**Comment by lervag** [comment]
Great, glad to hear it!
