### ISSUE TITLE
Backlinks from journal entries to wiki pages are not detected

### ISSUE THREAD

**Issue by agorf** [lervag/wiki.vim#209]
Hello, and thank you for wiki.vim

I'm not sure whether this is on purpose, a bug, or something I'm not using correctly since I'm a beginner. But here it goes:

# Description

1. Expected: Links in journal entries count as backlinks to wiki pages
2. Observed: They don't
3. Steps to reproduce: Please see "Minimal working example"

# Minimal working example

```
~/work/wiki/
├── index.wiki
└── journal
   └── 2021-12-29.wiki
```

Go to the journal page and add a link to a top level page, e.g. `[[/Foo]]`

Go to the Foo page and search for backlinks. None are found.

My vimrc:

```vim
let g:wiki_global_load = 0
let g:wiki_root = '~/work/wiki/'
let g:wiki_write_on_nav = 1
function! WikiTemplate(context)
  call append(0, '# ' . a:context.name)
  call append(1, '')
  startinsert
endfunction
let g:wiki_templates = [
      \ { 'match_re': '.',
      \   'source_func': function('WikiTemplate')},
      \]
Plug 'lervag/wiki.vim'
Plug 'lervag/wiki-ft.vim'
nmap <leader>fw :WikiFzfPages<CR>
```

Thanks!

**Comment by lervag** [comment]
Strange. On my end, it works as expected:

![image](https://user-images.githubusercontent.com/998898/147860551-2de8287e-6902-45cd-942c-bd03886375ce.png)

**Comment by lervag** [comment]
Perhaps the problem is that the `Foo` page does not exist when you are doing the backlink search? I.e., if I do exactly as in your example, then I can reproduce. But if I add a `:write` before I do `:WikiGraphFindBacklinks` then it works as expected.

**Comment by lervag** [comment]
I've pushed an adjustment that warns the user if the current file is not saved. It should make things more intuitive, I think.

**Comment by agorf** [comment]
> Perhaps the problem is that the `Foo` page does not exist when you are doing the backlink search? I.e., if I do exactly as in your example, then I can reproduce. But if I add a `:write` before I do `:WikiGraphFindBacklinks` then it works as expected.

Yes. That was the cause.

Thank you.
