### ISSUE TITLE
Suggestion: Split/Reduce WikiPrint functionality

### ISSUE THREAD

**Issue by jounathaen** [lervag/wiki.vim#21]
This is just my personal taste and a very minor issue, but I'm not super happy with the behaviour of `WikiPrint`.

### Complaints 😉
When I call `:WikiPrint`, I have 3 successive dialogues: View file, Print File and Export File.

I think dialogues are not the best interface in vim (very personal opinion).
My "Problem" with this is, that when I want to view the pdf and type 'y' when I'm asked "View file", It opens the pdf immediately (which is fine). But when I close the pdf viewer, I already have forgotten that I'm stil in the dialogue and wonder, why there is nothing happening in the buffer until I take a look at the bottom of the screen :-D

### Suggestion
I would argue, that all the functionality could also be provided with a single command `WikiGeneratePDF` and an optional parameter for the export filename (if not given, use /tmp/.. as default).
Maybe the command should now open the pdf viewer, but nothing more. Printing can (and should IMHO) be done from the PDF viewer, which provides a interface for printing options. (Acutally I have never printed from vim).
(Besides that, I think that "printing" is not the primary functionality of the `WikiPrint` and therefore it should not be named like this.)

The command `WikiGeneratePDF` could then provide almost the same functionality with less interaction required.

Thanks for developing this nice plugin 👍!

**Comment by lervag** [comment]
Thanks, this is a well argued feature request and I generally agree on all parts. How about something like this:

```
:[range]WikiGeneratePDF [-export PATH] [-view]
  Will generate a PDF from the current wiki file (or the given range). With
  `-export PATH` one can set the output file path, and with `-view` one can
  specify to open the generated PDF with a PDF viewer (useful to quickly
  inspect the file).
```

I'll merge the above with the current documentation. Note, this would deprecate
all of the current dialogues.

What do you think?

**Comment by jounathaen** [comment]
> What do you think?

Great! Maybe add something like _"if -export PATH is not specified, only a temporary file is generated but it can be viewed as well"_  

A message like `generated /tmp/wikipagefilename.pdf successfully` after a successfull generation would be nice.

**Comment by lervag** [comment]
Great, both of your comments are sensible. I'll address this later this week, if I get the time. Summarized:

- [ ] Add command `WikiGeneratePDF` as described below:

    ```
    :[range]WikiGeneratePDF [-export PATH] [-view]
      Will generate a PDF from the current wiki file (or the given range). With
      `-export PATH` one can set the output file path. If it is not provided,
      then a temporary file is created, e.g. "/tmp/path.pdf". With `-view` one
      can specify to open the generated PDF with a PDF viewer (useful to
      quickly inspect the file).
    ```

- [ ] The command should give output similar to `generated /tmp/path.pdf successfully`.

**Comment by lervag** [comment]
Ok, let me know what you think. The default mapping applies the `-view` argument. It somehow feels sensible, but I'm not 100% sure if it is intuitive or not.

**Comment by jounathaen** [comment]
Great, thank you for your effort! 👍 
It's almost how I imagined it.
However, I still have some small remarks 

I think, it might be better, if `-view` is the default, *if no other parameters are given*.
(On a MacBook, tempname() generates a paht like `/var/folders/54/gwtjf7ks0jz276z6lqhr6jh00000gp/T/nvimlPCi1k/15.pdf` which I don't want to open manually 😄.  This makes the blank `WikiGeneratePDF` command a bit useless)

It also feels like the `-export` flag is a bit redundant.
If the given parameter is not "-view", then it must be the filename. Therefore there might be no necessarity to add `-export`.

Command combinations:
- `WikiGeneratePDF`:  Generates temporary file and opens it.
- `WikiGeneratePDF mypage.pdf`: Generates _mypage.pdf_.
- `WikiGeneratePDF mypage.pdf -view`:  Generates _mypage.pdf_ and opens it.

This makes the `-view` parameter not 100% consistent but I think it would be easier to use and less typing.

Optional: The filename of the tempfile could be related to the Wiki Page file name.

**Comment by lervag** [comment]
Thanks, I agree with your comments. I think the new version might be good?

**Comment by jounathaen** [comment]
Pure `WikiGeneratePDF` and `WikiGeneratePDF -view` work as expected :cool: .

But when I call `WikiGeneratePDF mypdf.pdf` or `WikiGeneratePDF -view mypdf.pdf`, I get the following error:
```
Error detected while processing function wiki#page#generate_pdf:
line   10:
E684: list index out of range: 0
```
`WikiGeneratePDF mypdf.pdf -view`, creates a file _-view_ and opens it :smile:

**Comment by lervag** [comment]
Sorry about that! Fixed now. :)

**Comment by jounathaen** [comment]
Great!
Works and can be closed now! Thank you very much for your effort! :+1: 

I noticed, that when you export it with a different file suffix, pandoc will generate e.g. a _html_ or _odf_ file. As if it has not changed enough yet, but maybe renaming the function to something like `WikiExport` could make a feature out of the behaviour :smile: .

**Comment by lervag** [comment]
Yes, this sounds like a good idea. I would propose the following: `WikiExport` has option `-format` that takes e.g. `pdf` as input, and it has e.g. `-wiki-format` to set the desired input format (which is now `gfm`). An option `g:wiki_export` can be used to set the default values.

I would be happy to work on this, but can't do it right now. Could you open a new issue for this? I'll close this for now, since the original issue is resolved.
