### ISSUE TITLE
Whitespace in Reference Links does not work

### ISSUE THREAD

**Issue by BirgerNi** [lervag/wiki.vim#213]
Markdown links with whitespace work. The following link opens the file `wiki file.md`:

```vim
[wiki file](wiki file)
```

With reference style links there seem to be a problem with whitespace.

```vim
[1]

[1]: wiki:wiki file
```

* Expected behaviour: opens file `wiki file.md`
* Actual behaviour: opens file `wiki.md`

Please let me know whether I can provide more information or there is a known workaround.

**Comment by lervag** [comment]
> Please let me know whether I can provide more information or there is a known workaround.

Thanks, the description is clear. The reason for this is that I am not sure if this is really desirable. It may be. I'm not sure if there is a canonical specification here, but I found [this](https://www.markdownguide.org/basic-syntax#formatting-the-second-part-of-the-link), which also differs from the current implementation.

**Comment by lervag** [comment]
Other related references:

* https://docs.microsoft.com/en-us/contribute/how-to-write-links#reference-style-links
* https://spec.commonmark.org/0.30/#link-reference-definitions
* https://daringfireball.net/projects/markdown/syntax#link

I'm thinking that it could make sense to adhere to the commonmark spec, except, for simplicity, to avoid the newlines. What do you think?

**Comment by lervag** [comment]
By the way, I like the nomenclature used in the commonmark spec, so I could perhaps also update the docs and code to adhere the spec.

**Comment by BirgerNi** [comment]
The common way seems to be just enclose the URL in angle bracket.

```markdown
[1]

[1]: <wiki:wiki file>
```

I thing it is a good idea to follow CommonMark spec.

**Comment by lervag** [comment]
I believe the original issue is resolved now. Please test.

**Comment by lervag** [comment]
I've also updated the reference link support to be more or less according to the commonmarks spec, although with some limitations.

**Comment by BirgerNi** [comment]
Your support is impressive. The issue is solved, thank you.

**Comment by lervag** [comment]
Thanks for the kind words :)

I believe wiki.vim is improved due to your suggestions, so thanks for raising the issue and contributing through the discussion!
