### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by hoaxdream** [lervag/wiki.vim#218]
hi, first of all thank you for this great minimal plugin. everything is working. but one thing i only miss from vimwiki is toggle checkbox. i can't find in documentation of the plugin. is there such feature? thanks

**Comment by lervag** [comment]
Good question. This was part of wiki.vim before, but I extracted it as a separate plugin: [lists.vim](https://github.com/lervag/lists.vim). It should work well with wiki.vim. The only config I personally use is: `let g:lists_filetypes = ['markdown', 'wiki', 'help', 'text']`.
