### ISSUE TITLE
Making wiki.vim more accessible by improving documentation

### ISSUE THREAD

**Issue by tcftbl** [lervag/wiki.vim#220]
I recently migrated to wiki.vim from vimwiki and I wonder if this transition could be made easier by the documentation. Let me explain by example. As I installed wiki.vim I tried use use check list as they are in vimwiki, which don't work in plain wiki.vim. I checked the documentaion which doesn't mention check lists. I then searched the issues came across issue #1 which seemed to explain the functionality. However the check list functionality explained there doesn't work as per changes in design philosophy layed out in #15.

Would it be useful to lay out this design philosophy more explicitly in documention and maybe provide links to some vim plugins for check lists, tables etc.? Again using my example it would easier for new users keyword if searching the documentation for "check list" would match to a section explaining that wiki.vim isn't trying to include functionality better implemented in existing plugins and maybe listing a few of those plugins.

Maybe this is obvious for more advanced vim users, but I think newbies like me could benefit.

**Comment by lervag** [comment]
> I recently migrated to wiki.vim from vimwiki

Consider me honored :)

> and I wonder if this transition could be made easier by the documentation.

Yes, more than likely!

> ... Would it be useful to lay out this design philosophy more explicitly in documention and maybe provide links to some vim plugins for check lists, tables etc.?

Yes, this would be very useful. I'll do it. But it would be useful to get some help on which features I would need to mention. I propose this:

* I'll add a short note in the README to refer users to the right place in the docs.
* I'll add a section in the introduction of the docs to make these things more clear. I'll mention the features people would expect and refer to existing external plugins. For now, this means check lists (e.g. lists.vim), syntax (e.g. wiki-ft.vim), and tables. If you can think of other features, please let me know.

> Maybe this is obvious for more advanced vim users, but I think newbies like me could benefit.

I'm sure this is also useful for advanced users, even myself sometimes. I tend to forget things, and having it properly documented is always good!

**Comment by lervag** [comment]
I've pushed an updated documentation now. Please read it and give feedback. (`:help wiki-intro-plugins`).

**Comment by tcftbl** [comment]
Looks good! I'm sure the changes reduce the (not too high) barrier for entry. I'll have to try out a few of the plugins listed there myself. Thanks for this plugin and also vimtex!

**Comment by lervag** [comment]
Glad to hear it! :)
