### ISSUE TITLE
WikiLinkFollow for asciidoc links (angle bracketed links) doesn't call WikiResolver

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#222]
# Description

I keep journal entries under a separate directory and use a custom WikiResolver to see if the link points to a journal or to a regular file. I wanted to use asciidoc link like `<<some file>>` for already existing file. But following link created a new file under the `journal` directory. I figured out that it didn't call WikiResolver.

Could you please make WikiLinkFollow to call WikiResolver in this case?

If it doesn't make sense without a working example and test files, please excuse me and let me know. I'll prepare them and will update the issue.

Thanks!

**Comment by lervag** [comment]
It's hard to see immediately what you mean. It would be very useful if you could provide an example set of files and the relevant configuration.

But some quick thoughts: You are discussing the `g:wiki_resolver` option, right? If so, notice the initial text in the docs:

```
*g:wiki_resolver*
  The name of the function to resolve wiki-schemed links, i.e., the standard
  link scheme. The default should work well for most people, but this option
```

In particular, note that this is only relevant for wiki-schemed links. I believe this does not include the asciidoc links, since these will use the `adoc` link scheme.

**Comment by bybor** [comment]
Thank you, it makes sense. This means that it's "by design" behavior, but I didn't understand it.

Reading through the docs I assumed that `WikiFollowLink` will take me through `adoc` link to an anchor if it's specified, like <<here#go>>. I don't think documentation promises it, but it's mentioned. When I tried it I was blocked by the fact that custom path resolver (defined by me) is not called.

See, `WikiFollowLink` undestands `adoc` scheme though it's not `wiki.vim` scheme), but it doesn't apply resolver b/c it's not `wiki.vim` scheme. 

I'm not really sure `WikiFollowLink` can navigate to an anchor, so be it. Thanks!!

**Comment by lervag** [comment]
> Thank you, it makes sense. This means that it's "by design" behavior, but I didn't understand it.

I've tried to improve the documentation slightly. If you find something specific to be unclear, please don't hesitate to let me know.

> Reading through the docs I assumed that `WikiFollowLink` will take me through `adoc` link to an anchor if it's specified, like <<here#go>>. I don't think documentation promises it, but it's mentioned.

Anchors are supported and should work as explained in the docs, see `:help wiki-link-adoc-xref`. But note that the syntax is `<<filename.adoc#anchor>>`. You can't leave out the `.adoc` part, as that's part of the specification (if I've understood [the adoc xref documentation](https://docs.asciidoctor.org/asciidoc/latest/macros/xref/) correctly).
