### ISSUE TITLE
Is there a feature for remove links?

### ISSUE THREAD

**Issue by Skabit** [lervag/wiki.vim#224]
I like the way that you can create links: \<CR\>, but I can't found the way for remove links. For remove a link I delete it manually. So, is there a feature (or shortcut) for remove links?

I think about something like **Shift  + \<CR\>** but in the vim/neovim way.

**Comment by lervag** [comment]
Good question. But how should it work? I.e., given for instance these two links:

```
[[url|text]]
[text](url)
```

What should the "delete link" operator do? Delete the entire link, delete the link but keep the text?

**Comment by A-dot-S-dot** [comment]
I also would appreciate such a feauture. I think with vim it is not hard to delete the whole link without an additional command. But a command which deletes the url and keeps the text would be handy.

**Comment by lervag** [comment]
There are text objects that match the link url (`iu` and `au`) and the link text (`it` and `at`). The `au` object actually matches the entire link. Thus, `dau` will delete the current link, including the text and url; `cau` will delete and go to insert mode, etc. But I realize the docs for this feature is not very good, so I'll improve it.

Now, I agree it could be interesting to make a command that deletes a link but keeps the text part. Let's assume it is mapped to `&` for now - I think it should work like this (assume the cursor is inside the link):

```
Original link                   Result after operation
-------------                   ----------------------
This is [my link](url)          This is my link
This is [[url|my link]]         This is my link
This is an [[url]].             This is an.
```

Tasks:
* [ ] Improve documentation for the current text objects. Add examples.
* [ ] Implement "replace link with text" command. Include good documentation for it.

Before I work on it, I would be very glad to receive some feedback on this.

**Comment by A-dot-S-dot** [comment]
Looks good! However, one could discuss if the third example is necessary, since it has the same behaviour as `dau`. But I think it would be convinient. Is there anything else you are unsure about?

**Comment by lervag** [comment]
Ok, I've implemented this now. I already realize that this is very useful and that I will personally use this a lot. Thanks for suggesting it!

Please update and test, I'll appreciate feedback on both the documentation and on the feature. Please feel free to suggest a better default mapping as well.

**Comment by lervag** [comment]
Thanks for the good feedback! I've fixed the bad default mapping now.

**Comment by A-dot-S-dot** [comment]
Hey, 
above you mentioned

> There are text objects that match the link url (`iu` and `au`) and the link text (`it` and `at`). The `au` object actually matches the entire link. Thus, `dau` will delete the current link, including the text and url; `cau` will delete and go to insert mode, etc. But I realize the docs for this feature is not very good, so I'll improve it.

Could you add a note in your doc, that `au` has this behaviour? Wouldn't it be more natural if  `at` would have the same behaviour?

Best regards
