### ISSUE TITLE
Is there a way to have new notes be created in the repo root even if visited from the journal?

### ISSUE THREAD

**Issue by flancian** [lervag/wiki.vim#225]
If I visit a link from my journal page (e.g. `<repo>/journal/2022-05-26.md`), the target page is created in `<repo>/journal` but I'd like it to be created in the repository root.

That is, if I visit `[[test]]` in `2022-05-25.md`, I get:

```
/path/to/minimal-working-example-wiki
├── index.md
├── journal
│   └── 2022-05-25.md
│   └── test.md
```

But I'd like:

```
/path/to/minimal-working-example-wiki
├── index.md
├── journal
│   └── 2022-05-25.md
└── test.md
```

Is there any currently supported way to make this work like this? If not, would this be a reasonable contribution? Thank you :)

**Comment by bybor** [comment]
I'm another user who wanted to do the same. I think you can write it as `[[/test]]`, which IMHO is not very pretty.

My solution is:: all diary files go to `diary` folder (`journal` in your case), everything else should go to root.

`wiki.vim` allows to define your own function `WikiResolver`, which I did. Here is my code, you will need to change `diary` to `journal` and put it into your `.vimrc`. Feel free to write your own, what you see below is "works for me", nothing more.

```
let g:wiki_resolver = 'WikiResolver'

function! WikiResolver(fname, origin) abort " {{{1
  if empty(a:fname) | return a:origin | endif

  let l:f = fnamemodify(a:fname, ':t:r')

  if (match(l:f, '\d\{4}-\d\{2}-\d\{2}') == 0)
    let l:path = wiki#get_root() . '/diary/'. l:f
  else
    let l:path = wiki#get_root() . '/'. l:f
  endif

  " Determine the proper extension (if necessary)
  let l:extensions = wiki#u#uniq_unsorted(
        \ (exists('b:wiki.extension') ? [b:wiki.extension] : [])
        \ + g:wiki_filetypes)
  if (empty(fnamemodify(a:fname, ':e')))
      let l:path .= g:wiki_link_extension
  endif

  if index(l:extensions, fnamemodify(l:path, ':e')) < 0
    let l:path .= g:wiki_link_extension

    if !filereadable(l:path) && len(l:extensions) > 1
      for l:ext in l:extensions[1:]
        let l:newpath = l:path . '.' . l:ext
        if filereadable(l:newpath)
          let l:path = l:newpath
          break
        endif
      endfor
    endif
  endif

  return l:path
endfunction

```

**Comment by lervag** [comment]
Yes, @bybor is right that you can always write `[[/test]]`; the preceding `/` implies a link to the wiki root. In fact, `<cr>` on a word inside the journal will add the `/` automatically.

I can understand the motivation for this feature, but I hesitate to add many extra and special rules for how links are handled inside the journal. Currently, it basically works the same everywhere.

**Comment by flancian** [comment]
Thank you so much, bybor, that worked great! It fits my workflow perfectly as I only really use two directories for notes -- /journal for dates, the repository root for everything else.

**Comment by lervag** [comment]
The solution by @bybor will work. Here's a minor adjustment to the `WikiResolver` function, just for fun:

```vim
function! WikiResolver(fname, origin) abort
  if empty(a:fname) | return a:origin | endif

  let l:name = fnamemodify(a:fname, ':t:r')
  let l:ext = fnamemodify(a:fname, ':e')
  let l:path = l:name =~# '^\d\{4}-\d\{2}-\d\{2}'
        \ ? wiki#get_root() . '/diary/'. l:name
        \ : wiki#get_root() . '/'. l:name

  " Determine the proper extension (if necessary)
  let l:extensions = wiki#u#uniq_unsorted(
        \ (exists('b:wiki.extension') ? [b:wiki.extension] : [])
        \ + g:wiki_filetypes)

  if empty(l:ext)
    let l:path .= g:wiki_link_extension
  elseif index(l:extensions, l:ext) < 0
    let l:path .= g:wiki_link_extension

    if !filereadable(l:path) && len(l:extensions) > 1
      for l:e in l:extensions[1:]
        let l:newpath = l:path . '.' . l:e
        if filereadable(l:newpath)
          let l:path = l:newpath
          break
        endif
      endfor
    endif
  endif

  return l:path
endfunction
```

Note: If you make your own `WikiResolver`, you could possibly remove the extension search stuff, which is most of the function. If you _know_ the extension is always `.wiki` or `.md`, just use that. In this case:

```vim
function! WikiResolver(fname, origin) abort
  if empty(a:fname) | return a:origin | endif

  let l:name = fnamemodify(a:fname, ':t:r')
  let l:ext = fnamemodify(a:fname, ':e')
  let l:path = l:name =~# '^\d\{4}-\d\{2}-\d\{2}'
        \ ? wiki#get_root() . '/diary/'. l:name
        \ : wiki#get_root() . '/'. l:name

  return l:path . '.md'
endfunction
```

**Comment by flancian** [comment]
Beautiful, thank you both! And thank you @lervag for [[wiki vim]] -- I'm recommending it pretty widely :)

**Comment by lervag** [comment]
Thanks for the kind words! :)
