### ISSUE TITLE
Navigation breaks on Markdown links containing backslash

### ISSUE THREAD

**Issue by hektormisplon** [lervag/wiki.vim#227]
# Description

Navigation to a Markdown link containing a backslash does not work. This would be useful for allowing links to contain Mathjax.

e.g.
```
[The set of integers $\mathbb{Z}$](integers.md)
```

**Comment by lervag** [comment]
Thanks, I see no reason not to support this.

**Comment by lervag** [comment]
https://github.com/lervag/wiki.vim/commit/e849902fdd18dd23750e46859810103b16a49d9c
