### ISSUE TITLE
Journal file is not created using +WikiJournal

### ISSUE THREAD

**Issue by pmatulis** [lervag/wiki.vim#228]
The current day's journal file is not created when using `+WikiJournal`.

For example, with the **alacritty** terminal emulator:

`alacritty -e vim +WikiJournal`

If I use the vim command while currently in a buffer then it works:

`:WikiJournal`

The file gets created.

This is my configuration in `~/.vimrc`:

``` vim
let g:wiki_root = '~/data/sync/wiki'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
let g:wiki_global_load = 0
let g:wiki_index_name = 'index.md'
```

**Comment by lervag** [comment]
Does `vim +WikiJournal` work from the terminal?

**Comment by lervag** [comment]
See `:help g:wiki_index_name`:

```
*g:wiki_index_name*
  A string with the index page name for the wiki. The value should not include
  the file extension.

  Default: `'index'`
```

**Comment by pmatulis** [comment]
No, `vim +WikiJournal` does not work.

> You don't need to change g:wiki_index_name.

Ok, thanks. And should `vim +WikiIndex` also create the index file? It doesn't.

**Comment by pmatulis** [comment]
I used your approach to learn that the [`vim-startify`](https://github.com/mhinz/vim-startify) plugin is interfering. I moved it out of the way and both the index and the journal files get created as expected. Is this a complete blocker? I use startify quite a bit.

**Comment by pmatulis** [comment]
Okay, this does it:

```
vim --cmd 'let g:startify_disable_at_vimenter = 1' +WikiIndex
vim --cmd 'let g:startify_disable_at_vimenter = 1' +WikiJournal
```

This is worthy to document.

**Comment by lervag** [comment]
I'm happy to hear you figured it out! I'm not sure I agree that this should be documented for wiki.vim, though. But say we do add something: where do you think it should be added for it to be discoverable for anyone who might have a similar issue?
