### ISSUE TITLE
Plugin slows down the saving of files in vim

### ISSUE THREAD

**Issue by pmatulis** [lervag/wiki.vim#230]
After moving my vim plugins out of the way to identify whether they were causing a slowdown I determined that the **wiki.vim** plugin was causing it. When this plugin is moved out of the way the saving of files (`:w`) is immediate, but when it is enabled an approximate **2.5 seconds** is needed to complete the operation regardless of whether the file in question is under the **wiki_root** or not.

**Comment by pmatulis** [comment]
I did a test with a minimal `.vimrc` file and there is no slowdown. It must be caused by a combination with other things.

**Comment by lervag** [comment]
> After moving my vim plugins out of the way to identify whether they were causing a slowdown I determined that the **wiki.vim** plugin was causing it. When this plugin is moved out of the way the saving of files (`:w`) is immediate, but when it is enabled an approximate **2.5 seconds** is needed to complete the operation regardless of whether the file in question is under the **wiki_root** or not.

I do not have any similar issues.

> I did a test with a minimal `.vimrc` file and there is no slowdown. It must be caused by a combination with other things.

Yes, that is what I would expect. Let me know if you can reproduce this with a less minimal example, I'll be glad to help if I can.
