### ISSUE TITLE
Creating new links

### ISSUE THREAD

**Issue by GregoryShields** [lervag/wiki.vim#233]
Coming from VimWiki, I am used to being able to append a forward slash to my link text and have VimWiki automatically create a new directory having the name that would've been given to the new file if the forward slash had not been appended, as well as have VimWiki automatically create a new "index" file inside the newly created directory. Because of my current configuration, the new file would be named "wiki.md".

In wiki.vim the new directory is created, but there is no automatically created index file containing the name specified in my configuration. Instead, I get a new file named ".md.md".

It appears that wiki.vim expects the new file name to be explicitly provided. However, I'm guessing that you'd agree that the behavior I'm describing makes sense. Although it is nice to be able to tell wiki.vim to place a new file inside a subdirectory that is not the current working directory, that's not something I would usually do.

Is this a feature that you would consider implementing? If you don't have time for it, I suppose I could start familiarizing myself with your code and take a run at it myself if you like this idea.

If there is any confusion as to what I am describing, I can put forth a hypothetical example.

Thanks in advance.

**Comment by lervag** [comment]
Do I understand correctly, that, given the minimal wiki:

```
root/
  -> index.md
```

Where `index.md` contains:

```markdown
# Index

[[subdir/]]
```

If you follow the `subdir` link, then you expect to enter `root/subdir/index.md` and for the `subdir` directory to be created?

```
root/
  -> index.md
  -> subdir/
    -> index.md
```

And, further, that the issue is that `index.md` is _not_ created and opened as expected?

**Comment by lervag** [comment]
Ah, no, I believe I reproduced it. I create a minimal `test.vim` file

```vim
set nocompatible
set runtimepath^=~/.local/plugged/wiki.vim
filetype plugin indent on
syntax enable

let g:wiki_root = '~/test_wiki'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'

" The following option is not neccessary to reproduce:
let g:wiki_link_target_type = 'md'

runtime plugin/wiki.vim
WikiIndex
```

With a single `index.md` inside `~/test_wiki`. I then open with `nvim --clean -u test.vim`; for Vim, use `vim -u test.vim`. It will immediately open the root `index.md` file. I write `subdir/`, then from normal mode hit `<cr>` on top of `subdir/` and we get the link `[subdir/](subdir/.md)`.

Does this align with your experience/issue?

**Comment by GregoryShields** [comment]
With some variation due to my having a bit of a different setup, yes, that pretty much covers it.

____
As Sam Elliot said in The Big Lebowski, _"I like your style, dude."_

**Comment by lervag** [comment]
> Another nice thing that VimWiki does is that it replaces hyphens or underscores in the auto-generated link text with spaces to make it more readable, while preserving them in the auto-generated file or directory name.

Could you give an example or two of this? I believe it is close to what is possible with `:help g:wiki_map_link_create` (but it sounds to be more or less the _reverse_).

**Comment by GregoryShields** [comment]
> Could you give an example or two of this? I believe it is close to what is possible with `:help g:wiki_map_link_create` (but it sounds to be more or less the _reverse_).

Well, let's say we wanted to create a wiki file pertaining to the movie Fight Club, but we want the directory created by wiki.vim to be named Fight-Club so as to avoid problems with directory names containing spaces. So we type in `Fight-Club`, press <CR> while on top of it, and wiki.vim produces a directory exactly as we typed it, but replaces the hyphen with a space for the descriptive link text.

So yeah, I suppose it's exactly the opposite of the example provided in `:help g:wiki_map_link_create`. If I'm not mistaken, I could take the example code and reverse the values for the second and third arguments to `substitute()` and I'd get what I'm after. I'll give it a try.

**Comment by lervag** [comment]
> Well, let's say we wanted to create a wiki file pertaining to the movie Fight Club, but we want the directory created by wiki.vim to be named Fight-Club so as to avoid problems with directory names containing spaces. So we type in `Fight-Club`, press `<CR>` while on top of it, and wiki.vim produces a directory exactly as we typed it, but replaces the hyphen with a space for the descriptive link text.

So, something like this:

```
don’t talk about Fight-Club/

  |
  | press <cr> with cursor somewhere on "Fight-Club/"
  |
  ∨

don’t talk about [Fight Club](Fight-Club/)
```

Or, from your text, it seems you don't want to type the `/` and still want it to create a directory link?

In any case, it is very useful with a very explicit example similar to what I'm trying to create. So, if I'm not interpreting your right, then please correct the example. It is also useful for adding tests when we add new functionality.

> So yeah, I suppose it's exactly the opposite of the example provided in `:help g:wiki_map_link_create`. If I'm not mistaken, I could take the example code and reverse the values for the second and third arguments to `substitute()` and I'd get what I'm after, except that instead of the RegEx I would just put in a literal space character. I'll give it a try.

Feel free! However, would it not be better to turn this around? If you first write what you want to be the _text_ of the link, then convert the text to a link with either i) select the words and press `<cr>` from visual mode, or ii) use the operator mapping on the desired text, by default `gl`. With a simple `g:wiki_map_link_create`, you can control the desired output format of the link.

**Comment by GregoryShields** [comment]
Thanks, Karl.

I think before I consider solving this myself and doing a PR, I'd like to solve the issue I have with iVim and wiki.vim. I will start a separate issue for that.

**Comment by lervag** [comment]
I believe this is now resolved. Essentially, I changed the existing `g:wiki_map_create_link` and called the new option `g:wiki_map_text_to_link`. I believe the updated documentation should adequately explain how to use this, and I believe you can use it to achieve your desired goal. Let me know what you think!

**Comment by GregoryShields** [comment]
Wow, I can't believe it has been two years. I'm so sorry I dropped the ball, because you have always been so enthusiastic and receptive to my questions.

I'm looking at this now and I see that the new option `g:wiki_map_text_to_link` that you created back then no longer exists.

When I look at the current code, I see that the file...
`wiki.vim/autoload/wiki/link/word.vim`
...no longer exists. I do see this file...
`wiki.vim/autoload/wiki/link/class.vim`
...in the master branch. I know that I should RTFM, but if you have any comment on the evolution that happened relative to this, I'd be very interested.

**Comment by lervag** [comment]
> Wow, I can't believe it has been two years.

I know, time flies!

> I'm so sorry I dropped the ball, because you have always been so enthusiastic and receptive to my questions.

No problem; life happens to all of us. ;)

> I'm looking at this now and I see that the new option `g:wiki_map_text_to_link` that you created back then no longer exists.
> 
> When I look at the current code, I see that the file... `wiki.vim/autoload/wiki/link/word.vim` ...no longer exists. I do see this file... `wiki.vim/autoload/wiki/link/class.vim` ...in the master branch. I know that I should RTFM, but if you have any comment on the evolution that happened relative to this, I'd be very interested.

Well, I believe I found a more robust way to solve these things. The new option you should learn is `g:wiki_link_creation` - it was introduced in commit 62d63bcaad768717d9b6447e057e4d7a927ced99. For more info, see #296.

You may also want to read up on `g:wiki_link_schemes`, which is also relatively new (or newer than 2 years).

**Comment by GregoryShields** [comment]
Thanks for the heads up, and for taking the time to respond. I'll check those out.
