### ISSUE TITLE
wiki.vim saves journal note in a new folder instead of root

### ISSUE THREAD

**Issue by EricEWeir** [lervag/wiki.vim#236]
Getting started with  `wiki.vim`, I created a new wiki folder. Using `<leader>w<leader>w` I created a new journal note. When I went to check the folder to verify that it’d been saved I found it had been saved in a new folder, `~/0`, instead of in the folder designated as root in my .vimrc. 

I’ll check the documentation related to creating and saving journal entries. I’ll probably be mainly mystified, unsure of my understanding. But I’ll check out whatever imagined possible understandings to see if I can figure it out. 

Meantime, questions or suggestions that might lead to understanding would be appreciated.

A minimal vimrc file:

```vim
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set guifont=Menlo:h14

set wrap
set linebreak
set display=lastline
set backup

set clipboard=unnamed

set laststatus=2
set statusline=\ %F\ %r\ %l\ %c\ %y
set mousemodel=popup

set spell spelllang=en_us
set spellfile=~/.vim/spell/en.utf-8.add ~/.vim/spell/en.utf-8.add.spl

let mapleader = ","

noremap <Up> gk
noremap k gk
noremap <Down> gj
noremap j gj
noremap ^ g^
noremap $ g$
inoremap jj <ESC>
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

let g:notes_directories = ['~/mydocs/notes']
let g:notes_suffix = '.txt'

"let g:wiki_root = '~/vimwiki/'
"let g:wiki_root = '~/library/mobile documents/com~apple~CloudDocs/vimfiles/vimwiki/'
let g:wiki_root = '~/library/mobile documents/com~apple~CloudDocs/vimfiles/wiki/'


let g:session_autoload = 'prompt'
let g:session_lock_enabled = 0

autocmd BufRead,BufNewFile *.txt set ft=markdown
```

**Comment by EricEWeir** [comment]
Just tried opening the note with `<leader>w<leader>w`. I got `g:wiki_root is specified but the target path does not exist.`

**Comment by lervag** [comment]
I have to admit, I don't really know how to help here. I know more or less nothing about iVim. But I'll try.

So, you use the above config with iVim on iPad or iPhone?

With it, after starting iVim. What happens after `<leader>ww`? Does that work?

**Comment by lervag** [comment]
Can you, for sake of completeness, state the entire iVim configuration? I.e.:

* Do you have more content in your vimrc than the supplied file above?
* Do you have _other_ files inside your `~/.vim` folder?
* Perhaps you can supply the output of `:scriptnames` after opening iVim - if possible?

**Comment by EricEWeir** [comment]
> I have to admit, I don't really know how to help here. I know more or less nothing about iVim. But I'll try.

FYI I’m waiting for help from iVim folks. They’re not very responsive, though always helpful. Meantime I've resigned myself to using `wiki.vim` with the local root (`~/wiki`) on my iPhone, forgetting about syncing with other devices for the moment.

Things are working as they should. Files are saved in `~/wiki`, linking and folding work. So, as I say, the problem’s not `wiki.vim`.

> With it, after starting iVim. What happens after `<leader>ww`? Does that work?

When I switch to the root in the cloud `~/library/mobile documents/com~apple~CloudDocs/vimfilesbwiki` And do `<leader>ww` a new local directory `~/0` Is created and the index file is saved there

**Comment by EricEWeir** [comment]
> Can you, for sake of completeness, state the entire iVim configuration? I.e.:
> 
> * Do you have more content in your vimrc than the supplied file above? I believe somehow you must have more, because you are obviously loading at least wiki.vim and possibly other plugins.

No. The .vimrc copied above is my entire `.vimrc`.

> * Do you have _other_ files inside your `~/.vim` folder?

On the iPhone there are three folders in `~/.vim`:  `/after/ftplugin/` with a `wiki.vim` file with the `set wrap` command; `/pack/ivim/start/` with all my plugins; and `/sessions/` with a file (`default.vim`) that has a record of my saved sessions.
> * Perhaps you can supply the output of `:scriptnames` after opening iVim - if possible?

I can’t do that on the iPhone the way I did on the MacBook. Can’t copy the output and paste it into a file, or here. 

I found a plugin (`capture.vim`) that looks (to me) like it would work but there not instructions for use. (Necessary for me.) Also a command (let @ = execute(“scriptnames”) but I get `Invalid register name: ‘ ‘`

Also encountered discussion of `:redir` but don't see how to combine it with another command on the command line. (It’s used only in code?)

**Comment by lervag** [comment]
> Things are working as they should. Files are saved in `~/wiki`, linking and folding work. So, as I say, the problem’s not `wiki.vim`.

Great, I'm happy to hear that.

> > With it, after starting iVim. What happens after `<leader>ww`? Does that work?
> 
> When I switch to the root in the cloud `~/library/mobile documents/com~apple~CloudDocs/vimfilesbwiki` And do `<leader>ww` a new local directory `~/0` Is created and the index file is saved there.

My intuition is that the tilde's are problematic here; i.e. the `~apple~` part. It does seem to work as expected on my end, though.

> > Can you, for sake of completeness, state the entire iVim configuration? I.e.:
> > 
> > * Do you have more content in your vimrc than the supplied file above? I believe somehow you must have more, because you are obviously loading at least wiki.vim and possibly other plugins.
> 
> No. The .vimrc copied above is my entire `.vimrc`.

Ok, good; I see from the below answer how the plugins are loaded.

> > * Do you have _other_ files inside your `~/.vim` folder?
> 
> On the iPhone there are three folders in `~/.vim`: `/after/ftplugin/` with a `wiki.vim` file with the `set wrap` command; `/pack/ivim/start/` with all my plugins; and `/sessions/` with a file (`default.vim`) that has a record of my saved sessions.

Ok!

> > * Perhaps you can supply the output of `:scriptnames` after opening iVim - if possible?
> 
> I can’t do that on the iPhone the way I did on the MacBook. Can’t copy the output and paste it into a file, or here.
> 
> I found a plugin (`capture.vim`) that looks (to me) like it would work but there not instructions for use. (Necessary for me.) Also a command (let @ = execute(“scriptnames”) but I get `Invalid register name: ‘ ‘`

If `capture.vim` is this one: https://github.com/tyru/capture.vim, then that sounds like a good option. With it, you should be able to do `:Capture scriptnames` to do the `:scriptnames` command with the output captured into a buffer. You could save that buffer to a file with `:w ~/scriptnames.txt`, which may help in getting the output here?

> Also encountered discussion of `:redir` but don't see how to combine it with another command on the command line. (It’s used only in code?)

`:redir` is also possible, yes, but it is a little bit harder. One possibility is to use `:help execute()`, e.g. `:let @+ = execute('scriptnames')`, which will copy the output into the clipboard register.

**Comment by EricEWeir** [comment]
> If `capture.vim` is this one: https://github.com/tyru/capture.vim, then that sounds like a good option. With it, you should be able to do `:Capture scriptnames` to do the `:scriptnames` command with the output captured into a buffer. You could save that buffer to a file with `:w ~/scriptnames.txt`, which may help in getting the output here?

Thinking about this, lying in bed awake early morning. I figured, “What the hell,” got up and tried it first thing, before I read your response. It seems to have worked:

```
 1: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/vimrc
  2: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/syntax.vim
  3: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/synload.vim
  4: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/syncolor.vim
  5: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/filetype.vim
  6: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/menu.vim
  7: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/autoload/paste.vim
  8: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/ftplugin.vim
  9: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/indent.vim
 10: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/macmap.vim
 11: ~/.vimrc
 12: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/getscriptPlugin.vim
 13: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/gzip.vim
 14: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/logiPat.vim
 15: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/manpager.vim
 16: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/matchparen.vim
 17: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/netrwPlugin.vim
 18: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/rrhelper.vim
 19: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/spellfile.vim
 20: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/tarPlugin.vim
 21: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/tohtml.vim
 22: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/vimballPlugin.vim
 23: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/plugin/zipPlugin.vim
 24: ~/.vim/pack/ivim/start/calendar-vim/plugin/calendar.vim
 25: ~/.vim/pack/ivim/start/taskpaper.vim/ftdetect/taskpaper.vim
 26: ~/.vim/pack/ivim/start/vim-help/plugin/help.vim
 27: ~/.vim/pack/ivim/start/vim-misc/plugin/xolox/misc.vim
 28: ~/.vim/pack/ivim/start/vim-notes/plugin/notes.vim
 29: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc.vim
 30: ~/.vim/pack/ivim/start/vim-notes/autoload/xolox/notes.vim
 31: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc/path.vim
 32: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc/os.vim
 33: ~/.vim/pack/ivim/start/vim-session/plugin/session.vim
 34: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc/cursorhold.vim
 35: ~/.vim/pack/ivim/start/wiki-ft.vim/ftdetect/wiki.vim
 36: ~/.vim/pack/ivim/start/wiki.vim/plugin/wiki.vim
 37: ~/.vim/pack/ivim/start/wiki.vim/autoload/wiki/init.vim
 38: ~/.vim/pack/ivim/start/wiki.vim/autoload/wiki/u.vim
 39: ~/.vim/pack/ivim/start/wiki.vim/autoload/wiki/tags.vim
 40: /private/var/mobile/Containers/Data/Application/45016348-E695-47B5-A116-9A50F0B44C66/Library/ivim/scenes/session.vim
 41: ~/.vim/pack/ivim/start/vim-session/autoload/xolox/session.vim
 42: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc/option.vim
 43: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc/escape.vim
 44: ~/.vim/pack/ivim/start/vim-misc/autoload/xolox/misc/msg.vim
 45: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/autoload/netrw.vim
 46: ~/.vim/.netrwhist
 47: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/scripts.vim
 48: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/netrw.vim
 49: ~/.vim/pack/ivim/start/capture.vim/plugin/capture.vim
 50: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/markdown.vim
 51: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/html.vim
 52: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/javascript.vim
 53: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/vb.vim
 54: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/css.vim
 55: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/ftplugin/markdown.vim
 56: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/ftplugin/html.vim
 57: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/autoload/htmlcomplete.vim
 58: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/syntax/help.vim
 59: ~/.vim/pack/ivim/start/vim-help/ftplugin/help.vim
 60: /private/var/containers/Bundle/Application/94F7AD2F-6AF8-42CC-8CB4-637B97E160A0/iVim.app/runtime/ftplugin/help.vim
 61: ~/.vim/pack/ivim/start/capture.vim/autoload/capture.vim
```

**Comment by EricEWeir** [comment]
I predict that the problem will turn out to be my poor understanding of iVim’s `:iexdir` command, which enables links to directories outside iVim’s sandbox.

**Comment by EricEWeir** [comment]
Just tested `wiki.vim` with the cloud directory `~/Library/mobile documents/com~apple~CloudDocs/vimfile/wiki`. An index file and a journal file were saved in the correct directory, i.e., in the cloud. 

Again, the problem is either with my understanding of `iVim's` `:iexdir` command or with the command itself.

**Comment by lervag** [comment]
I can't see any obvious problems from the listing of `:scriptnames`. This command is very useful, because it will list all the files sourced by Vim. This can be helpful when you try to find problems. But, right now, I can't spot any obvious problems - it seems you are loading the plugins as expected and so on.

> I predict that the problem will turn out to be my poor understanding of iVim’s `:iexdir` command, which enables links to directories outside iVim’s sandbox.

I am not familiar with `:iexdir`, but from some quick searches I see that you may be right.

> Just tested `wiki.vim` with the cloud directory `~/Library/mobile documents/com~apple~CloudDocs/vimfile/wiki`. An index file and a journal file were saved in the correct directory, i.e., in the cloud.

But this is the same as in your original post - what is the difference now from then?

> Again, the problem is either with my understanding of `iVim's` `:iexdir` command or with the command itself.

I am not familiar with `:iexdir`, but from some quick searches I see that you may be right. I don't know if I can be of much help on this part. Sorry!
