### ISSUE TITLE
WikiFzfPages - question on different `globpath` results under Windows/Termux (linux)

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#237]
I understand that it's a pretty exotic question, but I hope there is something that I don't know, but you do.

Environment: Termux (let assume it's Linux, please - I hope it allows to reproduce the issue on your end, or you can just close it)

With this option

```
let g:wiki_filetypes = ['adoc', 'asciidoc', 'wiki', 'md', 'markdown' ]
```

When I call `:WikiFzfPages` I get only journal entries (from under `journal` subfolder. It returns *all* files when in Windows.

If I change this to be 

```
let g:wiki_filetypes = ['adoc']
```

It works in Termux (Linux) returning all files (that, by default, have `adoc` extension).

Here is the code that causes this issue:

https://github.com/lervag/wiki.vim/blob/f11ce14b3b5fc0741dfcf87735072996476745c0/autoload/wiki/fzf.vim#L14:L17

I typed in code from Line 17 substituting every variable and I can see that it grabbed only results for my journal.

Is it possible to make it return all files?

Thank you

**Comment by lervag** [comment]
Do you mean `g:wiki_filetypes`?

**Comment by bybor** [comment]
Yes, sorry

**Comment by lervag** [comment]
> Environment: Termux
> 
> With this option
> 
> ```
> let g:wiki_filetypes = ['adoc', 'asciidoc', 'wiki', 'md', 'markdown' ]
> ```
> 
> When I call `:WikiFzfPages` I get only journal entries (from under `journal` subfolder. It returns _all_ files when in Windows.
> 
> Here is the code that causes this issue:
> 
> https://github.com/lervag/wiki.vim/blob/f11ce14b3b5fc0741dfcf87735072996476745c0/autoload/wiki/fzf.vim#L14:L17
> 
> I typed in code from Line 17 substituting every variable and I can see that it grabbed only results for my journal.
> 
> Is it possible to make it return all files?

I believe the issue may be in which wildcards are supported for the `globpath()` function. I'm using the `{x,y}` expression, which means `x` or `y`. I believed this was supported more or less anywhere, but for some reason, it seems to not be supported on Vim in Termux.

To test this more specifically, you could do this: `:echo glob('{pre1*,pre2*}')` where `pre1` and `pre2` are some (different) prefixes used by some files in the folder you are in. It _should_ echo a list of the files that match, but I would not be surprised if this does not work for you on Termux.

**Comment by lervag** [comment]
For more info, see `:help wildcards`. Notice how the documentation is very vague on which wildcards are supported. It only lists a few wildcards that are probably ubiquitous.

**Comment by bybor** [comment]
I cannot find this syntax (with fancy brackets specifying a set/enumeration) `:echo glob('{pre1*,pre2*}')` described in help. I tried it as `:echo glob('{*}')` expecting *everything* but got nothing.

**Comment by lervag** [comment]
No, that was my point - this syntax is not documented. I believe it may be part of the underlying shell. In Bash, this is called brace expansion. Notice, it _has_ to have a comma, because it specifies a list of candidates that will all be accepted. So, e.g., in a bash shell, `ls file{a,b,c,d}.txt` would match `filea.txt`, `fileb.txt`, and so on. But not `filex.txt`.

**Comment by bybor** [comment]
OK, let it be so. Thank you for your help and time.

**Comment by lervag** [comment]
No problem; sorry I couldn't be of more help. :\
