### ISSUE TITLE
Text to link mapping not used with wiki-fzf-pages

### ISSUE THREAD

**Issue by RhvdG** [lervag/wiki.vim#239]
Perhaps this is not a bug report, but a feature request. I was expecting that hitting enter on a zero result wiki-fzf-pages search would cause my text to link mapping to be applied to the search string, which in my case would mean replacing spaces with underscores, but the spaces were retained.

**Comment by lervag** [comment]
I believe this is already supported with the option `g:wiki_map_create_page`, see `:help g:wiki_map_create_page` for more details. Let me know if I'm wrong, but if so, please provide more details.

**Comment by RhvdG** [comment]
Thanks I added 

````
let g:wiki_map_create_page = 'WikiCreatePage'
    function WikiCreatePage(name) abort
      let l:name = wiki#get_root() . '/' . a:name
    endfunction
````

to my .vimrc and sourced it and tried hitting enter on a zero result query, which now resulted in this:

``wiki: Opened new page "/0"``

So I guess more is needed...

**Comment by lervag** [comment]
Yes, please. Can you show an explicit example of what you want? I assume it is something like this:

1. You do an fzf search for a page. You enter a name of a page that does not exist, say "Foo Bar".
2. You accept the search entry ("Foo Bar") which does not have any fzf search results.
3. You expect to open a file named "Foo Bar_YYYYMMDD" (with some extension, like `.md` or `.wiki`).

Notice that it is very helpful if you provide more details. Especially, be explicit about which steps you are taking and what you want to happen. Explicit means to give a concrete example of strings and filenames, and to specify both the _observed_ and the _expected_ result.

By the way, you should notice that `g:wiki_map_create_page` is used when you open a _new_ page, thus, the name passed to the function will _not_ match any existing files. You don't need to check it yourself.

**Comment by lervag** [comment]
> I was expecting that hitting enter on a zero result wiki-fzf-pages search would cause my text to link mapping

Can you show me what this "text to link mapping" is? I.e., show me your relevant configuration.

> which in my case would mean replacing spaces with underscores, but the spaces were retained.

I believe this should work:

```vim
let g:wiki_map_create_page = 'WikiCreatePage'
function WikiCreatePage(text) abort
  return substitute(tolower(a:text), '\s\+', '-', 'g')
endfunction
```

**Comment by RhvdG** [comment]
> Can you show me what this "text to link mapping" is? I.e., show me your relevant configuration.

My .vimrc has

```
let g:wiki_map_text_to_link = 'MyTextToLink'
    function MyTextToLink(text) abort
      return [substitute(tolower(a:text), '\s\+', '_', 'g'), a:text]
    endfunction
```

> I believe this should work:
> 
> ```viml
> let g:wiki_map_create_page = 'WikiCreatePage'
> function WikiCreatePage(text) abort
>   return substitute(tolower(a:text), '\s\+', '-', 'g')
> endfunction
> ```

Yes, this works. I changed the dash to an underscore; that works, too (obviously). Thanks! Do you need more from me to put this issuer to rest?

**Comment by lervag** [comment]
> Yes, this works. I changed the dash to an underscore; that works, too (obviously). Thanks!

Ah, yes, you wrote underscores, I just missed that.

> Do you need more from me to put this issuer to rest?

No, it seems this is resolved. I'm glad to hear things work as expected now!

**Comment by RhvdG** [comment]
Me too! Thanks a lot for providing a clean and lean wiki for Vim.

**Comment by lervag** [comment]
My pleasure :)

**Comment by RhvdG** [comment]
A similar fault has surfaced. When using the rename wiki command ``<leader>wr``, I would expect TextToLink conversion to be applied. Instead, the new title for the file is retained, including uppercase words and spaces, and only ``.md`` is added.

```
function MyTextToLink(text) abort
  return [substitute(tolower(a:text), '\s\+', '_', 'g'), a:text]
endfunction
```

**Comment by lervag** [comment]
Hmm, that's an interesting request. The rename function does three things, basically:

1. Asks for a new filename
2. Changes the current filename to the new
3. Updates all links from to the previous filename to point to the new one

I'm not sure if the transformation `g:wiki_map_text_to_link` should apply here. Perhaps it should, but it could be surprising? What if you really _wanted_ to change the filename to something else? Also, if we apply the transformation, then the original text is really just garbage, because it will not be used for anything after the transformation..?

**Comment by RhvdG** [comment]
Good questions! Perhaps it's good like it is now.

**Comment by lervag** [comment]
Think about it. If you should still want this, then open a new issue and lets continue the discussion.
