### ISSUE TITLE
Pandoc with gfm format is not present in current Ubuntu stable

### ISSUE THREAD

**Issue by jounathaen** [lervag/wiki.vim#24]
Apparently wiki.vim uses pandoc with _gfm_ as input format.
https://github.com/lervag/wiki.vim/blob/67368c95355d02c3967c3368097c7b707a2d32f0/autoload/wiki/page.vim#L402

Unfortunately, this input format is not present Pandoc 1.19 which is shipped with the current Ubuntu stable (18.04).
It works with a more up to date version or with the (deprecated) _markdown_github_ format. But I don't know in which version of pandoc the _gfm_ format was added.

Maybe a minimum required pandoc version number should be added to the help page.

**Comment by lervag** [comment]
Good point. I agree that the requirement should be specified. But it could be useful to explain how to install the gfm backend for Ubuntu users. Are you able to help here with a suggestion of what I could write?

**Comment by jounathaen** [comment]
Haha, that is pretty easy. Pandoc provides packages for many architectures over here: https://pandoc.org/installing.html

Download and click on the file will open the installer and done.

**Comment by jounathaen** [comment]
Additional question: Why is _gfm_ and not  _markdown_ used as format specifier?

I don't know all the differences, but for example `pandoc -f markdown` would support stuff like `$ latexformula  \frac{1}{2}$` which seem to be already highlighted by the wiki filetype plugin.
And I think `markdown` is supported in older pandoc versions

**Comment by lervag** [comment]
I think my updates should resolve this now. I've used `gfm` because that has worked well for me. No other reason. I agree `markdown` seems a better default, so I've changed it.
