### ISSUE TITLE
Wiki.vim creates and saves

### ISSUE THREAD

**Issue by EricEWeir** [lervag/wiki.vim#241]
I am fine if this is low priority. I have taken too much of your time already.

On `<leader>ww`, `<leader>w<leader>w`, and `<leader>wn` wiki.vim creates and saves files to a new folder `/0`. 

When in root directory in netrw the new folder is `~/0`. 

When I navigate to the folder specified by `let g: wiki_root =`, which is  `'~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/wiki/'`, `/0` is created at `'~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/‘`. 

When I issue any of these commands I get the following error message: `“Root is specified but target path does not exist.”` On `<CR>` the file is created anyway. When I open the file after saving it I get the same message.

**Comment by lervag** [comment]
I believe there is something wrong with your `let g:wiki_root` statement in your vimrc file. Could you post your current vimrc file?

**Comment by EricEWeir** [comment]
Thanks, Karl. My .vimrc follows. 

I don’t know what I’m talking. Speculating on something I vaguely remember hearing once, but I wonder about the space in the fifth segment of the path, I.e., `/Mobile Documents/`. 

I also note in what I reported yesterday that when I issue these commands after I’ve navigated to the directory in the cloud the `/0` directory gets created at the point where `/wiki/` appears in the path specified in the `.vimrc`.
***
```
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set guifont=Menlo:h14

set wrap
set linebreak
set display=lastline
set backup

set clipboard=unnamed

set laststatus=2
set statusline=\ %F\ %r\ %l\ %c\ %y
set mousemodel=popup

set spell spelllang=en_us

let mapleader = ","

noremap <Up> gk
noremap k gk
noremap <Down> gj
noremap j gj
noremap ^ g^
noremap $ g$
inoremap jj <ESC>
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

"vim-markdown 
set conceallevel=2 
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_folding_level = 6 
let g:vim_markdown_autowrite = 1
let g:vim_markdown_strikethrough = 1

"let g:wiki_root = '~/lprivate/var/mobile/library/mobile documents/com~apple~CloudDocs/vimfiles/vimwiki/'
"let g:wiki_root = '~/vimwiki/'

let g:wiki_root = '~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/wiki/'
"let g:wiki_root = '~/wiki/'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md' 
let g:wiki_write_on_nav = 1
let g:wiki_journal = {
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \}
let g:session_autoload = 'prompt'
let g:session_lock_enabled = 0
```

**Comment by EricEWeir** [comment]
FWIW, for the time being I’m working with my wiki in a local directory. I’ve been getting anxious about being bogged down in getting the technology to work, about not actually using it to see how I can use it. I’ve made progress in approximating a zettelkasten workflow using wiki.vim without any enhance relates to note linking or searching. I do <cr> on a critical word creating a markdown file named with the word. After saving the file I do <leader>wr and add an appropriate number in front of current name. I have a rough index of base topics, each with a number of the form x.0. I use those numbers as guides in assigning numbers to subsidiary notes. It’s a little cumbersome, and workable I suspect because at this point the structure is pretty simple and the number of notes pretty small. I may have to rethink the process down the road, perhaps before long. And I’ll be looking for ways technology could streamline the process, making it less cumbersome, keeping it out of the way of

**Comment by lervag** [comment]
> I don’t know what I’m talking about. Speculating on something I vaguely remember hearing once, but I wonder about the space in the fifth segment of the path, I.e., `/Mobile Documents/`.

I believe that should work as expected. After you open Vim (MacVim, iVim, whatever) - no file, just after starting it: can you report the output of `:echo g:wiki_root`? And, if it looks sensible, the output of `:echo wiki#get_root()`?

> I’ve made progress in approximating a rough zettelkasten workflow using wiki.

That's good. I think it's a good approach; that is, to start just using things, making some real content/notes, and so on.

I'm still not convinced about the value of Zettelkasten, though. To me, it sounds like it makes everything more difficult that it needs to be.

**Comment by EricEWeir** [comment]
>After you open Vim (MacVim, iVim, whatever) - no file, just after starting it: can you report the output of `:echo g:wiki_root`? 

`~/private/var/mobile/library/mobile documents/com~apple~clouddocs/vimfiles/wiki/`

>And, if it looks sensible, the output of `:echo wiki#get_root()`?

`g:wiki_root is specified but the target path does not exist`.

> I'm still not convinced about the value of Zettelkasten, though. To me, it sounds like it makes everything more difficult that it needs to be.

I’m experimenting. I may come to that conclusion myself. 

Yesterday, after I’d worked a while, and made what seemed to be a little progress, I had a sense of accomplishment. And optimism.

Normally my mind is all over the place. I have many interests. They are extremely diverse. (I don’t imagine I am unique in this.) 

When I’m focused, whatever the context, I’m capable. But usually I’m not focused. I go around suspended in midair, ungrounded. Not always but a lot of the time.

**Comment by lervag** [comment]
> > And, if it looks sensible, the output of `:echo wiki#get_root()`?
> 
> `g:wiki_root is specified but the target path does not exist`.

This explains the problem, though. Vim does not recognize the path you specify with `let g:wiki_root` as a valid path. The function therefore gives a warning. I've just pushed a minor update to include the path parsed by wiki.vim in the error output. Can you update and show me the new error message from your end?

**Comment by EricEWeir** [comment]
> > > And, if it looks sensible, the output of `:echo wiki#get_root()`?
> > 
> > `g:wiki_root is specified but the target path does not exist`.
> 
> This explains the problem, though. Vim does not recognize the path you specify with `let g:wiki_root` as a valid path. The function therefore gives a warning. I've just pushed a minor update to include the path parsed by wiki.vim in the error output. Can you update and show me the new error message from your end?

Thanks, Karl. I don’t understand “the path parsed by wiki.vim in the error output.” My blind eyes don’t see that path.

But in the output this time I see a path:

`/private/var/mobile/Containers/Data/Application/BBD512C7-CCA0-47FD-B2F2-0AF17D9D03B5/Documents/wiki`

So is that the path I should be using  for `let g:wiki_root =`i.e., for my directory in the cloud?

**Comment by EricEWeir** [comment]
Also wondering if your update to wiki.vim addresses a problem unique to me or if is potentially relevant to others.

**Comment by lervag** [comment]
> > > > And, if it looks sensible, the output of `:echo wiki#get_root()`?
> > > 
> > > 
> > > `g:wiki_root is specified but the target path does not exist`.
> > 
> > 
> > This explains the problem, though. Vim does not recognize the path you specify with `let g:wiki_root` as a valid path. The function therefore gives a warning. I've just pushed a minor update to include the path parsed by wiki.vim in the error output. Can you update and show me the new error message from your end?
> 
> Thanks, Karl. I don’t understand “the path parsed by wiki.vim in the error output.” My blind eyes don’t see that path.
> 
> But in the output this time I see a path:
> 
> `/private/var/mobile/Containers/Data/Application/BBD512C7-CCA0-47FD-B2F2-0AF17D9D03B5/Documents/wiki`

That's what I meant. That the output would now contain a path. The point is,
that, if you specify `g:wiki_root` to a nonexistant directory, then this error
message appears:

```
g:wiki_root is specified but the target path does not exist.
Target path: /the/path/
```

My previous update was only to add the second line: "Target path: ...".

What this means, is that the path you specify in your vimrc file does not exist. I.e.,

```vim
let g:wiki_root = '~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/wiki/'
```

This path is not a valid directory. To confuse further, it seems from the output you reported:

> `/private/var/mobile/Containers/Data/Application/BBD512C7-CCA0-47FD-B2F2-0AF17D9D03B5/Documents/wiki`

that you are really using a different `g:wiki_root` than the one reported earlier? That's not important; the important thing is that the path you specify for `g:wiki_root` is not valid.

**Comment by EricEWeir** [comment]
> > Thanks, Karl. I don’t understand “the path parsed by wiki.vim in the error output.” My blind eyes don’t see that path.
> > But in the output this time I see a path:
> > `/private/var/mobile/Containers/Data/Application/BBD512C7-CCA0-47FD-B2F2-0AF17D9D03B5/Documents/wiki`
> 
> That's what I meant. That the output would now contain a path. 

Thanks. I understand.

> ```
> g:wiki_root is specified but the target path does not exist.
> Target path: /the/path/
> ```
> My previous update was only to add the second line: "Target path: ...".
> 
> What this means, is that the path you specify in your vimrc file does not exist. I.e.,

> To confuse further, it seems from the output you reported:
> > `/private/var/mobile/Containers/Data/Application/BBD512C7-CCA0-47FD-B2F2-0AF17D9D03B5/Documents/wiki`
> 
> that you are really using a different `g:wiki_root` than the one reported earlier? 

As I mentioned yesterday, I had been using a local directory. When you asked me to report the output of those two commands I switched back to the directory in the cloud. I may have switched back to the local directory before you asked me to report again. If so I may have forgotten to switch back to the directory in the cloud before I ran the command and reported back the second time.

>That's not important; the important thing is that the path you specify for `g:wiki_root` is not valid.

Discouraging news. I thought I had lucked out and discovered the correct path. And it seemed to work when I first started using it. In fact it was only a couple days ago that I started getting those `/0` directories n strange places.

I guess I’m going to have to be content with local directories, synchronizing, to the extent that I do, by copying directories between devices.

I have yet to get any help from people in the iVim github repository. I imagine the guy who developed iVim, and the :iexdir command, which enables establishing links with external directories, could help me, but rarely get a response from and never have on this issue.

So, again, thanks for your generosity. Sincerely. I imagine I’ll be less of a pest at least for a while.

**Comment by lervag** [comment]
> > That's not important; the important thing is that the path you specify for `g:wiki_root` is not valid.
> 
> Discouraging news. I thought I had lucked out and discovered the correct path. And it seemed to work when I first started using it. In fact it was only a couple days ago that I started getting those `/0` directories n strange places.

Well, I'm sorry to say I can't help much with this, except perhaps what I've already done: to clarify what this means.

> So, again, thanks for your generosity. Sincerely. I imagine I’ll be less of a pest at least for a while.

No problem. I hope you figure things out!
