### ISSUE TITLE
:WikiFzfPages fails for iCloud directory

### ISSUE THREAD

**Issue by dfsnow** [lervag/wiki.vim#243]
Using `:WikiFzfPages` fails when the root dir is set to an iCloud Drive directory or any directory with a `~` in the path. The error is 

```
(NFA) Could not pop the stack!
```

The full path to iCloud Drive on Mac systems is now: `~/Library/Mobile\ Documents/com~apple~CloudDocs`. When `:WikiFzfPages` is creating paths to search (L20), it uses the filenames within `substitute()` but doesn't escape the extra tildes, resulting in the error.

https://github.com/lervag/wiki.vim/blob/e31052698685393d9f27330eda0204d712911c4b/autoload/wiki/fzf.vim#L18-L22

A possible fix is to escape the path with `'\V'`, like so:

```
substitute(x, '\V' . escape(l:root, '\'), '', '')
```

See this [issue](https://vi.stackexchange.com/questions/27276/could-not-pop-the-stack-error-in-vimwiki-function) for reference.

**Comment by lervag** [comment]
Interesting. It seems the proposed fix is a good suggestion, so I've pushed it immediately. Let me know if this does fix your problem!

Thanks for the short and helpful issue report!

**Comment by dfsnow** [comment]
Works! Thanks for the quick fix.

**Comment by lervag** [comment]
Great, glad to hear it!
