### ISSUE TITLE
Missing tags when using the short form

### ISSUE THREAD

**Issue by VincentCordobes** [lervag/wiki.vim#244]
The help mentions multiple tags can be written like `:tag1:tag2:`.
However, after a `WikiTagReload`, I have noticed only the first is listed in `WikiFzfTags`. 

It works as expected when I write it like `:tag1: :tag2:` though.

**Comment by lervag** [comment]
Sorry, not sure what happened. But I think it is fixed now.

**Comment by VincentCordobes** [comment]
It's working perfectly now. Thank you! :)

**Comment by lervag** [comment]
Great, glad to hear it!

**Comment by VincentCordobes** [comment]
I've noticed the coc completion stop working when chaining short form tags. 
For example, here it works:
```
:ta
   ^
   completion works
```

But not here:
```
:tag1:ta
       ^
       completion does not work
```

Should I open an issue for this?

**Comment by lervag** [comment]
No, it's OK; I'll look into it.

**Comment by lervag** [comment]
I believe this is fixed now.

**Comment by VincentCordobes** [comment]
It is. Thank you!!
