### ISSUE TITLE
Creating new page now has a slash before the file name

### ISSUE THREAD

**Issue by jiangtianli91** [lervag/wiki.vim#245]
I used to create a link in a markdown file `~/Vimwiki/animal/dog.md` by pressing `enter` on a word `dog` in an index file at `~/Vimwiki/animal/index.md`. The created link used to be `[dog](dog.md)`.

**Previous index file created:** `~/Vimwiki/animal/index.md`
```
* [dog](dog.md)
* [cat](cat.md)
* [turtle](turtle.md)
```

However, now it creates a link `[dog](/dog.md)` instead of `[dog](dog.md)`. And the created file is at `~/Vimwiki/dog.md` instead of `~/Vimwiki/animal/dog.md`.

**Current index file created:** `~/Vimwiki/animal/index.md`
```
* [dog](/dog.md)
* [cat](/cat.md)
* [turtle](/turtle.md)
```

I wonder is there a way to create the file `dog.md` in the `~/Vimwiki/animal` directory? Was what I did in the past not an optimal way to do it?

**Comment by lervag** [comment]
It seems you are reporting two errors here? The index and creating links with `<cr>` (enter). Is that right? If so, please note that these _are_ two different issues that could require different fixes. Allow me to first consider only the first of these: Creating links with `<cr>`.

What I've currently tried to implement: Pressing `<cr>` on a word should either
* create a link to an existing page in the same directory, or
* look for an existing page with the same name in the root dir, or
* look for pages in the root directory where the word is a prefix, or
* create a new page at the root directory.

This may not be the optimal or desired behaviour at all times. For me, it works well, but I tend to work only in a flat structure. The only directory I use much is the journal directory, and I don't want other pages there, so the above model works well for me.

I don't mind changing this at all, but I would be glad to have a short discussion about what would be the expected and/or appropriate behaviour.

**Comment by jiangtianli91** [comment]
I wonder whether the behaviour in the past was to create a new page in the same directory of the current file instead of in the root directory? Maybe there could be an option for where to create a new page? Either in the root directory or in the directory of current file. I guess these two are the most obvious options?

I also noticed that ``[turtle](/turtle.md)`` leads me to ``turtle.md`` in the root directory of wiki, but ``[turtle](turtle.md)`` leads me to ``turtle.md`` in the directory of the current file.

**Comment by lervag** [comment]
> I wonder whether the behaviour in the past was to create a new page in the same directory of the current file instead of in the root directory?

Yes and no. The old behaviour was more random. I've made some recent changes
to clean up things. When I changed this exact thing I was aware it might break
someones workflow. But I wanted to hear it before addressing it, and I want to
discuss the solution with someone before implementing any adjustments.

> Maybe there could be an option for where to create a new page?

Perhaps; but I prefer to avoid options, if possible.

> Either in the root directory or in the directory of current file. I guess these two are the most obvious options?

I think these are the only alternatives that make sense.

> I also noticed that `[turtle](/turtle.md)` leads me to `turtle.md` in the root directory of wiki, ...

Yes, prepending the wiki url with `/` will anchor it to the wiki root. Sort of like an absolute path vs a relative path.

----

I propose the following logic when _toggling_ selected text (or the current word) with `<cr>`:

* If we are inside the journal (see `:help g:wiki_journal`):
  1. Check if any page exists inside the journal that matches the selected text/current word. If so, create link to that page.
  2. Check if any page exists at the wiki root that matches the selected text/current word. If so, create link to that page.
  3. Check if there are pages at the wiki root where the selected text/current word matches at the beginning. If so, let user choose which page to link to.
  4. If neither of the above, then create a link to a page with name based on the selected text/current word _at the wiki root_. The idea is that we would generally not want anything other than journal entries within the journal directory.
* Everywhere else:
  1. Check if any page exists inside the current directory that matches the selected text/current word. If so, create link to that page.
  2. Check if there are pages at the current directory where the selected text/current word matches at the beginning. If so, let user choose which page to link to.
  3. If neither of the above, then create a link to a page with name based on the selected text/current word in _current directory_.

I believe this may be closer to what most people expect, and it would also fit nicely with my own workflow. The general idea is that links should mostly be relative to the current directory, except within the journal, where we have some extra rules to help avoid cluttering the journal directory.

How does this sound to you?

**Comment by lervag** [comment]
> I wonder whether the behaviour in the past was to create a new page in the same directory of the current file instead of in the root directory?

Yes and no. The old behaviour was more random. I've made some recent changes
to clean up things. When I changed this exact thing I was aware it might break
someones workflow. But I wanted to hear it before addressing it, and I want to
discuss the solution with someone before implementing any adjustments.

> Maybe there could be an option for where to create a new page?

Perhaps; but I prefer to avoid options, if possible.

> Either in the root directory or in the directory of current file. I guess these two are the most obvious options?

I think these are the only alternatives that make sense.

> I also noticed that `[turtle](/turtle.md)` leads me to `turtle.md` in the root directory of wiki, ...

Yes, prepending the wiki url with `/` will anchor it to the wiki root. Sort of like an absolute path vs a relative path.

----

I propose the following logic when _toggling_ selected text (or the current word) with `<cr>`:

* If we are inside the journal (see `:help g:wiki_journal`):
  1. Check if any page exists inside the journal that matches the selected text/current word. If so, create link to that page.
  2. Check if any page exists at the wiki root that matches the selected text/current word. If so, create link to that page.
  3. Check if there are pages at the wiki root where the selected text/current word matches at the beginning. If so, let user choose which page to link to.
  4. If neither of the above, then create a link to a page with name based on the selected text/current word _at the wiki root_. The idea is that we would generally not want anything other than journal entries within the journal directory.
* Everywhere else:
  1. Check if any page exists inside the current directory that matches the selected text/current word. If so, create link to that page.
  2. Check if there are pages at the current directory where the selected text/current word matches at the beginning. If so, let user choose which page to link to.
  3. If neither of the above, then create a link to a page with name based on the selected text/current word in _current directory_.

I believe this may be closer to what most people expect, and it would also fit nicely with my own workflow. The general idea is that links should mostly be relative to the current directory, except within the journal, where we have some extra rules to help avoid cluttering the journal directory.

How does this sound to you?

**Comment by jiangtianli91** [comment]
I think this is a very good idea!

**Comment by lervag** [comment]
Ok, I believe this should behave as expected now. I also think the documentation is improved; please read `:help WikiLinkToggle` and let me know what you think.

**Comment by lervag** [comment]
G
