### ISSUE TITLE
Doesn't recognize Markdown anchor links that don't match case of header

### ISSUE THREAD

**Issue by TanukiTom** [lervag/wiki.vim#246]
Wiki.vim only recognizes Markdown anchor links in Markdown files that match the case of the associated header. I realize there are multiple flavors of Markdown. However, Markdown traditionally uses [lowercase anchors with spaces between words replaced by "-"](https://www.markdownguide.org/extended-syntax/#linking-to-heading-ids).

```
<!-- test-note.md -->
# Test Note

## Single Word Links:
- [Won't take me to ##Bookmark](#bookmark) <!-- Doesn't work -->
- [Will take me to ##Bookmark](#Bookmark) <!-- Works -->

## Multiple Word Links:
- [Won't take me to "##Another Bookmark"](#another bookmark) <!-- Doesn't work -->
- [Won't take me to "##Another Bookmark"](#another-bookmark) <!-- Doesn't work -->
- [Will take me to "##Another Bookmark"](#Another Bookmark) <!-- Works  -->
- [Will take me to "##Another Bookmark"](#Another-Bookmark) <!-- Works -->

---

## Bookmark

## Another Bookmark
```

This may be desirable behavior for many users. However, it creates a problem for users that want to use their Markdown files in other programs (such as [Markor](https://github.com/gsantner/markor)). These programs may not be able to parse the links.

Is there a variable or setting to set Wiki.vim to recognize traditional Markdown anchor links?

**Comment by lervag** [comment]
Ah, I think the only problem here is that the anchors are currently search while not ignoring case. I'll push an update immediately.
