### ISSUE TITLE
Warning if pandoc is not installed

### ISSUE THREAD

**Issue by jounathaen** [lervag/wiki.vim#25]
Related to #24 
If `pandoc` is not installed, `WikiGeneratePDF` fails without a warning.

Suggestion: Check if pandoc is installed and output an error message if not and `WikiGeneratePDF` is called.

Checking for a minimum required version would solve #24

**Comment by lervag** [comment]
I've added error handling now. I'll solve #24 with an update to the docs after possibly some input from you (or others). Thanks!
