### ISSUE TITLE
File rename not updating links

### ISSUE THREAD

**Issue by krankur** [lervag/wiki.vim#250]
# Description

File rename works but links to the file don't get updated.

**Steps**:
1. Navigate to the file to rename.
2. Hit `<leader>wr` and enter new file name (without extension) in the command line prompt.

**Actual Result**: File name is updated successfully but links to it don't get updated.

**Expected Result**: All links to renamed file should be updated to reflect the new name.

**Example**:
I have the following directory structure.
```
├── index.wiki
├── dir1
│   └── note1.wiki
├── dir2
    └── note2.wiki
```
And following is the content of `index.wiki`:
```
[[/dir1/note1|note1]]
[[/dir2/note2|note2]]
```
When I go to `note2.wiki` and rename it to `new-note` by hitting `<leader>wr`, the file name changes but the link in `index.wiki` doesn't get updated with the new name.

**Comment by krankur** [comment]
So, I tested some more. If I rename a file which is in the root directory, the links get updated with the new name. The issue seems to be happening only for files inside sub-directories.

**Comment by lervag** [comment]
That's strange. This works as expected for me. I did this:

1. Created a test directory with the files as in your example.
2. Created a `test.vim` file (contents below) at same location as `index.wiki`.
3. Ran `nvim --clean -u test.vim` and tried to reproduce - observe that things work as expected.

```vim
set nocompatible
set runtimepath^=~/.local/plugged/wiki.vim
filetype plugin indent on
syntax enable

let g:wiki_cache_persistent = 0
runtime plugin/wiki.vim

silent edit dir1/note1.wiki
```

Note: If you use Vim instead of neovim, use `vim -u test.vim` in step 3.

**Comment by krankur** [comment]
I tried with minimal `vimrc`:
```
call plug#begin(stdpath('data') . '/site/plugged')
    Plug 'lervag/wiki.vim'
    Plug 'lervag/wiki-ft.vim'
call plug#end()

set nocompatible
set backspace=indent,eol,start

set tabstop=4
set shiftwidth=4
set expandtab
set conceallevel=2

syntax enable
filetype plugin on
filetype plugin indent on

let mapleader=' '

inoremap jk <Esc>

let g:wiki_cache_persistent = 0
let g:wiki_root = '~/notes'
```
The behavior seem to be a bit flaky to me. My observations:
1. Sometimes renaming works perfectly fine and both file name and links get updated even for subdirectories.
2. Sometimes renaming updates the file name but not the links. No errors, just a message saying "_Updated 0 links in 0 files_" even though the file has references in other files.
3. Sometimes renaming updates the file name but while updating the links it throws the following error:

**Comment by krankur** [comment]
I tried with minimal `vimrc`:
```
call plug#begin(stdpath('data') . '/site/plugged')
    Plug 'lervag/wiki.vim'
    Plug 'lervag/wiki-ft.vim'
call plug#end()

set nocompatible
set backspace=indent,eol,start

set tabstop=4
set shiftwidth=4
set expandtab
set conceallevel=2

syntax enable
filetype plugin on
filetype plugin indent on

let mapleader=' '

inoremap jk <Esc>

let g:wiki_cache_persistent = 0
let g:wiki_root = '~/notes'
```
The behavior seem to be a bit flaky to me. My observations:
1. Sometimes renaming works perfectly fine and both file name and links get updated even for subdirectories.
2. Sometimes renaming updates the file name but not the links. No errors, just a message saying "_Updated 0 links in 0 files_" even though the file has references in other files.
3. Sometimes renaming updates the file name but while updating the links it throws the following error:

**Comment by krankur** [comment]
I tried with minimal `vimrc`:
```
call plug#begin(stdpath('data') . '/site/plugged')
    Plug 'lervag/wiki.vim'
    Plug 'lervag/wiki-ft.vim'
call plug#end()

set nocompatible
set backspace=indent,eol,start

set tabstop=4
set shiftwidth=4
set expandtab
set conceallevel=2

syntax enable
filetype plugin on
filetype plugin indent on

let mapleader=' '

inoremap jk <Esc>

let g:wiki_cache_persistent = 0
let g:wiki_root = '~/notes'
```
The behavior seem to be a bit flaky to me. My observations:
1. Sometimes renaming works perfectly fine and both file name and links get updated even for subdirectories.
2. Sometimes renaming updates the file name but not the links. No errors, just a message saying "_Updated 0 links in 0 files_" even though the file has references in other files.
3. Sometimes renaming updates the file name but while updating the links it throws the following error:

**Comment by krankur** [comment]
I played some more with it. This time I tried with a minimal `vimrc`:

```
call plug#begin(stdpath('data') . '/site/plugged')
    Plug 'lervag/wiki.vim'
    Plug 'lervag/wiki-ft.vim'
call plug#end()

set nocompatible
set backspace=indent,eol,start

set tabstop=4
set shiftwidth=4
set expandtab
set conceallevel=2

syntax enable
filetype plugin on
filetype plugin indent on

let mapleader=' '

inoremap jk <Esc>

let g:wiki_cache_persistent = 0
let g:wiki_root = '~/notes'
```

The behavior seems to be a bit flaky to me. My observations:

1. Sometimes renaming works perfectly fine and both file name and links get updated even for subdirectories.
2. Sometimes renaming updates the file name but not the links. No errors, just a message saying "_Updated 0 links in 0 files_" even though the file has references in other files.
3. Sometimes renaming updates the file name but while updating the links it throws the following error:
![vim-wiki-error](https://user-images.githubusercontent.com/11840300/197254011-11cdc0b2-3c12-4787-b428-5210adc15090.png)

**Comment by lervag** [comment]
This sounds like a cache problem. I've pushed a minor update that _might_ solve it and that adds a more readable error message. Can you update and try to reproduce again?

**Comment by krankur** [comment]
Tried renaming multiple times. Seems much stable now but did get the following error on one instance:
![image](https://user-images.githubusercontent.com/11840300/197331712-bab98a3c-85f3-41e4-8c1b-3ab783761ebc.png)

**Comment by lervag** [comment]
I've made some minor changes and updates. Now you will not get the error messages, and, I **hope** you will also not have an issue with links not being updated.

Can you test? If you still see links not being updated, let me know. If so, it would be very good to get as much info on when this happens as possible.

**Comment by krankur** [comment]
@lervag sorry for the delayed response. The issue seems to have been resolved. Thanks for fixing this. It seems to me that there is a slight increase in the time taken to perform the rename action but I might be wrong and even if it's true, it's a very slight delay and can be ignored.

Also, I would like to thank you for this awesome plugin. :)

**Comment by lervag** [comment]
> @lervag sorry for the delayed response.

No problem!

> The issue seems to have been resolved. Thanks for fixing this.

That's good to hear.

> It seems to me that there is a slight increase in the time taken to perform the rename action but I might be wrong and even if it's true, it's a very slight delay and can be ignored.

I actually believe it should be a slight _decrease_, although it may depend on the size of your wiki. For me, it is quite a lot faster now, but I have 3-4000 files and ~180000 lines of text. The new implementation uses caching and thus avoids parsing all of this, which was what the old version did.

> Also, I would like to thank you for this awesome plugin. :)

<3 Thank you for the kind feedback!
