### ISSUE TITLE
WikiJournal : could not parse journal url

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#252]
# Description

NOTE: it was introduced with e7ccd5e3f582d1bcc0006ea66c8e33b25dbe2fe9 and is present in every commit that followed.

This issue started happening after today's update, but I didn't update `wiki.vim` for months.

Neovim, Windows

0. run Neovim
1. Type `WikiJournal`
2. Expected: open today's file
3. Actual: text as below

```
wiki: could not parse journal url!
  URL:       2022-10-26
  Date:      2022-10-26
  Anchor: 
```

It's even more interesting in gVim (Windows) where it suggests looking for new app in Application Store after I do `:WikiJournal<CR>`

My settings

```
let g:wiki_cache_root = '.cache'
let g:wiki_filetypes = ['adoc', 'asciidoc', 'wiki', 'md', 'markdown']
let g:wiki_write_on_nav = 1
let g:wiki_root = '~\vimfiles\vimwiki'
let g:wiki_date_exe = 'wikidate.exe'
let g:wiki_journal = {
    \ 'name': 'diary',
    \ 'frequency': 'daily',
    \ 'date_format': {
    \   'daily' : '%Y-%m-%d',
    \   'weekly' : '%Y_w%V',
    \   'monthly' : '%Y_m%m',
    \ },
    \}
let g:wiki_mappings_use_defaults = 'global'

let g:wiki_link_extension = '.adoc'

let g:wiki_resolver = 'WikiResolver'

```

I use a custom wiki resolver as you may see above, but I don't think it is called in this particular case.

**Comment by lervag** [comment]
I think it is, actually. Journal urls are converted to wiki links.

You no longer need `g:wiki_date_exe`, by the way. I figured out how to do all the date parsing within Vim.

I'll look into this when I get the time, as soon as possible. I've made major changes to the journal backend, which is why the error occurs in the first place.

**Comment by lervag** [comment]
> My settings: ...

Here's a suggested update to your settings with some comments/questions:

```vim
" Is there a reason you don't want to put the cache in a central place?
let g:wiki_cache_root = '.cache'
let g:wiki_filetypes = ['adoc', 'asciidoc', 'wiki', 'md', 'markdown']
let g:wiki_write_on_nav = 1
let g:wiki_root = '~\vimfiles\vimwiki'
" You don't need to specify keys unless you change them from default values
let g:wiki_journal = {'name': 'diary'}
let g:wiki_mappings_use_defaults = 'global'
let g:wiki_link_extension = '.adoc'
let g:wiki_resolver = 'WikiResolver'
```

Basically, I removed `g:wiki_date_exe` and adjusted `g:wiki_journal`.

> I use a custom wiki resolver as you may see above, but I don't think it is called in this particular case.

I think it may be relevant to see the definition of `WikiResolver`.

**Comment by lervag** [comment]
With the following minimal example I have no issue:

**test.vim**

```vim
set nocompatible
set runtimepath^=~/.local/plugged/wiki.vim
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:wiki_cache_root = fnamemodify('cache', ':p')
let g:wiki_filetypes = ['adoc', 'asciidoc', 'wiki', 'md', 'markdown']
let g:wiki_write_on_nav = 1
let g:wiki_root = fnamemodify('wiki', ':p')
let g:wiki_journal = { 'name': 'diary' }
let g:wiki_link_extension = '.adoc'
```

Contents of test directory:

```
$ tree
.
├── cache/
│   └── capture.json
├── test.vim
└── wiki/
    ├── diary/
    └── index.adoc

3 directories, 3 files
```

`index.adoc` is empty. I run `nvim --clean -u test.vim`, then do `\w\w` (or `:WikiJournal`) and I reach the expected destination, as can be seen in this screenshot:

![image](https://user-images.githubusercontent.com/998898/198141575-d2e81e38-6929-4814-9df5-2cbdd8bebbaa.png)

**Comment by bybor** [comment]
Thank you very much for taking time and providing a mnimal example.

I can reproduce the issue on my end with it, so it's not related to wiki resolver that i've been using.

With Vim it tries to launch something along the lines: rundll32 FileProtocol, journal:2022-10-27

With nvim it just outputs the same message as before.

Could you tell where I can put some test (`echom`) messages to figure it out? I know that you don't have Windows.

Thanks again

**Comment by lervag** [comment]
> Thank you very much for taking time and providing a mnimal example.

No problem :)

> With Vim it tries to launch something along the lines: cmd /c (rundll32 url.dll, FileProtocolHandler ^"journal:2022-10-27")

I still believe this is somehow related to your WikiResolver. But perhaps I'm wrong.

> Could you tell where I can put some test (`echom`) messages to figure it out? I know that you don't have Windows.

Yes. Ok, so:

0. Can you ensure you have the latest version, just in case?
1. You can use `unsilent echom ...` to check the value of `l:date`, `l:path` and `l:frq` after this line:
    https://github.com/lervag/wiki.vim/blob/ac9166c5cef780f30b0b59c437eb14402f3bfad7/autoload/wiki/url/journal.vim#L12
2. Now, it would be useful to understand where in `wiki#journal#date_to_node` it returns and why. Again, `unsilent echom` and possibly `:message` afterwards could help figure this out. E.g., add `unsilent echom l:frq` after this line:
    https://github.com/lervag/wiki.vim/blob/ac9166c5cef780f30b0b59c437eb14402f3bfad7/autoload/wiki/journal.vim#L152

At least, that's somewhere to start.

**Comment by bybor** [comment]
> I still believe this is somehow related to your WikiResolver

I tested it with your minimal example as soon as I had it, so that we have the common ground - we can rule out my custom resolver at least for now.

I followed your instructions and `echom`-ed almost every variable that was there right after it was assigned.

![2022-10-28_10-43](https://user-images.githubusercontent.com/90693/198532930-f237fbd2-1324-4ab0-9aaa-4fa9a45b94a1.png)

**Comment by lervag** [comment]
Ok, so it seems the problem is in this function:

https://github.com/lervag/wiki.vim/blob/ac9166c5cef780f30b0b59c437eb14402f3bfad7/autoload/wiki/date.vim#L136-L151

Could you echo the various variables there? I think perhaps it is the last line that is problematic, i.e. `strptime('%F', ...)`. Can you change `%F` into `%Y-%m-%d` and see if that changes anything?

**Comment by bybor** [comment]
Changing `%F` to `%Y-%m-%d` doesn't help.

These two lines 

    let l:timestamp = wiki#date#strptime(s:date_format[l:frq], l:date)
    let l:node = l:timestamp > 0
          \ ? strftime(get(g:wiki_journal.date_format, l:frq), l:timestamp)
          \ : ''

The current code returns `0` as seen on the screenshot. I hard-coded `l:node` to `2022-10-28` and it opened the file. 

The documentation tells that `strptime()` is not portable, but I couldn't find what to use in place.

You probably use `strptime` to confirm that you have a valid date string. But could we use `strftime` without that validation?

**Comment by lervag** [comment]
> Changing `%F` to `%Y-%m-%d` doesn't help.

Ah, that's annoying.

> The documentation tells that `strptime()` is not portable, but I couldn't find what to use in place.
> 
> You probably use `strptime` to confirm that you have a valid date string. But could we use `strftime` without that validation?

I was aware that `strptime` was not portable, but I was not aware it was not at least _partly_ portable. The function converts a date/time in string format into a timestamp (an integer). I think the problem is that, on your side - Windows, it just returns 0 no matter what.

Can you provide some more details:
* Which Windows version?
* Which Vim version (or neovim)?
* What does `:echo exists('*strptime')` output?
* What does `:echo strptime('%Y', '2022')` output?

**Comment by bybor** [comment]
* Windows 10
* Vim 9.0
  - `echo exists('*strptime')`: 0
  - `echo exists('strptime')`: 0
  - `echo strptime('%Y', '2022')` : Unknown function
* Neovim 0.7.4
  * `echo exists('*strptime')`: 1
  * `echo exists('strptime')`: 0
  * `echo strptime('%Y', '2022')` : 0

**Comment by lervag** [comment]
Ok, thanks. So, I'll see if I can find an alternative. In the meantime, you may want to revert to the previous version that worked for you. Sorry about the inconvenience!

**Comment by lervag** [comment]
Can we go the other way around? That is, does this work: `:echo strftime('%Y-%m-%d %H:%M', 1666600000)`?

**Comment by lervag** [comment]
I've implemented a solution that I think may work - under the assumption that `strftime` works as expected also on Windows. Please update and test.

**Comment by lervag** [comment]
By the way, I'm quite happy with the implementation:

https://github.com/lervag/wiki.vim/blob/bddc4506fe4eaa0174fcb263d9edfa6bfb1af86b/autoload/wiki/date/strptime.vim#L14-L44

It uses `strftime` to calculate the `strptime` for an isodate _implicitly_.

**Comment by bybor** [comment]
> I've implemented a solution that I think may work - under the assumption that strftime works as expected also on Windows. Please update and test.

It does, thanks a lot!

**Comment by lervag** [comment]
Glad to hear it! :)

**Comment by bybor** [comment]
I'm sorry, i will reopen this issue, but it may belong to a new one. I grabbed the latest `wiki.vim` in my android/termux environment and I have the same issue with `strptime` now.

This line

https://github.com/lervag/wiki.vim/blob/bddc4506fe4eaa0174fcb263d9edfa6bfb1af86b/autoload/wiki/date/strptime.vim#L8

Could you please change it to be not windows specific, but rather `strptime` specific? I believe that the code you wrote for windows will work fine for Termux too.

I don't know if it's a good idea to ditch `strptime` and just use your own code, but it looks pretty tempting IMHO.

Thanks again
