### ISSUE TITLE
WikiJournal: cannot parse url (Termux) 

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#253]
https://github.com/lervag/wiki.vim/blob/bddc4506fe4eaa0174fcb263d9edfa6bfb1af86b/autoload/wiki/date/strptime.vim#L8

Could you make the above check platform-agnostic please?

I grabbed the latest `wiki.vim` in my android/termux environment and I have the same issue with `strptime` now.

This line

https://github.com/lervag/wiki.vim/blob/bddc4506fe4eaa0174fcb263d9edfa6bfb1af86b/autoload/wiki/date/strptime.vim#L8

Could you make it check for `strptime` presence? I believe that the code you wrote for windows will work fine for Termux too.

I don't know if it's a good idea to ditch `strptime` and just use your own code, but it looks pretty tempting IMHO.

Thanks again

**Comment by lervag** [comment]
I believe this is fixed now, please test.

**Comment by bybor** [comment]
Ouch, it doesn't. Before opening this issue I did `echo exists('strptime')` and got `0`. I don't know what `*strptime` (with a `star`) means in your source code changes; I just assumed I will do it in a more strict way (without a `star`).

In Termux/neovim, `strftime('%Y', '2020')` returns a value that is > 0, so it works as expected at least in some cases.

1. I'm going to add debug messages as you previously suggested for Windows
2. The changes you did in this issues - they were not necessary, but on another side, they make your intention more clear. I don't know if you keep it this way or revert.
3. I will probably open another issue when I have more data if you don't mind, because you resolved the current one as it was suggested. But the bug was something else. Let me know if I should keep posting new findings here instead.

**Comment by lervag** [comment]
Let's continue this discussion at #254. :)
