### ISSUE TITLE
I believe this is fixed now, please test.

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#254]
I believe this is fixed now, please test.

_Originally posted by @lervag in https://github.com/lervag/wiki.vim/issues/253#issuecomment-1295832373_
      
While `strptime('%Y', '2020')` returns correct value, the call to `stptime('%F', '2022-10-30')` returns 0. Your implicit implementation works fine though. I would make it the default one.

Thank you!

**Comment by lervag** [comment]
Fascinating. Can you try `strptime('%Y-%m-%d`, '2022-10-30')`? It may just be that `%F` is not supported, in which case I'll just revert that to `%Y-%m-%d`.

**Comment by lervag** [comment]
Response to [this comment](https://github.com/lervag/wiki.vim/issues/253#issuecomment-1295962012):

> Ouch, it doesn't. Before opening this issue I did `echo exists('strptime')` and got `0`. I don't know what `*strptime` (with a `star`) means in your source code changes; I just assumed I will do it in a more strict way (without a `star`).
> 
> In Termux/neovim, `strftime('%Y', '2020')` returns a value that is > 0, so it works as expected at least in some cases.
> 
> 1. I'm going to add debug messages as you previously suggested for Windows
> 
> 2. The changes you did in this issue - they were not necessary, but on another side, they make your intention more clear. I don't know if you keep it this way or revert.
> 
> 3. I will probably open another issue when I have more data if you don't mind, because you resolved the current one as it was suggested. But the bug was something else. Let me know if I should keep posting new findings here instead.

Thanks for looking into this! I believe the issue here is a slightly reduced set of fields available in Termux, as explained in my previous comment. If I'm right, changing `%F` to `%Y-%m-%d` will resolve this issue. Thus, it would be useful to get a confirmation from you whether `:echo strptime('%Y-%m-%d', '2022-10-30')` outputs a reasonable timestamp.

**Comment by bybor** [comment]
> Thus, it would be useful to get a confirmation from you whether :echo strptime('%Y-%m-%d', '2022-10-30') outputs a reasonable timestamp.

It works! 1667077200

**Comment by lervag** [comment]
Then I believe the latest update should solve your issue. Please test and report :)

**Comment by bybor** [comment]
Yes, it works fine now , thanks a lot!

**Comment by lervag** [comment]
Great, glad to hear it! And thanks for helping me figure things out :)
