### ISSUE TITLE
WikiJournal, cannot parse journal url 2022-11-01

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#255]
This method

    function! wiki#date#strptime#isodate_implicit(date_target) abort " {{{1

returns `0` for `2022-11-01` in Windows/Neovim.

Here are the values right before `endfunction` which means it goes to the end of `while` w/o returning value from inside

![image](https://user-images.githubusercontent.com/90693/199182996-d2b3e27e-f1a4-485e-8dd4-246c76a4df68.png)

**Comment by lervag** [comment]
Interesting. On your system, what's the output of `:echo strftime('%Y-%m-%d-%H', 1666562400)`?

**Comment by bybor** [comment]
`2022-10-24-01`

**Comment by lervag** [comment]
Thanks! I think that's enough for me to debug, but I don't have the time right now. If you have time, it would be interesting to also see which values `l:current` is oscillating between in the while loop, e.g. with something like this:

```vim
  while l:count < 100
    let l:count += 1

    let l:date = strftime('%Y-%m-%d-%H', l:current)
    if l:date ==# l:date_target | return l:current | endif

    let l:current += 31536000*(l:year - l:date[:3])
    let l:current += 2592000*(l:month - l:date[5:6])
    let l:current += 86400*(l:day - l:date[8:9])
    let l:current += 3600*l:date[10:]
    silent echom l:date l:current
  endwhile
```

**Comment by bybor** [comment]
I'm sorry for pasting it the way you see it below, I don't really know how to do it in a sane way, though I know there is one. It repeats `2022-10-31-00` all the way to 100. I changed it to `unsilent`

![image](https://user-images.githubusercontent.com/90693/199309258-44e455d9-448d-4ab8-a644-84b9212d2c21.png)

**Comment by lervag** [comment]
Thanks. And sorry about yet another bug, but I believe it should be solved in a satisfactory manner now!

**Comment by bybor** [comment]
It works fine. And thank you very much for developing and supporting your software. It's huge! Thanks a lot!

**Comment by lervag** [comment]
Glad to hear it, and thanks for the kind words! :)
