### ISSUE TITLE
Multiple Wikis with g:wiki_global_load = 0

### ISSUE THREAD

**Issue by Grueslayer** [lervag/wiki.vim#257]
I use Markdown as filetype and `.md` as extension, so I decline to load wiki.vim on all the Markdown files and restrict it to the wiki files, which will be determined by `g:wiki_root`.

But if you use multiple wikis (like I do for personal, company and one in an encrypted filesystem for secrects) you have to call `WikiEnable` each time by hand.

VimWiki therefore has a list of roots (in detail a list of configurations per wiki), so the wiki addin will be enabled for folders/subfolders in every wiki root of that list.

**Comment by lervag** [comment]
> I use Markdown as filetype and `.md` as extension, so I decline to load wiki.vim on all the Markdown files and restrict it to the wiki files, which will be determined by `g:wiki_root`.

Could I kindly ask _why_ you don't want wiki.vim loaded on all Markdown files? It basically provides link functionality, and it should as far as I know work well and not get in your way. If I'm wrong, then it might be worth an issue and changes to wiki.vim.

**Comment by Grueslayer** [comment]
While I really like autolinking / page creation with `<CR>` and moving backward with `<BS>` in wiki, it is sometimes in my way. 
But maybe the bigger problem is auto probing for `index.md` (because my extension is md) to get wiki root:

If I'm in a Hugo website or any other documentation which is not a wiki, the wiki commands like  `:WikiFzfPages` will not fallback to my default wiki but now using the current folder for searching.

So maybe having a fix list of wiki folders may fix that.

**Comment by lervag** [comment]
Interesting. I can see how the behaviour of `WikiFzfPages` and the result of `wiki#get_root()` can lead to undesireable situations here. I would be interested in changing this behaviour, though, but I really _don't_ like the idea of specifying a list of wikis.

Notice that you can essentially build this feature yourself with minimal code. Something like this:

```vim
" In vimrc or similar

augroup init_wiki
  autocmd!
  autocmd BufRead,BufNewFile *.md call PossiblyEnableWiki()
  " This may be slightly better than the above, not sure:
  " autocmd FileType markdown call PossiblyEnableWiki()
augroup END

function! PossiblyEnableWiki()
  let l:wikis = [LIST OF PATHS]
  if index(l:wikis, wiki#get_root()) >= 0
    WikiEnable
  endif
endfunction
```

I personally don't use FZF anymore and just use my own custom finder execution. If I used FZF, I would basically just use FZF on my main wiki directly without `WikiFzfPages`. I.e. something like this:

```vim
nnoremap LHS :call fzf#vim#files(wiki#get_root_global())<cr>
```

**Comment by lervag** [comment]
Any thoughts? Are you satisfied with the proposed personal customization here?

**Comment by Grueslayer** [comment]
Sorry for my missing answer, was ill for some days. I’m sure I will solve it using your tips! Thanx!

**Comment by lervag** [comment]
Great, glad to hear it :)
