### ISSUE TITLE
Force wiki to use its mappings?

### ISSUE THREAD

**Issue by renkam** [lervag/wiki.vim#258]
Trying to use wiki navigation with already existing mappings (e.g. `<CR>`)

I have `nmap <CR> :History<CR> ` in my vimrc, I was previously using vimwiki and it was remapping `<CR>` every time I open vimwiki index page with `\ww`. I was expecting the same from wiki.

Unfortunately looks like my mappings takes precedence over wiki mappings.

I am wondering if there is an easy way to force wiki to remap all the necessary keys (especially navigation is important for me).

**Comment by lervag** [comment]
> I have `nmap <CR> :History<CR> ` in my vimrc, I was previously using vimwiki and it was remapping `<CR>` every time I open vimwiki index page with `\ww`. I was expecting the same from wiki.

IMHO, A plugin should never override a user mapping.

With wiki.vim, it is easy to create custom mappings. If you already map `<cr>` globally, but you want to use the wiki.vim mapping for `.wiki` or `.md` files, then you need to manually override your own global mapping.

This is easy. You should use either an `autocmd` or a personal `ftplugin/wiki.vim` or `ftplugin/markdown.vim` file. Let's assume you use the `.wiki` extension. Then either:

1. In your `.vimrc` file (or similar), add

    ```vim
    augroup my_vimrc
      autocmd!
      autocmd FileType wiki nmap <cr> <plug>(wiki-link-follow)
    augroup END
    ```

2. Create a personal file `~/.vim/ftplugin/wiki.vim` (or `~/.config/nvim/ftplugin/wiki.vim`) with the following content:

    ```vim
    nmap <cr> <plug>(wiki-link-follow)
    ```

PS! If you use Lua, then more or less the same as above applies except you use the Lua apis and `.lua` extension.
