### ISSUE TITLE
Improvement: Utilize other export formats in WikiGeneratePDF

### ISSUE THREAD

**Issue by jounathaen** [lervag/wiki.vim#26]
As already mentioned in #21 

`WikiGeneratePFD` basically calls pandoc, which will generate the pdf. However, pandoc can generate much more different formats than pdf by changing the suffix of the ouput file. **This already works in wiki.vim:** 
`WikiGeneratePDF mypage.html` generates a html page.

Idea:  (once more) rename `WikiGeneratePDF` to `WikiExport` and adapt the description. The default for pdf is fine.

**Comment by lervag** [comment]
I've made the change as proposed and added more options for `:WikiExport` as well as a dictionary configuration option `g:wiki_export` to set defaults. Let me know what you think!

**Comment by jounathaen** [comment]
Thank you for your effort. 👍 👍 👍 
It looks really good now.
If I stumble uppon any bugs, I'll create a new Issue!

**Comment by lervag** [comment]
Great, and thanks!
