### ISSUE TITLE
unexpected behavior concerning g:wiki_cache_root

### ISSUE THREAD

**Issue by step-** [lervag/wiki.vim#261]
I read the documentation then added the following configuration to my Linux vimrc:

```vim
function! WikiRoot()
  let l:local = finddir('doc', ';./')
  return !empty(l:local) ? l:local : '~/wiki'
endfunction
let g:wiki_root = 'WikiRoot'
let g:wiki_cache_root = '~/.cache/wiki'
```

My intent is twofold:
1. define a dynamic index file, `doc/index.md` when `doc` exists, $HOME`.'/wiki/index.md'` otherwise
2. keep a common cache root for all wikis.

The first objective is met while the second one is not: every time I start vim in some folder the new directory structure

```
~
~/.cache
~/.cache/wiki
```

is created in vim's current folder to my dismay. Questions:

A. Is my intent correct from your point of view?
B. Is the plugin's behavior intentional or a coding bug? Maybe it just needs to be better documented what setting `g:wiki_cache_root` is supposed to do. Or maybe the default value, which I copied from the help documentation, is incorrect?
C. what is the right way, if any, to set `g:wiki_cache_root` to achieve my second intent but with a directory other than $HOME`.'/.cache/wiki'`?
 
Anyway, when I remove line `let g:wiki_cache_root = '~/.cache/wiki'` from vimrc, the plugin seems to use $HOME`.'/.cache/wiki'` for the cache because it's the default cache directory, I suppose.

Thank you very much  for this plugin.

**Comment by lervag** [comment]
> My intent is twofold: …
> 
> 2. keep a common cache root for all wikis.

That's the default behaviour already. The default value is `~/.cache/wiki.vim`, you want to change it to `~/.cache/wiki`. However, the option does not currently support expansions, so the tilde is not converted properly. I guess you could call this a bug; or at the very least a faulty doc. So, until fixed, you can use this:

```vim
let g:wiki_cache_root = expand('~/.cache/wiki')
```

> A. Is my intent correct from your point of view?

Yes, but I don't quite see why you want to change it from the default. Still, you should of course be free to do that; see above.

**Comment by lervag** [comment]
I believe this is fixed now, which means your original configuration should now work. Please test :)

**Comment by step-** [comment]
> I believe this is fixed now, which means your original configuration should now work. Please test :)

Yes, it works as I intended now. Thank you very much for your prompt response!

However, I need to point out a minor documentation issue in lines 798-800 https://github.com/lervag/wiki.vim/blob/8aded59761105ed4d4fe9f7de29d3205863752a4/doc/wiki.txt#L798

>  This setting would first search for a `wiki` directory in the current
>  relative directory, and fallback to a global `wiki` if the local wiki is not
> found.

`finddir('wiki', ';./')` searches for `wiki` in the current directory, then upwords until it find a 'wiki' directory, if any, otherwise falls back to the global 'wiki'.   At least this is the way it's working with my vim installation, Linux vim 9.0.1062  with `&cpoptions == 'aABceFs'`

**Comment by lervag** [comment]
Thanks! I've updated the docs accordingly!
