### ISSUE TITLE
apple silicon fzf

### ISSUE THREAD

**Issue by nagy135** [lervag/wiki.vim#263]
Hello, i just switched to apple silicon and fzf picker doesnt work for me.
I followed steps in readme, so I have (actually neovim version of it)
```
set rtp+=/opt/homebrew/opt/fzf
```
and i see it in `echo &runtimepath`.
Also this is true about my system (installed with homebrew)
```sh
which fzf # /opt/homebrew/bin/fzf
```
also there is folder in `/opt/homebrew/opt/fzf` with `./bin/fzf`

Yet after this it still says **wiki: fzf must be installed for this to work** when running `:WikiFzfPages`

Any ideas what might be wrong?

**Comment by nagy135** [comment]
I m actually gonna write a telescope picker for myself to avoid fzf dependency entirely, will post it

**Comment by nagy135** [comment]
If anyone wants lua telescope version, this is it
```lua
vim.keymap.set('n', '<leader>wp', function()
    require("telescope.builtin").find_files { 
        prompt_title = "WikiFzfPages",
        cwd = "~/wiki",
    }
end, { desc = 'WikiFzfPages' })

```

**Comment by lervag** [comment]
> Hello, i just switched to apple silicon and fzf picker doesnt work for me. … Any ideas what might be wrong?

No, sorry. I believe it would be better to ask at the fzf repo. :\

> If anyone wants lua telescope version, this is it

Cool, thanks! I also use telescope for this these days. I've customized some more, perhaps it is useful to you for inspiration?

https://github.com/lervag/dotnvim/blob/cf90c4ed8450005022507d64db9ab0507ca83a76/lua/init/telescope.lua#L40-L71
