### ISSUE TITLE
WikiJournalIndex: Allow relative link paths

### ISSUE THREAD

**Issue by lervag** [lervag/wiki.vim#265]
From comment by @artkpv in #260:

> > Here the expected output is similar, except we want something like this at the end:
> > ```
> > [2023-01-01](/diary/2023-01-01)
> > [2023-01-01](/diary/2023-01-01_book-review)
> > [2023-01-02](/diary/2023-01-02)
> > ```

> Can we have relative links everywhere option? I mean here it would try to generate relative to current file links. Why:  We decouple this file from wiki.vim as only wiki.vim knows where the root dir '/' is. Examples: 1) I use Markor (markdown editor) on my Android device which supports markdown rendering but it doesn't know anything about root directories of the wiki. 2) To render markdown on my Linux I use Firefox plugin 'Markdown Viewer' which also doesn't know about root dirs.

This should be configurable with something like `let g:wiki_index_relative_paths` and possibly also as an argument to the command itself.

**Comment by lervag** [comment]
I've implemented `g:wiki_journal_index.link_url_parser` which makes it easy to get the behaviour you want. It is explained in the docs at `:help wiki_journal_index`. Please test and let me know what you think!

**Comment by artkpv** [comment]
The index works, it creates links and headers! Thank you. One thing though, I couldn't make links relative. This `    \ 'link_url_parser': { b, d, p -> wiki#paths#relative(wiki#get_root() . p, expand('%:h')) } ` expand my links into `[2023-02-05 ](/home/art/mydir/notes/2023/2023-02-05-2222.md)`, not relative. I tried different options. My root is `let g:wiki_root = '~/mydir/notes/'`

**Comment by lervag** [comment]
> The index works, it creates links and headers! Thank you.

Great, glad to hear it!

> One thing though, I couldn't make links relative. This
> 
> ```viml
>       \ 'link_url_parser': { b, d, p -> wiki#paths#relative(wiki#get_root() . p, expand('%:h')) }
> ```
> 
> expand my links into `[2023-02-05 ](/home/art/mydir/notes/2023/2023-02-05-2222.md)`, not relative. I tried different options. My root is `let g:wiki_root = '~/mydir/notes/'`.

Huh. Ok, what's the output of `:echo expand('%:h')` in the file where you are making the index? On my end, that specific configuration seemed to work as expected.

For debugging, you could try this:

```vim
let g:wiki_journal_index = {}
function! g:wiki_journal_index.link_url_parser(b, d, p) abort
  let l:root = wiki#get_root()
  let l:path = l:root . a:p
  unsilent echom 'DBG' a:p
  unsilent echom 'DBG' l:root
  unsilent echom 'DBG' l:path
  unsilent echom 'DBG' expand('%:h')
  return wiki#paths#relative(l:path, expand('%:h'))
endfunction
```

I believe it should work and should give some relevant messages. It may be too noisy, so perhaps try it in a small test environment first, if you have that.

**Comment by artkpv** [comment]
> what's the output of :echo expand('%:h') in the file where you are making the index?
It prints: `.` (dot)

> For debugging, you could try this:
It outputs this. 
```
DBG .
DBG /2023/2023-01-04-2118.md.md
DBG /home/art/mydir/notes
DBG /home/art/mydir/notes/2023/2023-01-04-2118.md.md
```

This `.md.md`ending because of `let g:wiki_link_extension = '.md'`, I guess (added this to always include the .md extension (so other apps work) but it adds double extension sometime.

Thanks!

**Comment by lervag** [comment]
Ah; does it work if you use `expand('%:p:h')`?

**Comment by lervag** [comment]
> This `.md.md`ending because of `let g:wiki_link_extension = '.md'`, There is no such file with '.md.md'. I guess (added this to always include the .md extension (so other apps work) but it adds double extension sometime.

Hmm, that's strange. I believe that may be an issue, but unrelated to this one. Could you try and make a new issue report with a slightly better description?

**Comment by artkpv** [comment]
> Ah; does it work if you use expand('%:p:h')?

Yes! :+1: 

> > This .md.mdending because of let g:wiki_link_extension = '.md', There is no such file with '.md.md'. I guess (added this to always include the .md extension (so other apps work) but it adds double extension sometime.

> Hmm, that's strange. I believe that may be an issue, but unrelated to this one. Could you try and make a new issue report with a slightly better description?

This might be because of my function as below. I fixed this to handle '.md' extension. Now `:WikiJournalIndex` doesn't have this '.md.md'

```
function WikiMapTextToLink(text) abort
  if a:text !~# '\v\.(md|wiki|txt)$'
    let t = substitute(tolower(a:text), '\v[ \t;:.*?\)\(]+', '_', 'g')
    if getcwd() !~# '\v\/0$|\/0\/'
        let t = strftime('%Y-%m-%d-%H-%M') . '_' . t
    else
        let t = strftime('%Y%m%d%H%M') . '_' .  t
    endif
    if t !~ '\.md$'
        let t = t . '.md'
    endif
    return [t, a:text]
  else
    return [a:text =~ '.md' ? a:text[:-4] : a:text, a:text]
  endif
endfunction
```

**Comment by lervag** [comment]
> > Ah; does it work if you use expand('%:p:h')?
> 
> Yes!

Great, glad to hear it. I'll update the docs accordingly.

> > Hmm, that's strange. I believe that may be an issue, but unrelated to this one. Could you try and make a new issue report with a slightly better description?
> 
> This might be because of my function as below. I fixed this to handle '.md' extension. Now `:WikiJournalIndex` doesn't have this '.md.md'

Ok, good. Feel free to open a new issue if you should have any more troubles.

By the way, I believe your function could be simplified to this:

```viml
function WikiMapTextToLink(text) abort
  if a:text =~# '\v\.(md|wiki|txt)$'
    return [a:text =~# '.md$' ? a:text[:-4] : a:text, a:text]
  endif

  let t = (getcwd() !~# '\v\/0$|\/0\/'
        \   ? strftime('%Y-%m-%d-%H-%M')
        \   : strftime('%Y%m%d%H%M'))
        \ . '_'
        \ . substitute(tolower(a:text), '\v[ \t;:.*?\)\(]+', '_', 'g')
        \ . '.md'

  return [t, a:text]
endfunction
```

Clearly, I've made some subjective choices here, so feel free to ignore!
