### ISSUE TITLE
`:WikiJournalNext` and `:WikiJournalPrev` moves to non-existent files

### ISSUE THREAD

**Issue by artkpv** [lervag/wiki.vim#266]
Related to #260 .

# Description

WikiJournalNext or WikiJournalPrev moves to non-existent notes.

See below example files created for the below steps.

WikiJournalNext. Steps. 
 1) Open existing file  2022-12-30-1242.md;
 2) Run WikiJournalNext 
 3) Result: Buffer opens for non-existent file named 2022-12-30.md  
Expected: Next existing file is opened (2022-12-31-1243.md). 

WikiJournalPrev. Steps:
 1) Open existing file  2022-12-30-1242.md;
 2) Run WikiJournalPrev
 3) Result: Buffer opens for non-existent file named 2022-12-29.md  
Expected: Previous existing file is opened (2022-12-31-1243.md). 

# Minimal working example

``
.
├── test.vim
└── wiki
    ├── diary
    │   ├── 2022-12-29-1241.md
    │   ├── 2022-12-30-1242.md
    │   ├── 2022-12-31-1243.md
    └── index.md
```

```vim
set nocompatible
set runtimepath^=~/.local/plugged/wiki.vim
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:wiki_cache_persistent = 0

let g:wiki_filetypes = ['md']
let g:wiki_write_on_nav = 1
let g:wiki_root = fnamemodify('wiki', ':p')
let g:wiki_link_extension = ''
let g:wiki_link_target_type = 'md'
let g:wiki_journal = {
    \ 'name': 'diary',
    \ 'index_use_journal_scheme': v:false,
    \}

runtime plugin/wiki.vim

silent edit wiki/index.md
WikiJournalIndex
```

**Comment by lervag** [comment]
I think this is fixed now, please test.

**Comment by lervag** [comment]
There are probably more issues with the journal due to my assumption that journal entries are unique for each date. I will be glad to work towards a generalization of this, but it helps a lot if you can let me know when you stumble into errors.

**Comment by artkpv** [comment]
:+1:  It works. Thank you!

**Comment by lervag** [comment]
Glad to hear it!
