### ISSUE TITLE
Links are not recognized if line starts with inline code

### ISSUE THREAD

**Issue by kosciak** [lervag/wiki.vim#267]
Links are not recognized properly when placed on line starting with inline code:
```
`inline code` [link](target)
```
The problem seems to be in function: `wiki#u#is_code()` - it seems to checks the synstack of first column of line under cursor (if I understand vimscript syntax correctly). Maybe it should check cursor column instead?

**Comment by lervag** [comment]
It's not immediately reproducable to me. Can you explain how to reproduce?

**Comment by kosciak** [comment]
Create markdow file and insert:
```
[name](target)
 `code` [name](target)
`code` [name](target)

    code [name](target)
```
Now let's check links in each line with `<leader>wll` after placing cursor on the link
First line as expected → wiki: Link info
Second line as expected → wiki: Link info
Third line NOT as expected → wiki: No link detected
Last line as expected → wiki: No link detected

vim-markdown recognizes correctly links in first 3 lines and conceals them. But  wiki.vim has problems with link on the second line (checking with `<leader>wll`, or just pressing `<cr>`)

**Comment by lervag** [comment]
I can't properly reproduce, but I can see from the code that you are probably right that there's a bug here.

**Comment by lervag** [comment]
I think it is fixed now.

**Comment by kosciak** [comment]
That was fast! Can confirm, link detection works as expected in all cases I've mentioned. Thanks!

**Comment by lervag** [comment]
Great, glad to hear it! :)
