### ISSUE TITLE
Improvement: Customizable Pandoc Arguments

### ISSUE THREAD

**Issue by jounathaen** [lervag/wiki.vim#27]
`WikiGeneratePDF` basically calls `pandoc -f gfm -o mypage.pdf mypage.wiki`. It might be interesting to change the arguments, for example to use pandoc templates.

Idea: add a variable like `wiki_pandoc_arguments` that defaults to `-f gfm` but can be changed for example to `-f markdown_mediawiki --template awesometemplate`.

This could be part of a solution for #24 :
Format flag defaults to `-f markdown` or `-f gfm` but can be changed via the variable.
Setting it by default to `markdown` should increase compatibility with old versions of pandoc.

**Comment by lervag** [comment]
Ok, I've made some noticable updates that should solve this issue, I think. Let me know what you think. I am not surprised if there are bugs, so feel free to raise new issues or continue discussion here.
