### ISSUE TITLE
[Feature Request] support for Jabref as Bibliography Program

### ISSUE THREAD

**Issue by felixschurk** [lervag/wiki.vim#286]
# Description

It would be nice if wiki.vim could also support [JabRef](https://www.jabref.org/) as an Literature Program similar to the existing Zotero implementation.

1. A description of the expected behavior
JabRef does store the Bibliography files an in `*.bib` file which does look like
```bib
@Report{Mustermann2011,
  author      = {Max Mustermann},
  date        = {2011-08},
  title       = {Just some sample entry},
  type        = {resreport},
  file        = {:Mustermann2011.pdf:PDF;Mustermann2011.epub:ePUB},
}
```
meaning I would like to make an reference in an Wiki Entry over `@Mustermann2011`.
When I am on the entry I would then like to have the choice to open JabRef or the PDF etc. (As it is implemented with Zotero).

The `.vimrc` could look something like that:
```vim
let g:wiki_use_jabref = True
let g:wiki_zotero_root = '/path/to/folder-with-all-literature-and-bib-file'
```

I guess to make this available one would just need to change the "Zotero" executable to allow an other also.

**Comment by lervag** [comment]
I need more to work on this. Preferably a full minimal example:

1. A wiki file (or Markdown) with an example `@link` 
2. A `.bib` file with the definition
3. A PDF and/or ePUB file
4. Explicit steps for how it should work

Notice that the location of the files are also important. E.g., perhaps we need to store the location of the `bib` file in an option, and similarly with potential pdfs and epubs?

**Comment by felixschurk** [comment]
1. wiki file (here in type markdown)
```markdown
@Chen2023

 Some test entry taken from Elsevier open access.
```

2. A `test.bib` file with the definition
```bib
@Article{Chen2023,
  author    = {Yidong Chen and Chen Li and Yonghong Hu and Zhonghua Lu},
  journal   = {Parallel Computing},
  title     = {A parallel non-convex approximation framework for risk parity portfolio design},
  year      = {2023},
  month     = {jul},
  pages     = {102999},
  volume    = {116},
  doi       = {10.1016/j.parco.2023.102999},
  file      = {:Chen2023 - A Parallel Non Convex Approximation Framework for Risk Parity Portfolio Design.pdf:PDF},
  publisher = {Elsevier {BV}},
  url       = {https://www.sciencedirect.com/science/article/pii/S0167819123000054},
}

@Comment{jabref-meta: databaseType:bibtex;}
```
The layout of my folder structure is currently like this, `test.bib.sav` is automatically created from JabRef as backup.
`Chen2023 - .... .pdf` has the name which is linked in the `file` section of `test.bib`.
```
literature-folder 
├── Chen2023 - A Parallel Non Convex Approximation Framework for Risk Parity Portfolio Design.pdf
├── test.bib
└── test.bib.sav
```

3. A PDF file
This one I do not have attached here in the issue, but the article in 2. contains the URL for the open access document.

4. `.vimrc` file
```vim
let g:wiki_zotero_root = '~/literature-folder'
```

5. Explicit steps for how it should work
- [ ] Omni Completion should provide suggestion after `@` (is working if `wiki_zotero_root` is set, but does searches the *.pdf files and not the Cite-Key if the file is named CiteKey.pdf)
- [ ] Enter on bib key should allow to follow
    1. Follow in JabRef: Chen2023
    2. Open PDF: Chen2023 - A Para .... .pdf
    x: Abort
Currently the `Open PDF` is already working.

The JabRef executable is usually installed under `/opt/jabref/bin/JabRef` however as I personally have that not on the path I have a alias to this command which is only called `jabref`.

**Comment by lervag** [comment]
Thanks! Now, with "Follow in JabRef" - how does _that_ work? I mean, can you show me how you would follow a bib entry based on the citation key from a terminal? I guess it would be something like `JabRef Chen2023`, but I'm not familiar with with, so I would appreciate the help.

Notice that the "Open PDF" action works by searching (also within subdirectories) for a file named `KEY*.pdf` where `KEY` is the citation key and `*` is the glob pattern for "anything". If more than 1 file is found, you will get a menu to select one. Thus, it will work mostly as expected for you already as long as you are consistent in naming your PDFs with the citation key as the first part of the file name.

I would prefer _not_ to parse the bib file to read the `file` key, so if you find the above explained behaviour suitable, then I would be quite happy to rely on the same mechanism for the JabRef implementation.

**Comment by felixschurk** [comment]
> Thanks! Now, with "Follow in JabRef" - how does that work? I mean, can you show me how you would follow a bib entry based on the citation key from a terminal? I guess it would be something like `JabRef Chen2023`, but I'm not familiar with with, so I would appreciate the help.

I checked the documentation from JabRef and noticed that this is not supported to open the database on a specific entry (or I did not find it). This is a bit unsatisfactory, however still the database can be opened from the terminal.

Opening the database can be achieved over following command:
`/opt/jabref/lib/runtime/bin/JabRef ~/literature-folder/test.bib`
The path to the JabRef is however platform specific, thus it would be good to have there the option to set the specific path otherwise, I guess this would only work under Linux.

> Notice that the "Open PDF" action works by searching (also within subdirectories) for a file named KEY*.pdf where KEY is the citation key and * is the glob pattern for "anything". If more than 1 file is found, you will get a menu to select one. Thus, it will work mostly as expected for you already as long as you are consistent in naming your PDFs with the citation key as the first part of the file name.

Sure this works already perfect, I think there is no other mechanism needed.

**Comment by lervag** [comment]
> I checked the documentation from JabRef and noticed that this is not supported to open the database on a specific entry (or I did not find it). This is a bit unsatisfactory, however still the database can be opened from the terminal.

Oh; well, then it seems to me that the only real value here is to allow to open
the PDFs, right? That is, it would be trivial to create a shortcut to open
your JabRef database; e.g. this should work:

```vim
nnoremap <leader>j :!/opt/jabref/lib/runtime/bin/JabRef ~/literature-folder/test.bib&<cr>
```

So, perhaps what we want here is simply to write some relevant documentation that helps users setup a JabRef integration by use of the Zotero backend?

**Comment by lervag** [comment]
For example, I could add something like this under `:help wiki-link-url` under the `zot` scheme:

```
  zot ~
    This is an early version of a Zotero scheme. It uses `fd`, `fdfind`, or
    `find` (in preferred order) to search the Zotero storage for a matching
    pdf. This works very well if one uses the Zotfile extension and the Better
    Bibtex extension to ensure that all pdf files are named according to the
    format `%b - {%T - } {%t}`, where `%b` is the citekey. Then links like
    `zot:citekey` should result in unique matches. The resulting file is
    opened with |g:wiki_viewer|. The Zotero storage root may be specified with
    |g:wiki_zotero_root|.

    The same link type can also work well for JabRef bibliographies. JabRef
    does not allow to open the database on a specific key. But if your JabRef
    library has PDFs that are named similarly as explained above, then it
    should suffice to point |g:wiki_zotero_root| to your literature folder. Now
    following `zot:citekey` or `@citekey` will allow to open the PDFs
    directly.
```

**Comment by felixschurk** [comment]
Yes that would be perfect, then other JabRef users can also use the wiki more easily and also helps to understand how to name the corresponding PDF files in the folder.

**Comment by lervag** [comment]
Cool; I've pushed the suggested update to the docs. Do you agree this resolves the issue, or should we do more?

**Comment by felixschurk** [comment]
I think it is solved. 
I just  noticed that the Completion `@CiteKey` is only working if there is an existing file, that contains the name, but that would require to parse the `*.bib` file which is not needed.

**Comment by lervag** [comment]
Great, glad to hear it!
