### ISSUE TITLE
Change default file format to Markdown

### ISSUE THREAD

**Issue by lervag** [lervag/wiki.vim#289]
wiki.vim is enabled by default for `.wiki` files, that is, files with filetype `wiki`. However, the `wiki` filetype is unspecified and the [wiki-ft.vim plugin](https://github.com/lervag/wiki-ft.vim/) mention in the README file is not quite appropriate as a default value. Further, wiki.vim works perfectly well with e.g. Markdown. Thus, it does not make sense to have `wiki` be the default filetype.

Proposed changes:

* Change the default value of `g:wiki_filetypes` to `['md']`.
* Change the default value of `g:wiki_link_target_Type` to `'md'`.
* Change the default value of `g:wiki_link_extension` to `'.md'` (Markdown links are by default _path_ links, thus it is likely that most people want the link with extensions applied).
* Update `README.md`: remove the text in the "Note: " from "A simple alternative". Say instead that wiki.vim is activated for Markdown files by default.
* Update the section `wiki-intro-plugins` in the docs and better explain about filetype plugins.
* Ensure that the docs reflect the updated default values.

**Comment by lervag** [comment]
@saccarosium Does this sound good to you? Did I miss anything?

**Comment by saccarosium** [comment]
We can debate about change also the default link format. I think that going for as close to base markdown as possible is the way to go. As such I think is better having the `[description](link)` the default link scheme.

As for the rest sounds exactly what I was thinking.

**Comment by lervag** [comment]
Yes, good point - I've updated the proposed changes list. I'm out of time now. I think I'll make these changes in a pull request and perhaps schedule another version release before I merge it. But it shouldn't be too long.

Thanks for suggesting these things - I think you make good points and I think these changes will make the overall experience better for most users.

**Comment by saccarosium** [comment]
I was thinking, that since this will likely break people configuration, do we make a deprecation notice? 

I was also thinking of a transition script, simce you used a very similar format to markdown should be as easy as changing all extention of the file and then using adding to the vimrc like using wiki stiled link and making the the link extention `''`.

Something like:
```bash
#!/bin/sh

os=$(uname)
 
set -f
find <wikidir> -iname *.wiki | cut -d. -f1 | xargs -I {} mv {}.wiki {}.md
set +f

if [ "$os" = "Darwin" ]; then
  sed -i'' "/let g:wiki_root/a g:wiki_link_target_Type = 'wiki\nlet g:wiki_link_extension = '''" <vimrv>
elif [ "$os" = "Linux" ]; then
  sed -i "/let g:wiki_root/a g:wiki_link_target_Type = 'wiki' \let g:wiki_link_extension = '''" <vimrc>
fi
```

Be kind I've made this at 4a.m in the morning later today I will test this and modify it accoddently.

**Comment by bybor** [comment]
@lervag , please keep wiki.vim format agnostic. There are a lot of markdown options, but wiki.vim may be the only one of its kind.

I understand that this issue is only about setting defaults, but where is a smoke, there is a fire 🙂

**Comment by saccarosium** [comment]
> @lervag , please keep wiki.vim format agnostic. There are a lot of markdown options, but wiki.vim may be the only one of its kind.

@bybor this upcoming changes are trying to make wiki.vim more filetype agnostic, see #288 for example. The change to markdown as the default from the current default `wiki` filetype is because as it is implemented in wiki.vim and in its companion filetype plugin, the `wiki` filetype is basically markdown with wikilinks extension and for this reason why don't just use regular markdown instead of inventing a new filetype (more context [here](https://github.com/lervag/wiki-ft.vim/issues/14).

**Comment by lervag** [comment]
> @lervag , please keep wiki.vim format agnostic. There are a lot of markdown options, but wiki.vim may be the only one of its kind.

I believe @saccarosium already answered this quite well. The idea is to adjust the docs and defaults so that wiki.vim is more aligned with user expectations. I think these are all good changes.

> I was thinking, that since this will likely break people configuration, do we make a deprecation notice?

Yes. I am committing things now, but I won't push it until I also have the time to make a release that I can announce on Reddit. I'm sorry that this will probably mean I may be somewhat delayed, as I don't have so much time to play with these things. But I hope I may be able to push the update today or tomorrow.

> I was also thinking of a transition script, simce you used a very similar format to markdown should be as easy as changing all extention and make incompatible markdown things compatible.

Thanks! Changing my wiki to Markdown in the sense of changing the extensions is not really the big problem for me. Instead, I will need to adjust the syntax to align with _proper_ Markdown (probably Commonmark). That's a bigger job, and I don't want to start it until I have some spare time.

**Comment by lervag** [comment]
I've also written the release notes: https://github.com/lervag/wiki.vim/releases/tag/v0.6
