### ISSUE TITLE
New Tags are only found after vim restart

### ISSUE THREAD

**Issue by jounathaen** [lervag/wiki.vim#29]
I add a Tag to an existing wiki page and safe the file (buffer is still open).
When I now do `WikiTagReload` and `WikiTagSearch mytag`, the page is not listed.

However, when I restart vim and do the same, the tag is found as expected.

In other words: I have to restart vim in order make changes to tags happen.

(Using neovim on MacOS)

**Comment by lervag** [comment]
Sorry, should be fixed now.
