### ISSUE TITLE
No more WikiFzfPages / WikiFzfTags

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/wiki.vim#291]
After a recent update, the commands `:WikiFzfPages` and `:WikiFzfTags` stopped working in `.wiki` files (I get the `not an editor command` error message). I don't think the problem has to do with any other changes I have made to my configuration. Before I do more extensive testing and a full bug report, I wanted to check whether this change is intentional; perhaps the commands have simply been renamed?

(I noticed that you changed the default filetype to markdown, so I added the lines

```vim
let g:wiki_link_extension = ['wiki']
let g:wiki_filetypes = ['wiki']
```

That makes `wiki.vim` work again in my wiki files, but it hasn't brought these commands back.)

**Comment by lervag** [comment]
> After a recent update, the commands `:WikiFzfPages` and `:WikiFzfTags` stopped working in `.wiki` files (I get the `not an editor command` error message).

The problem is that these are deprecated. You should now use `:WikiPages` and `:WikiTags` instead. It is mentioned in the latest release notes: https://github.com/lervag/wiki.vim/releases/tag/v0.6

**Comment by alexandreroberts** [comment]
Thank you! Now I know where to look first if there seem to be any breaking changes.

**Comment by lervag** [comment]
Yes; although, releases are not so often. You can also check the Git log; I use conventional commits, so breaking changes are indicated with exclamation marks, e.g. "feat!: ...".
