### ISSUE TITLE
Tag parser only seems to gather the first set of tags.

### ISSUE THREAD

**Issue by trev-dev** [lervag/wiki.vim#292]
I have been attempting to parse tags in a couple different ways.  In regular files, I use YAML headers.  In journals I use #hash #tags

The reason for this is the subject may change from header to header.

For example:

```markdown
# I had a meeting about Java
#java #spring

Blah blah blah

...many paragraphs later

# Cool tip about vim
#vim

Blah blah blah
```

My parser is only grabbing the #java and #spring tags, while ignoring the #vim tag.

I had a look at tag functions here:  https://github.com/lervag/wiki.vim/blob/6777c73c4438dcc07660f4b2bbd09a58e98cf6a2/autoload/wiki/tags.vim#L363 but can't spot anything wrong there.

My parsers are here: https://git.sr.ht/~trevdev/vim/tree/main/item/plugins.vim#L182

Any suggestions?

**Comment by lervag** [comment]
The first thing that comes to mind is this:

```
*g:wiki_tag_scan_num_lines*
  A number of lines to read from the top of a page when scanning tags. To scan
  lines from the bottom, use a negative number, e.g. >vim

    let g:wiki_tag_scan_num_lines = -10
<
  To scan the entire files, use: >vim

    let g:wiki_tag_scan_num_lines = 'all'
<
  Default: >vim

    let g:wiki_tag_scan_num_lines = 15
```

It's also documented under `:help wiki-tags` in the second paragraph.

**Comment by trev-dev** [comment]
Of course.  Here it is: https://github.com/lervag/wiki.vim/blob/6777c73c4438dcc07660f4b2bbd09a58e98cf6a2/autoload/wiki/tags.vim#L479

**Comment by trev-dev** [comment]
Thank you @lervag!

**Comment by lervag** [comment]
Glad to help :)
