### ISSUE TITLE
Feature request: apply wiki resolver to all supported link types

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#297]
Right now the wiki resolver is called only for `wiki` styled links. Could you enable it for all?

My use case is that I generally use a journal in a separate folder, with files named after `yyyy-MM-dd.adoc` pattern, while every other file resides in a root wiki folder. Defining a custom wiki resolver and using wiki links simplifies cross-referencing journal and regular entries without too much thinking.

Switching to say asciidoc xref links requires me to specify relative paths to journal folder or to parent folder.

This was previously discussed in https://github.com/lervag/wiki.vim/issues/222, but it looks like the `wiki.vim` development is now taking a more universal approach, so could you consider implementing this as well?

Thanks.

**Comment by lervag** [comment]
Yes, you are right: I am now actively trying to make a more robust and customizable experience that is filetype agnostic. Allowing a url resolver for more link types may be a good idea.

You are asking for a specific case of this. It would be very helpful if you could provide an example of how you think you would _configure_ wiki.vim to have the desired features. That can make it easier for me to write som relevant tests, as well as possibly spot some useful abstractions.

**Comment by bybor** [comment]
So, I'm in the journal entry named `2023-05-02.adoc`. I want to reference a "regular" entity with asciidoc supported syntax

    xref:Thinkpad.adoc[Laptop]

so that it would be resolved to the wiki root.

Instead it now resolves to a file under `journal`

And this syntax also resolve to `journal` (with a leading slash, which IMHO works for wiki links): 

    xref:/Thinkpad.adoc[Laptop]

And only this one resolves to wiki root:

    xref:../Thinkpad.adoc[Laptop]

The same would apply to entities named like below, always residing under `journal`

    xref:2023-05-01.adoc[2023-05-01]

Does it make sense?

Here is my `WikiResolver`

```
let g:wiki_resolver = 'WikiResolver'

function! WikiResolver(fname, origin) abort " {{{1
  if empty(a:fname) | return a:origin | endif

  if (match(a:fname, '\.adoc$') > 0)
    let l:f = fnamemodify(a:fname, ':t:r')
  else
    let l:f = fnamemodify(a:fname, ':t')
  endif

  if (match(l:f, '\d\{4}-\d\{2}-\d\{2}') == 0)
    let l:path = wiki#get_root() . '/diary/'. l:f
  else
    let l:path = wiki#get_root() . '/'. l:f
  endif

  "echom '1ST: '.l:path

  " Determine the proper extension (if necessary)
  let l:extensions = wiki#u#uniq_unsorted(
        \ (exists('b:wiki.extension') ? [b:wiki.extension] : [])
        \ + g:wiki_filetypes)
  if (empty(fnamemodify(a:fname, ':e')))
      let l:path .= g:wiki_link_extension
  endif

  "echom '2ND: '.l:path

  if index(l:extensions, fnamemodify(l:path, ':e')) < 0
    let l:path .= g:wiki_link_extension

    if !filereadable(l:path) && len(l:extensions) > 1
      for l:ext in l:extensions[1:]
        let l:newpath = l:path . '.' . l:ext
        if filereadable(l:newpath)
          let l:path = l:newpath
          break
        endif
      endfor
    endif
  endif

  "echom '3RD: '.l:path
  return l:path
endfunction
```

**Comment by lervag** [comment]
Yes, it makes sense. But it is still somewhat unclear to me what would be a good solution here. I think I want to tackle #296 first, as I think it may lead to some generalizations that will be useful before I handle this particular issue.

**Comment by lervag** [comment]
I believe #302 may be more or less what you want. I would love feedback. Notice that #301 is also relevant, as well as #299 (which seems ready).

**Comment by lervag** [comment]
I've merge #299 and #301 now, and I'll start working on a solution for #302. When it is finished, I believe you will have something that should allow to resolve your issue. Thus, I'll close this for now. But feel free to reopen or open a new issue if it turns out I'm wrong!
