### ISSUE TITLE
Feature Request: escape out of fzf prompts

### ISSUE THREAD

**Issue by nat-418** [lervag/wiki.vim#300]
I am a user of [fzf-lua](https://github.com/ibhagwan/fzf-lua) and I think it would be good to borrow the feature of being able to `<Esc>` out of the search prompt quickly.

**Comment by nat-418** [comment]
> Your request is very _unspecific_. In which search prompt are you missing this feature?

`:WikiPages` and related commands that can be configured with fzf.

**Comment by lervag** [comment]
Ok; are you on neovim? Did you change any default options?

**Comment by lervag** [comment]
I believe you are, and if so, then fzf-lua is used implicitly through the `vim.ui.select` function. And wiki.vim does not configure this, you need to configure it yourself.

**Comment by nat-418** [comment]
> Ok; are you on neovim? Did you change any default options?

Yes. Here is the relevant config: 
```lua
vim.g.wiki_select_method = 'fzf'
```

**Comment by lervag** [comment]
Cool; so, this means that fzf-lua is a fully compatible fzf backend?

wiki.vim has a few options that are probably relevant here: `g:wiki_fzf_{pages,tags}_opts`, so you could easily add fzf options that adds the desired escape mechanism.

Further, fzf-lua allows you to specify a lot of options, see [here](https://github.com/ibhagwan/fzf-lua#customization). I feel like what you ask for is something you should configure yourself, not something that should come hard-coded in wiki.vim.

**Comment by lervag** [comment]
Also, I'm not sure if wiki.vim really _uses_ fzf-lua. wiki.vim relies on the vimscript API of fzf.vim, which ships with fzf. I.e., I use the `fzf#run` and `fzf#wrap` functions, and I believe this will _not_ use fzf-lua.

Notice, though, that you can add custom options for fzf.vim. You can find the relevant docs here: https://github.com/junegunn/fzf/blob/master/doc/fzf.txt. Notice in lines 119 to 132 that there are 4 options to control fzf.vim. I believe you can get the desired behaviour by configuring these options.

**Comment by nat-418** [comment]
> Also, I'm not sure if wiki.vim really _uses_ fzf-lua. wiki.vim relies on the vimscript API of fzf.vim, which ships with fzf. I.e., I use the `fzf#run` and `fzf#wrap` functions, and I believe this will _not_ use fzf-lua.
> 
> Notice, though, that you can add custom options for fzf.vim. You can find the relevant docs here: https://github.com/junegunn/fzf/blob/master/doc/fzf.txt. Notice in lines 119 to 132 that there are 4 options to control fzf.vim. I believe you can get the desired behaviour by configuring these options.

I only brought up fzf-lua to give an example of another plugin that "does the right thing" without requiring extra user configuration. Since you aren't interested in implementing this feature, I will close the issue.

**Comment by lervag** [comment]
Ok. I believe my point is right, because wiki.vim is _not_ a search plugin. It relies on external plugins for that, such as fzf. And fzf can be configured by the user to do "the right thing".
