### ISSUE TITLE
Custom motion keymap for Colemak (i) clashes with default wiki.vim keymaps

### ISSUE THREAD

**Issue by daneorie** [lervag/wiki.vim#308]
# Description
As a Colemak user, I use a custom set of keymaps for my basic `hjkl` motions. I use `neio`, and the `i` seems to clash with some default keymap(s) from wiki.vim when in VISUAL mode. I looked around the documentation quite a bit to try and see if there's a way that I can deactivate these keymaps or replace them, but I haven't had any luck.

Behavior:
When in VISUAL mode, if I press `i`, there is a slight delay before moving the cursor up a line. This is due to a default keymap from wiki.vim. Every other motion works quick as expected.

# Notes
My best guess is that the following mappings are the problem for me:
[wiki.txt location](https://github.com/lervag/wiki.vim/blob/master/doc/wiki.txt#LL1559C1-L1561C1)
```
  `ox`    iu                  |<plug>(wiki-iu)|
  `ox`    it                  |<plug>(wiki-it)|
```

# Minimal working example
```lua
-- custom motion keymaps
	vim.keymap.set({ "n", "x" }, "n", "h", { noremap = true }) -- arrow: left
	vim.keymap.set({ "n", "x" }, "e", "j", { noremap = true }) -- arrow: down
	vim.keymap.set({ "n", "x" }, "i", "k", { noremap = true }) -- arrow: up
	vim.keymap.set({ "n", "x" }, "o", "l", { noremap = true }) -- arrow: right
	vim.keymap.set({ "n", "x" }, "h", "i", { noremap = true }) -- insert
	vim.keymap.set({ "n", "x" }, "k", "o", { noremap = true }) -- newline insert
	vim.keymap.set({ "n", "x" }, "l", "e", { noremap = true }) -- end of word
	vim.keymap.set({ "n", "x" }, "j", "n", { noremap = true }) -- next match

-- minimal wiki.vim configuration, but I think most of this is irrelevant
	local g = vim.g
	g.wiki_filetypes = { "md", "wiki" }
	g.wiki_link_extension = ".md"
	g.wiki_link_target_type = "md"

	vim.keymap.set("n", "<S-C-n>", "<Plug>(wiki-journal-prev)", { noremap = true })
	vim.keymap.set("n", "<S-C-o>", "<Plug>(wiki-journal-next)", { noremap = true })
```

**Comment by lervag** [comment]
> As a Colemak user, I use a custom set of keymaps for my basic `hjkl` motions. I use `neio`, and the `i` seems to clash with some default keymap(s) from wiki.vim when in VISUAL mode.

Yes; the `i` clash with `it` and `iu`, see `:help wiki-mappings-default`. The same section of the docs explain how to configure the mappings themselves. To disable these mappings, you would want:

```lua
vim.g.wiki_mappings_local = {
  ["o_<plug>(wiki-it)"] = "",
  ["x_<plug>(wiki-it)"] = "",
  ["o_<plug>(wiki-iu)"] = "",
  ["x_<plug>(wiki-iu)"] = "",
}
```

Notice, though, that you probably _don't_ want to do this. Instead, you want to read about text objects and learn to use them! See e.g. the user manual `:help 04.8` and `:help text-objects`.

> ```lua
> vim.keymap.set("n", "<S-C-n>", "<Plug>(wiki-journal-prev)", { noremap = true })
> vim.keymap.set("n", "<S-C-o>", "<Plug>(wiki-journal-next)", { noremap = true })
> ```

You don't want to change mappings this way. Instead, do this:

```lua
vim.g.wiki_mappings_local_journal = {
  ["<plug>(wiki-journal-prev)"] = "<s-c-n>",
  ["<plug>(wiki-journal-next)"] = "<s-c-o>",
}
```

The reason for this is that this will ensure that the mappings are only applied when you really want them.

**Comment by daneorie** [comment]
Great, thank you! Not sure how I missed the correct way of defining the keymaps. I found this way of defining them online somewhere that I can’t recall, and I clearly didn’t question it at the time.

I do use text objects quite often, so I’ll tinker around with finding an alternative, although it’s clearly not as intuitive to switch such keymaps around.

Thanks for your help!

**Comment by lervag** [comment]
> Great, thank you! Not sure how I missed the correct way of defining the keymaps. I found this way of defining them online somewhere that I can’t recall, and I clearly didn’t question it at the time.

No problem; happy to help! Note, though, that it can usually be a good idea to check the docs - in some cases they may be more updated and helpful than random posts online :)

**Comment by daneorie** [comment]
Okay, I tried implementing what you suggested, but I haven't had any luck of it removing the delay when pressing `i`. Here is my full configuration file just to cover my bases. I call the setup function via `require("config.wiki").setup()` when the plugin is loaded. I recently had to update from `g:wiki_map_text_to_link` to `g:wiki_link_creation`, so I'm wondering if I somehow missed some other deprecation.
```lua
-- config/wiki.lua
local M = {}

local g = vim.g

function M.setup()
	g.wiki_root = "~/Documents/iCloud/iCloud~md~obsidian/Documents/wiki"
	g.wiki_filetypes = { "md", "wiki" }
	g.wiki_journal = {
		date_format = {
			daily = "%Y/%m/%Y-%m-%d",
			weekly = "%Y/%Y-week_%V",
			monthly = "%Y/%m/%Y-%m-summary",
		},
	}
	g.wiki_mappings_local = {
		["o_<plug>(wiki-it)"] = "",
		["x_<plug>(wiki-it)"] = "",
		["o_<plug>(wiki-iu)"] = "",
		["x_<plug>(wiki-iu)"] = "",
	}
	g.wiki_mappings_local_journal = {
		["<plug>(wiki-journal-prev)"] = "<s-c-n>",
		["<plug>(wiki-journal-next)"] = "<s-c-o>",
	}
	g.wiki_link_creation = {
		md = {
			link_type = "md",
			url_extension = ".md",
			url_transform = function(x)
				-- the filename will always be lowercase
				local path = x:lower()

				-- This is not truly exhaustive as it should be, but for most of my use cases, I will only have spaces and/or colons.
				path = string.gsub(path, " ", "-") -- replace spaces with dashes
				path = string.gsub(path, "&", "and") -- replace ampersand with the word "and"
				path = string.gsub(path, ":", "") -- remove colons
				path = string.gsub(path, ",", "") -- remove commas

				-- Remove the .md extension if it exists, because it will be automatically added later.
				path = string.gsub(path, ".md$", "")

				-- If the relative path of the file is already specified, then remove it from the link description/name but keep the path for the link.
				if string.find(x, "/") then
					local link_description = string.gsub(x, "^.*/", "") or x

					-- Remove the './' if it's specified, since that's implied if there is no path given. './' would be specified at all to ensure the auto-nesting behavior doesn't occur.
					path = string.gsub(path, "^./", "") or path

					return path
				end

				local current_file = vim.fn.expand("%:t:r"):lower()
				-- If the current file is index, then don't try to put the link in a subfolder like everywhere else.
				if current_file == "index" then
					return path
				end

				-- Create the new link in a subfolder using the name of the current file. This creates an auto-nesting behavior.
				return current_file .. "/" .. path
			end,
		},
	}
end

return M
```

I've verified that the variables are being set correctly via `:echo g:wiki_mappings_local`, but they don't appear to be used.
```
-- :echo g:wiki_mappings_local
{'o_<plug>(wiki-iu)': '', 'x_<plug>(wiki-it)': '', 'x_<plug>(wiki-iu)': '', 'o_<plug>(wiki-it)': ''}
```

Any ideas?

**Comment by daneorie** [comment]
Wait, it might be another plugin...I was pretty sure that I had isolated it to wiki.vim, but perhaps something else is affecting me now.

**Comment by lervag** [comment]
After openin a wiki file, what's the output of `:xmap i`? or `:omap i`?

**Comment by lervag** [comment]
> Okay, I tried implementing what you suggested, but I haven't had any luck of it removing the delay when pressing `i`.

This is the step where I kindly ask for minimal examples. I.e., create a `test.vim` that only loads the specific plugin with your configuration, then run `nvim --clean -u test.vim` to start neovim (or `vim -u test.vim` for Vim).

> Here is my full configuration file just to cover my bases.

I don't see any specific issues with your config, but I believe your problem may be due to either another plugin or your own configuration at some other point.

**Comment by daneorie** [comment]
Yep, go figure. I did correctly isolate the collision to wiki.vim, but in the time between you giving me the solution and me actually implementing it, I **happened** to install [another plugin](https://github.com/andymass/vim-matchup) with a similar collision. I appreciate the help! I definitely learned a lot with your troubleshooting steps, and I'll need to be more careful and aware going forward.

Thanks!

```
-- :xmap i
x  i           * k
x  i%            <Plug>(matchup-i%)

-- :omap i
o  i%            <Plug>(matchup-i%)
```

**Comment by lervag** [comment]
Yes, there you are. :)
