### ISSUE TITLE
WikiExport and Relative Paths

### ISSUE THREAD

**Issue by CrossR** [lervag/wiki.vim#31]
Currently, I think the `WikiExport` runs on a temporary version of the file, or does so at least in neovim. That is, it runs on something in `/tmp/nvim_____/`.

This in turn causes issues if I have some images linked in my markdown files, since `![My Image](./images/001.png)` is no longer a valid link. Running `pandoc` directly on the file in the original location produces the expected pdf with images.

Using relative links lets me convert all my notes via `MkDocs` and host it online, but since that is private I would love an export feature so I can send some of the pages as PDF etc when I occasionally need to do that.

Perhaps this could be solved by using `resource-path` in `pandoc`? I attempted to get this working with the current config options, but I couldn't see a way to define a relative path in the current form of the arguments.

**Comment by lervag** [comment]
Good questions. I used `/tmp` (or more specifically, `tempname()`) to avoid cluttering the file system. The temporary file is necessary in order to make some minor substitutions before applying pandoc.

Perhaps a better default is to create the temporary file at the same location as the current file. I'll try this now, let me know what you think.

**Comment by lervag** [comment]
It seems to me the latest changes fixes this.

**Comment by CrossR** [comment]
It looks like the path is correct, but `pandoc` treats the paths as relative to the working directory, rather than the file.

That is, `pandoc` looks for the `images` folder in the folder it was invoked in, rather than next to the file. See: https://github.com/jgm/pandoc/issues/3752.

Looks like `wiki.vim` would either need to invoke `pandoc` in the folder the file is in, or allow the `resource-path` command line option somehow. Or if this starts to fall out of the scope of `wiki.vim`, I can look for a more dedicated pandoc vim plugin?

**Comment by lervag** [comment]
Ah. Well, then, we can simply change the working directory before running pandoc. :)

**Comment by CrossR** [comment]
Ah! That works perfectly now!

Thanks for the quick fix!

**Comment by lervag** [comment]
No problem, happy to help :)
