### ISSUE TITLE
Toggling links with `gl` doesn't correctly display the "choose UI"

### ISSUE THREAD

**Issue by aldur** [lervag/wiki.vim#310]
First things first: thank you for this amazing plugin! :)

# Description

Toggling links having multiple choices using `gl` on `nvim` (`v0.9.0` if relevant) doesn't correctly display the "choose UI".

See screenshot below; the lines above the `>` should display the chooser.

<img width="938" alt="Screenshot 2023-06-06 at 22 52 56" src="https://github.com/lervag/wiki.vim/assets/1721633/26ba7ffb-9c22-4d87-9e04-8c39721e253b">

# Minimal working example

```bash
mkdir t
cd t
echo "test" > index.md
touch TestUppercase.md
mkdir journal

cat << EOF > test.vim
> let g:wiki_filetypes = ['md']  " default
>
> let g:wiki_link_target_type = 'md'
> let g:wiki_link_extension = ''
>
> let &rtp  = '~/.vim/plugged/wiki.vim,' . &rtp
>
> EOF

tree .

.
├── TestUppercase.md
├── index.md
├── journal
└── test.vim

2 directories, 3 files
```

Now:

```bash
nvim --clean -u test.vim +WikiIndex` 
# now `gl` on the word `test`
```

In case it's relevant, also the relevant output of `env` (redacted for privacy):

```bash
env

TERM_PROGRAM=iTerm.app
TERM=xterm-256color
TERM_PROGRAM_VERSION=3.4.19
ITERM_PROFILE=Default
LC_TERMINAL_VERSION=3.4.19
LC_CTYPE=UTF-8
LC_TERMINAL=iTerm2
COLORTERM=truecolor
```

I have also tested this through `neovide` and get the same issue.

**Comment by lervag** [comment]
> First things first: thank you for this amazing plugin! :)

I'm glad you like it! :)

> Toggling links having multiple choices using `gl` on `nvim` (`v0.9.0` if relevant) doesn't correctly display the "choose UI".

Yes, you are right. I've postponed working on this... :p

> # Minimal working example

Thanks for the minimal example; having one will make it easier to work on this and possibly find a solution!

So, first: the test you provide does not immediately work on my end. If I change `echo test` to `echo Test`, it seems I can reproduce. I hope this is also correct on your end?

I'll look into this when I get the time!

**Comment by lervag** [comment]
Notice, though, that:

```vim
" This is default, so we don't need to set it explicitly unless we _change_
" it.
let g:wiki_filetypes = ['md']

" These are deprecated, see :help g:wiki_link_creation for the "new way".
let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = ''
```

**Comment by aldur** [comment]
> So, first: the test you provide does not immediately work on my end. If I change `echo test` to `echo Test`, it seems I can reproduce. I hope this is also correct on your end?

In my case, both `test` and `Test` trigger the issue. I am on macOS, where by default the file system is case insensitive. Maybe that's relevant?

> I'll look into this when I get the time!

Thank you!


> Notice, though, that:
> 
> ```viml
> " This is default, so we don't need to set it explicitly unless we _change_
> " it.
> let g:wiki_filetypes = ['md']
> 
> " These are deprecated, see :help g:wiki_link_creation for the "new way".
> let g:wiki_link_target_type = 'md'
> let g:wiki_link_extension = ''
> ```

Noted, thank you! I was using latest tagged release, but will refresh the config :)

**Comment by lervag** [comment]
> > So, first: the test you provide does not immediately work on my end. If I change `echo test` to `echo Test`, it seems I can reproduce. I hope this is also correct on your end?
> 
> In my case, both `test` and `Test` trigger the issue. I am on macOS, where by default the file system is case insensitive. Maybe that's relevant?

Yes, that sounds relevant, indeed.

> > Notice, though, that:
> > ```viml
> > " This is default, so we don't need to set it explicitly unless we _change_
> > " it.
> > let g:wiki_filetypes = ['md']
> > 
> > " These are deprecated, see :help g:wiki_link_creation for the "new way".
> > let g:wiki_link_target_type = 'md'
> > let g:wiki_link_extension = ''
> > ```
> 
> Noted, thank you! I was using latest tagged release, but will refresh the config :)

Ah, the mentioned changes are not _released_ yet and are only part of the `master` branch. So, if you're on the `v0.7` tag, then you probably still need the above options.

**Comment by lervag** [comment]
The main UI for selecting stuff does not work when it is used from a function used as an `'operatorfunc'`. I've found a fallback that uses `inputlist`, which seems to work OK.

I may look for generally better solutions in the future, but at least I think this solves the main issue. Let me know what you think.

**Comment by aldur** [comment]
It solves the issue for me, thank you for the quick turnaround! :)

**Comment by lervag** [comment]
Glad to hear it!
