### ISSUE TITLE
Feature request: Check for orphaned wiki files

### ISSUE THREAD

**Issue by sbalnave** [lervag/wiki.vim#311]
It feels like wiki pages could get lost in the aether if a link is accidentally deleted. If would be ideal if WikiGraphCheckLinksG could check for orphaned wiki pages alongside broken links and add them to the quickfix list too

**Comment by lervag** [comment]
In my view, these are different use cases. I.e., checking for broken links is not the same as checking for orphans. Thus, perhaps we should instead add a `:WikiGraphOrphans` that will list all files that do not have incoming links?

**Comment by lervag** [comment]
Can you test the recent update that brings `WikiGraphCheckOrphans`?

**Comment by lervag** [comment]
Glad to hear it! Thanks for the suggested feature! :)
