### ISSUE TITLE
how to attach marksman lsp to wiki index.md properly

### ISSUE THREAD

**Issue by Aneeqasif** [lervag/wiki.vim#315]
# Description
i want to use marksman with wiki.vim but the workspace folder is not adding properly and this i cannot use its features like go to def in other files.
is there a way to automatically vim.lsp.buf.add_workspace_folder(vim.fn.expand('%:p:h')) whenever marksman is attached to my index.md file in wiki.vim

or some other way.
i am using lunarvim with default config of wiki.v8im

**Comment by lervag** [comment]
I'm sorry, but I'm not familiar with marksman and the question is not really specific to wiki.vim. That is, I don't really know how to help with this.

**Comment by Aneeqasif** [comment]
i am sorry if it is in wrong place i know the command that can change the workspace folder of lsp server i was just looking for some kind of event / autocomand etc that gets executed on wiki index or etc but never mind the problem got resolved by just a git init in wiki root and lsp server is taking it as a project and attaching root correctly as workspace folder instead of working in  single file mode. thanks for repy

**Comment by lervag** [comment]
Glad to hear you found a solution!
