### ISSUE TITLE
<cr> creating nested links that are not required

### ISSUE THREAD

**Issue by Aneeqasif** [lervag/wiki.vim#316]
# Description

lets say i have following structur
```
wiki_root
├── index.md
├── a.md
├── b.md
└── foo
    ├── foo_index.md
    ├── c.md
    └── d.md
```

if i put `[[foo/c]]` in index.md it follows it perfectly but when i am in `foo_index` and a reference to c.md like same as `[[foo/c]]` pressing <cr> will create it in a new foo directory inside wiki_root/foo like `wiki_root/foo/foo/c.md` but if i put `[[../foo/c]]` it finds the note and open it. i am wondering why it is not just considering the wikiroot while searching for a note in some directory tree.i am used to obsidian and in nvim marksman lsp and previously telekasten.nvim and  if it is the default by design behavior then please let me of any way to make it coherent with my workflow that is on my muscle memory. it will be extremely helpful. thanks :)

**Comment by lervag** [comment]
> … but when i am in `foo_index` and a reference to c.md like same as `[[foo/c]]` pressing will create it in a new foo directory inside wiki_root/foo like `wiki_root/foo/foo/c.md` but if i put `[[../foo/c]]` it finds the note and open it.

Yes, that is correct. Links are generally assumed to be relative to the origin file. So, to link from `foo_index.md` to `c.md`, you can use `[[c]]`.

> i am wondering why it is not just considering the wikiroot while searching for a note in some directory tree.

Because I prefer it this way.

If you want, you can customize the link resolver. See `:help g:wiki_link_schemes` and `:help wiki-advanced-config` for more info.

> i am used to obsidian and in nvim marksman lsp and previously telekasten.nvim and if it is the default by design behavior then please let me of any way to make it coherent with my workflow that is on my muscle memory. it will be extremely helpful. thanks :)

You can change the behaviour, as said. The `resolver` function is what you want to change, and you can see the current resolver here:

https://github.com/lervag/wiki.vim/blob/228b8753e5a977fcafbbe16c87af8b89af9cfea7/autoload/wiki/url/resolvers.vim#L128-L139

Specifically, you would want to implement a resolver that uses a different `resolve_path` function.

**Comment by Aneeqasif** [comment]
sir i donot have any expertise in vimscript can u please help on it i-e the resolver

**Comment by lervag** [comment]
Ok: You can use something like this (although you may want to adjust according to how you prefer to configure things):

1. Create the file `~/.config/nvim/autoload/personal/wiki.vim` (or choose something similar if you are on another platform).
2. Add the following content:

    ```vim
    function! personal#wiki#link_resolver(url) abort
      let l:url = deepcopy(a:url)

      let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

      let l:path = split(l:url.stripped, '#', 1)[0]
      let l:url.path = personal#wiki#path_resolver(l:path, l:url.origin)

      return l:url
    endfunction

    function! personal#wiki#path_resolver(filename, origin) abort
      if empty(a:filename) | return a:origin | endif

      let l:path = wiki#paths#s(wiki#get_root() . '/' . a:filename)

      if l:path =~# '/$'
        let l:path .= g:wiki_index_name
      endif

      return wiki#url#utils#add_extension(l:path)
    endfunction
    ```

3. Finally, wherever you configure wiki.vim, add this:

    ```vim
    let g:wiki_link_schemes = {
          \ 'wiki': {
          \   'resolver': function('personal#wiki#link_resolver'),
          \ }
          \}
    ```

**Comment by Aneeqasif** [comment]
thank you so much sir for this :)

**Comment by lervag** [comment]
My pleasure; I hope you find wiki.vim useful! :)
