### ISSUE TITLE
Option to disable popups for ui#input

### ISSUE THREAD

**Issue by shaunbalnave** [lervag/wiki.vim#317]
I find the command line the more natural place to for example input the new name of a wiki page when calling `wiki-page-rename` (or something near the bottom like the telescope layout strategy "bottom_pane"). Wondering if you could add an option to disable the use of popups for `ui#input`? (sorry if it's there already and I missed it.)

**Comment by lervag** [comment]
> I find the command line the more natural place to for example input the new name of a wiki page when calling `wiki-page-rename` (or something near the bottom like the telescope layout strategy "bottom_pane").

That's fair!

> Wondering if you could add an option to disable the use of popups for `ui#input`? (sorry if it's there already and I missed it.)

Nope, this is not there; I'll add it. I think I'll add something like this:

```vim
let g:wiki_ui_method = {
      \ 'input': 'legacy',
      \ 'confirm': 'legacy',
      \ 'select': 'nvim',
      \}
```

Where the defaults will be `nvim` on Neovim and `legacy` else. I want to call it "legacy", because it utilizes the "old" `input()` functions.

What do you think?

**Comment by lervag** [comment]
I've added a first version now, please test. If you update, then you can use configuration similar to what I proposed above.

**Comment by shaunbalnave** [comment]
That's a good solution, thank you! I like the separation of input, confirm and select, I think legacy is good mainly for renames, since I check the status line for the current filename first so my eyes are already at the command line (and I'm used to using vim-eunuch to `:Rename` at the command line too)

**Comment by lervag** [comment]
Great, I'm glad you like the solution!

One of the core ideas behind adding these popups was actually aligned to what you are writing. I found I was using these things while my eyes where focusing on the cursor, so having the popups there seemed more convenient :)
