### ISSUE TITLE
Error when invoking WikiGraphCheckOrphans

### ISSUE THREAD

**Issue by Bridouz** [lervag/wiki.vim#322]
```
Error detected while processing function wiki#graph#check_orphans:

line    5:
E716: Key not present in Dictionary: "refresh_cache"
```
Not have a lot of clues, default config for everything.

Reproduced on :
  - OpenBSD (manual repos clone)
  - Termux (Paq manager)

Thanks for your wonderful plugin.

**Comment by lervag** [comment]
Thanks, I've pushed an update that I believe fixes this - please test!

Also, thanks for the kind words! <3
