### ISSUE TITLE
wrong TOC level

### ISSUE THREAD

**Issue by step-** [lervag/wiki.vim#323]
# Minimal working example

```md
# One
1

### Three
3
```

# Description

In the minimal working example, pressing ` \wf ` should produce the following TOC

```md
*Contents*
* [One](#One)
                * [Three](#One##Three)
```

but instead it produces:

```
*Contents*
        * [Three](#One##Three)
```

with the level-3 heading promoted to level 2. Consequently, following the link always jumps to the level 1 heading.

The point is that I would like to be able to jump to the level 3 heading from the generated TOC even if there is no intermediate level 2 heading in the markdown file.

**Comment by lervag** [comment]
This seems like a bug. I'll look into it.

**Comment by lervag** [comment]
Or, at least, it is a bug that the link does not work.

How should the TOC look like for this file?

```
# One
1

### Three
3

## Two
2

### Two three
2.3
```

**Comment by step-** [comment]
I think it should look like if there was a hidden level-2 heading between One an Three, except that the hidden heading's TOC entry should also be hidden.

**Comment by step-** [comment]
I agree, it's more important for the link to work, that's the key point.

**Comment by lervag** [comment]
> I think it should look like if there was a hidden level-2 heading between One an Three, except that the hidden heading's TOC entry should also be hidden.

Not fully sure what you mean. Do you mean something like this (which is what we get today)?

```md
*Contents*
* [One](#One)
        * [Three](#One#Three)
    * [Two](#One#Two)
        * [Two three](#One#Two#Two three)
```

> I agree, it's more important for the link to work, that's the key point.

I think this is fixed now. Please update and test.

**Comment by lervag** [comment]
I agree that it would be nice to avoid the extra indent _if_ there are _no_ middle sections (such as in your initial example). However, I don't see immediately a nice solution for implementing this that would not be quite "hacky". And so I'm wondering if it is worth the work to implement it.

**Comment by step-** [comment]
> Not fully sure what you mean. Do you mean something like this (which is what we get today)?
> 
> ```
> *Contents*
> * [One](#One)
>         * [Three](#One#Three)
>     * [Two](#One#Two)
>         * [Two three](#One#Two#Two three)
> ```

I mean this
```
Contents*
* [One](#One)
        * [Three](#One##Three)
    * [Two](#One#Two)
        * [Two three](#One#Two#Two three)
```

**Comment by lervag** [comment]
That's the same as what I posted..?

**Comment by lervag** [comment]
By the way, I pushed another fix that should ensure that the first entry of the TOC is also properly printed.

**Comment by step-** [comment]
> That's the same as what I posted..?

Yours `#One#Three`, mine `#One##Three`

**Comment by lervag** [comment]
Ah; but I think `One#Three` is what we want here for the URLs to work correctly.

**Comment by lervag** [comment]
Cool!

**Comment by step-** [comment]
Looks good to me. Thank you!

**Comment by lervag** [comment]
My pleasure, and thanks for raising the issue!
