### ISSUE TITLE
Feature. Create link with a relative path and a header in markdown 

### ISSUE THREAD

**Issue by artkpv** [lervag/wiki.vim#325]
# Description

Thank you for the tool! I use it a lot. 

How can I create such links? I often create links from current markdown page to another markdown page. I don't want any special schemes present in my markdown added by wiki.vim (like wiki:, zot:, etc.), I don't want any absolute paths from my root wiki dir because I use other tools as well to read my notes (markdown viewers at PC, Markor at Android). And I wish to be tool agnostic when I create my markdown files (improving decoupling). 

Expected behavior. From insert mode or from normal mode when I've opened any buffer with my note from my wiki. I call some function (omnifunc?) that presents me with a list of wiki pages. I filter that list using title or filename. I use fzf to filter my lists in vim. I press Enter. A link created in markdown like: `[The page title](./relative/path/to/my/page.md)`  (note, the path is relative to the current page).

`:WikiPages` allows me to open a page but not to create a link.

# Minimal working example

Any wiki pages you have in markdown format.

**Comment by lervag** [comment]
> Thank you for the tool! I use it a lot.

Glad to hear it!

> I often create links from current markdown page to another markdown page. I don't want any special schemes present in my markdown added by wiki.vim (like wiki:, zot:, etc.), I don't want any absolute paths from my root wiki dir because I use other tools as well to read my notes (markdown viewers at PC, Markor at Android). And I wish to be tool agnostic when I create my markdown files (improving decoupling).

If I understand correctly, you want your regular Markdown links (e.g. `[text](url)`) to be interpreted by wiki.vim like this:

* If the url has a scheme, then it should be respected (e.g. `http://...` urls).
* If the url does _not_ have a scheme, then it should be considered a link to another page _relative_ to the origin page.

An unschemed url will be considered to be a `wiki:` scheme. You can change how the link urls are resolved with something like this:

```vim
function! MyWikiResolver(url) abort
  let l:url = deepcopy(a:url)

  let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

  let l:path = split(l:url.stripped, '#', 1)[0]
  let l:url.path = PathResolver(l:path, l:url.origin)

  return l:url
endfunction

function! PathResolver(filename, origin) abort
  if empty(a:filename) | return a:origin | endif

  let l:root = !empty(a:origin)
        \ ? fnamemodify(a:origin, ':h')
        \ : wiki#get_root()
  let l:path = wiki#paths#s(l:root . '/' . a:filename)

  " Link that ends with `/` goes to folder index file
  if l:path =~# '/$'
    let l:path .= get(get(b:, 'wiki', {}), 'index_name', '')
  endif

  return wiki#url#utils#add_extension(l:path)
endfunction

let g:wiki_link_schemes = {
      \ 'wiki': {
      \   'resolver': function('MyWikiResolver'),
      \ }
      \}
```

This will make the links behave the way you want. I.e., the link urls are now always relative to the current file, but falls back to the wiki root if necessary.

**HOWEVER**: This is more or less how the links are resolved already. That is, wiki.vim will resolve the paths relative to the current file by default. It has a simple syntax for making a link relative to the root by prefixing with `/`. Thus, `[](/this/is/relative/to/wiki/root)` whereas `[](this/is/relative/to/file)`.

So, the first thing we have to address here: Do you have any issues currently with how the links are resolved in wiki.vim? That is, do your links currently navigate to the desired targets?

> How can I create such links?

> Expected behavior. From insert mode or from normal mode when I've opened any buffer with my note from my wiki. I call some function (omnifunc?) that presents me with a list of wiki pages. I filter that list using title or filename. I use fzf to filter my lists in vim. I press Enter. A link created in markdown like: `[The page title](./relative/path/to/my/page.md)` (note, the path is relative to the current page).

The current completion function does complete links. You can do `[](<c-x><c-o>` to start the omni completion. You can filter by files relative to the current file or relative to root if you prefix with `/`.

**Comment by artkpv** [comment]
Thank you for your detailed answer. :+1: 

Regarding the point if links work at all ("If I understand correctly, you want your regular Markdown links..."). This works as expected now, i.e. relative links are resolved using the path for the current opened markdown file. 

Regarding, the completion. Yeah, I see `[](<C-X><C-O>` works somewhat as I want but I wish it used fzf and the ability to search in markdown headers (the header that comes from `:WikiLinkExtractHeader`). Currently I use `:Files` provided by fzf-vim to create links (I search for a file then wrap it inside `[](my absolute path to a file)` and correct the path to the file I found (because my "current dir" (`:cd`) is always at the root of my wiki). But that takes many keys to type time each time and I'm lazy :) So I'd like to type as few keys as possible. I wish I had a greater workflow for my markdown links. As I wrote above I strive to create my files agnostic to any tool.  

I guess this is the question not for wiki.vim but for how I configure omnifunc or fzf or something. So I'm closing this issue.

**Comment by lervag** [comment]
> Thank you for your detailed answer. 👍

My pleasure. :)

> Regarding, the completion. Yeah, I see `[](<C-X><C-O>` works somewhat as I want but I wish it used fzf and the ability to search in markdown headers (the header that comes from `:WikiLinkExtractHeader`). Currently I use `:Files` provided by fzf-vim to create links (I search for a file then wrap it inside `[](my absolute path to a file)` and correct the path to the file I found (because my "current dir" (`:cd`) is always at the root of my wiki). But that takes many keys to type time each time and I'm lazy :) So I'd like to type as few keys as possible. I wish I had a greater workflow for my markdown links. As I wrote above I strive to create my files agnostic to any tool.

I would recommend to use an autocomplete engine such as nvim-cmp or similar. If you combine that with a source for omni complete functions, then you can get something that at least I personally find to be relatively smooth: After I type the `(` in `[...](`, the completion popup will open immediately and I can continue typing to filter the candidates.

The parts of my personal configuration relevant to completion for my wiki are here, in case you are interested: https://github.com/lervag/dotnvim/blob/b1dc12bc2d4ecf8f5b5e5c467ccbdd88f5303986/lua/lervag/init/packages.lua#L738-L745. (My config is quite large, so I can understand if you find it hard to get any value from looking it.)

> I guess this is the question not for wiki.vim but for how I configure omnifunc or fzf or something. So I'm closing this issue.

Yes, I agree. There are a lot of completion plugins out there. Today, nvim-cmp has become vere popular (for good reasons) in the neovim community. But you also have things like deoplete, YCM, and others. Installing, configuring and learning to use one of these is time well spent, in my opinion.
