### ISSUE TITLE
Remapping of `<C-i>` disables `<Tab>` (aka `:WikiLinkNext`)

### ISSUE THREAD

**Issue by PhilippFeO** [lervag/wiki.vim#330]
# Description

Disclaimer: I use Neovim.

1. A description of the expected behaviour
Pressing `<Tab>` moves cursor to the next (markdown) link.
2. A description of the observed behaviour
Nothing happens. The cursor remains at its position although there is at least one link left in the document.
3. The steps required to reproduce the issue
Minimal working configuration with remapping of `<C-i>` below. Start Neovim with the minimal working configuration. Type `:WikiIndex` to open the index of the wiki containing a link (not on position `(1,1)`, example file below). Type `<Tab>`.

# Minimal working example
```
/tmp/test_wiki
└── test_index.md
```
## Contents of `test_index.md`
```
Lorem ipsum

[This link doesn't work]() 

Lorem ipsum
```

## Minimal configuration
Please also provide a minimal ~vimrc~ `minimal_init.lua` file, e.g. 
```lua
vim.o.runtimepath = '~/.local/share/nvim/lazy/wiki.vim/'

vim.keymap.set('n', '<C-i>', '<C-i>zz', { desc = 'Center after moving up in jumplist' })

vim.g.wiki_root = '/tmp/test_wiki'
vim.g.wiki_index_name = 'test_index'
vim.g.wiki_filetypes = { 'md' }
vim.g.wiki_link_extension = '.md'
vim.g.wiki_link_target_type = 'md'
```

# Additional information
When starting Neovim via `nvim -u minimal_init.lua` the following error message emerges:
```
Fehler beim Ausführen von "/tmp/.mount_nvimsVLvcU/usr/share/nvim/runtime/syntax/syntax.vim":
Zeile   43:
E216: Keine solche Gruppe oder Ereignis: filetypedetect BufRead
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
```
Non verified English translation:
```
Error when executing of "/tmp/.mount_nvimsVLvcU/usr/share/nvim/runtime/syntax/syntax.vim":
Line 43:
E216: No such group or event: filetypedetect BufRead
Type ENTER or any command
```
---
Edit: Please ignore the commit below. It wasn't meant to play a role in this issue and intended for my personal record (it is also quite messed up). I didn't know GitHub connects commits automatically. I removed it from my history but GitHub remembers it anyway.

**Comment by lervag** [comment]
Thanks for the quite thorough issue description. So, the problem here is that `<c-i>` and `<tab>` are very often _the same_ keycode.

I only partly understand these things. I've found a few good resources, e.g.:

* https://unix.stackexchange.com/questions/631241/mapping-otherwise-conflicting-or-unmappable-keys-in-terminal-vim
* http://www.leonerd.org.uk/hacks/fixterms/
* https://vi.stackexchange.com/questions/13328/is-it-possible-to-map-c-s-space-in-neovim

> Edit: Please ignore the commit below. It wasn't meant to play a role in this issue and intended for my personal record (it is also quite messed up). I didn't know GitHub connects commits automatically. I removed it from my history but GitHub remembers it anyway.

No problem!

**Comment by PhilippFeO** [comment]
I have closed the issue, because I interpret your answer as an issue not related to wiki.vim.

---

> Thanks for the quite thorough issue description.

Thank you for wiki.vim and the additional resources! Is it possible to donate somewhere? I haven't found any information in the repository. Your plugin has developed into my backbone for studying and organizing.

**Comment by lervag** [comment]
> I have closed the issue, because I interpret your answer as an issue not related to wiki.vim.

Yes, correct; I don't believe this is an issue with wiki.vim. But let me know if you should have any further problems.

> Thank you for wiki.vim and the additional resources! Is it possible to donate somewhere? I haven't found any information in the repository. Your plugin has developed into my backbone for studying and organizing.

Glad you like it! I have a donation link at the top of the README in my other repo: https://github.com/lervag/vimtex/ :)

**Comment by lervag** [comment]
Thanks, @PhilippFeO; appreciated ❤️

**Comment by PhilippFeO** [comment]
I didn't reckon with an answer but I am glad to know you received the donation! :)
