### ISSUE TITLE
Wiki links without full path

### ISSUE THREAD

**Issue by hiqsol** [lervag/wiki.vim#332]
# Description

I have my markdown files organized in a shallow (one level deep) tree. I want wiki links `[[Filename]]` to work without specifying full path `[[Directory/Filename]]`. Actually it is a folder with Obsidian vault and links work that way in Obsidian app.

# Minimal working example

For example for the file structure like given below:

```
├── index.md
├── Flowers/
│   └── Rose.md
│   └── Daisy.md
├── Colors/
│   └── White.md
│   └── Black.md
```

I want link `[[White]]` to work globally (from any file, not only from files at the same directory e.g. `Black.md`).

How can I achieve such behavior? Did I miss something obvious in documentation?

Thanks in advance!

**Comment by lervag** [comment]
> I have my markdown files organized in a shallow (one level deep) tree. I want wiki links `[[Filename]]` to work without specifying full path `[[Directory/Filename]]`. Actually it is a folder with Obsidian vault and links work that way in Obsidian app.

I'll assume you already figured out how to use the Wiki link syntax.

> How can I achieve such behavior? Did I miss something obvious in documentation?

I wouldn't say _obvious_, but I believe the main part is there if you already know your way around Vim and Vimscript or similar. See `:help wiki-advanced-config-2`. Still, this _is_ advanced, and I wouldn't be surprised if most users will find it somewhat hard.

I believe you can achieve what you want with something like the following code. It's Vimscript; if you want Lua it should be relatively straightforward to convert it (I can help).

```vim
function! MyWikiResolver(url) abort
  let l:url = deepcopy(a:url)

  let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

  let l:filename = split(l:url.stripped, '#', 1)[0]
  if empty(l:filename)
    let l:url.path = l:url.origin
  else
    let l:pattern = printf('%s/**/%s.*',
          \ wiki#get_root(),
          \ l:filename)
    let l:paths = glob(l:pattern, v:true, v:true)
    let l:path = wiki#ui#select(l:paths)

    let l:url.path = wiki#url#utils#add_extension(wiki#paths#s(l:path))
  endif

  return l:url
endfunction

let g:wiki_link_creation = {
      \ 'md': {
      \   'link_type': 'wiki',
      \   'url_extension': '',
      \ }
      \}

let g:wiki_link_schemes = {
      \ 'wiki': {
      \   'resolver': function('MyWikiResolver'),
      \ }
      \}
```

**Comment by lervag** [comment]
If you want Lua, then I believe this may work. I didn't test it, so it may have a bug or two.

```lua
vim.g.wiki_link_creation = {
  md = {
    link_type = "wiki",
    url_extension = "",
  }
}

vim.g.wiki_link_schemes = {
  wiki = {
    resolver = function(url)
      local url = vim.deepcopy(url)
      url.anchor = vim.fn["wiki#url#utils#extract_anchor"](url.stripped)

      local filename = url.stripped:match "(.-)#"
      if filename == nil or filename == "" then
        url.path = url.origin
      else
        local pattern = string.format(
          "%s/**/%s.*",
          vim.fn["wiki#get_root"](),
          filename
        )
        local paths = vim.fn.glob(pattern, true, true)
        local selected_path = vim.fn["wiki#ui#select"](paths)
        url.path = vim.fn["wiki#url#utils#add_extension"](
          vim.fn["wiki#paths#s"](selected_path)
        )
      end

      return url
    end
  }
}
```

**Comment by hiqsol** [comment]
Works fine! Thank you very much!
