### ISSUE TITLE
new incompatibility between wiki.vim and lists.vim

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/wiki.vim#334]
# Description

I use wiki.vim and lists.vim together. I recently found that `list.vim`'s insert-mode `<c-a>`, which is supposed to call `i_<plug>(lists-new-element)`, stopped working. This must be because now `wiki.vim` now maps the same insert-mode key combination:
```
  i     <c-a>               |<plug>(wiki-link-add)|
```
How can I disable or change this new wiki.vim mapping? And wouldn't it be better if these two plugins don't conflict?

**Comment by lervag** [comment]
Yes, I actually just noticed this myself (see [here](https://github.com/lervag/dotnvim/commit/7c4c96171c51d2de564d7f9b3d1186b3f7e0f3f5)). Perhaps we should use another default mapping here? E.g. `<c-q>`?

**Comment by alexandreroberts** [comment]
`<c-q>` sounds great. I don't use it for anything else in insert mode.

**Comment by lervag** [comment]
Done!

**Comment by alexandreroberts** [comment]
Wonderful, thank you!

**Comment by lervag** [comment]
Thanks; I wasn't quite sure how to resolve this, but I think changing the default was better than having this incompatibility. So, thanks for raising the issue and helping me resolve it in a better way!
