### ISSUE TITLE
wiki link add, prefix with backslash

### ISSUE THREAD

**Issue by felixschurk** [lervag/wiki.vim#335]
I would expect that `WikiLinkAdd` inserts a backslash to have always absolute paths when the page is in a different directory after adding some link over `WikiLinkAdd` I would expect to become `[[/directory/some-page]]` however I do get `[[directory/some-page]]`.
This link can then not be resolved when inserted into a page in `directory-b`.

My wiki is structured into different directories, which each contain different pages, as some of the topics are quite separated.

It might also has to do with the way how I add the links into the wiki, my relevant settings are:

```vim
let g:wiki_link_creation = {
            \ 'md': {
            \   'link_type': 'wiki',
            \   'url_extension': '',
            \ },
            \}
```

Can I change the `wiki_link_creation` or something to prefix the added page, when not in the same directory, with a backslash to start from the wiki root?

**Comment by lervag** [comment]
Can you update and test; I believe the latest version should resolve your issue.

**Comment by felixschurk** [comment]
Hei, yes I tested it and now it is resolved. Thank you a lot!

**Comment by lervag** [comment]
Great, glad to hear it! :)
