### ISSUE TITLE
Non Functioning Links to Headers if Header contains a Space

### ISSUE THREAD

**Issue by Kojuma04** [lervag/wiki.vim#337]
As I have seen in an issue, links currently don't support spaces.
Because of that linking to a headers, which contain spaces, can't be done.
Though I would appreciate added support for spaces in links, it technically isn't necessary.
Added support for header ID's would also resolve this issue.

**Comment by Kojuma04** [comment]
OK it does work, it just doesn't pick up my syntax highlighting.
Though I can swear when I tried it yesterday it wouldn't let me.
Anyway, I'll mark this as resolved. Sorry for unnecessarily creating more work.

**Comment by Kojuma04** [comment]
Already implemented.

**Comment by lervag** [comment]
> OK it does work, it just doesn't pick up my syntax highlighting. Though I can swear when I tried it yesterday it wouldn't let me. Anyway, I'll mark this as resolved. Sorry for unnecessarily creating more work.

I don't know why it didn't work before for you, but I guess it must be some config problem.

wiki.vim does not provide any syntax highlighting, so if you have issues with that you must raise them with the filetype plugin you are using.

In any case, I'm glad to hear things work as expected.
