### ISSUE TITLE
Need help - asciidoctor files with wiki links, moving to lua/latest wiki.vim

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#338]
# Description

I cannot figure out how to re-create my setup with the latest `wiki.vim` (lua) and I'm not sure how to provide a minimal example - I'm trying to switch to `lazyvim` config going all Lua w/o .nvimrc file (or init.lua).

I want to navigate from `Index.adoc` files with `asciidoctor` filetype; by using `wiki` styled lilnks without extension

```
~/vimwiki/vimfiles
├── index.adoc
├── diary
│   └── 2017-11-24.adoc
└── Current.adoc
```

## Issue

`index.adoc` has wiki format links as below:
```
[[Current]]
```
I cannot navigate (wiki follow) unless I change it to `[[Current.adoc]]`.

Here is my current config for `wiki.vim`:

```lua
  {
    "lervag/wiki.vim",
    lazy = false,
    init = function(_, opts)
      vim.g.wiki_root = "~/vimfiles/vimwiki"
      vim.g.wiki_date_exe = "wikidate.exe"
      vim.g.wiki_write_on_nav = 1
      vim.g.wiki_mappings_use_defaults = "global"
      -- vim.g.wiki_link_extension = ".adoc"
      vim.g.wiki_link_creation = {
        asciidoctor = {
          link_type = "wiki",
          url_extension = "adoc",
        },
        adoc = {
          link_type = "wiki",
          url_extension = "adoc",
        },
        wiki = {
          link_type = "wiki",
          url_extension = "adoc",
        },
        _ = {
          link_type = "wiki",
          url_extension = "adoc",
        },
      }
      vim.g.wiki_default_schemes = {
        wiki = {
          adoc = "wiki",
        },
      }
      vim.g.wiki_filetypes = { "adoc", "asciidoc", "md", "markdown" }
      vim.g.wiki_journal = {
        ["name"] = "diary",
        ["frequency"] = "daily",
        ["date_format"] = {
          ["daily"] = "%Y-%m-%d",
          ["weekly"] = "%Y_w%V",
          ["monthly"] = "%Y_m%m",
        },
      }

      vim.keymap.set("n", "<leader>fp", ":WikiPages<CR>", { silent = true })
      -- file, tags and buffers as supported by fzf
      vim.g.wiki_mappings_local = {
        ["<Plug>(wiki-link-follow)"] = "<Leader>wf",
        ["<Plug>(wiki-link-follow-split)"] = "<Leader>we",
        ["<Plug>(wiki-page-rename)"] = "<Leader>wr",
        ["<Plug>(wiki-journal-next)"] = "<Leader>dn",
        ["<Plug>(wiki-journal-prev)"] = "<Leader>dp",
        ["<Plug>(wiki-link-return)"] = "<Leader>wb",
        ["<Plug>(wiki-link-next)"] = "<Leader>wn",
        ["<Plug>(wiki-link-prev)"] = "<Leader>wp",
      }
    end,
  },

```

**Comment by lervag** [comment]
> `index.adoc` has wiki format links as below:
> 
> ```
> [[Current]]
> ```
> 
> I cannot navigate (wiki follow) unless I change it to `[[Current.adoc]]`.

Ok, I think this has a relatively easy fix. Try with the following config:

```lua
  {
    "lervag/wiki.vim",
    lazy = false,
    init = function()
      vim.g.wiki_root = "~/vimfiles/vimwiki"
      vim.g.wiki_date_exe = "wikidate.exe"
      vim.g.wiki_write_on_nav = 1

      vim.g.wiki_filetypes = { "adoc", "md" }
      vim.g.wiki_link_creation = {
        adoc = {
          link_type = "wiki",
          url_extension = "",
        },
        _ = {
          link_type = "wiki",
          url_extension = "",
        },
      }
      vim.g.wiki_link_default_schemes = {
        wiki = {
          adoc = "wiki",
        },
      }

      vim.g.wiki_journal = {
        ["name"] = "diary",
        ["frequency"] = "daily",
        ["date_format"] = {
          ["daily"] = "%Y-%m-%d",
          ["weekly"] = "%Y_w%V",
          ["monthly"] = "%Y_m%m",
        },
      }

      vim.keymap.set("n", "<leader>fp", ":WikiPages<CR>", { silent = true })
      vim.g.wiki_mappings_use_defaults = "global"
      vim.g.wiki_mappings_local = {
        ["<Plug>(wiki-link-follow)"] = "<Leader>wf",
        ["<Plug>(wiki-link-follow-split)"] = "<Leader>we",
        ["<Plug>(wiki-page-rename)"] = "<Leader>wr",
        ["<Plug>(wiki-journal-next)"] = "<Leader>dn",
        ["<Plug>(wiki-journal-prev)"] = "<Leader>dp",
        ["<Plug>(wiki-link-return)"] = "<Leader>wb",
        ["<Plug>(wiki-link-next)"] = "<Leader>wn",
        ["<Plug>(wiki-link-prev)"] = "<Leader>wp",
      }
    end,
  },
```

The main changes:

* Use correct name: `wiki_link_default_schemes`
* You wanted to _not_ have the extension as part of the url, so we set it to blank.
* I removed some (seeminly) unnecessary stuff
* I grouped the related options

Notice:

* You are specifying to also activate wiki.vim for Markdown files, but you are now using the default link settings. I guess that's what you want, but I'm mentioning it in case it was not.
* wiki.vim uses mainly filetype _extensions_, not the filetype _names_; thus, you want `adoc` and not `asciidoctor` as keys for the various options. This is mentioned in the documentation for the relevant options.

**Comment by bybor** [comment]
Thank you very much! It works fine now

**Comment by bybor** [comment]
@lervag , could you please help me a bit more? It's another part of upgrade that got me stuck

I used to have this function as a resolver - it "splits" urls into 2 buckets : journal and root.

```
function! WikiResolver(fname, origin) abort
  if empty(a:fname) | return a:origin | endif

  let l:name = fnamemodify(a:fname, ':t:r')
  let l:ext = fnamemodify(a:fname, ':e')
  let l:path = l:name =~# '^\d\{4}-\d\{2}-\d\{2}'
        \ ? wiki#get_root() . '/diary/'. l:name
        \ : wiki#get_root() . '/'. l:name

  return l:path . '.adoc'
endfunction
```

How would you write it with Lua? It also looks like there is only a single parameter (instead of 2 as before)

I think it should be defined here

```
      vim.g.wiki_link_schemes = {
        adoc = {
          resolver
        }
      }
```

It's probably enough to just change this method (leaving it in VimScript) so that it works with the latest `wiki.vim`.

Please let me know if I'm asking too much :) I am slowly moving through a few guides on Lua/neovim; I know I'll figure it out, but it feels very tempting to switch to the latest `wiki.vim`. I got stuck with 0.6 release because of not being able to adopt to the newer builds.

**Comment by lervag** [comment]
> @lervag , could you please help me a bit more? It's another part of upgrade that got me stuck

Sure!

> How would you write it with Lua? It also looks like there is only a single parameter (instead of 2 as before)

I think you want something like this:

```lua
vim.g.wiki_link_schemes = {
  adoc = {
    resolver = function(url)
      local r = vim.deepcopy(url)

      r.anchor = vim.fn["wiki#url#utils#extract_anchor"](r.stripped)

      local root = vim.fn["wiki#get_root"]()
      local path = vim.fn.split(r.stripped, "#", 1)[1]
      local name = vim.fn.fnamemodify(path, ":t:r")
      if name:match "^%d%d%d%d-%d%d-%d%d" then
        r.path = root .. "/diary/" .. name .. ".adoc"
      else
        r.path = root .. "/" .. name .. ".adoc"
      end

      return r
    end,
  }
}
```

> Please let me know if I'm asking too much :) I am slowly moving through a few guides on Lua/neovim; I know I'll figure it out, but it feels very tempting to switch to the latest `wiki.vim`. I got stuck with 0.6 release because of not being able to adopt to the newer builds.

No problem; and I would very much advice to stay on the latest wiki.vim, as I believe there have been some good updates. :)

**Comment by lervag** [comment]
I understand that it is somewhat hard to both learn Lua and at the same time configure things like this that is also in itself slightly complex. I've tried to provide a thorough documentation of these things, but I know it can still be hard. So don't worry about asking questions!

**Comment by lervag** [comment]
Also, let me know if this did not work as expected - I didn't really try it first :p

**Comment by bybor** [comment]
I so much appreciate your help!

I had to do a small change to make it work for my schema (adoc files with wiki urls), but I would not figure it out without your code

```
vim.g.wiki_link_schemes = {
  wiki = {
    resolver = function(url)
...
```

**Comment by lervag** [comment]
> I so much appreciate your help!

Glad to hear it!

> I had to do a small change to make it work for my schema (adoc files with wiki urls), but I would not figure it out without your code …

Ah, yes, I should have noticed that. But I'm glad to hear you figured it out!
