### ISSUE TITLE
calling <plug>(wiki-journal-next) 

### ISSUE THREAD

**Issue by ivhak** [lervag/wiki.vim#34]
I have set up `wiki.vim` to use weekly journals with 

```
let g:wiki_root = '/home/myname/Notes'
let g:wiki_filetypes = ['md', 'markdown', 'markdown.pandoc']
let g:wiki_list_todos = ['TODO', 'DOING', 'DONE']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
let g:wiki_template_title_week = '# Uke %(week) - %(year)'
let g:wiki_journal = {
    \ 'name': 'journal',
    \ 'frequency': 'weekly',
    \ 'date_format': {
    \   'daily' : '%Y-%m-%d',
    \   'weekly' : '%Y_w%V',
    \   'monthly' : '%Y_m%m',
    \ },
    \}

```

While inside vim,`<leader>w<leader>w` (`<plug>wiki-journal`) opens the current weeks journal, and `<C-k>` (`<plug>(wiki-journal-next)`) opens the next journal entry and `<C-j>` (`<plug>(wiki-journal-prev)`) opens the previous journal entry as expected. But, if I open the current weeks journal directly from the terminal, e.g. `vim /home/username/Notes/journal/2019_w16.md` and enter `<C-k>` (`<plug> (wiki-journal-next)` or `<C-j>` (`<plug>(wiki-journal-prev)`), either nothing happens or a new buffer is created with the path `/home/username/Notes/journal/journal/2019_w16.md`. Have I configured something wrong or is this a bug?

Anyways, thank you for `wiki.vim`. I previously used `vimwiki`, but this plugin suits all my needs and nothing more.

**Comment by lervag** [comment]
This should be fixed now. There was a minor error in parsing the collected links. Thanks for reporting!

**Comment by ivhak** [comment]
Seems to work now, thanks!

**Comment by lervag** [comment]
Great, happy to hear it. :)
