### ISSUE TITLE
citekey: link to BibDesk (in wiki.vim too) [feature request]

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/wiki.vim#341]
This is a feature request just like [the one I just opened](https://github.com/lervag/vimtex/issues/2908) for `vimtex`. It too is based on [an old thread from a year ago](https://github.com/lervag/wiki-ft.vim/issues/13) about how doing so might be feasible.

What I would like is to be able to enter a single command (in the case of wiki.vim, simply `<CR>`) in order to open the citekey under the cursor in BibDesk (on MacOS). Unlike in vimtex, I don't think wiki.vim "knows" which `.bib` file to use, so perhaps it would make most sense for it to simply be a reference to whatever `.bib` file is open in BibDesk at the time. I think this might be what `open x-bdsk://citekey` (see description [here](https://github.com/lervag/wiki-ft.vim/issues/13#issuecomment-1493383863)) does by default anyway.

**Comment by lervag** [comment]
Just for completeness, could you give one or more examples of wiki text with citekeys?

As a very simple, first step, I've added a handler for `bdsk:` schemes. Thus, if you write a link like `bdsk:citekey`, then I believe it should work as expected already.

**Comment by alexandreroberts** [comment]
> Just for completeness, could you give one or more examples of wiki text with citekeys?

Here is an example: `See @ei2 and @BS.` (The cite keys are `ei2` and `BS`, respectively. Note that final dots do not count as part of the citekey, as we determined [here](https://github.com/lervag/wiki-ft.vim/issues/13#issuecomment-1486512009).)

> As a very simple, first step, I've added a handler for `bdsk:` schemes. Thus, if you write a link like `bdsk:citekey`, then I believe it should work as expected already.

I've just tested it and can confirm that it works: when I type `<CR>` while the cursor is over the text `bdsk:ei2` in a wiki file, BibDesk opens and displays the `ei2` entry.

**Comment by lervag** [comment]
Ok, so what is missing now is to connect `@...` with `bdsk:...`. Or, is it? In fact, it is not. You can change it with:

```vim
let g:wiki_link_default_schemes = { 'cite': 'bdsk' }
```

Can you test this and see if it is actually a sufficient solution here?

**Comment by alexandreroberts** [comment]
That did it! Once I added this line to my nvim configuration, it worked perfectly: with cursor over the `@`, `e`, `i`, or `2` in `@ei2.`, pressing `<CR>` brought opened the `ei2` entry in BibDesk.

As I tested it further, I noticed a "bug" related to that wiki-ft.vim query of mine from a year ago: if the citekey contains `:`, then wiki-ft.vim and wiki.vim treat it as if the citekey ended before the `:`, i.e., both in how it is highlighted and what citekey string wiki.vim passes to BibDesk. Many of my citekeys use the character `:`.

I think the solution to that "bug" would be the same as for `.`: count `:` as part of the citekey unless it is the very last permissible character of a citekey.

**Comment by lervag** [comment]
> That did it! Once I added this line to my nvim configuration, it worked perfectly: with cursor over the `@`, `e`, `i`, or `2` in `@ei2.`, pressing `<CR>` brought opened the `ei2` entry in BibDesk.

Great, glad to hear it!

> As I tested it further, I noticed a "bug" related to that wiki-ft.vim query of mine from a year ago: if the citekey contains `:`, then wiki-ft.vim and wiki.vim treat it as if the citekey ended before the `:`, i.e., both in how it is highlighted and what citekey string wiki.vim passes to BibDesk. Many of my citekeys use the character `:`.
> 
> I think the solution to that "bug" would be the same as for `.`: count `:` as part of the citekey unless it is the very last permissible character of a citekey.

Could you give a couple of examples of this? And, just for the sake of clarity, is this a bug in wiki.vim or in wiki-ft.vim? Or both?

**Comment by lervag** [comment]
Nevermind, I think I figured out what you want and I think my latest commit fixes it. Please update and test.

**Comment by lervag** [comment]
Huh, strange. Can you type `<leader>wl` on that link and post the information you get here?

**Comment by alexandreroberts** [comment]
The citekey is `@john.skylitzes:histories:thurn1973`. This is what wiki.vim returns:

```
 Type:          url
 Match:         skylitzes:histories:thurn1973
 URL:           skylitzes:histories:thurn1973
 Description:   N/A
                
 Resolved URL object: 
   url:         skylitzes:histories:thurn1973
   stripped:    histories:thurn1973
   origin:      /Users/robe941/Documents/wikiNotepad/index.wiki
   scheme:      skylitzes
```

So it looks like `.` and `:` don't work together in the same citekey.

Here is a screenshot showing that this citekey is nevertheless correctly highlighted:

<img width="374" alt="Screenshot 2024-04-04 at 9 00 51 PM" src="https://github.com/lervag/wiki.vim/assets/6886906/89b41d7a-aaba-45f9-81b9-5f6f492b8956">

**Comment by alexandreroberts** [comment]
Ah, but curiously when I put my cursor over the `john` part, this is what I get instead:

```
 Type:          cite
 Match:         @john.skylitzes:histories:thurn1973
 URL:           bdsk:john.skylitzes:histories:thurn1973
 URL (raw):     john.skylitzes:histories:thurn1973
 Description:   N/A
                
 Resolved URL object: 
   url:         bdsk:john.skylitzes:histories:thurn1973
   stripped:    john.skylitzes:histories:thurn1973
   origin:      /Users/robe941/Documents/wikiNotepad/index.wiki
   scheme:      bdsk
```

But even then, `<CR>` does nothing.

**Comment by alexandreroberts** [comment]
This makes me wonder whether there are two problems:

1. wiki.vim isn't parsing it quite right
2. even when it does parse it right, maybe `bdsk:` links that include `:` don't work. Maybe the colons need to be somehow escaped in the URL?

**Comment by lervag** [comment]
I pushed another commit that at least fixes one of these issues. That is, the type should now be cite.

However, the next problem is probably a bit harder. One thing we can try is to see if url encoding works here. You could try something like this:

```vim
function! ResolverBdsk(url) abort
  let a:url.stripped = wiki#url#utils#url_encode(a:url.stripped)
  return a:url
endfunction

" Change the wiki scheme resolver
let g:wiki_link_schemes = {
      \ 'bdsk': {
      \   'resolver': function('MyWikiResolver'),
      \ }
      \}
```

Or, simply just try this to use this link: `<bdsk:john.skylitzes%3Ahistories%3Athurn1973>`. The `%3A` is the url encoding for a colon.

**Comment by lervag** [comment]
Sorry, my mistake: Notice the name mismatch: `MyWikiResolver` should be `ResolverBdsk`.

**Comment by lervag** [comment]
I _could_ add this url encoding as a default built-in behaviour here, but if so, I should first check if it works with Zotero.

**Comment by alexandreroberts** [comment]
That fixed it! Now the last link (the one with the colon) works perfectly.

I do think it would make sense to make this the default built-in behavior, assuming it doesn't cause any problems for Zotero. Maybe it could be used only in the case that the BibDesk option is set?

**Comment by lervag** [comment]
Yes. However, I believe it does make sense to do this at the url level. That is, if I did url encoding only for the cite _links_, then it won't apply the url encoding for e.g. `[[bdsk:LINK]]` or `<bdsk:...>` or similar, only for `@my:citation`.

And as such, I think the pragmatic choice for now is to just add this as the default behaviour for bdsk url's, and then consider this for Zotero if anyone should want it/ask for it.

**Comment by alexandreroberts** [comment]
That makes sense to me. Thank you for this significant improvement to wiki.vim!

**Comment by lervag** [comment]
No problem; I pushed the change now, so you can remove the latest update to your config. Let me know if it works :)

**Comment by alexandreroberts** [comment]
I just updated it. This is now the error that I get:

<img width="1439" alt="Screenshot 2024-04-04 at 10 10 45 PM" src="https://github.com/lervag/wiki.vim/assets/6886906/f35a89c2-b8cd-4a6d-967e-a756914d1540">

**Comment by alexandreroberts** [comment]
(I also removed the additional code from my config.)

**Comment by lervag** [comment]
Sorry! I'll fix that asap.

**Comment by lervag** [comment]
There...

**Comment by alexandreroberts** [comment]
It works now, thank you!

**Comment by lervag** [comment]
Great, glad to hear it!
