### ISSUE TITLE
Default keybinds not loading when attempting to use `adoc`

### ISSUE THREAD

**Issue by jamiereid** [lervag/wiki.vim#343]
# Description

Default keybindings don't seem to load when attempting to use `adoc`.

# More detail

When `vim.g.wiki_filetypes` is set to `{"adoc"}` the default keybindings are not loaded when opening a file within the `wiki_root` (either via the cli, or `<leader>ww` for index).

When `vim.g.wiki_filetypes` is set to `{"md"}` they do load.

This image shows that the keybinds are there when `wiki_filetypes` is set to `{"md"}`.
<img width="892" alt="telescope keymap view showing wiki.vim bindings" src="https://github.com/lervag/wiki.vim/assets/883147/60a8e0ab-7147-435f-8204-311a284cb9fd">

This image show that the keybinds are not there when `wiki_filetypes` is set to `{"adoc"}`.
<img width="1190" alt="telescope keymap view showing that wiki.vim bindings aren't set" src="https://github.com/lervag/wiki.vim/assets/883147/e3883405-b6dc-476b-aae1-88f048a063cd">

Setting `vim.g.wiki_mappings_use_defaults` to "all" doesn't appear to have any effect.

I am using `lazy` as my package manager, config is below.

```lua
return {
    "lervag/wiki.vim",
    config = function()
        vim.g.wiki_root = "~/n"
        vim.g.wiki_index_name = "workingbrain"

        vim.g.wiki_filetypes = {"adoc"}

        vim.g.wiki_select_method = {
            pages = require("wiki.telescope").pages,
            tags  = require("wiki.telescope").tags,
            toc   = require("wiki.telescope").toc,
            links = require("wiki.telescope").links,
        }

        vim.keymap.set("n", "<leader>wp", ":WikiPages<cr>")
        vim.keymap.set("n", "<leader>wt", ":WikiTags<cr>")
        vim.keymap.set("n", "<leader>we", ":WikiExport<cr>")

    end
}
```

If this is a simple config error, I apologise. I've searched through the doco and I can't find where I might be going wrong.

**Comment by lervag** [comment]
You need to use the `init` function for wiki.vim. This is because the options must be defined _before_ wiki.vim is loaded.

```
return {
    "lervag/wiki.vim",
    init = function()
        vim.g.wiki_root = "~/n"
        vim.g.wiki_index_name = "workingbrain"

        vim.g.wiki_filetypes = {"adoc"}

        vim.g.wiki_select_method = {
            pages = require("wiki.telescope").pages,
            tags  = require("wiki.telescope").tags,
            toc   = require("wiki.telescope").toc,
            links = require("wiki.telescope").links,
        }

        vim.keymap.set("n", "<leader>wp", ":WikiPages<cr>")
        vim.keymap.set("n", "<leader>wt", ":WikiTags<cr>")
        vim.keymap.set("n", "<leader>we", ":WikiExport<cr>")
    end
}
```

**Comment by jamiereid** [comment]
Thank you!

**Comment by lervag** [comment]
No problem! :)
