### ISSUE TITLE
How can I avoid affecting certain default templates of wiki.vim

### ISSUE THREAD

**Issue by VimWei** [lervag/wiki.vim#344]
Today, I wanted to retest the week/month summary and discovered new issues.

## Expected behaviour

Open week summary with title which defined by `g:wiki_template_title_week`

## But case 1

1. Restart gVim 9.1 (win 10 pro 22H2)
2. Open journal today：`<leader>w<leader>w`
3. Open week summary: `<leader>wu`

Result: 
```
Error detected while processing function wiki#journal#go_to_frq[15]..wiki#journal#open[14]..wiki#url#follow[15]..function wiki#journal#go_to_frq[15]..wiki#journal#open[14]..wiki#url#follow[12]..wiki#url#handlers#wiki[3]..wiki#url#utils#go_to_file[10]..BufNewFile 自动命令 "*.md"..function <SNR>51_autoload[3]..wiki#buffer#init[25]..wiki#template#init[14]..<SNR>111_template_apply[2]..GeneralTemplate:
line    1:
E716: Key not present in Dictionary: "link"
E116: Invalid arguments for function get(a:context.origin.link, 'text', a:context.name)
```

![originlink](https://github.com/lervag/wiki.vim/assets/25874852/878bacd0-7085-4d0e-8e3b-d8933ae96c9e)

## Case 2

1. Restart gVim 9.1 (win 10 pro 22H2)
2. Open journal today：`<leader>w<leader>w`
3. Enter any wiki link, such as: `[test](test)`
4. Reopen journal today: `<leader>w<leader>w`
5. Open week summary: `<leader>wu`

Result:  the week summary page's title is latest wikilink's text, such as `test`.

![originlink2](https://github.com/lervag/wiki.vim/assets/25874852/3227f0b7-c68c-4cd6-b58a-1dfc75124d90)

## Analysis of the cause and question about default templates

It's possible that my following vimrc settings have affected this behavior... How can I avoid affecting certain default templates of wiki.vim (such as week/month summary)?

```
    function! GeneralTemplate(context) abort
        let title = get(a:context.origin.link, 'text', a:context.name)
        call append(0, '# ' . title)
        call append(1, '')
        execute "normal! I## "
    endfunction
    let g:wiki_templates = [
                \ { 'match_re': '.*',
                \   'source_func': function('GeneralTemplate') },
                \]
```
My vimrc configuration related to wiki.vim: https://github.com/VimWei/vim-init/blob/master/init/plugins.vim#L313-L386

**Comment by lervag** [comment]
> Today, I wanted to retest the week/month summary and discovered new issues.

> It's possible that my following vimrc settings have affected this behavior... How can I avoid affecting certain default templates of wiki.vim (such as week/month summary)?
> 
> ```
>     function! GeneralTemplate(context) abort
>         let title = get(a:context.origin.link, 'text', a:context.name)
>         call append(0, '# ' . title)
>         call append(1, '')
>         execute "normal! I## "
>     endfunction
>     let g:wiki_templates = [
>                 \ { 'match_re': '.*',
>                 \   'source_func': function('GeneralTemplate') },
>                 \]
> ```

You can fix the error message like this:

```vim
    function! GeneralTemplate(context) abort
        let title = a:context.name
        if exists('a:context.origin.link.text')
          let title = a:context.origin.link.text
        endif
        call append(0, '# ' . title)
        call append(1, '')
        execute "normal! I## "
    endfunction
```

But I think we also want to change the matcher so it doesn't apply to journal entries. Notice that only a single template will apply:

https://github.com/lervag/wiki.vim/blob/928ae30ec85d953ef46e47fe9f179eea669bf0b7/autoload/wiki/template.vim#L19-L32

Thus, to have the weekly/monthly templates apply we need for the general template to _not_ apply. You have to use a less general regex, or you could use a function or a lambda that combines stuff. For instance:

```vim
    let g:wiki_templates = [
                \ { 'match_func': { x -> x.path_wiki !~# 'journal' },
                \   'source_func': function('GeneralTemplate') },
                \]
```

Notice, `match_func` is a function (or lambda) with the same context argument. Also, notice that my suggestion here is probably not fully sufficient, as it will prevent your template for any note that has "journal" in its path string.

**Comment by VimWei** [comment]
That's fantastic, your revision suggestions completely meet my needs. Every time I see your response, it exceeds my expectations, salute!

**Comment by lervag** [comment]
> That's fantastic, your revision suggestions completely meet my needs. Every time I see your response, it exceeds my expectations, salute!

Great! And thanks for the kind words!
