### ISSUE TITLE
Possible to use one prefix to delimit a line of tags?

### ISSUE THREAD

**Issue by fmenozzi** [lervag/wiki.vim#345]
First of all, thank you for creating this plugin. I was previously using a home-grown script to manage a flat directory of markdown files for writing notes, but the better editor integration and additional features that wiki.vim offers have convinced me to make the switch, and so far I am very pleased with it. Great work!

One aspect of wiki.vim that differs from how I've usually done things is the tag system. In wiki.vim, tags are _individually_ delimited with certain prefixes and/or suffixes (e.g. the default `:`-based tags `:tag:`, or the common hash tags `#tag`). However, the way my current setup handles it is to simply use the first line to write out a comma-separated list of tags. For example, my notes typically take the following structure:

```
tags: tag1, tag2, tag3

# Title

## Heading 1

## Heading 2

...
```

Because I do not require that tags can be placed arbitrarily within the note, it makes tag parsing quite trivial: scan the first line for the `tags: ` prefix, and then simply split the rest of the line by commas and return the resulting list of tags. I find this system to be easier to use too, since I do not have to worry about annotating each individual tag with extra characters. Tags always appear on the first line, and always after the initial `tags: ` prefix.

I am wondering whether this system is compatible with the custom tag parser API that wiki.vim uses. I've never written Vimscript, but from looking through the project documentation it seems the main API is supplying custom regexes for `re_match` and `re_findstart` and a custom function for `make`. From what I gather, this _seems_ like it should be enough for my usecase (basically pretend like the first line is one giant tag and then do the split in `make`) but my Vimscript is quite poor so I thought I'd ask. I'm also wondering whether there would be any issues with this setup for e.g. renaming tags across all pages.

**Comment by lervag** [comment]
> First of all, thank you for creating this plugin. I was previously using a home-grown script to manage a flat directory of markdown files for writing notes, but the better editor integration and additional features that wiki.vim offers have convinced me to make the switch, and so far I am very pleased with it. Great work!

Thanks for the kind words; I'm glad to hear you find wiki.vim useful!

> One aspect of wiki.vim that differs from how I've usually done things is the tag system. In wiki.vim, tags are _individually_ delimited with certain prefixes and/or suffixes (e.g. the default `:`-based tags `:tag:`, or the common hash tags `#tag`). However, the way my current setup handles it is to simply use the first line to write out a comma-separated list of tags. …

I think your system is neat. I like simple things!

I believe you can configure a simple tag parser that should work for your tags. Something like this (I'm assuming you use Vimscript for configuration):

```vim
let s:tag_parser = {
      \ 're_findstart': '\v^tags:\s*(\w*,\s*)*\zs\w+$',
      \}
function! s:tag_parser.match(line) dict abort
  return a:line =~# '^tags:'
endfunction

function! s:tag_parser.parse(line) dict abort
  let l:tagstring = matchstr(a:line, '^tags:\s*\zs.*')
  return split(l:tagstring, ',\s*')
endfunction

function! s:tag_parser.make(taglist, ...) dict abort
  if empty(a:taglist)
    return ''
  endif

  return 'tags: ' . join(a:taglist, ", ")
endfunction

let g:wiki_tag_parsers = [s:tag_parser]
```

I did not test this, so I wouldn't be surprised if there is a bug. Let me know if it works or not, and I'll help you fix the bugs if there are any.

> I am wondering whether this system is compatible with the custom tag parser API that wiki.vim uses. I've never written Vimscript, but from looking through the project documentation it seems the main API is supplying custom regexes for re_match and re_findstart and a custom function for make. From what I gather, this seems like it should be enough for my usecase (basically pretend like the first line is one giant tag and then do the split in make) but my Vimscript is quite poor so I thought I'd ask. I'm also wondering whether there would be any issues with this setup for e.g. renaming tags across all pages.

Yes, I think it should be. Although, it _may_ break if there is a sudden sporadic line in your notes that start with `tags: ...` that is _not_ a tag line. If you should experience something like that, let me know - I'll consider it a bug and will fix it.

**Comment by fmenozzi** [comment]
Oh wow, thanks for implementation. Seems to work great, handles trailing commas, doesn't trigger in the middle of a line or on sporadic `tags: ...` lines. Can match multiple lines at the start, which is probably nice for readability with a large number of tags. Nicely done!

**Comment by lervag** [comment]
> EDIT: should mention that I had `wiki_tag_scan_num_lines` set to 5; setting it to 1 would make it behave like I originally described

Hah, yes, I forgot about that setting. Thus, my comment that it could match sporadically is not so relevant.

> Oh wow, thanks for implementation. Seems to work great, ...

Great, glad to hear it!
