### ISSUE TITLE
WikITocGenerate for more filetypes

### ISSUE THREAD

**Issue by felixschurk** [lervag/wiki.vim#346]
I would like to be able to use the `WikiTocGenerate` function for generation of the TOC for "non-standard" file types, however still following the Markdown syntax.

Currently, when calling the function I do get
`wiki: No TOC support for filetype: vimwiki.wiki!`
which also makes sense. 

Maybe a little background. I use `wiki.vim` for keeping my notes in wiki, as I use taskwarrior for task management I also use [taskwiki](https://github.com/tools-life/taskwiki) as a plugin on vim to handle taskwarrior data. With minor adjustments as in my local repository https://github.com/felixschurk/taskwiki/.
Now in order to have that plugin working as well as the normal wiki I created a custom file type `vimwiki.wiki` which is standard Markdown and also the files are stored as `*.md` files.

I assume that the `WikiTocGenerate` runs over the page and parses `# blabla` in order to generate the TOC, therefore I do think it would also work with a different file type, as the content in the file is still Markdown. 
`WikiToc` is working, and there also the headers are parsed correctly.

**Comment by lervag** [comment]
I've updated how we consider filetypes for the toc system. Please update and see `:help wiki_toc_filetypes`. I believe it may also even "just work" for you now without changing any options, since I changed how it specifies the filetype.

**Comment by felixschurk** [comment]
Thank you a lot. Yes now it does "just work". :)

**Comment by lervag** [comment]
Glad to hear it!
