### ISSUE TITLE
WikiJournalNext / WikiJournalPrev navigate out of journal folder

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#347]
# Description

NOTE: I think it worked before and got broken with some recent update (before 0.9 tag). I heavily rely on the described workflow and I think I would notice it from the start.

I keep journal files in a separate folder and use a custom resolver to navigate to journal (e.g. entry named `[[2024-04-20]]` is for journal)

Here is the file/folder structure

```
vimwiki
|
|-- diary
|      |-- 2024-04-20.adoc
|      |-- 2024-04-19.adoc     EXPECTED
|
|---- 2024-04-19.adoc   ACTUAL
```

1. Navigate to today with `WikiJournal`
2. Do `WikiJournalPrev`, see the message `wiki: Opened new page 'diary/2024-04-19.adoc`
3. The file is actually under `vimwiki`, named `2024-04-19.adoc`, the bindings for `in journal` don't work since we are not in the journal folder

Here are some lines of code from my lua config

```lua
  {
    "lervag/wiki.vim",
    lazy = false,
    init = function(_, opts)
      vim.g.wiki_root = "~/vimwiki"
      vim.g.wiki_write_on_nav = 1
      vim.g.wiki_filetypes = { "adoc", "md" }
      vim.g.wiki_link_creation = {
        adoc = {
          link_type = "wiki",
          url_extension = "",
        },
        _ = {
          link_type = "wiki",
          url_extension = "",
        },
      }
      vim.g.wiki_link_schemes = {
        wiki = {
          resolver = function(url)
            local r = vim.deepcopy(url)
            --print(url)

            r.anchor = vim.fn["wiki#url#utils#extract_anchor"](r.stripped)
            --print(r.anchor)

            local root = vim.fn["wiki#get_root"]()
            --print("root: " .. root)
            local path = vim.fn.split(r.stripped, "#", 1)[1]
            --print("path: " .. path)
            local name = vim.fn.fnamemodify(path, ":t:r")
            --print("name: " .. name)
            if name:match("^%d%d%d%d-%d%d-%d%d$") then
              r.path = root .. "/diary/" .. name .. ".adoc"
            else
              r.path = root .. "/" .. name .. ".adoc"
            end
            --print("r.path: " .. r.path)

            return r
          end,
        },
      }
      vim.g.wiki_link_default_schemes = {
        wiki = {
          adoc = "wiki",
        },
      }
      vim.g.wiki_journal = {
        ["name"] = "diary",
        ["frequency"] = "daily",
        ["date_format"] = {
          ["daily"] = "%Y-%m-%d",
          ["weekly"] = "%Y_w%V",
          ["monthly"] = "%Y_m%m",
        },
      }

      vim.keymap.set("n", "<leader>fp", ":WikiPages<CR>", { silent = true })
      vim.g.wiki_mappings_use_defaults = "global"
      -- file, tags and buffers as supported by fzf
    end,
  },

```

Could you please take a look?

**Comment by lervag** [comment]
> NOTE: I think it worked before and got broken with some recent update (before 0.9 tag).

Do you update often? I.e., do you have any idea at which point in time wiki.vim worked as expected for you?

> 1. Navigate to today with `WikiJournal`
>
> 2. Do `WikiJournalPrev`, see the message `wiki: Opened new page 'diary/2024-04-19.adoc`

The results of the steps are a little bit unclear to me. Can you repeat and give me the output as asked here:

1. `:WikiJournal`
    * What is the output of `:echo expand('%:p')`?
2. `:WikiJournalPrev`
    * What is the output of `:echo expand('%:p')` now?

> 3. The file is actually under `vimwiki`, named `2024-04-19.adoc`, the bindings for `in journal` don't work since we are not in the journal folder

I don't quite understand this. Are you saying that, despite the message "Opened new page 'diary/2024-04-19.adoc'", the page you open is instead at the wiki root?

> Here are some lines of code from my lua config …

You can simplify it somewhat. E.g., you don't need to set what is already default values. Thus, this should be equivalent:

```lua
  {
    "lervag/wiki.vim",
    lazy = false,
    init = function(_, opts)
      vim.g.wiki_root = "~/vimwiki"
      vim.g.wiki_write_on_nav = 1
      vim.g.wiki_filetypes = { "adoc", "md" }
      vim.g.wiki_link_creation = {
        adoc = {
          link_type = "wiki",
          url_extension = "",
        },
      }
      vim.g.wiki_link_schemes = {
        wiki = {
          resolver = function(url)
            local r = vim.deepcopy(url)
            r.anchor = vim.fn["wiki#url#utils#extract_anchor"](r.stripped)

            local root = vim.fn["wiki#get_root"]()
            local path = vim.fn.split(r.stripped, "#", 1)[1]
            local name = vim.fn.fnamemodify(path, ":t:r")
            if name:match("^%d%d%d%d-%d%d-%d%d$") then
              r.path = root .. "/diary/" .. name .. ".adoc"
            else
              r.path = root .. "/" .. name .. ".adoc"
            end

            return r
          end,
        },
      }
      vim.g.wiki_link_default_schemes = {
        wiki = {
          adoc = "wiki",
        },
      }
      vim.g.wiki_journal = {
        name = "diary",
      }

      vim.keymap.set("n", "<leader>fp", ":WikiPages<CR>", { silent = true })
      vim.g.wiki_mappings_use_defaults = "global"
    end,
  },
```

It seems you are using a custom resolver that will recognize iso dates as links to diary entries. Notice that there are two similar mechanisms for that already, built in:

* The `journal:` scheme can be used to create links to diary entries. E.g. `[[journal:2024-04-20]]` will be converted to `[[wiki:/diary/2024-04-20]]`.
* ISO dates are already recognized as links where the journal scheme is used behind the scenes. Thus, the text `2024-04-20` is a link already, you don't need to use the `[[...]]` syntax.

So, I am curious if you may find the default resolver sufficient in combination with one or both of the above points?

**Comment by bybor** [comment]
> :WikiJournal
> 
>     What is the output of :echo expand('%:p')?
> 
/home/lexa/vimwiki/diary/2024-04-20.adoc

>:WikiJournalPrev
>
>     What is the output of :echo expand('%:p') now?
/home/lexa/vimwiki/2024-04-19.adoc


> * The journal: scheme can be used to create links to diary entries. E.g. [[journal:2024-04-20]] will be converted to [[wiki:/diary/2024-04-20]].

The point of my resolver is to avoid using `journal` scheme, but it's a personal preference. Whenever there is `[[2024-12-12]]` and you do `WikiFollowLink` it will go into the diary. It provides me seamless navigation between the journal and root wiki, so that all journal pages are under the separate directory, but only them - every other page is under wiki root.

> * ISO dates are already recognized as links where the journal scheme is used behind the scenes. Thus, the text 2024-04-20 is a link already, you don't need to use the [[...]] syntax.

It works fine, just as you describe, but I want links to stand out visually, hence I'd rather use brackets.

I update my plugins every few days because the LazyVim distro encourages doing so. I guess it's just a usual fear of missing out, and I still don't know if I love it, but my regular configuration that I dragged into Neovim back from Vim days felt slow. It feels a lot snappier now, even with all bells and whistles  :P

I will try the simplified configuration that you suggest, thank you!

I cannot tell for sure how long ago the breaking change happened, but I would be surprised if it happened more than 2 weeks ago - I would notice it. I can go through recent commits and try applying them one by one. Will it help?

**Comment by lervag** [comment]
> > :WikiJournal
> > ```
> > What is the output of :echo expand('%:p')?
> > ```
> 
> /home/lexa/vimwiki/diary/2024-04-20.adoc

Ok, that's as expected.
> 
> > :WikiJournalPrev
> > ```
> > What is the output of :echo expand('%:p') now?
> > ```
> 
> /home/lexa/vimwiki/2024-04-19.adoc

Whereas this is definitely not!

> > * The journal: scheme can be used to create links to diary entries. E.g. [[journal:2024-04-20]] will be converted to [[wiki:/diary/2024-04-20]].
> 
> The point of my resolver is to avoid using `journal` scheme, but it's a personal preference.

Ok, that's fine of course.
> 
> I update my plugins every few days because the LazyVim distro encourages doing so.

Sounds good. I update about once a week.

> I will try the simplified configuration that you suggest, thank you!

No problem!

> I cannot tell for sure how long ago the breaking change happened, but I would be surprised if it happened more than 2 weeks ago - I would notice it. I can go through recent commits and try applying them one by one. Will it help?

Yes, that will help for sure. Since February 12 there has been about 15 commits, so it should not be too hard to check. I would propose that you use `git bisect` for this, though - if you don't know it already, it is a very convenient way to figure out which commit breaks something.

**Comment by bybor** [comment]
I'm sorry, I was wrong, it's not about any `wiki.vim` recent changes, it's about my custom resolver

with this code used for resolver

```

```

**Comment by bybor** [comment]
It's like `name:match("^%d%d%d%d-%d%d-%d%d$")` returns `false` for `2024-04-20` input

**Comment by bybor** [comment]
I figured it out.

My pattern matching code was wrong, it should be `("^%d%d%d%d%-%d%d%-%d%d$")`

It doesn't look like it could ever work even though I would swear it worked just fine. :shrug: 

Thank you very much for you guidance!

**Comment by lervag** [comment]
> My pattern matching code was wrong, it should be `("^%d%d%d%d%-%d%d%-%d%d$")`

Ah, yes! That's a hard-to-catch bug! The `-` is a "magic character" in lua patterns and must of course be escaped! I'm very glad to hear you figured it out, and glad to hear my guidance was useful.
