### ISSUE TITLE
WikiExport: Why does pandoc's input filename include ".tmp"?

### ISSUE THREAD

**Issue by VimWei** [lervag/wiki.vim#351]
# Description

There's a wiki page under g:wiki_root/test.md

```
# test
This is a test markdown page.
```

Similar to `:WikiExport test.pdf` , an error occurs after executing `:WikiExport test.html` .

```
wiki: Something went wrong when running cmd:
  pandoc  -f markdown -o 'test.html' 'D:/WeirdData/wiki/test.md.tmp'
  Shell output:
  [WARNING] Could not deduce format from file extension .html'

  Defaulting to html

pandoc: 'D:/WeirdData/wiki/test.md.tmp': openBinaryFile: invalid argument (Invalid argument)
wiki: Page was exported to test.html
```

Why does pandoc's input filename include ".tmp"?

## Comparison: Custom pandoc conversion command

This is my custom function: https://github.com/VimWei/vim-init/blob/master/autoload/Pandoc.vim

The successful execution of the following commands confirms that my pandoc and MiKTeX installations are correct.

```
command! PandocToPDF call Pandoc#ToPdf()
command! PandocToDOCX call Pandoc#ToDocx()
command! PandocToHTML call Pandoc#ToHtml()
```

# Environment

- Windows 10 Pro 22H2
- gvim_9.1.0363_x64_signed.exe

**Comment by lervag** [comment]
> Similar to `:WikiExport test.pdf` , an error occurs after executing `:WikiExport test.html` .

Do you mean that there is an error for both of the commands, or only one of them?

On my system, both of those work well.

> Why does pandoc's input filename include ".tmp"?

We're applying some minor clean up and adjustments before running pandoc. These are written to `ORIGFILENAME.tmp` and the temporary file is removed afterwards.

See the code, here:

https://github.com/lervag/wiki.vim/blob/8f28b6c7b1ca6e6ee8aff4095ea32c450ea764f2/autoload/wiki/page.vim#L416-L428

In your case, this fails for a currently unknown reason. What is the content of the `.tmp` file? I believe it is not deleted if the command fails to execute.

I would expect the content to be identical.

**Comment by lervag** [comment]
To be more specific, the `.tmp` file is the original file where wiki style links are replaced with regular text.

**Comment by VimWei** [comment]
> Do you mean that there is an error for both of the commands, or only one of them?

there is an error for both of the commands

**Comment by lervag** [comment]
Ok, then, what is the output of running `pandoc  -f markdown -o 'test.html' 'D:/WeirdData/wiki/test.md.tmp'` in a terminal?

**Comment by VimWei** [comment]
```
C:\Users\chenw>pandoc -f markdown -o 'test.html' 'D:/WeirdData/wiki/test.md.tmp'
[WARNING] Could not deduce format from file extension .html'
  Defaulting to html
pandoc: 'D:/WeirdData/wiki/test.md.tmp': openBinaryFile: invalid argument (Invalid argument)
```

**Comment by lervag** [comment]
How about `pandoc  -f markdown -o 'test.html' 'D:/WeirdData/wiki/test.md'`?

Notice, this sort of proves that the problem is not really related to wiki.vim already?

**Comment by lervag** [comment]
Which version of pandoc do you have?

**Comment by VimWei** [comment]
I've found the issue: on Windows, we need to use "" instead of ''.

`pandoc  -f markdown -o "test.html" "D:/WeirdData/wiki/test.md.tmp"`

**Comment by VimWei** [comment]
> Which version of pandoc do you have?

```
C:\Users\chenw>pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: C:\Users\chenw\AppData\Roaming\pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by lervag** [comment]
> I've found the issue: on Windows, we need to use "" instead of ''.
> 
> This is OK: `pandoc -f markdown -o "test.html" "D:/WeirdData/wiki/test.md.tmp"`

Ah, ok. I guess it doesn't hurt to just change this to `"..."`, as that should still work on Linux and MacOS as well.

Notice that there is now pandoc version 3.1.13, so you might consider updating. But it shouldn't matter for the present issue.

**Comment by lervag** [comment]
Hmm. The `shellescape()` function, which I'm using, is supposed to use the appropriate quotes for the system. See `:help shellescape()`.  It seems you have `shellslash` enabled?

**Comment by VimWei** [comment]
I've  enabled shellslash

**Comment by lervag** [comment]
Ok; I've pushed a fix for this - please update and test.

**Comment by VimWei** [comment]
Update.
Restart gVim.
`:WikiExport test.html`


```
Error detected while processing function Redir#redir[11]..wiki#page#export[59]..<SNR>138_export[16]..wiki#u#shellescape:
line   10:
E121: Undefined variable: a:cmd
E116: Invalid arguments for function shellescape(a:cmd), '\')
E116: Invalid arguments for function escape(shellescape(a:cmd), '\')
E121: Undefined variable: a:cmd
E116: Invalid arguments for function shellescape(a:cmd), '\')
E116: Invalid arguments for function escape(shellescape(a:cmd), '\')
```

**Comment by VimWei** [comment]
> I've enabled shellslash

```
function! ToggleShellslashForVimPlug()
  if exists('g:plugs')
    autocmd User PlugBegin set noshellslash
    autocmd User PlugEnd set shellslash
  endif
endfunction

set noshellslash

call plug#begin()
........
call plug#end()

set shellslash
call ToggleShellslashForVimPlug()

```

**Comment by lervag** [comment]
Sorry, my mistake. Update again and try one more time.

**Comment by VimWei** [comment]
The test passed this time, thank you for your prompt fix!

**Comment by VimWei** [comment]
The test passed this time, thank you for your prompt fix!

**Comment by lervag** [comment]
Great, glad to hear it works!
