### ISSUE TITLE
Using custom resolver breaks WikiJournalNext/WikiJournalPrev

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#356]
# Description

I'm using a custom resolver in my config, and I found that it somehow breaks journal navigation for me.

What happens:

1. `WikiJournal` to navigate to `2024-05-15`
2. `WikiJournalPrev` to navigate to `2024-05-14`
3. In  `2024-05-14` there are no "journal" commands available except `WikiJournal` and `WikiJournalIndex`

It works as expected if I comment out this node from the configuration (this node includes a resolver function)

```lua
     vim.g.wiki_link_schemes = {
        wiki = { ... }
     }
```

Here is my config

```lua
  {
    "lervag/wiki.vim",
    lazy = false,
    init = function(_, opts)
      vim.g.wiki_root = "~/vimwiki"
      vim.g.wiki_write_on_nav = 1
      vim.g.wiki_filetypes = { "adoc", "md" }
      vim.g.wiki_link_creation = {
        adoc = {
          link_type = "wiki",
          url_extension = "",
        },
        _ = {
          link_type = "wiki",
          url_extension = "",
        },
      }
      vim.g.wiki_link_schemes = {
        wiki = {
          resolver = function(url)
            local r = vim.deepcopy(url)
            --print(url)

            r.anchor = vim.fn["wiki#url#utils#extract_anchor"](r.stripped)
            --print(r.anchor)

            local root = vim.fn["wiki#get_root"]()
            --print("root: " .. root)
            local path = vim.fn.split(r.stripped, "#", 1)[1]
            --print("path: " .. path)
            local name = vim.fn.fnamemodify(path, ":t:r")
            --print("name: " .. name)
            if name:match("^%d%d%d%d%-%d%d%-%d%d$") then
              r.path = root .. "/diary/" .. name .. ".adoc"
            else
              r.path = root .. "/" .. name .. ".adoc"
            end
            --print("r.path: " .. r.path)

            return r
          end,
        },
      }
      vim.g.wiki_link_default_schemes = {
        wiki = {
          adoc = "wiki",
        },
      }
      vim.g.wiki_journal = {
        name = "diary",
      }

      vim.keymap.set("n", "<leader>fp", ":WikiPages<CR>", { silent = true })
      vim.g.wiki_mappings_use_defaults = "global"
      -- file, tags and buffers as supported by fzf
      vim.g.wiki_mappings_local = {
        ["<Plug>(wiki-link-follow)"] = "<Leader>wf",
        ["<Plug>(wiki-link-follow-split)"] = "<Leader>we",
        ["<Plug>(wiki-page-rename)"] = "<Leader>wr",
        ["<Plug>(wiki-journal-next)"] = "<Leader>dn",
        ["<Plug>(wiki-journal-prev)"] = "<Leader>dp",
        ["<Plug>(wiki-link-return)"] = "<Leader>wb",
        ["<Plug>(wiki-link-next)"] = "<Leader>wn",
        ["<Plug>(wiki-link-prev)"] = "<Leader>wp",
      }
    end,
  },
```

Could you please take a look?

**Comment by lervag** [comment]
> I'm using a custom resolver in my config, and I found that it somehow breaks journal navigation for me.

That's strange. I tried to reproduce with your config; I created `test.lua` with this content:

```lua
vim.opt.runtimepath:prepend "~/.local/plugged/wiki.vim"
vim.cmd [[filetype plugin indent on]]
vim.cmd [[syntax enable]]

vim.keymap.set("n", "q", "<cmd>qall!<cr>")

vim.g.wiki_root = vim.fn.fnamemodify("wiki", ':p')
vim.g.wiki_cache_root = "."
vim.g.wiki_cache_persistent = false

vim.g.wiki_write_on_nav = 1
vim.g.wiki_filetypes = { "adoc", "md" }
vim.g.wiki_link_creation = {
  adoc = {
    link_type = "wiki",
    url_extension = "",
  },
  _ = {
    link_type = "wiki",
    url_extension = "",
  },
}
vim.g.wiki_link_schemes = {
  wiki = {
    resolver = function(url)
      local r = vim.deepcopy(url)

      r.anchor = vim.fn["wiki#url#utils#extract_anchor"](r.stripped)

      local root = vim.fn["wiki#get_root"]()
      local path = vim.fn.split(r.stripped, "#", 1)[1]
      local name = vim.fn.fnamemodify(path, ":t:r")
      if name:match("^%d%d%d%d%-%d%d%-%d%d$") then
        r.path = root .. "/diary/" .. name .. ".adoc"
      else
        r.path = root .. "/" .. name .. ".adoc"
      end

      return r
    end,
  },
}
vim.g.wiki_link_default_schemes = {
  wiki = {
    adoc = "wiki",
  },
}
vim.g.wiki_journal = {
  name = "diary",
}

vim.cmd [[runtime plugin/wiki.vim]]
vim.cmd [[WikiJournal]]
```

Then in the same test directory, I created the `wiki` and `wiki/diary` directories with `mkdir -p wiki/diary`. Also, I created some entries with `touch wiki/diary/2024-05-{10..20}.adoc`.

Now. when I run `nvim --clean -u test.lua`, I'm brought to todays entry. Navigation works as expected on my end.

> What happens:
> 
> 1. `WikiJournal` to navigate to `2024-05-15`
> 
> 2. `WikiJournalPrev` to navigate to `2024-05-14`
> 
> 3. In  `2024-05-14` there are no "journal" commands available except `WikiJournal` and `WikiJournalIndex`

I could not reproduce your problem with these steps when I started with the minimal config file.

Could you see if you can reproduce the problem with a similar minimal test file that you start with `nvim --clean -u test.lua`?

**Comment by bybor** [comment]
Thank you very much for your feedback and the `test.lua` file that you provide - I always struggled with creating test `vimrc` files and I didn't even know how to create a `lua` one.

1. I still can reproduce the issue with `test.lua`, with reported behavior. I should have mentioned that it happens under Windows
2. While testing I found that it works fine under Linux with my own configuration

So, it looks like the code that activates `journal` commands checks that it's inside the journal and it fails under Windows after navigating. 

I recalled about `shellslash` and tried setting it and it fixed the issue for me. Now, I would rather not use it :(  

1) In the past it broke something for me, but it's not a show stopper at the moment
2) I'm sharing the same config between linux and windows, and I need to figure out how to have it enabled for Windows only

Do you think it's possible to fix in `wiki.vim`? 

Thank you!

**Comment by lervag** [comment]
> Thank you very much for your feedback and the `test.lua` file that you provide - I always struggled with creating test `vimrc` files and I didn't even know how to create a `lua` one.

Glad to hear it helps! Also, understandable that these things are hard. I've started to aquire some experience with these things now... :)

> So, it looks like the code that activates `journal` commands checks that it's inside the journal and it fails under Windows after navigating.
> 
> I recalled about `shellslash` and tried setting it and it fixed the issue for me. Now, I would rather not use it :(

Ah, that seems like a plausible explanation here. It's slightly hard to fully solve this on my own, since I don't work in a Windows environment.

> Do you think it's possible to fix in `wiki.vim`?

Yes, definitely, but I hope you are willing to assist with fixing it. There is a slight chance that I will find the problem fast, but if not, then I would have to ask you to debug things for me, e.g. by adding `:echom ...` stuff around the code and reporting the output. If you're up for it, I think we should be able to fix it relatively fast.

**Comment by bybor** [comment]
> If you're up for it

I'm all for it, just let me know what to do.

**Comment by bybor** [comment]
I think it may help, with `vim.g.wiki_link_schemes = {` commented out and `noshellslash` the diary navigation works as expected.

**Comment by bybor** [comment]
The version from the bottom of your message didn't fix the issue. It has a typo - line 9 has `name` while it should probably be `wiki_path` , so I tested the version with `wiki_path`.

Here is the output of version with `print`s and `noshellslash` (WikiJournalPrev successfully navigated only once)

```
{
  anchor = "",
  origin = "C:\\Users\\Alex\\vimwiki\\diary\\2024-05-17.adoc",
  path = "C:\\Users\\Alex\\vimwiki/diary/2024-05-16.adoc",
  scheme = "wiki",
  stripped = "/diary/2024-05-16.adoc",
  url = "wiki:/diary/2024-05-16.adoc"
}
```

And with `shellslash`

```
{
  anchor = "",
  origin = "C:/Users/Alex/vimwiki/diary/2024-05-17.adoc",
  path = "C:/Users/Alex/vimwiki/diary/2024-05-16.adoc",
  scheme = "wiki",
  stripped = "/diary/2024-05-16.adoc",
  url = "wiki:/diary/2024-05-16.adoc"
}
```

Thank you!

**Comment by lervag** [comment]
> The version from the bottom of your message didn't fix the issue. It has a typo - line 9 has `name` while it should probably be `wiki_path` , so I tested the version with `wiki_path`.

Yes, there was a minor error. I've fixed it. Notice that the pattern should also be updated!

> Here is the output of version with `print`s and `noshellslash` (WikiJournalPrev successfully navigated only once) …

Thanks, this does verify my hypothesis.

Does it work now with the updated script?

**Comment by bybor** [comment]
Yes, it works fine. Thank you very much!

**Comment by lervag** [comment]
Great, I'm happy to hear that!
