### ISSUE TITLE
Enhancement request for WikiJournalIndex: reverse order and update

### ISSUE THREAD

**Issue by VimWei** [lervag/wiki.vim#363]
## Background

I often need to review my latest journals, and currently, I primarily use the following two methods to achieve this:

* Method 1: Use WikiJournalIndex to output the Journal Index, and then jump to the end of the Journal Index (i.e., the newest part) to select and browse.
* Method 2: Open today's Journal with `<leader>w<leader>w` and browse through the entries using `<plug>(wiki-journal-prev)` and `<plug>(wiki-journal-next)`.

However, both methods have some inconvenient aspects:

* Method 1: (1) To update the Index, I need to manually delete the old one and then use WikiJournalIndex to output the latest one, which requires two steps. (2) The Journals are organized chronologically with the oldest journal at the top, but I often need to review recent journals, so I always have to jump to the end of the document to consult them.
* Method 2: Sometimes `<plug>(wiki-journal-prev)` and `<plug>(wiki-journal-next)` malfunction, and I have not found the specific reason for the failure. Although most of the time they work, when they don't, I need to keep switching to the wiki index page and then back to today's journal to regain functionality.

## Request

I hope that the WikiJournalIndex can be upgraded to (Prioritize expectations from high to low):

1.  Provide an option for reverse ordering.
2.  Open Journal index file: `<leader>wi`
3.  One-step update Wiki Journal Index.

**Comment by lervag** [comment]
I added a reverse option to `g:wiki_journal_index`; would be happy to hear if it works and if it adequately solves your issue.

**Comment by VimWei** [comment]
Cool, thanks!

**Comment by lervag** [comment]
Great, glad to hear it!
