### ISSUE TITLE
Is it possible for wiki-link-types to support jumping to Vim help?

### ISSUE THREAD

**Issue by VimWei** [lervag/wiki.vim#364]
The Vim ecosystem is vast, and I often need to consult the Vim help documentation for various topics. I've made quite a few wiki notes, and while I can search for the keywords mentioned in these notes using `:h subject`, it always feels like it would be much more convenient if the wiki-link-types supported a format like `|vim help subject|` or something similar. With this feature, recognizing and using wiki links with a simple press of the Enter key would enable direct jumping to the help content.

PS: I have configured the Vim help document type to be accessed in a way that mimics the wiki approach.

```vim
" Jump
nnoremap <buffer> <CR> <C-]>
nnoremap <buffer> <BS> <C-T>

" Lookup |label| using <Tab>/<S-Tab>
nnoremap <buffer> <Tab> /<Bar>\zs\k*\ze<Bar><CR>:noh<CR>
nnoremap <buffer> <S-Tab> ?<Bar>\zs\k*\ze<Bar><CR>:noh<CR>
```

**Comment by lervag** [comment]
You can use the `vimdoc` scheme, e.g. `vimdoc:user-manual`.

I notice that I've added support for a few things, such as this, that I forgot to document. I'll keep this issue open until I've documented it.

**Comment by lervag** [comment]
`<plug>(wiki-link-return)` will not work here, because we end up in a non-wiki file. But the other mappings _should_ work. Are you sure they don't work?

**Comment by lervag** [comment]
Can confirm that the other `wiki-link-follow-...` does not work as expected. I'll look into it.

**Comment by lervag** [comment]
I think the follow maps should work now, please update.

**Comment by VimWei** [comment]
After updating, the following key mappings now work! Thank you!

```
  `n`     <c-w><cr>           |<plug>(wiki-link-follow-split)|
  `n`     <c-w><tab>          |<plug>(wiki-link-follow-vsplit)|
  `n`     <c-w>u              |<plug>(wiki-link-follow-tab)|
```

**Comment by lervag** [comment]
No problem; glad to hear it works.
