### ISSUE TITLE
Infinite loop on template rendering if function starts at index 0 in template file

### ISSUE THREAD

**Issue by anjiro** [lervag/wiki.vim#367]
# Description

If a template file starts with a user-defined function, then the template rendering code loops forever. I believe the problem is [this line in template.vim](https://github.com/lervag/wiki.vim/blob/5943633f66d8c50834baebd0354d8248df171be6/autoload/wiki/template.vim#L90), which, if `matchstrpos()` has returned a start position of 0 into `l:c1`, sets `l:pre` to the entire template file. I don't have time to test a fix, so please forgive the bug report in place of a pull request.

**Comment by lervag** [comment]
Thanks, it should be fixed now.
