### ISSUE TITLE
HTML text objects are overwritten by text objects for link texts

### ISSUE THREAD

**Issue by A-dot-S-dot** [lervag/wiki.vim#368]
Thank you for your Plugin I enjoy it very much. 

I'd like to use the built in text object `it` and `at` for hmtl tags. However, these are overwritten by `wiki-at` and `wiki-it`. Could you add a variable to disable them gloabally or map them to another binding? 

Thanks in advance!

**Comment by lervag** [comment]
> Thank you for your Plugin I enjoy it very much.

Thanks, glad to hear you enjoy it!

> I'd like to use the built in text object `it` and `at` for hmtl tags. However, these are overwritten by `wiki-at` and `wiki-it`. Could you add a variable to disable them gloabally or map them to another binding?

You can disable or change it like this:

```vim
" disable
let g:wiki_mappings_local = {
      \ 'o_<plug>(wiki-it)': '',
      \ 'x_<plug>(wiki-it)': '',
      \ 'o_<plug>(wiki-at)': '',
      \ 'x_<plug>(wiki-at)': '',
      \}

" use different map (e.g. d for description)
let g:wiki_mappings_local = {
      \ 'o_<plug>(wiki-it)': 'id',
      \ 'x_<plug>(wiki-it)': 'id',
      \ 'o_<plug>(wiki-at)': 'ad',
      \ 'x_<plug>(wiki-at)': 'ad',
      \}
```

See `:help wiki_mappings_local`.

**Comment by A-dot-S-dot** [comment]
Thank you very much!

**Comment by lervag** [comment]
My pleasure :)
