### ISSUE TITLE
Help to decide between using .md or .wiki extension

### ISSUE THREAD

**Issue by skervim** [lervag/wiki.vim#37]
Thank you very much for this awesome plugin! 

I would like to know which benefits there are for using the `.wiki` extension over using markdown files (`.md`).

I thought about using markdown files, because it is the standard that I see everywhere and I am familiar with. 

Why is the default file type `wiki` and which advantages will I miss if I change it to `markdown`?

**Comment by lervag** [comment]
> Thank you very much for this awesome plugin!

Thanks!, and you're welcome :)

> which benefits there are for using the .wiki extension over using markdown files (.md).

None, really. It's mostly historical. It all started with Vimwiki, which defines its own filetype (wiki files). I forked and tried to separate features to make things more clean and lean. After some time, I realized that there should be no filetype plugin. The wiki features are only loosely connected to the filetype. However, my own personal wiki uses the wiki extension, and so I never bothered to change this in `wiki.vim`. But it should work equally well with Markdown files. Relevant options:

- `g:wiki_filetypes`
- `g:wiki_link_target_types` (see `:h wiki-links` for the styles; you can use both `wiki` and `markdown` as a relevant setting here)

So: you should feel very free to just continue using markdown files. You should not miss any features by doing it.
