### ISSUE TITLE
Add completion source for `:WikiOpen`

### ISSUE THREAD

**Issue by savq** [lervag/wiki.vim#372]
It'd be really useful if `:WikiOpen` had a `-complete` source that allowed it to complete existing paths in the wiki.

**Comment by lervag** [comment]
Thanks, I agree and I've added it now. Please test and let me know what you think.

Also, sorry for the long wait - it's been vacation time and a lot has happened in my life. :\

**Comment by savq** [comment]
It's working pretty well. It seems limited by the fact that `wildoptions+=fuzzy` doesn't work for file paths, but I guess that's on me for not using a fuzzy finder in the first place...

Np for the wait. The code will still be there after a break. Take care.

**Comment by lervag** [comment]
> It's working pretty well. It seems limited by the fact that `wildoptions+=fuzzy` doesn't work for file paths, but I guess that's on me for not using a fuzzy finder in the first place...

In fact, this behaviour depends on how we add the completion mechanism. See `:help command-completion-custom`; the relevant snippet is here:

```
The function may use these for determining context.  For the "custom"
argument, it is not necessary to filter candidates against the (implicit
pattern in) ArgLead.  Vim will filter the candidates with its regexp engine
after function return, and this is probably more efficient in most cases. If
'wildoptions' contains "fuzzy", then the candidates will be filtered using
|fuzzy-matching|.  For the "customlist" argument, Vim will not
filter the returned completion candidates and the user supplied function
should filter the candidates.
```

I found it was much easier to use `customlist`. I tried to use the `custom` argument, but it ended up being much slower. Perhaps there's a way to make it fast, not sure.

> Np for the wait. The code will still be there after a break. Take care.

Thanks!
