### ISSUE TITLE
Delay in `<leader>wgb` or fetching backlinks after `<leader>wr` or file rename

### ISSUE THREAD

**Issue by diskfault** [lervag/wiki.vim#374]
# Description

Following from #373, specifically the comment [here](https://github.com/lervag/wiki.vim/issues/373#issuecomment-2266724804).

## Steps leading to issue

1.1. File `/folder_a/index.md` links (via `markdown`) to `/folder_a/a1.md` (filenames only hereafter, for brevity)
1.2. `nvim a1.md`

From within `a1.md`;

2.1. Rename; `<leader>wr` to `foo.md`
2.2. `wiki: Updated 1 links in 1 file`
2.3. **`<leader>wgb`; `wiki: No other file links to this file`**
2.4. Rename; `<leader>wr` to `bar.md`
2.5. `wiki: Updated 1 links in 1 file`
2.6. **`<leader>wgb`; `wiki: No other file links to this file`**
2.7. Check `/folder_a/index.md` for link; links correctly to `bar.md`
2.8. (after some time) `<leader>wgb` shows backlinks correctly

## Expected behaviour

Steps 2.3 and 2.6 state (erroneously) that there is no link to this file. This is due to [how the graphing works](https://github.com/lervag/wiki.vim/issues/373#issuecomment-2266788819) and will correct after some time but is potentially confusing to users unfamiliar with this behaviour, or otherwise not ideal as it pertains to speed of use.

# Minimal working example

Folder structure;

```
/path/to/minimal-working-example-wiki
├── index.md
├── folder_a
│   └── index.md
│   └── a1.md
└── test.md
```

`init.vim`;

```vim
call plug#begin()

" for goyo
Plug 'vim-voom/VOoM'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'

" for writing
Plug 'kana/vim-textobj-user'
Plug 'preservim/vim-pencil'
Plug 'preservim/vim-textobj-quote'
Plug 'preservim/vim-textobj-sentence'
Plug 'preservim/vim-wordchipper'

" for text highlighting
Plug 'inkarkat/vim-mark'
Plug 'inkarkat/vim-ingo-library'

" for formatting
Plug 'lervag/lists.vim'
Plug 'dhruvasagar/vim-table-mode'

" for markdown
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'

" for wiki
Plug 'lervag/wiki.vim'

" for telescope
Plug 'nvim-telescope/telescope.nvim' ", { 'tag': '0.1.8' }
Plug 'nvim-lua/plenary.nvim'
Plug 'BurntSushi/ripgrep'
Plug 'nvim-telescope/telescope-fzf-native.nvim'
Plug 'nvim-treesitter/nvim-treesitter'

" for colour scheme
Plug 'https://git.sr.ht/~leon_plickat/paige'

call plug#end()

" for colours
:colorscheme pablo

set termguicolors

" for writing
let g:pencil#wrapModeDefault = 'soft'

augroup pencil
	autocmd!
	autocmd FileType markdown,mkd	call pencil#init()
	autocmd FileType text		call pencil#init({'wrap': 'hard'})
augroup END

augroup textobj_quote
	autocmd!
	autocmd FileType markdown call textobj#quote#init()
augroup END

" for markdown
set conceallevel=2
let g:pandoc#syntax#conceal#urls = 1
 
" for wiki
let g:wiki_root = '~/wiki/doc/pages'

let g:wiki_link_creation = {
			\ 'md': {
			\	'link_type': 'md',
			\	'url_extension': '',
			\	'url_transform': { x ->
			\		substitute(tolower(x), '\s\+', '-', 'g')},
			\ }
			\}
```

**Comment by lervag** [comment]
Thanks! I reproduced it and I think I've fixed it. Let me know if it works for you.
