### ISSUE TITLE
Suggestion: Enabling closing parenthesis in `markdown` link

### ISSUE THREAD

**Issue by diskfault** [lervag/wiki.vim#375]
# Description

As per #164, markdown (or parsing markdown with regex) poses a problem whereby the link *itself* contains a closing bracket or parenthesis. Hence, as per this [comment](https://github.com/lervag/wiki.vim/issues/164#issuecomment-869661567);

```
1. Here is a [link to a file with parens](file (parens)).
2. Here is a ([link to a file _inside_ parens](another file)).
``` 

The standard process across the web (and elsewhere) is to use ASCII encoding (my apologies if this has already been considered). Hence; `http://en.wikipedia.org/wiki/Syntax_%28programming_languages%29` renders as `http://en.wikipedia.org/wiki/Syntax_(programming_languages)`.

# Suggestion

Perhaps if the user wishes to include parentheses, the plugin allows one to encode the link similarly and so hence; `[link](file:path/to/my/%28paren%29/file.md)` resolves to `[link](file:path/to/my/(paren)/file.md)`. In that way, I believe the regex to capture this is thus; `/%28.*%29/gm`.

# Potential issues

This does, of course, require some more editing on the part of the user, and so may fall out of the scope or intention of this plugin. Additionally there is the (perhaps unlikely) scenario that one may *literally* wish to include the encoded value from the character-set which would mangle the URI were this to be implemented.

Perhaps to mitigate this, allow the user to later define their own encoding character-set (using the de facto [standard](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding) URL encoding set as default)?

**Comment by lervag** [comment]
I _believe_ this is addressed in one of the advanced configuration examples. Please see `:help wiki-advanced-config-2`. I'm trying to write docs that are understandable, so I hope it's OK if I'll leave it at that with the first go - but please, let me know if it is confusing or if you think this should be further improved somehow!
