### ISSUE TITLE
TOC generation does not work properly when document headers have parens

### ISSUE THREAD

**Issue by fmenozzi** [lervag/wiki.vim#383]
# Description

When calling `:WikiTocGenerate` on a document whose header has parens, the parens are not URL-encoded and thus conflict with the markdown link syntax `[]()`.

# Minimal working example

Suppose you have a document like so:

```
# Title (with parens)

## Heading

## Another Heading
```

Calling `:WikiTocGenerate` will produce the following TOC:

```
Contents:
* [Title (with parens)](#Title (with parens))
    * [Heading](#Title (with parens)#Heading)
    * [Another Heading](#Title (with parens)#Another Heading)

# Title (with parens)

## Heading

## Another Heading
```

These links produced in the TOC will not work when using `Enter` to try and follow them.

I believe the solution would simply be to URL-encode `(` and `)` in header names when generating the TOC.

**Comment by lervag** [comment]
Thanks. I agree that this example should preferably "just work". Right now, you will need to customize the url handler, see e.g. `:help wiki-advanced-config-2` for an example of how to do it. The example is not precisely what you want here, though.

I'll look into it and see if I can find a simple, viable solution for the default behaviour. I think I should also add a builtin transformer and resolver that is more "in line" with standard Markdown expected behaviour.

**Comment by lervag** [comment]
Sorry for the long delay here!

I believe I've implemented what you want now. `:WikiTocGenerate` should now apply URL encoding for parantheses and the URLs will be decoded when the are resolved.

**Comment by fmenozzi** [comment]
Hey @lervag, thanks for looking into this. Unfortunately it doesn't appear that the original issue has been resolved. If I use the same minimal working example as before, calling `:WikiTocGenerate` producing a table of contents whose links are still unnavigable using `Enter`. Specifically, 

```
# Title (with parens)

## Heading

## Another Heading
```

becomes

```
*Contents*
* [Title (with parens)](#title-(with-parens))
    * [Heading](#title-(with-parens)#heading)
    * [Another Heading](#title-(with-parens)#another-heading)

# Title (with parens)

## Heading

## Another Heading
```

It does not appear that the generated ToC links were URL-encoded.

**Comment by lervag** [comment]
Can you show me your wiki.vim configuration?

**Comment by fmenozzi** [comment]
```
Plug 'lervag/wiki.vim'

let g:wiki_root = '~/documents/notes'

nmap <leader>wf :WikiPages<cr>
nmap <leader>wt :WikiTags<cr>
nmap <leader>wc :WikiToc<cr>

" When creating links from text under the cursor, convert to lowercase and
" replace spaces with dashes.
let g:wiki_link_creation = {
            \ 'md': {
            \   'link_type': 'md',
            \   'url_extension': '.md',
            \   'url_transform': { x ->
            \       substitute(tolower(x), '\s\+', '-', 'g') },
            \ },
            \}

" Use fzf for searching pages, tags, etc., with nice markdown previews.
let g:wiki_select_method = {
            \ 'pages': function('wiki#fzf#pages'),
            \ 'tags': function('wiki#fzf#tags'),
            \ 'toc': function('wiki#fzf#toc'),
            \ 'links': function('wiki#fzf#links'),
            \}
let g:wiki_fzf_pages_opts = '--preview "mdcat {1}" --preview-window="up"'
let g:wiki_fzf_tags_opts = '--preview "mdcat {2..}" --preview-window="up"'

" Use custom tag parser to recognize tags on the first line in the form
" tags: tag1, tag2, tag3...
let g:wiki_tag_scan_num_lines = 1
let s:tag_parser = {
      \ 're_findstart': '\v^tags:\s*(\w*,\s*)*\zs\w+$',
      \}
function! s:tag_parser.match(line) dict abort
  return a:line =~# '^tags:'
endfunction
function! s:tag_parser.parse(line) dict abort
  let l:tagstring = matchstr(a:line, '^tags:\s*\zs.*')
  return split(l:tagstring, ',\s*')
endfunction
function! s:tag_parser.make(taglist, ...) dict abort
  if empty(a:taglist)
    return ''
  endif
  return 'tags: ' . join(a:taglist, ", ")
endfunction
let g:wiki_tag_parsers = [s:tag_parser]
```
Looking at it now, perhaps my overwriting `g:wiki_link_creation` is the problem? My guess is that I need to incorporate some kind of URL-encoding in the `url_transform` function. I think I took this example from the docs so I forgot that I had even made this change.

**Comment by lervag** [comment]
> Looking at it now, perhaps my overwriting `g:wiki_link_creation` is the problem? My guess is that I need to incorporate some kind of URL-encoding in the `url_transform` function. I think I took this example from the docs so I forgot that I had even made this change.

Yes, precisely. You can try to just remove it at first. And if you find you want more adjustment to the transforms I can help you make that.

Notice that you don't have to include the `link_type` and `url_extension`, since these are not changed from the default value.

**Comment by fmenozzi** [comment]
Sounds good. Thanks again for implementing this feature!

**Comment by lervag** [comment]
@artkpv Could you please open a new issue for this? I won't have time to look at it immediately, so it would help a lot to have a fresh issue when I start looking - that way I don't have to spend time reading a long issue thread for context.

**Comment by artkpv** [comment]
https://github.com/lervag/wiki.vim/issues/395#issue-2757600281
