### ISSUE TITLE
Markdown: make links with spaces handling as per these standards 

### ISSUE THREAD

**Issue by artkpv** [lervag/wiki.vim#386]
# Description

I find the way wiki.vim handles spaces in links confusing as it is clearly diverge from the standards: https://spec.commonmark.org/0.31.2/#links , https://github.github.com/gfm/#links, other. I mean that these are implemented by other apps:
- vim.markdown, https://github.com/preservim/vim-markdown/blob/master/doc/vim-markdown.txt#L236
- https://github.com/simov/markdown-viewer
- https://github.com/gsantner/markor
- others

Why not implement in wiki.vim? 

Current behavior. A link `[How to calculate contra amount](<How to calculate contra amount.md>)` opens into `<How to calculate contra amount.md>.md` file. 

Expected behavior. A link `[How to calculate contra amount](<How to calculate contra amount.md>)` opens into `How to calculate contra amount.md`. 

Similarly for all other functionality: graph, tags, etc.

I guess, this should break current behavior that treats spaces inside link as a valid, i.e. `[My link here](my page with spaces.md)`, but without < and > as an invalid link. I don't know exactly why those standards include this requirement.  

# Minimal working example

See above

**Comment by artkpv** [comment]
Refs https://github.com/lervag/wiki.vim/issues/199

**Comment by lervag** [comment]
First, I'm very sorry for the late reply! It's been a very busy autumn and I've simply not been able to follow up as much as I want to.

Now, you are correct that I've not implemented the links perfectly according to specs.

I don't think I want to make any big breaking changes, so I don't want to make changes that make the link handling more strict unless it is clearly "necessary". But in this case, it seems you are addressing a specific point where the default behaviour of wiki.vim does not handle a link with a url that is according to the specs.

For instance, the following files has a couple of links that one would expect to work in wiki.vim by default. Only one of them will work, though:

```markdown
!!! foo.md
# Foo title

[Link to bar](<bar.md>)
[Another link to bar][bar]


[bar]: <bar.md>

!!! bar.md
# Bar title

[Link to foo](foo.md)
```

So, I propose to update wiki.vim to handle the `<...>` syntax for the url part of Markdown links. I assume it is the same for reference style links, so I'll make sure that one works as well.

I would be happy if you could confirm my understanding of the issue. Let me know if I missed something or if you think my suggested solution is somehow wrong.

**Comment by lervag** [comment]
I think a very simple solution that would "just work" is to strip the `<` and `>` from the URL when a link is first parsed, i.e. here:

https://github.com/lervag/wiki.vim/blob/969aecfd794f643960a4c83e195454b9d6f92159/autoload/wiki/link/class.vim#L11-L16

I'm trying to think of why it might _not_ be a good idea... I'll think about it for a day or two before committing to it.

**Comment by step-** [comment]
I can't think of too many reasons why stripping the angular brackets would be a bad idea but you are right to ponder.
Some things to keep in mind...

In CommonMark the `<`...`>` link syntax introduces an autolink, see the [spec](https://spec.commonmark.org/0.31.2/#autolinks).
Autolinks require absolute URIs, otherwise they angular brackets are to be treated as regular text.
However, angular brackets in reference link definitions can be stripped. Here's an experiment, and its sanctioned CommomMark
[outcome](<https://spec.commonmark.org/dingus/?text=%3Chttp%3A%2F%2Fexample.com%3E%20%23%20autolink%0A%0A%3Cthis.md%3E%20%20%23%20regular%20text%0A%0A%3Cthis%20file.md%3E%20%23%20raw%20HTML%20tag%0A%0A%5Bthis%20file.md%5D%3A%20%3Cthis%20file.md%3E%0A%0A%5Bthis%20file.md%5D%20%23%20reference%20link>).

```
<http://example.com> # autolink

<this.md>  # regular text

<this file.md> # raw HTML tag

[this file.md]: <this file.md>

[this file.md] # reference link
```

**Comment by step-** [comment]
Sure, as for angular brackets in Markdown links, this is CommonMark's [spec](https://spec.commonmark.org/0.31.2/#link-destination).

**Comment by lervag** [comment]
Ok; I've not thought of any reason this would be bad, so I've removed the angled brackets now. That should resolve this issue, I think.

**Comment by artkpv** [comment]
@lervag Thank you for your time and changes! I can't test this because other commit broke my setup. Pls see https://github.com/lervag/wiki.vim/issues/383#issuecomment-2559523192

**Comment by lervag** [comment]
My pleasure! I think #395 (and thus #383) is resolved now, and if I'm right, then you should be able to test now. Sorry for the inconvenience!
