### ISSUE TITLE
Tag parser for #tag tags

### ISSUE THREAD

**Issue by felixschurk** [lervag/wiki.vim#389]
https://github.com/lervag/wiki.vim/blob/982a54c651c5f62d944d120f533c569dbdaad671/doc/wiki.txt#L2179C1-L2185C42

Hei, 
I wanted to change the tag parser to be able to parse tags that would be of the form `#tags` or even then a bit further to be able to use yaml tags such as 
```
tags:
  - sometag
  - sometag/with-sub-tag
```

As a first starting point I wanted to use the linked documentation hint for modifying the tag parser, however when adding the required lines to my `.vimrc` I see following startup errors
![image](https://github.com/user-attachments/assets/d7e8e9c6-a1a7-4b21-ac46-7c77e48b2178)
hinting to some error for the input in the `deepcopy` function of vim. 

Is there any other way to write/change the tag parser?

**Comment by lervag** [comment]
Great, glad to hear it was helpful. Let me know if you have other problems. :)
