### ISSUE TITLE
[FEAT] WikiPages keybindings to open in new tab/split

### ISSUE THREAD

**Issue by Rubiginosa** [lervag/wiki.vim#391]
The fzf.vim plugin's `Files` command (and others from the plugin) support `<C-t>`, `<C-x>`, `<C-v>` to open the selected file in a new tab or split. wiki.vim has `WikiLinkFollowSplit` and `WikiLinkFollowTab` commands for links in text, and something like `--bind 'alt-enter:print-query+abort'` [for `WikiPages`] to force open a path. Replicating fzf.vim's behavior for `WikiPages` would improve both parity and convenience.

**Comment by lervag** [comment]
> The fzf.vim plugin's `Files` command (and others from the plugin) support , , to open the selected file in a new tab or split.

this feels like an incomplete or malformed sentence. Or did you mean the commas "literally", i.e. that the `Files` command supports that you type the comma key `,` (once or twice?) to open the selected file in a new tab? Or a split?

> wiki.vim has WikiLinkFollowSplit and WikiLinkFollowTab commands for links in text, and something like `--bind 'alt-enter:print-query+abort' to force open a path. Replicating fzf.vim's behavior for WikiPages would improve both parity and convenience.

Ok, so you want there to be additional key bindings for `WikiPages` with the fzf backend? But it is unclear what these should be, cf. that the first sentence seems "broken" somehow.

**Comment by lervag** [comment]
Ok, when I edited your post I was able to see what you meant. Notice that you _need_ to escape things like `<c-t>` with backquotes `` ` `` for the Github markdown, else it becomes "invisible" because it will be interpreted as an html tag.

Now, to consider adding this I need to know exactly what you want. Is this correct: In `:WikiPages` with fzf backend,

* `<c-t>` should open the entry in a new tab
* `<c-x>` should open in a new split
* `<c-v>` should open in a new split (same as `<c-x>`)

**Comment by Rubiginosa** [comment]
Whoops, sorry about the html problem.

> `<c-t>` should open the entry in a new tab
> `<c-x>` should open in a new split
> `<c-v>` should open in a new split (same as <c-x>)

This is almost right—the difference between `<c-v>` and `<c-x>` is that it opens `<c-v>` opens a vertical split and `<c-x>` opens a horizontal split. I believe fzf.vim implements this [here](https://github.com/junegunn/fzf.vim/blob/556f45e79ae5e3970054fee4c4373472604a1b4e/autoload/fzf/vim.vim#L356).

**Comment by lervag** [comment]
Please update and test; I think it should work as expected now.

**Comment by Rubiginosa** [comment]
This works perfectly, thank you!

**Comment by lervag** [comment]
Great, glad to hear it!
