### ISSUE TITLE
Error updating wiki.vim through LazyVim distribution

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#392]
There is a notification about plugin update, but the update process reports an error during check out

```
        error: invalid path 'test/test-toc/aux/headers-with-parens-input.md'
        error: invalid path 'test/test-toc/aux/headers-with-parens-reference.md'
```

**Comment by lervag** [comment]
Oh; I remember @clason explained to me once that `aux` is not a valid directory name on MacOS. I'll update the names and push asap.

**Comment by lervag** [comment]
Should be fixed now.

**Comment by lervag** [comment]
Thanks for reporting so fast, by the way!

**Comment by bybor** [comment]
It was Windows in my case, not MacOS, but it works just fine now. Thank you!

**Comment by lervag** [comment]
Oh, I must have remembered wrong about that, then. But in any case, glad to hear it works now!
