### ISSUE TITLE
Extend supported alphabets for creating wiki links

### ISSUE THREAD

**Issue by wailmerpailmer** [lervag/wiki.vim#42]
Creating links on the following does not work:

ウィキ
土壇場

Entering visual mode to highlight these entries produces garbage next to the new link and looks even worse pasted here:

孛苣ꎂ苣嶭艝ભ
孛鳥螣ꃥ嶴ꁝ઴

I would assume this is undefined behavior (as CJK text cannot be used to create links in normal mode) and could be (hopefully) easily implemented.

Additionally, the following text may not be made into a link unless highlighted in visual mode:

être
Pokémon
ça
miałyście

Though it does not produce garbage text like with CJK characters.

**Comment by lervag** [comment]
Thanks! I think this is fixed now, please test.

Note, it is somewhat difficult to define a good regex for words. I think the current definition may work well, but it could fail. Feel free to let me know if you notice unexpected behavoiur!
