### ISSUE TITLE
[bug/feature]: overwrite <c-s> binding in insert mode

### ISSUE THREAD

**Issue by sophiabrandt** [lervag/wiki.vim#43]
I would like to use the default key mappings that come with wiki.vim _but_ overwrite some of them.
I've used `g:wiki_mappings_global` to customize global mappings.
Specifically, I want to overwrite the standard `<c-s>` binding.
```vim
" WIKI.VIM
let g:wiki_mappings_global = {
      \ '<plug>(wiki-list-toggle)' : '<c-w>',
      \}
```

**Expected behavior:**
Wiki.vim respects the customization **in insert mode and normal mode**.
Expected output of `:imap <c-w>` (within a wiki file with above customization options):
```
i <C-W>   @<Plug>(wiki-list-toggle)
```

**Observed behavior:**
Wiki.vim accepts the customized key binding in normal mode, but using `<c-s>` within a wiki file still triggers the `wiki-list-toggle` plug in _insert mode_.
Output of `:imap <c-w>` (within a wiki file):
```
No mapping found
```
Output of `:imap <c-s>`:
```
i <C-S>   @<Plug>(wiki-list-toggle)
```

# Minimal working example
```vim
let g:wiki_root                  = '~/wiki'
let g:wiki_filetypes             = ['md']
let g:wiki_link_target_type      = 'md'
let g:wiki_mappings_global = {
      \ '<plug>(wiki-list-toggle)' : '<c-w>',
      \}
```

```
/~wiki
├── index.md
├── log
│   └── 2017-11-24.md
└── test.md
```
NeoVim:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

**Thank you for creating this plugin, it's very useful!**

**Comment by lervag** [comment]
> I would like to use the default key mappings that come with wiki.vim _but_ overwrite some of them.
> I've used `g:wiki_mappings_global` to customize global mappings.
> Specifically, I want to overwrite the standard `<c-s>` binding.
> ```vim
> " WIKI.VIM
> let g:wiki_mappings_global = {
>       \ '<plug>(wiki-list-toggle)' : '<c-w>',
>       \}
> ```

You can overwrite the `<c-s>` mapping wiht the `g:wiki_mappings_local` option, e.g. like this:

```vim
let g:wiki_mappings_local = {
      \ '<plug>(wiki-list-toggle)' : '<c-w>',
      \ 'i_<plug>(wiki-list-toggle)' : '<c-w>',
      \}
```

Here the second line with the `i_` prepended indicates insert mode. This is admittedly not so well documented.

> **Thank you for creating this plugin, it's very useful!**

Thanks for the kind words! I'm happy you find it useful!

**Comment by lervag** [comment]
I've updated the docs to make this more clear. I hope it is better now.

**Comment by sophiabrandt** [comment]
Thank you, @lervag.

**Comment by lervag** [comment]
My pleasure. Please feel free to open other issues if you notice bugs or have ideas for improving things.
