### ISSUE TITLE
V (visual mode) breaks link creation

### ISSUE THREAD

**Issue by Zeitvertreib** [lervag/wiki.vim#45]
# Description
For link creation I like to hit `V`, so the whole line gets highlighted.
But on link creation there gets `^@` inserted at the end of the link.

The link works, but it link gets modified to a not intended string.

This does not happen with other visual selection.
`ve<cr>` works normal, as expected
`<c-v>e` works normal, as expected

# Example
With the cursor on `word` entering `V<cr>` turns it into `[[word^@]]`

(This is somewhat important for me, to link files in folders.)

**Comment by lervag** [comment]
Thanks, I think this is fixed now.

**Comment by Zeitvertreib** [comment]
same.
