### ISSUE TITLE
request: fzf tags binding

### ISSUE THREAD

**Issue by gauteh** [lervag/wiki.vim#48]
It would be great if there was a key binding for fzf searching wiki tags!

**Comment by lervag** [comment]
Hi @gauteh, thanks for your interest and for the feature suggestion!

I assume you are referring to the `:help wiki-tags` feature, and that you are asking for a command similar to `WikiFzfPages`? I.e., you want `WikiFzfTags` (and `wiki#fzf#tags()`) to complement the `WikiTagSearch` command?

**Comment by lervag** [comment]
Also, with "key binding": There is no default binding for the `WikiFzfPages`, and I would suggest to not add a default binding for a corresponding tag search. Instead, if I add this, you should add your own custom binding. I assume this would be fine with you?

**Comment by gauteh** [comment]
Yes , exactly! I must have meant a command.

tir. 7. jan. 2020, 00:01 skrev Karl Yngve Lervåg <notifications@github.com>:

**Comment by lervag** [comment]
One question, though: How should this work? I mean, there is already functionality to gather tags. The tags are collected in a dictionary, where each entry has the tag as a key and the locations in a list as a value.

How would `WikiFzfTags` work?

**Comment by lervag** [comment]
I've implemented a very simple version now. It is sure to not be quite enough, but it probably makes it easier to discuss how to improve it.

**Comment by gauteh** [comment]
Thanks, this looks pretty good! Before you implemented this I tried getting a similar thing working with .ctags / gutentags and `:Tags` from [fzf.vim](https://github.com/junegunn/fzf.vim). But I failed to get the vimwiki style tags to work: `:tag1:tag2:tag3:`. I use your wiki-ft, with markdown setting `ft=wiki` for markdown files (I found the other md ft plugins too heavy).

One feature I am missing from this compared to my `:Tags`/`rg` set-up is to be able to select items or select all and loading into quickfix/location.

```
  let $FZF_DEFAULT_COMMAND = 'rg --files --color=never --glob ""'
  let $FZF_DEFAULT_OPTS = '--bind ctrl-a:select-all --color fg:252,bg:233,hl:67,fg+:252,bg+:235,hl+:81 --color info:144,prompt:161,spinner:135,pointer:135,marker:118'
au  FileType fzf tnoremap <buffer> <C-j> <Down>
```

I have a custom fzf grep command like this:

```

command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg -i --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)

nmap -r :Rg<Space>
```

my partly working ctags (which I guess could replace the command/feature I just request from you!):
```
--langdef=markdown
--langmap=markdown:.md
--regex-markdown=/^#[ \t](.*$)/\1/h,heading,headings/
--regex-markdown=/\%(^\|\s\)\@<=:\%([^:''[:space:]]\+:\)\+\%(\s\|$\)\@=/\1/t,tag/
```

**Comment by lervag** [comment]
> to select items or select all and loading into quickfix/location.

Proposal: `WikiFzfTags` would present a list of tags with a count of how many pages (or locations) the particular tag is found. When you activate a tag, it will load all locations into the quickfix list (or, perhaps better, the location list). The first entry will be focused.

How does this sound to you?

**Comment by gauteh** [comment]
Yes, I tested a few of the other FZF commands, and normally you are not able to select all / select several. Thinking a bit more about this I think this extra step will in most cases be unwanted. So perhaps it is better to leave the current behaviour (unless it can be combined in some way)?

I got an error when I tried to invoke the command outside a wiki buffer.

**Comment by lervag** [comment]
> So perhaps it is better to leave the current behaviour (unless it can be combined in some way)?

Perhaps, but I felt like testing it anyhow. I've pushed an update where instead of filtering all the files/locations, one first uses Fzf to select a tag, then the locations are put into the location list.

A possible alternative is to first search tag, then use Fzf to search for location.

I also think I fixed the issue with invoking the command outside a wiki buffer.

**Comment by gauteh** [comment]
This will be very useful. If I have to choose only one I think the first
one is better, but maybe another key (<S-enter> / <C-a>) can be used to
have this behavior rather than the flattened list.

**Comment by lervag** [comment]
> This will be very useful. If I have to choose only one I think the first one is better, but maybe another key (`<S-enter>` / `<C-a>`) can be used to have this behavior rather than the flattened list.

So, you propose having two variants? This would require either two different commands/mappings, or an option. I would prefer to provide a single command/mapping that just works the way one would expect. If that is not possible, then I think we should add an option for it. But please, let us first try to get this without any options.

I would be very happy if you could describe what you would call an optimal workflow with fzf and wiki tags. It could help to hear how you would want to use it. Personally, I've not really used tags, as I think links are enough. To find any page or topic I want, I simply use a search for a related page, and if I should miss the correct entry I probably get close enough that there is a relevant link nearby.

If one uses tags, then I would assume that the idea is to search for some page/entry/topic by first filtering by tag, then looking for the specific location, that is, page and line number. This is why I thought the current version should work well. But you liked the previous version better, and so, it would be good to hear more about how you want to fit this into your workflows.

**Comment by gauteh** [comment]
I use tags for creating explicit anchors to topics or locations where searching would give too many results or I'd easily end up in the wrong place. So e.g. a model I keep referring to in academic notes or in notes. With the first flattened alternative it is possible to see the location and navigate to it easily, if it turned out to be wrong I re-search (the tags). In the latter case the location list approach is better. So if I am not sure about the correct one, or I somehow want to review them, then the latter is much better. fzf.vim has different keybindings than Enter when filtering, allowing to open in new tab, split, etc, or selecting all and loading into qf.

Maybe something similar could be used here. Show e.g. flattened list with locations: Enter means open, Alt-A or Ctrl+X or something means load all locations with this tag into qf or location-window. Then there would only be one command.

fzf.vim has a :Tags which shows a flattened list, but does not allow multiple entries to be selectes (as far as I know).

I will probably complement this with the general ctags version which can also include headings etc.

**Comment by lervag** [comment]
> Maybe something similar could be used here. Show e.g. flattened list with locations: Enter means open, Alt-A or Ctrl+X or something means load all locations with this tag into qf or location-window. Then there would only be one command.

Yes, I think this could work. I'll push something along these lines in a short while. Let me know what you think!

**Comment by lervag** [comment]
Ok, I've pushed now. The interface is now reverted to the old style, but if you press `ctrl-l` it will put all entries for a given tag in the location list.

**Comment by gauteh** [comment]
Great! Thanks, I'll check it out!

**Comment by gauteh** [comment]
I am getting error: run[69] let Undefined variable a:tag

**Comment by lervag** [comment]
Sorry, try again now.

**Comment by gauteh** [comment]
Now it works, thanks. I think this works quite well!!!

 If there was one improvement I could wish for in the future it would be to
use Tab or space to mark lines (Alt+a to mark all) and use enter to load
those specific into the location list. But, that is not necessary for now.

**Comment by lervag** [comment]
Great, I'll consider this issue resolved then. Feel free to open a new issue for the enhancement requests in the future.

**Comment by gauteh** [comment]
Just wanted to say that this works great! I have one use case which I think is quite neat. I tag a project if I mention it in a journal entry (one file per day), this works really well for finding mentions about that project: either just find a single day, or get a list of all days that I mentioned that project. less noise than with grepping.

**Comment by lervag** [comment]
I'm happy to hear it, and thanks for the suggestion. Did I understand correctly that you use a specific tag for each project, then add that tag both to the project related files and to each journal entry where the project is mentioned? It sounds like a convenient way to find stuff. Personally, I've used links for this (i.e. by writing a short text with a link to the project specific wiki pages), but I can see that tags may give more flexibility.

**Comment by gauteh** [comment]
Yes. Pretty much. And if I have minutes or notes from a meeting or
something I also use the tag.

lør. 15. feb. 2020, 17:35 skrev Karl Yngve Lervåg <notifications@github.com
