### ISSUE TITLE
WikiFzfTags and esc without selecting anything gives error

### ISSUE THREAD

**Issue by gauteh** [lervag/wiki.vim#55]
40_callback: Vim(let):E684: list index out of range 0

**Comment by lervag** [comment]
Sorry, I can't reproduce this. Could you provide some more context?

**Comment by gauteh** [comment]
A bit more log from running with vim -Vlog:
```
                 /Users/gauteh
Calling shell to execute: "(tput cup 48 > /dev/tty; tput cnorm > /dev/tty; cat '/var/folders/3j/_r_6nnwx3t5gbcx_wx1tq1vh0000gn/T/vTywa9p/6'|'fzf'  --expect=ctrl-l --prompt "WikiTags> "  --height=19 > /var/folders/3j/_r_6nnwx3t5gbcx_wx1tq1vh0000gn/T/vTywa9p/5  2> /dev/tty)>/var/folders/3j/_r_6nnwx3t5gbcx_wx1tq1vh0000gn/T/vTywa9p/7 2>&1"
Error detected while processing function wiki#fzf#tags[16]..fzf#run[63]..<SNR>40_callback:
line   21:
Vim(let):E684: list index out of range: 0
```

1. open vim
2. :WikiFzfTags
3. <ESC>

I have a lot of other plugins going on as well.

**Comment by lervag** [comment]
Thanks. I think this is something else, actually. None of the wiki functions for the fzf stuff is 21 lines long...

Could you design a real minimal example (that is, minimal vimrc)?

**Comment by gauteh** [comment]
Yup, will try to do soon.

**Comment by lervag** [comment]
Feel free to reopen if you can reproduce this with a minimal example.
