### ISSUE TITLE
Wrong link recognition

### ISSUE THREAD

**Issue by rattletat** [lervag/wiki.vim#59]
Hi,

I noticed that the regex matcher recognizes links in checkbox lists that aren't actual links when using a markdown wiki.

Example:
```
- [o] [Link](...)
- [o] []()
- [] [] <--- is sufficient
keywords: [ This, is, recognized, as, a, link ]
```

**Comment by lervag** [comment]
Ah, yes. I'm not quite sure how to actually solve this, though. The same syntax is used for "bottom style" links, e.g.

```markdown
# Some section

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. [0]

[0]: https://en.wikipedia.org/wiki/Lorem_ipsum

Or also [this] type of link.

[this]: url
```

So, how can we properly know that `[o]` is _not_ a link?

Personally I've just come to ignore this, but I agree it is annoying, and I'll be glad to implement a fix if I/anyone can come up with a good way to do it.

**Comment by jabirali** [comment]
The following is not a complete solution, but perhaps a good enough heuristic for most users.

If using a bottom-style link in a list, I think most users would either use descriptive labels:
```
- [Interesting]
- [Look at this]
```
Or use numeric links that are situated deeper into the text:
```
- This was one interesting link [0];
- So was this [1], and this [2].
```
However, I think few people would use bottom links like this:
```
- [1] This was interesting;
- [x] So was this.
```

Conversely, MarkDown checkboxes always appear right after a list opening, and consist of one character:
```
- [o] This is one item
- [x] This is another
- [ ] This is not done
- [-] Partially done.
```

So if you match for an extended regexp like `^[-+*]\s*\[.\]\s+` to declare something a checkbox, I think that would capture basically all MarkDown checkboxes, while almost never interfering with bottom links.

**Comment by lervag** [comment]
I think this is actually quite simple. Currently, the `[....]` is recognized as a reference style link (see `:help wiki-links-reference`) with a very greedy regular expression. It matches almost anything that looks like `[...]` or `[...][...]`. This issue could probably be solved if we simplified things extensively. For instance, perhaps it would suffice to use a regex where the `target` part only matches:

- `\d\+` (numbers)
- `[a-zA-Z ]\{2,}` (words and text, minimum 2 characters to avoid collision with the todo lists)

What do you think? It would mean to change the target regex into something like: `\[\(\d\+\|[a-zA-Z ]\{2,}\)\]` (slightly more complicated to handle edge cases, but you get the idea).

**Comment by jabirali** [comment]
That sounds like a good solution! However, perhaps adding slightly more characters to the revised regexp would be helpful? I don't know about you, but I can often call a link something that contains number in the text (say something that contains `i3wm` or `CO2`). I think that hyphens and underscores may perhaps also be quite common in such reference labels.

Quickly checking [the original MarkDown documentation](https://daringfireball.net/projects/markdown/syntax), it seems like the "official" definition is:

> Link definition names may consist of letters, numbers, spaces, 
> and punctuation — but they are **not** case sensitive.

It's not really clear what "punctuation" is allowed here, but I would guess that underscores and hyphens in reference labels could be quite common. Perhaps allowing general combinations of minimum 2x letters, numbers, spaces, hyphens, and underscores is a good general rule? Possibly also periods?

**Comment by lervag** [comment]
> So something like [a-zA-Z][-_.a-zA-Z0-9]* for the non-digit part of your regexp.

Agreed, this looks good! I'll get to work!

**Comment by jabirali** [comment]
Quick correction: I think I forgot whitespace in the `[-_. a-zA-Z0-9]`, and probably the `*` at the end should be a `+` (in extended regexp) to avoid zero-character matches. The logic should still stand :).

**Comment by lervag** [comment]
Ok, I think this is fixed and works as expected now.
