### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by lervag** [lervag/wiki.vim#6]
I'm considering a change of name, and would be happy for some feedback. [/u/slugmanns commented on reddit](https://www.reddit.com/r/vim/comments/8hz8bd/some_questions_regarding_note_taking_with_vim/dyp5q0e/) that it could be wise, and one suggestion there was `wikinotes`. I've also been considering `wiki.vim`.

Are there other suggestions or comments on this from interested/possible users?

**Comment by feroze** [comment]
+1 for wiki.vim

**Comment by jgilchrist** [comment]
Another :+1: for `wiki.vim`

**Comment by lervag** [comment]
Thanks! It seems like a sensible name. So far:

- wiki.vim has three votes (mine included)
- wikinotes has no votes (I still think it is a good suggestion, though)

I'll probably make the change of name in not too long, but I'll allow some more time first.

**Comment by lervag** [comment]
Ok, `wiki.vim` it is. Thanks!
