### ISSUE TITLE
Renaming a wiki file succeeds, but buffer is blank upon doing so

### ISSUE THREAD

**Issue by wailmerpailmer** [lervag/wiki.vim#62]
# Description

Expected behavior:
Rename wiki file and be put back in the file with the file's contents still in tact.

Observed behavior:
File is renamed and references in other files is updated, but buffer is now blank and pressing back leads to previous file but with no text except for what seems like a directory name (?).

Steps to reproduce:
With `autochdir` set:
1. Navigate to any wiki file.
2. `:cd` to set working directory to a path other than the directory containing the current wiki file.
3. Rename the file using wiki.vim's rename function.

With `noautochdir` set:
1. Navigate to a wiki file.
2. Rename the file using wiki.vim's rename function.

**Comment by lervag** [comment]
Thanks. I think I've fixed this now.

**Comment by wailmerpailmer** [comment]
Seems like rename only works in the root directory now. Renaming files in folders causes all wiki buffers to become relative to the root wiki directory.

For example, given the file `~/wiki/folder/test.wiki`, upon renaming `test` to `test2` the open buffer `~/wiki/folder/test.wiki` changes to `~/wiki/test2.wiki`, which does not exist.

**Comment by lervag** [comment]
This should be fixed now, thanks for reporting!
