### ISSUE TITLE
Absolute paths and navigation

### ISSUE THREAD

**Issue by ErickChacon** [lervag/wiki.vim#63]
# Description

When making notes, I use absolute and relative paths in markdown because I link my main `index.md` to projects located in other folders. A simple example would be as follows.

```
/home/user
├── wiki
│   └── index.md
│   └── other.md
├── proj-1
│   └── README.md
├── proj-2
│   └── README.md
├── proj-3
│   └── README.md
├── proj-4
│   └── README.md
└── test.wiki
```

My `index.md` would look like follows:

```
- [other](other.md)
- [proj-1](~/proj-1/README.md)
- [proj-2](~/proj-2/README.md)
- [proj-3](~/proj-3/README.md)
- [proj-4](~/proj-4/README.md)
```

1. A description of the expected behaviour

I would expect to be able to press enter to go to an absolute or relative path and then being able to navigate between links.

2. A description of the observed behaviour

However, when I press enter to `~/proj-1/README.md`, *wiki.vim* tries to create a file `/home/user/wiki/~/proj-1/README.md`. And if I use `gf`, then I am not able to navigate adequately (it cannot go to previous link).

I was wondering if it would be possible to work under this workflow (using a mix of absolute paths).

**Comment by lervag** [comment]
Yes, this is possible already. You should use the `file:` scheme, like so:

```markdown
- [other](other.md)
- [proj-1](file:~/proj-1/README.md)
- [proj-2](file:~/proj-2/README.md)
- [proj-3](file:~/proj-3/README.md)
- [proj-4](file:~/proj-4/README.md)
```

See `:help wiki-links-url` for a specification of the various schemes available and how to implement your own.

Note that your project files are not counted as part of the main wiki. Instead, when you open them, they will be considered as separate wikis. The main implication is that you can't use implicit links between these project wikis, you have to be explicit with the `file:` scheme.
