### ISSUE TITLE
Feature request: Export to specific path and Export all

### ISSUE THREAD

**Issue by Mxbonn** [lervag/wiki.vim#65]
First of all, thank you for this wonderful plugin.

I've been using it a for a while now. But recently I've been wanting to export my wiki to html. It would be really useful if I could specify a path to store the exported html to. I know `fname` does that but I would like an option where the fname is the same as the wiki file but the path a specified one and not temporarily.

Example:
```vim
let g:wiki_root = '~/documents/wiki'
let g:wiki_export = {
        \ 'args' : '',
        \ 'from_format' : 'markdown',
        \ 'ext' : 'html',
        \ 'path': 'build/', (relative to wiki_root)
        \ 'view' : v:false,
        }
```
If you would then run WikiExport on `bar/foo.md` it would export to `build/html/bar/foo.html`

Additionally an option to export the entire wiki in one go would also be very useful.

**Comment by lervag** [comment]
> First of all, thank you for this wonderful plugin.

Thanks for the kind words :)

> I've been using it a for a while now. But recently I've been wanting to export my wiki to html. It would be really useful if I could specify a path to store the exported html to. I know fname does that but I would like an option where the fname is the same as the wiki file but the path a specified one and not temporarily.

This seems like a good request. I never really used the export feature for anything except printing things through pdf files, so I never considered that people would use it like this. But it seems like a relatively easy task to implement and if it is useful, then why not?

The export path would be either absolute or relative to wiki root.

Would it be necessary to include the `ext` part in the path? I.e. `build/html/bar/foo.html` vs `build/bar/foo.html`?

**Comment by Mxbonn** [comment]
Not necessary but it would be convenient in case you want to export everything to different file formats. Although that is something you can also just manually add to the path config (since you need to change the extension as well). I have no preference of one method over the other, so I'll leave that up to you ;).

**Comment by lervag** [comment]
I've implemented this now. You can specify the output directory with `:WikiExport -output dir` or with the `output` key in `g:wiki_export`.

> Additionally an option to export the entire wiki in one go would also be very useful.

I understand the desire for this, but I think this crosses the line where it would be much better to use a Makefile and plugins like [vim-dispatch](https://github.com/tpope/vim-dispatch) or similar. That way you get much better control of such a full export. I think implementing something like this in wiki.vim is a hornets nest in that there are probably a lot of things that can go wrong.
