### ISSUE TITLE
<plug>(wiki-link-return) same as <C-o>

### ISSUE THREAD

**Issue by ErickChacon** [lervag/wiki.vim#69]
When using `<bs>` or `<plug>(wiki-link-return)`, I just go back to the previous jump instead of the previous buffer. Is that the expected behaviour?

**Comment by lervag** [comment]
Yes. When you toggle/open a link, the original position is added to a stack. Pressing `<bs>` goes back one step in this stack. Thus, it is similar to the regular jump list feature in Vim, that is, `<c-o>` and friends, see `:help jumplist`.

**Comment by lervag** [comment]
Note, it is not exactly the same, because the jump list includes many types of motions. Thus, `<bs>` is not the same as `<c-o>`, because `<bs>` _only_ undoes opening a link. A link may refer to a different position in the same file, and `<bs>` works for that as well.

**Comment by ErickChacon** [comment]
Thank you so much for the clarification. It is a behavior that I did not expect. For example, if I open `index.md`, then `a.md` from `index.md` and then `b.md` from `a.md`; I expected to go back to `index.md` using two times `<plug>(wiki-link-return)`. This is not the case, but I imagine it is simply not the goal of `<plug>(wiki-link-return)`.

**Comment by lervag** [comment]
> This is not the case, but I imagine it is simply not the goal of <plug>(wiki-link-return).

Not sure what you mean. For me, this is exactly what happens. If I open `index.wiki`, then open a link to a new page, then again a link to a different page, then two times `<bs>` returns me to `index.wiki.`.

**Comment by ErickChacon** [comment]
> Not sure what you mean.

Under the example I provided above, the first time I press `<bs>` under file 'b.md', it goes back to 'a.md'. Then, if I press `<bs>` again, it goes back to `b.md` instead of going to `index.md`. It happens even using a minimal `nvim/init.vim` as below, and under nvim  version `v.0.4.3`.

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/wiki.vim'
call plug#end()
let g:wiki_root = '~/Documents/Organizer'
let g:wiki_filetypes = ['md']
```

**Comment by lervag** [comment]
Ok, I'll look into it.

**Comment by lervag** [comment]
The old version only worked when you have `set hidden`, because the navigation state was stored in buffer variables. I've changed it to be stored in a script local variable instead, which I think should work as expected in most cases I can think of.

**Comment by ErickChacon** [comment]
Thank you for taking a view on this. I tested, it works as expected.

**Comment by lervag** [comment]
Great, happy to hear it works! :)
