### ISSUE TITLE
WikiFileOpen .png filetype leaves vim blank after closing Image

### ISSUE THREAD

**Issue by annata83** [lervag/wiki.vim#70]
Hi Karl, I am Learning the workings of wiki.vim; currently trying to setup image viewer configuration; I did copy the doc's function and add images suport fine using sxiv but dont work  like pdf files do in zathura; what Am  saying is a .pdf files opens in their own window instances but .png files don't they leave vim hanging so when I close the image vim gets blank like so:

![pic-full-200428-2245-57](https://user-images.githubusercontent.com/18301363/80554247-e4874900-89a2-11ea-99b8-948f549465d1.png)

Afer closing the image I have to kill the current windows because is totally blank.

This is the `WikiFileOpen` function:
`
```vim
let g:wiki_file_open = 'WikiFileOpen'
function! WikiFileOpen(...) abort dict
  if self.path =~# 'pdf$'
    silent execute '!zathura' fnameescape(self.path) '&'
    return 1
  else
    if self.path =~# 'png$'
      silent execute '!sxiv' fnameescape(self.path) '&'
      return 1
    endif
  endif
  return 0
endfunction
```

This is the text syntax for execution:

`![imageTest](file:~/Pictures/wall/hackerWall.png)`

```
/home/documents/wiki
├── index.md
/home/Pictures/wall/hacker/
├──hackerWall.png
```

Also, How is the syntax for Multiple filetypes? I try these:
* `if self.path =~# 'png$''jpg$'`
* `if self.path =~# 'png$' , 'jpg$' `
* `if self.path =~# 'png$' || 'jpg$'`

**Comment by lervag** [comment]
Hi @annata83!

I do not immediately see why things work with pdf's and zathura and why they don't work with `sxiv` and png files. However, I found a minor bug in your function; it was missing an endif. It was probably a typo in the issue description (I've edited your post and fixed it). In any case, I would rewrite the function slightly to something like this:

```vim
function! WikiFileOpen(...) abort dict
  if self.path =~# 'pdf$'
    silent execute '!zathura' fnameescape(self.path) '&'
    return 1
  endif

  if self.path =~# '\v(png|jpg)$'
    silent execute '!sxiv' fnameescape(self.path) '&'
    return 1
  endif

  return 0
endfunction
```

This includes multiple file extensions with the regex group method `(a|b|c)`. The `\v` is used to specify very magic mode, which means the we don't need to escape the parantheses and "pipes" in the regex, see `:help \v`.

Could you confirm if this function still does not work as expected?

If it does not work: Could you try a different viewer, e.g. `feh`?

**Comment by annata83** [comment]
@lervag Thanks for clarifying how to achieve multiple file extensions & also for helping me figure out what I was doing wrong; 

It works great now as espected!. 

I am changing from [Jopling](https://joplinapp.org/terminal/) to this as my main note taking method and also gonna take a look at how to use it as journal, I'm currently using [Jrnl](https://jrnl.sh/).

Thanks Again

**Comment by lervag** [comment]
> @lervag Thanks for clarifying how to achieve multiple file extensions & also for helping me figure out what I was doing wrong; It works great now as espected!.

No problem, and I'm happy to hear it works!

> Just to make sure if I would add epub to the options syntax would be:
>
>  ```vim
>  if self.path =~# '\v(pdf|epub)$'
>     silent execute '!zathura' fnameescape(self.path) '&'
>  ```

Yes, that should work (and it should be easy to just test it, right?). The syntax `variable =~# 'regex'` is the standard way to test if `variable` matches the specified regular expression. The `#` implies that the regex is case sensitive by default. And as I wrote before, `\v` sets the very magic mode, in which a regex group is defined as `(first|second|third)`. By default in Vim, regexes are specified in the more verbose "magic mode", which would be `\(first\|second\|third\)`. So, you could also have written `if self.path =~# '\(pdf\|epub\)$`.

> I am changing from Jopling to this as my main note taking method and also gonna take a look at how to use it as journal, I'm currently using Jrnl.

I don't really know either Jopling or Jrnl myself, but I hope ! Feel free to suggest improvements and report bugs if (when) you find them! :)
