### ISSUE TITLE
[Bug] g:wiki_map_link_target not called on all WikiLinkOpen invocations

### ISSUE THREAD

**Issue by wbthomason** [lervag/wiki.vim#71]
# Description
It's possible that I've misunderstood the intent of `g:wiki_map_link_target`, but: `WikiLinkOpen` does not call `g:wiki_map_link_target` *unless* opening plain text as a link. I would expect that *every* invocation of `WikiLinkOpen` would call `g:wiki_map_link_target` (if defined).

# Minimal working example
Consider the following wiki file, in Markdown format:
```markdown
[[foo bar]]
foo bar
```

with the following config (the default minimal vimrc with the `g:wiki_map_link_target` example given in the docs added)

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/wiki.vim,' . &rtp

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

let g:wiki_root = '/path/to/minimal-working-example-wiki'
let g:wiki_map_link_target = 'MyFunction'
function MyFunction(text) abort
  return substitute(tolower(a:text), '\s\+', '-', 'g')
endfunction
```

I would expect that pressing `<cr>` or calling `:WikiLinkOpen` either inside the link in the example page or with the second line ("foo bar") selected in visual mode would call `MyFunction` and open a page `foo_bar` (with the default wiki extension).

However, I have observed that when `:WikiLinkOpen` is used inside the link, `MyFunction` is not called, and a page `foo bar` is opened instead. When the second line is selected in visual mode and `:WikiLinkOpen` is used, the expected behavior occurs.

Looking at https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/link.vim#L141, it seems that the only code path that will invoke a defined `g:wiki_map_link_target` is https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/link.vim#L147, which may (by way of https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/link.vim#L169) call https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/link.vim#L307, which is the only place I see a reference to `g:wiki_map_link_target`.

# Resolution Ideas

If I've misunderstood the intent of `g:wiki_map_link_target`, sorry for the confusion - I'll submit a PR for the docs to try to clarify its purpose. If, however, this is a bug, I'd be happy to make a PR to call `g:wiki_map_link_target` in `wiki#link#open` (if that's the right place to do so).

Related: it seems like https://github.com/lervag/wiki.vim/blob/master/test/test-common/test_links_open.vim is misnamed; the test only tests `wiki#page#open`, and not `wiki#link#open` (as the filename would imply). It seems that 73d5805 updated this test to use `g:wiki_map_create_page`, which is correct for the test that's in the file, but means that there are no tests for `g:wiki_map_link_target`.

**Comment by lervag** [comment]
Hi, thanks for the good issue description!

First, from `:help g:wiki_map_link_target`:

```
*g:wiki_map_link_target*
  This option may be used to transform text before creating a new link. ...
```

In particular, notice "**creating** a new link". `wiki.vim` assumes that link urls in defined links are explicit. There is no transformation or mapping between a link, except optionally adding an extension. The `g:wiki_map_link_target` option is designed to allow a transformation/mapping when one _creates_ the link urls with the `WikiLinkOpen` or `WikiLinkToggle` commands applied to plain text. It was not designed to transform link urls when following them.

I don't think your issue will change this behaviour, and so: the first issue here is that the docs somehow does not communicate the intended behaviour well enough. Do you agree? Perhaps it would help to change the name to `g:wiki_map_link_create`?

Next: What you are expecting is not an impossible thing to add. I could imagine `g:wiki_map_link_follow`. However, I would first point out that this feature would render your notes _tightly_ tied to your personal configuration. That makes them less useful if you were to share them somehow. As such, I would first ask if this is something you really want and something that is actually useful?

> Related: it seems like https://github.com/lervag/wiki.vim/blob/master/test/test-common/test_links_open.vim is misnamed; the test only tests `wiki#page#open`, and not `wiki#link#open` (as the filename would imply). It seems that [73d5805](https://github.com/lervag/wiki.vim/commit/73d5805e5bb2c78b7ffe61a4f86a4b0cacb1ce6d) updated this test to use `g:wiki_map_create_page`, which is correct for the test that's in the file, but means that there are no tests for `g:wiki_map_link_target`.

I have to admit that the tests are not perfect. There are some feature that remains untested (and I don't have the full overview), and some features are not consistently tested. I'm working on it. For context, I relatively recently (like last summer or so) landed on a method of testing Vim plugins that I find convenient and simple. It is based on simple vimrc files that specify the actions to test, example data, and Makefiles. My time for maintaining Vim plugins is (unfortunately) limited, so I prioritize to add new tests when working on new features and/or fix issues.

Back to business: You're wrong that `g:wiki_map_link_taget` is not tested; see https://github.com/lervag/wiki.vim/blob/92734dc5ce3602897ea8da2e5e22b74ef0ba28e6/test/test-common/test_links_toggle.vim#L3-L15.

**Comment by wbthomason** [comment]
> In particular, notice "creating a new link".

Ah, yep. Sorry about that; I misread the docs.

> Perhaps it would help to change the name to g:wiki_map_link_create?

I think that would be more clear, yes.

> However, I would first point out that this feature would render your notes tightly tied to your personal configuration. That makes them less useful if you were to share them somehow. As such, I would first ask if this is something you really want and something that is actually useful?

Fair enough. I think this is a good argument for not adding the feature.

> My time for maintaining Vim plugins is (unfortunately) limited, so I prioritize to add new tests when working on new features and/or fix issues.

Yes, totally reasonable. Sorry if my comment came across as a criticism or demand; I didn't mean it to be such.

> You're wrong that g:wiki_map_link_taget is not tested; see https://github.com/lervag/wiki.vim/blob/92734dc5ce3602897ea8da2e5e22b74ef0ba28e6/test/test-common/test_links_toggle.vim#L3-L15

Good point. I should've been more precise - I didn't find any tests for what I (incorrectly) thought g:wiki_map_link_target was meant to do, i.e. non-toggle/creation transformations.

Thanks! Sorry for misreading the docs.

**Comment by lervag** [comment]
> Yes, totally reasonable. Sorry if my comment came across as a criticism or demand; I didn't mean it to be such.

> Thanks! Sorry for misreading the docs.

No worry, I think you came across just fine. Constructive and useful. If you misunderstood things, then others likey may as well.

> Fair enough. I think this is a good argument for not adding the feature.

Great, let's leave this, then.

> I think that would be more clear, yes.

Thanks; let's consider to change the option name, then. Do you have further suggestions for how to improve the docs to avoid confusion for others?

**Comment by wbthomason** [comment]
No, I think the name change for the option will help. The docs are already clear that the option only applies to **creation**; I just drew too much from the name of the option and didn't pay attention to the rest of the docs around it. Thanks!

**Comment by lervag** [comment]
The option name is now changed, so remember to update your config.

**Comment by wbthomason** [comment]
Thanks!
