### ISSUE TITLE
Possibility to jump to "Reference Links"

### ISSUE THREAD

**Issue by alwc** [lervag/wiki.vim#74]
I'm testing out the features of this plugin and so far I'm quite happy with it. Thanks for the creation! @lervag 

By the way, for "Reference Links", is it possible to add a feature that let us jump to the "footnote" if it is not a link? For example,

```
This is cool [1]. This is awesome [2]. This is fantastic [3].

[1]: zot:alwc-github-2020
[2]: https://github.com/lervag/wiki.vim/
[3]: The subject refers to lervag/wiki.vim.
```

Right now [1] and [2] open their respective program because they are links. [3] does not work with `<cr>` at the moment, but it would be useful if the file is a long text file.

**Comment by lervag** [comment]
Ah, this is an interesting proposal! I think your suggestion is very good, as it seems immediately useful. Even if one does not care about footnotes. That is, if the reference is detected, but the link scheme is not "valid" or recognized, then jumping to the reference allows easy fixing of an url or similar. This also sort of allows multiple links for a single reference if the first part is not recognized as an url.

I'll look into when I get the time; in not too long.

**Comment by lervag** [comment]
> I'm testing out the features of this plugin and so far I'm quite happy with it. Thanks for the creation! @lervag

Oh, and thanks! I'm happy you find it useful! I've been a long time user of Vimwiki, but I found it strange to use a separate file type when I really only needed markdown with wiki functionality. Thus, I try to develop a plugin that is filetype agnostic and that does not "get in the way" of other functionality. I try to keep the features limited and focussed, and I am very happy to get feedback, both feature requests and bug reports!

**Comment by alwc** [comment]
> I try to keep the features limited and focussed, and I am very happy to get feedback, both feature requests and bug reports!

I'll try to see if I could pick up vimscript during my spare time and contribute to this project :)

**Comment by lervag** [comment]
> I'll try to see if I could pick up vimscript during my spare time and contribute to this project :)

Please do, and I'll be happy to help in any way I can. IMHO, the code for wiki.vim is quite well written, and I aim for it to be quite easy to read.

**Comment by lervag** [comment]
I've added a first version. Let me know what you think!

**Comment by alwc** [comment]
It works with the new update! Thanks!

**Comment by lervag** [comment]
Great! :)

**Comment by alwc** [comment]
Hi @lervag , I updated to the latest `wiki.vim` and it seems it no longer jumps to the footnote. Now if I hit `<cr>` on say `[1]`, it will become `[1]([1])`.

**Comment by lervag** [comment]
Strange. It still works for me. Could you open a new issue with a minimal example?

**Comment by alwc** [comment]
> Strange. It still works for me. Could you open a new issue with a minimal example?

My bad. I think I've forgotten the function of the footnote feature. Hitting `<cr>` on `[1]` in the writing will jump to `[1]` footnote if already exists. However, if `[1]` footnote does not exist, hitting `<cr>` on `[1]` will become `[1]([1])`. That's expected right?

**Comment by lervag** [comment]
> However, if `[1]` footnote does not exist, hitting `<cr>` on `[1]` will become `[1]([1])`. That's expected right?

Yes, you're right. And it's a good question. What _would_ we expect here? Perhaps a warning? What currently happens is that the link is "toggled" and changed from a ref style link into a markdown style link, but this does not make sense. So, I think the current behaviour is not quite right.

**Comment by lervag** [comment]
Note: It is easy to chage this, but it would be nice to hear what you think is an appropriate behaviour here.

**Comment by lervag** [comment]
Ok, I've added a warning now. I think this behaviour is better.

**Comment by WovenTales** [comment]
I know this is reviving an old issue, but jump-to-reference/footnote isn't working for me, with the current HEAD and NVim 0.8.2.  Does that still work on your end?  If so, I'm willing to chalk it up to some bad interaction with vim-pandoc or something else in my setup and not be too concerned about fixing it (I've not built my vim flow around within-file jumps, beyond any marks I might set manually), but I wanted to mention it just in case this was a regression.

**Comment by lervag** [comment]
As far as I now, reference links work as expected. If they don't work as expected for you, then please feel free to open a new issue. I may have missed something and added a bug here unintentionally, or perhaps there's a bug that I was never aware of. I would be glad to fix it if this is the case!

**Comment by WovenTales** [comment]
I think it was my habit of indenting them two spaces -- [the change](https://github.com/lervag/wiki.vim/commit/5371054c40a826e6b6fa7539c2b392f637f07017#diff-2c819c983e2a7c4d1303a3a3286719e452f8c7357197151062bc0779b050beccL26-R26) you made as part of solving the bare links fixes them.  Thanks again!

**Comment by lervag** [comment]
Glad to hear it!
