### ISSUE TITLE
Description found in wiki link by default when text with whitespace is created as wiki link

### ISSUE THREAD

**Issue by alwc** [lervag/wiki.vim#76]
If I have the following settings in the vimrc file

```
let g:wiki_filetypes=['md']
```

then if I press `<cr>` on a text string,
* Case 1: `wikipedia`, it will become `[[wikipedia]]`
* Case 2: `english wikipedia `, it will become `[[english-wikipedia|english wikipedia]]`

How come for Case 2 there will be "description" in the link by default? Isn't it supposed to be `[[english-wikipedia]]`?

**Comment by lervag** [comment]
> If I have the following settings in the vimrc file
>
> ```
> let g:wiki_filetypes=['md']
> ```

I think you have more configuration. In particular, I think you have defined the `g:wiki_map_link_create` option as well to convert spaces into dashes. In this case, the original text is used as the "text" part of the link.

**Comment by alwc** [comment]
> > If I have the following settings in the vimrc file
> > ```
> > let g:wiki_filetypes=['md']
> > ```
> 
> I think you have more configuration. In particular, I think you have defined the `g:wiki_map_link_create` option as well to convert spaces into dashes. In this case, the original text is used as the "text" part of the link.

You are right. I think I added some other configurations, sorry about that!

**Comment by lervag** [comment]
Great, happy to hear it :)
