### ISSUE TITLE
[very low priority] Question about WikiJournalToWeek

### ISSUE THREAD

**Issue by wbthomason** [lervag/wiki.vim#77]
I have a question about how the summarization aspect of `WikiJournalToWeek` works.

From the docs, the command says that it "Go[es] to week summary. If not existing, then parse the day entries to make a first draft. The title is given by |g:wiki_template_title_week|."

I'm a bit confused by how "pars[ing] the day entries" works - when I run WikiJournalToWeek from a day entry, sometimes I get a new document with some of the content of my day entries for that week, but (a) usually it does not include all the entries, and (b) more often, the new document is blank except for the title, templated as described in the docs.

I've looked through the code to try and figure out where the summarization is invoked to read the logic, but I haven't had much luck. Could you please either point me to where this happens or explain the logic, so that I can figure out what determines if content in an entry is/is not included in a summary? If the behavior I'm seeing *isn't* just user error on my end, I'll gladly help make a PR to fix any bugs. Thanks!

**Comment by lervag** [comment]
> I'm a bit confused by how "pars[ing] the day entries" works - when I run WikiJournalToWeek from a day entry, sometimes I get a new document with some of the content of my day entries for that week, but (a) usually it does not include all the entries, and (b) more often, the new document is blank except for the title, templated as described in the docs.

Ah, yes. This feature is probably not used by a lot of people (except myself). And it is designed to fit exactly my workflow.

My personal workflow is to write daily journal entries structured as follows:

```
HEADER - some metadata for each day, including work hours per project

Project title
* list of descriptions/comments/info related to what I did

Project title 2
* list of descriptions/comments/info related to what I did for this project

Project title 3
* list of descriptions/comments/info related to what I did for this project

...

# Meeting notes (if I attend a meeting)
lorem ipsum

# Other specific free form notes
lorem ipsum

```

All days follow the same structure, and the weekly summary parser will gather the _Project title_s and their associated list of info/comments. Thus, if I worked on "Project123" three days one week, then the list entries will be gathered automatically for me and aggregated (chronologically) under the same header in my weekly summary. I tend to spend some minutes on "cleaning up" the summaries on top of this automated workflow.

> I've looked through the code to try and figure out where the summarization is invoked to read the logic, but I haven't had much luck. Could you please either point me to where this happens or explain the logic, so that I can figure out what determines if content in an entry is/is not included in a summary? If the behavior I'm seeing *isn't* just user error on my end, I'll gladly help make a PR to fix any bugs. Thanks!

The code is given in `autoload/wiki/template.vim`. I have to admit it is not the most beautiful code I've written. I think `wiki.vim` is quite well done; clearly not perfect, with regard to the main features such as links and url treatment. But for this particular feature, it is mainly something I wrote to suit my own preferances, and I've made some updates to make it slightly more customizable (such as allowing custom titles).

I will be very glad to get help on improving this! I think a sensible route would be to improve the general parts and perhaps to allow more custom parsing of entries. That is, it should be possible to somehow write a custom parser with a clear API wrt. function input and output that allows more flexible ways to parse a journal entry and collect whatever you want.

Let me know what you think, and feel free to ask about how things work if you still find the code difficult to understand.

**Comment by wbthomason** [comment]
Great, thank you for the information! I’ll take a look and see if I can come up with a good way to make the summarization more general.

Also, I do find the `wiki.vim` code to be quite nice overall - I’ve used it to help teach myself how to write good vimscript. My inexperience with vimscript just made it a little hard to trace the control flow to find the summarization code.

Thanks!

**Comment by lervag** [comment]
> Great, thank you for the information! I’ll take a look and see if I can come up with a good way to make the summarization more general.

Sounds good.

> Also, I do find the `wiki.vim` code to be quite nice overall - I’ve used it to help teach myself how to write good vimscript. My inexperience with vimscript just made it a little hard to trace the control flow to find the summarization code.

Thanks! I try to keep things well structured, but as mentioned, some parts are more "hacky" than others. I don't have as much time as I would like to spend on improving things, although I should say that wiki.vim really do suit 99.5% of my personal needs. Still, it is fun to keep improving things and making it more accessible and better, and I am just happy if I can help others to join in this experience.

I'll leave it to you to close the issue. I answer follow ups on issues if they're closed as well. Feel free to ask any questions, and if you should propose a PR, I will be happy to do code reviews, discuss, and merge when things are ready. :)
