### ISSUE TITLE
Strange bug with wiki#link#open

### ISSUE THREAD

**Issue by wbthomason** [lervag/wiki.vim#81]
# Description

**Note:** I'm not sure if this is a `wiki.vim` bug or a Neovim bug - it feels more like the latter.

When I place my cursor over an unlinked word in any wiki buffer and invoke `WikiLinkOpen` (either manually or through the default `<cr>` map), I get the following errors:

```vim
E716: Key not present in Dictionary: open, a:000, l:link)
E116: Invalid arguments for function call
E488: Trailing characters
```
*However*, if I modify `autoload/wiki/link.vim` at line 144: https://github.com/lervag/wiki.vim/blob/d89a4ac224d9be94e694372ba9d4e9d4cfaab74a/autoload/wiki/link.vim#L144 by adding the line `echom l:link.open` (which I did while trying to debug the issue), I get the expected behavior - no errors, and the word becomes a link. This is strange to me, as I would not expect `echom` to modify any state that would cause the call to `l:link.open` to not have errors it otherwise throws. As such, I'm wondering if this is a bug in Vim/Neovim.

It is worth noting that `echom l:link` does **not** prevent the errors, and there does not seem to be an `open` key in the `l:link` dict. Given the control flow at line 144, this makes sense - I'm separately confused about why `E716` doesn't seem to be caught by the `catch` line below that call.

# Minimal working example

This happens for me with default config and any wiki file. I am using Neovim built from current `master`, so it's entirely possible that this is a bug on their end - I'm mostly curious if others can replicate the error.

**Comment by wbthomason** [comment]
This may be related? https://github.com/vim/vim/issues/538

**Comment by lervag** [comment]
> **Note:** I'm not sure if this is a `wiki.vim` bug or a Neovim bug - it feels more like the latter.

Which version of neovim are you on? I'm using neovim myself and I don't have this issue. My version is `NVIM v0.5.0-132-g83b6d9f19`.

> ```viml
> E716: Key not present in Dictionary: open, a:000, l:link)
> E116: Invalid arguments for function call
> E488: Trailing characters
> ```

The error message says that the `open` key is not present in the `l:link` dictionary.

> It is worth noting that `echom l:link` does **not** prevent the errors, and there does not seem to be an `open` key in the `l:link` dict. Given the control flow at line 144, this makes sense - I'm separately confused about why `E716` doesn't seem to be caught by the `catch` line below that call.

This seems consistent with the error message. However, it seems inconsistent
that it should work if you add `echom l:link.open`... strange!

I'll look into it and see if I can reproduce.

**Comment by lervag** [comment]
Ok, so, the code is implemented with a `try .. catch` block that is supposed to catch the error. I guess that you're onto something here with the Vim issue, except it is for Vim and not neovim...?

Do thinks work if you add a random `let` statement after the `call`?

**Comment by wbthomason** [comment]
> Which version of neovim are you on? I'm using neovim myself and I don't have this issue. My version is NVIM v0.5.0-132-g83b6d9f19.

Fascinating, I'm on `NVIM v0.5.0-553-gd8c5d122f`, but have had this issue with earlier commits too. I'll triple-check that there's not some config file being sourced in my setup that would cause this behavior.

> The error message says that the open key is not present in the l:link dictionary.

Yup, but I would expect the `catch` to catch that error and call `wiki#link#toggle`...

> I guess that you're onto something here with the Vim issue, except it is for Vim and not neovim...?

Yes, but given the age (it's from 2015), I wouldn't be surprised if the buggy code was still in Neovim.

> Do thinks work if you add a random let statement after the call?

I'm not sure I understand - a `let` statement after the `call` on 144 should never be reached if the `call` throws an error? A `let` on the line before (still within the `try-catch`) does not change anything.

**Comment by lervag** [comment]
> > Do thinks work if you add a random let statement after the call?
>
> I'm not sure I understand - a `let` statement after the `call` on 144 should never be reached if the `call` throws an error?

Yes, exactly. I was wondering if this would somehow avoid the "bug". For instance, I've noticed that a `try ... catch` block does not work well to catch errors in the `<expr>` in `return <expr>`, so that one should split it to `let var = <expr>; return var`. Not sure if this makes much sense, but the point was just to look for a "hack" that mitigates the "bug" in a silly manner.

So, do you still see the bug with the following?

```vim
  try
    call call(l:link.open, a:000, l:link)
    let l:dummy = 1
  catch /E716:/
```

**Comment by wbthomason** [comment]
>So, do you still see the bug with the following?

Unfortunately, yes, I do. I'm also not able to find anything in my configuration that would change how `try-catch` works, and I tried changing https://github.com/lervag/wiki.vim/blob/995dbb3bc15169ace97537514fa15bb56bb773f6/autoload/wiki/buffer.vim#L82 to not include the `<silent>` modifier - still no luck, which maybe hints that the other issue I linked is not related?

One workaround would be to use `has_key(l:link, 'open')` rather than relying on the `try-catch` mechanism, but (1) this **should** work and (2) it seems that the issue is unique to my setup (at least, it doesn't happen for you), so making a change without a known cause for the error seems unnecessary.

**Comment by lervag** [comment]
> One workaround would be to use has_key(l:link, 'open') rather than relying on the try-catch mechanism, but (1) this should work and (2) it seems that the issue is unique to my setup (at least, it doesn't happen for you), so making a change without a known cause for the error seems unnecessary.

Yes, I agree. I'll probably just do that. As you say, it should not be necessary. But who really cares about **should** if things don't work?

**Comment by lervag** [comment]
I think that should fix things, please check.

**Comment by wbthomason** [comment]
That does fix this issue, thanks!

However, in the process of testing the updated version, I discovered *another* strange bug: calling `exists('*' . something)` seems to cause error `E129` when `something` begins with `~` or `/` (because that makes `something` not a valid function name), which makes the new flexible `wiki_root` feature fail if one has `g:wiki_root` set to an absolute path or a path from one's home directory.

I'll close this issue and open another for that.

**Comment by lervag** [comment]
Thanks for notifying about the other issue. I should have tested that update better. :\
