### ISSUE TITLE
Bug with flexible wiki_root

### ISSUE THREAD

**Issue by wbthomason** [lervag/wiki.vim#82]
# Description

As mentioned in #81, the change to allow functions for `g:wiki_root` can cause a bug if `g:wiki_root` is instead set to a path beginning with `~` or `/`.

# Minimal working example
Have a wiki:
```
~/mywiki
```
Set `g:wiki_root`:
```vim
set nocompatible
let &rtp  = '~/.vim/bundle/wiki.vim,' . &rtp
filetype plugin indent on
syntax enable

let g:wiki_root = '~/mywiki'
```
Call any `wiki.vim` function that calls `wiki#get_root()`. You should get `E129` from https://github.com/lervag/wiki.vim/blob/49326cad11c780204ff250b0cc625b66b288dbb2/autoload/wiki.vim#L24.

**Comment by lervag** [comment]
Sorry about that! Fixed now.

Although, I did use the same "pattern" for fixing it as I've done before with `try ... catch`, so I hope this does not again lead to the same bug as in #81?

**Comment by wbthomason** [comment]
It doesn't seem to cause the #81 bug (for me, at least). Thanks!

**Comment by lervag** [comment]
Great, and no problem! :)
