### ISSUE TITLE
[feature / question] Is there a way to insert a page via search?

### ISSUE THREAD

**Issue by cantdoart5** [lervag/wiki.vim#84]
# Description

Sorry if this is not the place for questions or if this is in the manual and I missed it.

In Roam you can type `[[` and it will pull up a search box of all the available pages that can be inserted.  Does this exist in wiki.vim?  Ideally one would be able to search by all the link names you gave it and by the page's filename.

If not, I could probably just create a helper to get the name of a file I find with fzf/ctrlp and have the helper copy that filename to a register to paste into the link.  Or maybe this could be done by a coc plugin.

**Comment by lervag** [comment]
>  Does this exist in wiki.vim? Ideally one would be able to search by all the link names you gave it and by the page's filename.

Yes, or at least partially. See `:help CtrlPWiki` and `:help WikiFzfPages`. Is this what you're looking for?

**Comment by cantdoart5** [comment]
CtrlPWiki is great, but I am looking for an easier way to create page links of existing pages.  Something more in line with basic tab completion.

**Comment by lervag** [comment]
Ah, OK. I understand. Yes, this does exist. You should first learn about completion in Vim in general. The feature is called omnicompletion, see `:help i_CTRL-X_CTRL-O`. wiki.vim provides this and allows `<c-x><c-o>` after e.g. `[[` to complete pages. See more info in `:help wiki-completion`.

For _auto_completion (which is not a feature provided by Vim directly), you need plugins. E.g. coc.nvim. There is not currently a published solution for this. I have a custom extension that I use myself, but it does not work well enough that I want to share it (yet). Sorry!

**Comment by cantdoart5** [comment]
Thanks for the help.  I didn't think to try omnicompletion.  I'll close the issue as a coc plugin would likely be a separate community project.

**Comment by lervag** [comment]
> Thanks for the help. I didn't think to try omnicompletion. I'll close the issue as a coc plugin would likely be a separate community project.

No problem. I would be very happy to see a good coc extension for this. My current version is not good and doesn't work properly. I don't know why. :\

**Comment by lervag** [comment]
Ok, I think I did it. It seems to work for me at least. I've added a coc source in wiki.vim now, and I think it should "just work" if you already use `coc.nvim`. Can you test?
