### ISSUE TITLE
Pandoc/Vimtex Integration

### ISSUE THREAD

**Issue by kwrobert** [lervag/wiki.vim#9]
This is more of an open discussion/feature request than any sort of bug or issue so I did not follow the issue template. 

I was thinking it would be nice to support integration with [Vimtex](https://github.com/lervag/vimtex) and [Pandoc](https://pandoc.org/), and to support the Pandoc flavor of markdown. 

Supporting Vimtex integration would give users access to all the convenient text objects, insert mode mappings, and other typesetting features of Vimtex when taking notes in their wiki. Pandoc's flavor of markdown supports inline Latex, making access to Vimtex's mappings extremely valuable. Conforming to Pandoc's flavor of markdown allows users to render their wiki files to a multitude of output formats. 

I am perhaps the ideal example use case for this integration. As a physics graduate student, having access to inline math via Latex is indispensable. I use Pandoc to convert my weekly journal summaries to PDF and send them along to my advisor to keep him updated about my progress. I have enabled this integration using the following snippet in my vimrc 

```vim
augroup wiki_setup
    autocmd!
    " Enable pandoc for all wiki files
    autocmd BufNewFile,BufFilePre,BufRead *.wiki set filetype=wiki.pandoc.tex
    " Now enable vimtex plugin to get vimtex keybindings and such
    autocmd BufNewFile,BufFilePre,BufRead *.wiki call vimtex#init()
augroup END
```

Perhaps this is a vimtex issue and not a wiki issue, but I can't get vimtex to initialize using multiple filetypes like I have above. I need to explicitly call `vimtex#init()`. 

From a development perspective, one could offload the syntax highlighting to the [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) plugin, and only add syntax extensions onto that. It provides nice highlighting for math, lists, etc. Currently there is some weirdness with how the syntax from wiki.vim and vim-pandoc interact. 

Anyway, I opened this issue to get people's thoughts and see if anyone else would find this useful. Also fishing for some cool ideas :) 

Feel free to close if this seems too vague or not particularly useful.

**Comment by lervag** [comment]
Hi @kwrobert! Thanks for the interesting post! As you might have understood, I am also using this plugin for taking notes, and improving the tools may give big benefits to me as well. (I currently have about 125 000 lines of notes that I've written over the years ...)

# Pandoc syntax

I agree on going towards the pandoc variant of markdown, or at least a markdown format that is well supported by pandoc. I see the convenience in being able to use pandoc for converting to other formats.

Perhaps it is a good choice to build on `vim-pandoc-syntax`, but I am not sure. In principle, markdown format is quite simple, and so it should not be too complicated to implement the missing syntax elements in a good way. To be blunt, I am not sure if the pandoc plugin is very well written and robust/efficient. But if I am wrong and if it is, then it does seem tempting to simplify wiki.vim.

However, to improve the syntax support, it would be very helpful if you could open a new issue on this topic to continue the discussion there. Or possibly, open multiple issues on more concrete syntax shortcomings.

*Note:* As I just wrote in a different thread (#8), I don't want wiki.vim to become a general markdown plugin, and so for now, I'm going to restrict it to `.wiki` files. In the future, I might relax this and allow wiki.vim to work with `.md` files by simple configuration, but before that it must be much more mature.

# vimtex

I would be happy if you could open a separate issue for this as well. I don't quite understand how this integration should work, so it would be very helpful if you could give some examples of wiki notes where vimtex integration would be convenient.

**Comment by lervag** [comment]
Also, I'm closing this since I would prefer that we open two (or more) separate issues as described.
