### ISSUE TITLE
"trim" not found

### ISSUE THREAD

**Issue by mdebellevue** [lervag/wiki.vim#90]
# Description

My version of vim isn't finding the function "trim" that you use in wiki.vim/autoload/wiki/link.vim, line 186.  I'm running Ubuntu 18.04.4 LTS, which includes vim 8.0 by default.  Maybe trim is just in some later version of vim?

# Minimal working example

When highlighting text in visual mode and hitting enter as in the quick start guide:
'''
= My knowledge base =
    * [[Tasks]] -- things to be done _yesterday_!!!
    * [[Project]] Gutenberg -- good books are power.
    * Scratchpad -- various temporary stuff.
'''

 this error was produced.

'''
Error detected while processing function wiki#link#toggle_visual:
line    3:
E117: Unknown function: trim
E15: Invalid expression: { 'url' : trim(getreg('w')), 'text' : '', 'scheme' : ''
, 'lnum' : line('.'), 'c1' : getpos("'<")[2], 'c2' : s:handle_multibyte(getpos("
'>")[2]), 'toggle' : function('wiki#link#template_word'),}
'''

Here's the minimal vimrc that produced this issue.

```vim
call plug#begin('~/.vim/plugged')

Plug 'lervag/wiki.vim'
let g:wiki_root = '~/Documents/notes'

call plug#end()

set nocompatible
filetype plugin on
syntax 
```

**Comment by mdebellevue** [comment]
Indeed, updating vim to 8.2 resolved this issue.

**Comment by lervag** [comment]
Ah, yes. The `trim` function was not introduced to Vim before some later patch than what is readily available on Ubuntu 18.04. I have not specified which Vim version that wiki.vim is compatible with, but it could be sensible to make it work as expected on Ubuntu 18.04, as this is a common and popular distribution.

**Comment by mdebellevue** [comment]
Thanks so much for taking care of that!  At first I thought it's not worth the bother, since users can just upgrade to the latest version of vim, but this actually breaks your other plugin, vimtex (fantastic plugin by the way!)

**Comment by lervag** [comment]
> Thanks so much for taking care of that! At first I thought it's not worth the bother, since users can just upgrade to the latest version of vim, but  (fantastic plugin by the way!)

No problem, and thanks for the kind words. I'm curious, what do you mean with "this actually breaks your other plugin, vimtex"? Is vimtex broken for you?

**Comment by mdebellevue** [comment]
> Is vimtex broken for you?
It broke after I upgraded to the latest version of vim.  It started working normally again once I reinstalled vim to the version shipped with the 18.04 LTS.  Do you want to see the error code that resulted?  I could upgrade to the latest version again to try to reproduce the error.

**Comment by mdebellevue** [comment]
I'll just go ahead an do it.  Here were my steps to reproduce:

1. Update vim via an unofficial repository:
`sudo add-apt-repository ppa:jonathonf/vim`
`sudo apt update`
`sudo apt install vim`
2.  Open any latex file (existing or new).  The following error occurs:

> 
<pre><span style="background-color:#CC0000"><font color="#EEEEEC">Error detected while processing BufRead Autocommands for &quot;*.tex&quot;..function dist#ft#FTtex[47]..Fil</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">eType Autocommands for &quot;*&quot;..function &lt;SNR&gt;14_LoadFTPlugin[17]..script ~/.vim/plugged/vim</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">tex/ftplugin/tex.vim[25]..function vimtex#init[3]..&lt;SNR&gt;42_init_state[1]..vimtex#state#init[9]..1</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">[38]..vimtex#view#init_state[11]..BufRead Autocommands for &quot;*.tex&quot;..function dist#ft#FTtex[47]..F</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">ileType Autocommands for &quot;*&quot;..function &lt;SNR&gt;14_LoadFTPlugin[17]..script ~/.vim/plugged/v</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">imtex/ftplugin/tex.vim[25]..function vimtex#init[3]..&lt;SNR&gt;42_init_state[1]..vimtex#state#init[9].</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">.1[38]..vimtex#view#init_state[5]..vimtex#view#zathura#new[18]..vimtex#log#warning[1]..25[13]..vi</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">mtex#debug#stacktrace:</font></span>
<font color="#AF5F00">line   44:</font>
<span style="background-color:#CC0000"><font color="#EEEEEC">E684: list index out of range: 1</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">E116: Invalid arguments for function matchstr( vimtex#util#command(&apos;verbose function &apos; . l:func_n</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">ame)[1], v:lang[0:1] ==# &apos;en&apos;   ? &apos;Last set from \zs.*\.vim&apos; : &apos;\f\+\.vim&apos;)</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">Error detected while processing BufRead Autocommands for &quot;*.tex&quot;..function dist#ft#FTtex[47]..Fil</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">eType Autocommands for &quot;*&quot;..function &lt;SNR&gt;14_LoadFTPlugin[17]..script ~/.vim/plugged/vim</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">tex/ftplugin/tex.vim[25]..function vimtex#init[3]..&lt;SNR&gt;42_init_state[1]..vimtex#state#init[9]..1</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">:</font></span>
<font color="#AF5F00">line   38:</font>
<span style="background-color:#CC0000"><font color="#EEEEEC">E170: Missing :endfor</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">Error detected while processing BufRead Autocommands for &quot;*.tex&quot;..function dist#ft#FTtex[47]..Fil</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">eType Autocommands for &quot;*&quot;..function &lt;SNR&gt;14_LoadFTPlugin[17]..script ~/.vim/plugged/vim</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">tex/ftplugin/tex.vim[25]..function vimtex#init[3]..&lt;SNR&gt;42_init_state[1]..vimtex#state#init:</font></span>
<font color="#AF5F00">line    9:</font>
<span style="background-color:#CC0000"><font color="#EEEEEC">E171: Missing :endif</font></span>
</pre>

3. While the file is opened, vimtex commands like "cse" don't do anything.  Trying to compile with <leader>ll produces the following error:
`Error detected while processing function vimtex#compiler#compile:`
`line    1:`
`E121: Undefined variable: b:vimtex`


3. Problem is solved by reverting to the LTS version of vim via the following:

`sudo apt-get remove vim vim-runtime vim-common`
`sudo add-apt-repository --remove ppa:jonathonf/vim`
`sudo apt-get install vim`

**Comment by lervag** [comment]
Did you try to update vimtex? I think I fixed that issue in https://github.com/lervag/vimtex/issues/1764.

**Comment by mdebellevue** [comment]
I just tried that and it does indeed fix the issue!  I'm using vim-plug, and I just ran :PlugUpdate.

**Comment by lervag** [comment]
Good to hear. If you encounter issues with vimtex, don't hesitate to raise them at the issue tracker.
