### ISSUE TITLE
Journal entries in wiki root

### ISSUE THREAD

**Issue by samgriesemer** [lervag/wiki.vim#91]
## Description
This issue is meant to address details with creating journal notes in the main wiki root, as opposed to its own separate
folder. While this is mostly possible when specifying an empty string for the journal name, it seems it was a design
decision to assume there would be a separate folder for journal files, resulting in a few small inconsistencies.

**Desired behavior**: I want to be able to specify an empty journal name, and have journal files created in the main
wiki root. This of courses assumes all existing commands and behaviors work as expected.

**Observed behavior**: When specifying an empty journal name in my `.vimrc`, I find a few unexpected behaviors:

1. When using internal commands to access journal files, they show as `<wiki_root>//<date>.md`, with two forward
   slashes. This seems be a result of line 9 in the `autoload/wiki/url/journal.vim` file:

   ```
   let a:url.stripped = printf('/%s/%s', g:wiki_journal.name, a:url.stripped)
   ```

   which includes that first forward slash before the wiki journal name. I have removed this forward slash in my local
   `wiki.vim` fork, and have observed the correct file path when opening journal files. The only issue with this change
   is that, as mentioned before, there appears to be a few other components operating on the assumption that there is a
   distinct separate journal folder. The main issue I've observed on this front is described in (2).
2. A few journal specific commands break or override global commands since journal files are now at the same level as
   other wiki files. The main mapping I've noticed is the `<Leader>wn` mapping for the `wiki-journal-copy-tonext`
   journal buffer function, overriding the main `<Leader>wn` for `wiki-open`. So all note files are treated like journal
   files when using this command, in the sense that the plugin attempts to copy the file's contents to a new journal
   file. Tangentially, I find this mapping confusing on its own; I often want to create new files using `<Leader>wn`
   from within a journal file. I think it would make sense to reconsider the default mapping
   for`wiki-journal-copy-tonext` while in journal files (perhaps `<Leader>wcn` or `<Leader>wjn`).

## Minimal working example
The journal settings I have in my `.vimrc` are as follows:

```vim
let g:wiki_journal = { 
    \ 'name' : '',
    \ 'frequency' : 'daily',
    \ 'date_format' : {
        \   'daily' : '%Y-%m-%d',
        \   'weekly' : '%Y_w%V',
        \   'monthly' : '%Y_m%m',
    \ },
\}
```

This is just a copy of the default journal settings, with the name changed to an empty string. This should be enough to
observe the same results above.

**Comment by lervag** [comment]
> **Desired behavior**: I want to be able to specify an empty journal name, and have journal files created in the main
> wiki root. This of courses assumes all existing commands and behaviors work as expected.

Seems doable and reasonable!

>     1. When using internal commands to access journal files, they show as `<wiki_root>//<date>.md`, with two forward
>        slashes.

Could you explain how to reproduce that? For me, this is not happening. The code you referred to should not be a problem, because the path is simplified in the `url/wiki.vim` code, which should remove the double slash (and this seems to work for me).

>     2. A few journal specific commands break or override global commands since journal files are now at the same level as
>        other wiki files. The main mapping I've noticed is the `<Leader>wn` mapping for the `wiki-journal-copy-tonext`
>        journal buffer function, overriding the main `<Leader>wn` for `wiki-open`. So all note files are treated like journal
>        files when using this command, in the sense that the plugin attempts to copy the file's contents to a new journal
>        file. Tangentially, I find this mapping confusing on its own; I often want to create new files using `<Leader>wn`
>        from within a journal file. I think it would make sense to reconsider the default mapping
>        for`wiki-journal-copy-tonext` while in journal files (perhaps `<Leader>wcn` or `<Leader>wjn`).

I think this seems sensible. So, in short: I should avoid the journal specific mappings to conflict with the more general wiki mappings. I think the `copy-tonext` is the only one with a conflict.

You propose `<leader>wcn` or `<leader>wjn`. I'm curious, could perhaps `<leader><c-n>` be an option, as it is "aligned" with the `wiki-journal-next` mapping? What do you think?

**Comment by samgriesemer** [comment]
> Could you explain how to reproduce that? For me, this is not happening. The code you referred to should not be a problem, because the path is simplified in the `url/wiki.vim` code, which should remove the double slash (and this seems to work for me).

It's funny that this should be the code that resolves the issue, seeing as it was inspired by my own PR (whoops..). For whatever reason it appears my local `wiki.vim` was either not updated entirely or not on the correct branch. I'm observing the proper behavior now.

> I think this seems sensible. So, in short: I should avoid the journal specific mappings to conflict with the more general wiki mappings. I think the `copy-tonext` is the only one with a conflict.

I think you're right, `copy-tonext` was the only mapping I noticed with any conflicts in practice.

> You propose `<leader>wcn` or `<leader>wjn`. I'm curious, could perhaps `<leader><c-n>` be an option, as it is "aligned" with the `wiki-journal-next` mapping? What do you think?

This makes sense to me. I personally don't use `copy-tonext` due to a custom template setup, but I think the reasoning you mentioned is sound. If I'm not mistaken, that's the only change needed to resolve the issue at this point. I can create a PR if you'd like, or I can just leave things if you'd rather avoid the PR overhead and just make a commit directly. Either way, I'll go ahead and close the issue. Thanks for the feedback!

**Comment by lervag** [comment]
> It's funny that this should be the code that resolves the issue, seeing as it was inspired by my own PR (whoops..). For whatever reason it appears my local `wiki.vim` was either not updated entirely or not on the correct branch. I'm observing the proper behavior now.

Hah, yes, look at that. Good to hear it works on your side as well.

> > You propose `<leader>wcn` or `<leader>wjn`. I'm curious, could perhaps `<leader><c-n>` be an option, as it is "aligned" with the `wiki-journal-next` mapping? What do you think?
> 
> This makes sense to me. I personally don't use `copy-tonext` due to a custom template setup, but I think the reasoning you mentioned is sound. If I'm not mistaken, that's the only change needed to resolve the issue at this point. I can create a PR if you'd like, or I can just leave things if you'd rather avoid the PR overhead and just make a commit directly. Either way, I'll go ahead and close the issue. Thanks for the feedback!

I'll just make the change myself. Thanks!
