### ISSUE TITLE
Omnifunc for markdown links not working

### ISSUE THREAD

**Issue by BonaBeavis** [lervag/wiki.vim#93]
# Description

1. Should autocomplete markdown links
2. It does not

3a. Type `[[Foo#B` -> Vim shows `Bar` in complete menu.
3b. Type `[Foo](Foo#B` -> Nothing happens
3c. Type `[Foo](Foo.md#B` -> Nothing happens

Any advice how to get this working?

```vim
set nocompatible
filetype off

call plug#begin('~/.vim/bundle')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug  'lervag/wiki.vim'
call plug#end()

syntax on
filetype plugin indent on
set hidden
set conceallevel=0

" wiki
let g:wiki_root = '~/cloud/wiki/'
let g:wiki_filetypes = ['md']
let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = '.md'
```

**Comment by lervag** [comment]
Thanks for raising this issue. So, first: This feature is currently not available. The idea has been that one do not really make internal links with markdown style links. I can see that this is not true for everyone, though, so let's implement it!

I'm pushing an update that should mostly just work. However, not that in `.md` files, you will typically have the `markdown` filetype which may implement its own `omnifunc`. This means we may need to consider things in more depth.

**Comment by BonaBeavis** [comment]
Wow, the update actually mostly works!
A way round could be implementing a source for coc, this would be markdown plugin agnostic and async,with the cost of a dependency.

GitHub seems to handle anchors this [way](https://gist.github.com/asabaylus/3071099).

You do match the anchors hierarchically, for example with the document `Foo.md`:

```md
# Foo
## Bar
```

If you want to link to Bar,
typing `[Get me to the bar](Fo` gives `Foo` as completion, then you type `#B` and get `Bar`.

It would be faster if the completion suggests headers from all levels:
Like typing `[Even faster](Ba` suggests `Bar` as option and completes to `[Even faster](Foo#Foo#Bar)`

**Comment by lervag** [comment]
> Wow, the update actually mostly works!

Great, good to hear!

> A way round could be implementing a source for coc, this would be markdown plugin agnostic and async,with the cost of a dependency.

Actually, there is already a source for coc, so I think that works as expected now! :)

> It would be faster if the completion suggests headers from all levels:
> Like typing `[Even faster](Ba` suggests `Bar` as option and completes to `[Even faster](Foo#Foo#Bar)`

This is a different issue altogether, and I'm not sure how easy it is to implement in a robust manner. From `](Ba`, the completion would start to search pages named `Ba...`, if you want the initial candidate list to also include pages with anchors, it would imply a quite expensive search (assuming you have a large wiki bank). IMHO, the current behaviour, which first looks for pages, then from the first `#` considers anchors, is a very good compromise. I am tempted to state that I don't want to change that. Instead, I would be willing to change how each of those parts work, independently. In particular, currently, completion of anchors is always one level at a time. I agree it could be equally good to instead list all possible anchors immediately. Thus, `](Foo#<c-x><c-o>` would give a completion menu like this:

```
Foo
Foo#Bar
Foo#Baz
Bar
Bar#Baz
```

Regarding how anchors work in e.g. github: I think to support other anchor mechanisms is a semi major feature request. I believe we could add support for it similar to how the option `g:wiki_map_link_create` works, and perhaps call it something like `g:wiki_map_anchors`. If you want something like that, please open a new feature request for it so we can keep the threads separated.
