### ISSUE TITLE
Diary Encryption

### ISSUE THREAD

**Issue by annata83** [lervag/wiki.vim#95]
How would you go about automatic diary encryption?

**Comment by lervag** [comment]
Hi. This is a good question. I don't do this myself, but if I wanted to, I think I would go for a solution based on [GnuPG](https://wiki.archlinux.org/index.php/GnuPG). A quick search revealed a few relevant links that may help you get started:

* [Vim Tips Wiki:  Edit gpg encrypted files](https://vim.fandom.com/wiki/Edit_gpg_encrypted_files)
* [Plugin: vim-gnupg](https://github.com/jamessan/vim-gnupg)
* [Blog: Password Management with Vim and GnuPG](https://pig-monkey.com/2013/04/password-management-vim-gnupg/)

I think the gist is to add autocommands that decrypt the file when reading it into a Vim buffer and encrypt it when you save the file. This should work well with wiki.vim, but I have not tested it myself.

**Comment by annata83** [comment]
Hello Again @lervag , I am using the built-in x encryption method for regular wiki pages and it works, something is different in the Diary configuration  that do not allow vim x encryption  keybind.  
Will take a look at your suggestions and report back to you.

Thanks.

**Comment by lervag** [comment]
>  Will take a look at your suggestions and report back to you.

Great, thanks.

**Comment by annata83** [comment]
I am sorry but I not very good with vim yet; can't figure it out; just have to get into command mode and then use X to encrypt for now.. may I ask.. How does this plugin works in the background, meaning the wikiJornalIndex command is not recognize unless inside a wiki buffer and it prints the jornal index inside the buffer not allowing to get into individual days because changes have been made to the buffer ( The History of diary gets paste into the current open wiki ) the question is completely unrelated to the original but it can help me understand basics on how I may find a solution... I mean commands that are specific for wiki are not useful for vim in general but how to modify mappings to work indie the wiki instance.. Don't need full explanation only if you could point me out towards resources like before...

Thanks again

**Comment by lervag** [comment]
> So @lervag I would like your opinion on maybe using autocmd to exec X after saving I not good at this hoping you get some idea.

My opinion doesn't matter so much, because I don't really have much experience with encryption, and even less with Vim + encryption.

> I set an autocmd like so:
> 
> ```
> autocmd bufwritepost /path/to/your/diary/* X
> ```

You should use the Pascal case version `BufWritePost`, not `bufwritepost`. Except for that I think this could/should work. But I suggest you do some experimenting with it yourself and try to figure it out. I'm sorry to say I don't really know how to help more than suggested links in my previous post.
