### ISSUE TITLE
Customizing link opening for pandoc markdown links

### ISSUE THREAD

**Issue by wasowski** [lervag/wiki.vim#96]
Thanks for an excellent plugin @lervag. 

I ma having some trouble customizing how to open links (perhaps just inadequate skills in reading the docs).  I am considering links to non-text files like below:
```
file://./folder/file.jpg
![](file://./folder/file.jpg)
![](folder/file.jpg)
```
I like the last format of the link because pandoc seems to respect it and is able to include the image both in the PDF and the HTML exports. However the first two (with `file://` URI) are the only ones for which I managed to customize how to open them in wiki.vim (using an exteranal image viewer via `g:wiki_file_open`). So I locked myself into either being able to preview images from vim, or to be able to export them with pandoc.  Is there any way to customize how normal mardkown links (like `![](folder/file.jpg)`) are opened so that I could keep both words?

**Comment by lervag** [comment]
> Thanks for an excellent plugin @lervag.

My pleasure :)

> I ma having some trouble customizing how to open links (perhaps just inadequate skills in reading the docs). I am considering links to non-text files like below:
> 
> ```
> file://./folder/file.jpg
> ![](file://./folder/file.jpg)
> ![](folder/file.jpg)
> ```

First, I think these should work:

```
file:folder/file.jpg
![](file:folder/file.jpg)
```

That is, you don't need to use the `//` part. You also don't need `./`. But this is off topic, sorry.

> I like the last format of the link because pandoc seems to respect it and is able to include the image both in the PDF and the HTML exports. However the first two (with `file://` URI) are the only ones for which I managed to customize how to open them in wiki.vim (using an exteranal image viewer via `g:wiki_file_open`).

Yes, you are quite right. wiki.vim currently doesn't recognize the `![...](...)` type of links. I think the solution here is to add this as a new type of link whose url (the `(...)` part) should by default be recognized as a `file:` scheme. Right now, the url is by default recognized as a wiki link, i.e. `![](this)` is the same as `![](wiki:this)`.

I'll look into this and try to fix it asap.

**Comment by wasowski** [comment]
Thanks for positive reaction. I just realized that I might be able to customize a few things via a markdown plugin I am using. I hope it is not a bad idea to use both wiki.vim and a markdown plugins simultaneously.  I am a bit tied up (but just for others that hit this discussion via google) I thought I will mention this idea.  I will check this within the next few days and report.

**Comment by lervag** [comment]
> I hope it is not a bad idea to use both wiki.vim and a markdown plugins simultaneously.

No! In fact, it is one of the "ideas" behind wiki.vim as opposed to vimwiki. I don't want wiki.vim to be a filetype plugin. Instead, the main focus is to interprete links and allow wiki link functionality. I'll admit there are some features that goes beyond this, but at least it is the general idea. So, you should definately be able to combine this with a proper markdown plugin.

**Comment by lervag** [comment]
I've implemented this now, let me know if it works as expected.
